"""W0-99 - build a copy of W0-05's port-order analysis that reads ValeVision's WORKING TREE (the end of Wave 0)
instead of the git index (the tree right after W0-02), and writes only into scratch/W0-99/pom/.

The original script is not changed. Every replacement is anchored and asserted to match exactly once.
Run:  python -B make_pom_endW0.py   then   python -B pom/port_order_map__endW0.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'W0-05', 'port_order_map.py')
DST_DIR = os.path.join(HERE, 'pom')
DST = os.path.join(DST_DIR, 'port_order_map__endW0.py')

text = open(SRC, encoding='utf-8').read()

REPLACEMENTS = [
    # 1. scratch and outputs go to scratch/W0-99/pom only
    ('SCRATCH = os.path.join(EXEC, "scratch", "W0-05")',
     'SCRATCH = os.path.join(EXEC, "scratch", "W0-99", "pom")'),
    ('    out1 = os.path.join(PARITY, "data", "port_order_map.json")\n'
     '    out2 = os.path.join(EXEC, "port_order_map.json")\n',
     '    out1 = os.path.join(SCRATCH, "port_order_map__endW0.json")\n'
     '    out2 = os.path.join(SCRATCH, "port_order_map__endW0__copy.json")\n'),
    # 2. "after" = the working tree, read from disk (paths relative to the VV app root)
    ('    vv1 = ls_index(VCB, VV_PFX)\n',
     '    vv1 = ls_worktree(VV_ROOT)\n'),
    ('    blobs_vv = cat_blobs(VCB, list(vv0_mods.values()) + list(vv1_mods.values()) + [vv1["index.html"]])\n',
     '    blobs_vv = cat_blobs(VCB, list(vv0_mods.values()))\n'
     '    blobs_vv.update({s: open(s[3:], "rb").read() for s in list(vv1_mods.values()) + [vv1["index.html"]]})\n'),
]

for old, new in REPLACEMENTS:
    n = text.count(old)
    if n != 1:
        raise SystemExit('anchor found %d times: %r' % (n, old[:80]))
    text = text.replace(old, new)

# 3. helpers: the working-tree lister, and Exports reading a 'WT:' entry from disk
HELPERS = '''

# -----------------------------------------------------------------------------
# W0-99: the working tree as the "after" tree (end of Wave 0)
# -----------------------------------------------------------------------------
_WT_SKIP = {".git", ".claude", "node_modules", "__pycache__", ".wrangler"}


def ls_worktree(root):
    """path (relative to the VV app root, '/'-separated) -> 'WT:<absolute path>' for every file on disk, pruning
    .claude/worktrees, node_modules and the AUDIT evidence folder (none of them is app code)."""
    res = {}
    for dp, dn, fn in os.walk(root):
        rel_dir = os.path.relpath(dp, root).replace(os.sep, "/")
        dn[:] = [d for d in dn if d not in _WT_SKIP and not (rel_dir == "." and d.startswith("ValeVision__AUDIT__"))]
        for f in fn:
            p = f if rel_dir == "." else rel_dir + "/" + f
            res[p] = "WT:" + os.path.join(dp, f)
    return res

'''
anchor = '\ndef check_index_is_w0_02_only():'
assert text.count(anchor) == 1
text = text.replace(anchor, HELPERS + anchor)

LOAD_OLD = '''        if not self.repo or path not in self.tree or not is_module(path):
            return False
        blob = cat_blobs(self.repo, [self.tree[path]])[self.tree[path]]'''
LOAD_NEW = '''        if path not in self.tree or not is_module(path):
            return False
        if str(self.tree[path]).startswith("WT:"):
            blob = open(self.tree[path][3:], "rb").read()
        elif not self.repo:
            return False
        else:
            blob = cat_blobs(self.repo, [self.tree[path]])[self.tree[path]]'''
assert text.count(LOAD_OLD) == 1
text = text.replace(LOAD_OLD, LOAD_NEW)

os.makedirs(DST_DIR, exist_ok=True)
with open(DST, 'w', encoding='utf-8', newline='\n') as fh:
    fh.write('# GENERATED by scratch/W0-99/make_pom_endW0.py from scratch/W0-05/port_order_map.py - reads the VV WORKING\n'
             '# TREE (end of Wave 0) as its "after" tree and writes only into scratch/W0-99/pom/.\n')
    fh.write(text)
print('wrote', DST)
