"""W1-99 (Wave 1 continuation) - the end-of-Wave-1-continuation port-order analysis: part 1's working-tree copy of
W0-05's script (scratch/W1-99/pom/port_order_map__endW1.py), with only its output folder and file names changed, written
into scratch/W1-99/C2/pom/. Neither the original nor part 1's copy is changed. Every replacement is anchored and asserted
to match exactly once. The analysis is read-only on both repositories (git ls-tree, ls-files, cat-file, diff --cached,
rev-parse; files read from disk) and writes only into scratch/W1-99/C2/pom/.

Run:  python -B make_pom_endW1c.py   then   python -B pom/port_order_map__endW1c.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'pom', 'port_order_map__endW1.py')
DST_DIR = os.path.join(HERE, 'pom')
DST = os.path.join(DST_DIR, 'port_order_map__endW1c.py')

text = open(SRC, encoding='utf-8').read()
REPLACEMENTS = [
    ('SCRATCH = os.path.join(EXEC, "scratch", "W1-99", "pom")',
     'SCRATCH = os.path.join(EXEC, "scratch", "W1-99", "C2", "pom")'),
    ('    out1 = os.path.join(SCRATCH, "port_order_map__endW1.json")\n'
     '    out2 = os.path.join(SCRATCH, "port_order_map__endW1__copy.json")\n',
     '    out1 = os.path.join(SCRATCH, "port_order_map__endW1c.json")\n'
     '    out2 = os.path.join(SCRATCH, "port_order_map__endW1c__copy.json")\n'),
]
for old, new in REPLACEMENTS:
    n = text.count(old)
    if n != 1:
        raise SystemExit('anchor found %d times: %r' % (n, old[:80]))
    text = text.replace(old, new)
lines = text.split('\n')
assert lines[0].startswith('# GENERATED by scratch/W1-99/make_pom_endW1.py'), lines[0]
assert lines[1].startswith('# VV WORKING TREE (end of Wave 1)'), lines[1]
text = '\n'.join(lines[2:])
os.makedirs(DST_DIR, exist_ok=True)
with open(DST, 'w', encoding='utf-8', newline='\n') as fh:
    fh.write('# GENERATED by scratch/W1-99/C2/make_pom_endW1c.py from scratch/W1-99/pom/port_order_map__endW1.py - reads\n'
             '# the VV WORKING TREE (end of the Wave 1 continuation) as its "after" tree and writes only into\n'
             '# scratch/W1-99/C2/pom/.\n')
    fh.write(text)
print('wrote', DST)
