#!/usr/bin/env python3
# =============================================================================
# WHITECARDOPEDIA - APPLY DESIGNERS AND CONCEPT ARTISTS TO project.json
# =============================================================================
#
# FILE       : AutomationUtil__ApplyDesignersToWhitecardopedia__Main__.py
# NAMESPACE  : Whitecardopedia
# MODULE     : Designer + Artist Backfill Tool
# AUTHOR     : Adam Noble - Noble Architecture
# PURPOSE    : Patch the productionData.designer (and conceptArtist where
#              missing) field into every Whitecardopedia project.json using
#              the master CSV as primary source and an optional hand-filled
#              supplement CSV for legacy 2025 projects.
# CREATED    : 26-Jun-2026
#
# DESCRIPTION:
# - Two data sources:
#     1. Main CSV  (required) : generated by AutomationUtil__ExtractProjectDesignersAndArtists__.
#                               Covers all 2026 and 13 2025 projects with *__ProjectData__.json.
#     2. Supplement CSV (opt) : template generated by --dry-run for the ~47 legacy 2025 WCP
#                               projects whose VP folder never had a ProjectData JSON created.
#                               User fills in the Designer column then re-runs with --supplement.
# - Matching is by projectCode. Multi-scheme disambiguation uses the WCP folder
#   name suffix (Scheme-02, Orangery, ...) matched against the CSV Project Name.
# - designer      : always written from matched CSV row.
# - conceptArtist : written only if currently empty / null / FetchFrom__* placeholder
#                   so hand-entered values are never overwritten.
# - Dry-run by default; pass --apply to write files.
# - Supplement template is always written when unmatched projects exist:
#     C:\01__ValeProjects\Project__Data__Query__Legacy2025Supplement__.csv
#
# USAGE:
#   python AutomationUtil__ApplyDesignersToWhitecardopedia__Main__.py
#   python ... --dry-run
#   python ... --apply
#   python ... --apply --supplement "C:\01__ValeProjects\Project__Data__Query__Legacy2025Supplement__.csv"
#
# -----------------------------------------------------------------------------
#
# DEVELOPMENT LOG:
# 26-Jun-2026 - Version 1.0.0
# - Initial release: two-source matching, dry-run + apply, supplement template.
#
# =============================================================================

import csv
import json
import re
import sys
import argparse
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# -----------------------------------------------------------------------------
# REGION | Module Constants
# -----------------------------------------------------------------------------

    # MODULE CONSTANTS | Paths
    # ------------------------------------------------------------
WCP_PROJECTS_ROOT = Path(r"D:\10_CoreLib__ValeCodebase\WebApps\Whitecardopedia\Projects")  # <-- WCP project.json root
DEFAULT_CSV_PATH  = Path(__file__).parent / "Project__Data__Query__DesignersAndArtists__.csv"   # <-- Main source CSV (co-located)
SUPPLEMENT_OUT    = Path(__file__).parent / "Project__Data__Query__Legacy2025Supplement__.csv"  # <-- Generated template / re-input (co-located)
    # ------------------------------------------------------------

    # MODULE CONSTANTS | Console Colours
    # ------------------------------------------------------------
C_RESET  = '\033[0m'
C_GREEN  = '\033[92m'
C_YELLOW = '\033[93m'
C_RED    = '\033[91m'
C_CYAN   = '\033[96m'
C_GREY   = '\033[90m'
C_BOLD   = '\033[1m'
    # ------------------------------------------------------------

    # MODULE CONSTANTS | Codes to Skip (example / template rows in CSV)
    # ------------------------------------------------------------
SKIP_CODES = {'00001', '12345'}                               # <-- Example and test project codes
    # ------------------------------------------------------------

# endregion -------------------------------------------------------------------


# -----------------------------------------------------------------------------
# REGION | CSV Loading and Lookup Building
# -----------------------------------------------------------------------------

    # HELPER FUNCTION | Extract Variant Suffix From a Name String
    # ------------------------------------------------------------
def na_extract_variant(raw: str) -> str:
    """Returns lowercase variant token, e.g. 'scheme-02', 'orangery', '' for default."""
    m = re.search(
        r'(?:__|[\s])(scheme-\d+|orangery|porch|blockout|fullversion|egypthouse)',
        raw,
        flags=re.IGNORECASE,
    )
    return m.group(1).lower() if m else ''
    # ------------------------------------------------------------

    # HELPER FUNCTION | Test Whether a conceptArtist Value Is a Missing Placeholder
    # ------------------------------------------------------------
def na_is_placeholder(value: Optional[str]) -> bool:
    if not value:
        return True                                           # <-- None or empty string
    if str(value).startswith('FetchFrom__'):
        return True                                           # <-- Legacy fetch-from-list token
    return False
    # ------------------------------------------------------------

    # FUNCTION | Load a Designer CSV Into a Dict Keyed by projectCode
    # ------------------------------------------------------------
def na_load_csv(csv_path: Path) -> Dict[str, List[dict]]:
    """
    Returns {code: [row_dict, ...]} — one list entry per CSV row for that code.
    Works for both the main CSV and the supplement CSV (shares same required columns).
    """
    result: Dict[str, List[dict]] = {}
    with open(csv_path, newline='', encoding='utf-8-sig') as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            code = row.get('Code', '').strip()
            if not code or code in SKIP_CODES:
                continue                                      # <-- Skip blank / example rows
            designer = row.get('Designer', '').strip()
            if not designer or designer.startswith('FetchFrom__'):
                continue                                      # <-- Skip rows with no useful designer

            result.setdefault(code, []).append({
                'code'          : code,
                'project_name'  : row.get('Project Name', '').strip(),
                'designer'      : designer,
                'concept_artist': row.get('Concept Artist', '').strip(),
            })
    return result
    # ------------------------------------------------------------

    # FUNCTION | Merge a Supplement Lookup Into the Main Lookup
    # ------------------------------------------------------------
def na_merge_supplement(main: Dict[str, List[dict]], supplement: Dict[str, List[dict]]) -> None:
    """Adds supplement rows into main where code is absent or project_name is new."""
    for code, rows in supplement.items():
        if code not in main:
            main[code] = rows                                 # <-- Entirely new code
        else:
            existing_names = {r['project_name'] for r in main[code]}
            for row in rows:
                if row['project_name'] not in existing_names:
                    main[code].append(row)                    # <-- New variant row for existing code
    # ------------------------------------------------------------

# endregion -------------------------------------------------------------------


# -----------------------------------------------------------------------------
# REGION | WCP project.json Discovery
# -----------------------------------------------------------------------------

    # FUNCTION | Collect All WCP project.json Paths
    # ------------------------------------------------------------
def na_collect_wcp_projects(root: Path) -> List[Path]:
    """Walk Projects/2025/ and Projects/2026/ under root, return all project.json paths."""
    paths = []
    for year_dir in sorted(root.iterdir()):
        if not year_dir.is_dir() or year_dir.name not in ('2025', '2026'):
            continue
        for proj_dir in sorted(year_dir.iterdir()):
            if not proj_dir.is_dir():
                continue
            pj = proj_dir / 'project.json'
            if pj.exists():
                paths.append(pj)
    return paths
    # ------------------------------------------------------------

# endregion -------------------------------------------------------------------


# -----------------------------------------------------------------------------
# REGION | Matching Logic
# -----------------------------------------------------------------------------

    # HELPER FUNCTION | Pick the Best CSV Row for a Given WCP Folder
    # ------------------------------------------------------------
def na_pick_best_row(folder_name: str, csv_rows: List[dict]) -> Tuple[Optional[dict], str]:
    """
    Returns (best_row, pick_status).
    pick_status:
      'ok'        - single row, unambiguous
      'ok-multi'  - multiple rows with identical designer (safe to apply)
      'ambiguous' - multiple rows with conflicting designer (skip)
    """
    if len(csv_rows) == 1:
        return csv_rows[0], 'ok'                             # <-- Trivial single-row case

    designers = {r['designer'] for r in csv_rows}
    if len(designers) > 1:
        return None, 'ambiguous'                             # <-- Conflicting designers — skip

    # All rows share the same designer.  Try variant matching for conceptArtist accuracy.
    folder_variant  = na_extract_variant(folder_name)
    variant_matches = [r for r in csv_rows if na_extract_variant(r['project_name']) == folder_variant]
    best = variant_matches[0] if variant_matches else csv_rows[0]
    return best, 'ok-multi'
    # ------------------------------------------------------------

    # FUNCTION | Resolve the CSV Match for One WCP project.json
    # ------------------------------------------------------------
def na_resolve_match(folder_name: str, project_code: str, lookup: Dict[str, List[dict]]) -> Tuple[Optional[dict], str]:
    """
    Returns (matched_row, status):
      'matched'   - found, ready to apply
      'unmatched' - code not present in any loaded CSV
      'ambiguous' - code present but designer conflicts across multi-scheme rows
    """
    rows = lookup.get(project_code)
    if not rows:
        return None, 'unmatched'

    best, pick_status = na_pick_best_row(folder_name, rows)
    if pick_status == 'ambiguous':
        return None, 'ambiguous'

    return best, 'matched'
    # ------------------------------------------------------------

# endregion -------------------------------------------------------------------


# -----------------------------------------------------------------------------
# REGION | project.json Patching
# -----------------------------------------------------------------------------

    # HELPER FUNCTION | Read a project.json File
    # ------------------------------------------------------------
def na_read_project_json(path: Path) -> Optional[dict]:
    try:
        with open(path, encoding='utf-8') as fh:
            return json.load(fh)
    except Exception as exc:
        print(f"{C_RED}ERROR reading {path}: {exc}{C_RESET}")
        return None
    # ------------------------------------------------------------

    # HELPER FUNCTION | Write a project.json File
    # ------------------------------------------------------------
def na_write_project_json(path: Path, data: dict) -> bool:
    try:
        with open(path, 'w', encoding='utf-8') as fh:
            json.dump(data, fh, indent=4, ensure_ascii=False)
            fh.write('\n')                                   # <-- Trailing newline convention
        return True
    except Exception as exc:
        print(f"{C_RED}ERROR writing {path}: {exc}{C_RESET}")
        return False
    # ------------------------------------------------------------

    # FUNCTION | Compute Which Fields Would Change and Optionally Apply Them
    # ------------------------------------------------------------
def na_compute_and_apply(data: dict, csv_row: dict, apply: bool) -> Tuple[List[str], bool]:
    """
    Returns (list_of_change_descriptions, did_write).
    When apply=True, mutates data in-place and the caller writes the file.
    """
    changes: List[str] = []
    pd = data.setdefault('productionData', {})               # <-- Ensure key exists

    current_designer = pd.get('designer') or ''
    new_designer     = csv_row['designer']
    if new_designer and current_designer != new_designer:
        changes.append(f"designer '{current_designer}' -> '{new_designer}'")
        if apply:
            pd['designer'] = new_designer

    current_artist = pd.get('conceptArtist') or ''
    new_artist     = csv_row['concept_artist']
    if new_artist and na_is_placeholder(current_artist):
        changes.append(f"conceptArtist '{current_artist}' -> '{new_artist}'")
        if apply:
            pd['conceptArtist'] = new_artist

    return changes, bool(changes)
    # ------------------------------------------------------------

# endregion -------------------------------------------------------------------


# -----------------------------------------------------------------------------
# REGION | Supplement CSV Template Generation
# -----------------------------------------------------------------------------

    # FUNCTION | Write Supplement Template CSV for Unmatched Projects
    # ------------------------------------------------------------
def na_write_supplement_template(unmatched: List[dict], out_path: Path) -> None:
    """
    Writes a CSV pre-filled with Folder/Code/Name/ConceptArtist/NotesSnippet.
    The Designer column is empty — user fills it in, then re-runs with --supplement.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ['Folder', 'Code', 'Project Name', 'Concept Artist', 'Notes Snippet', 'Designer']
    with open(out_path, 'w', newline='', encoding='utf-8-sig') as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for rec in sorted(unmatched, key=lambda r: r['folder']):
            notes_raw  = (rec.get('additional_notes') or '').replace('\n', ' ').replace('\r', '')
            notes_clip = notes_raw[:120]
            writer.writerow({
                'Folder'         : rec['folder'],
                'Code'           : rec['code'],
                'Project Name'   : rec['project_name'],
                'Concept Artist' : rec['concept_artist'],
                'Notes Snippet'  : notes_clip,
                'Designer'       : '',                       # <-- Fill this in
            })
    print(f"\n{C_CYAN}Supplement template -> {out_path}{C_RESET}")
    print(f"{C_GREY}  Fill in the Designer column then re-run with --supplement \"{out_path}\"{C_RESET}")
    # ------------------------------------------------------------

# endregion -------------------------------------------------------------------


# -----------------------------------------------------------------------------
# REGION | Report Printing
# -----------------------------------------------------------------------------

    # HELPER FUNCTION | Print a Section Divider With Title
    # ------------------------------------------------------------
def na_print_section(title: str) -> None:
    print(f"\n{C_BOLD}{title}{C_RESET}")
    print('-' * 80)
    # ------------------------------------------------------------

    # FUNCTION | Print the Full Backfill Report
    # ------------------------------------------------------------
def na_print_report(
    matched   : List[dict],
    unmatched : List[dict],
    ambiguous : List[dict],
    apply_mode: bool,
) -> None:
    mode_lbl = 'APPLY' if apply_mode else 'DRY-RUN'
    print(f"\n{C_BOLD}{'=' * 80}{C_RESET}")
    print(f"{C_BOLD}  DESIGNER BACKFILL REPORT  [{mode_lbl}]{C_RESET}")
    print(f"{C_BOLD}{'=' * 80}{C_RESET}")

    # MATCHED section
    na_print_section(f"MATCHED ({len(matched)})")
    for r in sorted(matched, key=lambda x: x['folder']):
        if r['wrote']:
            lbl = f"{C_GREEN}WROTE     {C_RESET}"
        elif r['no_change']:
            lbl = f"{C_GREY}SKIP-SAME {C_RESET}"
        else:
            lbl = f"{C_CYAN}DRY-RUN   {C_RESET}"
        changes_str = '  |  ' + ', '.join(r['changes']) if r['changes'] else ''
        print(f"  {lbl}  {r['folder']:<50}{changes_str}")

    # UNMATCHED section
    if unmatched:
        na_print_section(f"UNMATCHED — no CSV source, needs supplement ({len(unmatched)})")
        for r in sorted(unmatched, key=lambda x: x['folder']):
            print(f"  {C_YELLOW}NO-SOURCE {C_RESET}  {r['folder']:<50}  artist={r['concept_artist']}")

    # AMBIGUOUS section
    if ambiguous:
        na_print_section(f"AMBIGUOUS — conflicting multi-scheme rows ({len(ambiguous)})")
        for r in sorted(ambiguous, key=lambda x: x['folder']):
            print(f"  {C_RED}AMBIGUOUS {C_RESET}  {r['folder']:<50}  code={r['code']}")

    # Summary counts
    wrote_count     = sum(1 for r in matched if r['wrote'])
    skip_same_count = sum(1 for r in matched if r['no_change'])
    dry_run_count   = sum(1 for r in matched if not r['wrote'] and not r['no_change'])
    print(f"\n{C_BOLD}{'-' * 80}{C_RESET}")
    print(f"  {C_GREEN}Wrote      : {wrote_count}{C_RESET}")
    print(f"  {C_GREY}Skip-same  : {skip_same_count}  (values already correct){C_RESET}")
    if dry_run_count:
        print(f"  {C_CYAN}Would write: {dry_run_count}  (re-run with --apply){C_RESET}")
    print(f"  {C_YELLOW}Unmatched  : {len(unmatched)}  (supplement CSV required){C_RESET}")
    if ambiguous:
        print(f"  {C_RED}Ambiguous  : {len(ambiguous)}  (review manually){C_RESET}")
    print()
    # ------------------------------------------------------------

# endregion -------------------------------------------------------------------


# -----------------------------------------------------------------------------
# REGION | Main Entrypoint
# -----------------------------------------------------------------------------

    # FUNCTION | Parse CLI Arguments
    # ------------------------------------------------------------
def na_parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description='Patch designer + conceptArtist into Whitecardopedia project.json files.'
    )
    p.add_argument('--apply',      action='store_true', help='Write changes to project.json files (default: dry-run)')
    p.add_argument('--dry-run',    action='store_true', help='Explicit dry-run — no writes (default behaviour)')
    p.add_argument('--csv',        type=Path,           default=DEFAULT_CSV_PATH,
                   help=f'Main designer CSV (default: {DEFAULT_CSV_PATH})')
    p.add_argument('--supplement', type=Path,           default=None,
                   help='Supplement CSV for legacy 2025 projects (optional)')
    return p.parse_args()
    # ------------------------------------------------------------

    # FUNCTION | Main Orchestrator
    # ------------------------------------------------------------
def na_main() -> None:
    args       = na_parse_args()
    apply_mode = args.apply and not args.dry_run             # <-- --apply wins unless --dry-run also given

    # LOAD MAIN CSV
    if not args.csv.exists():
        print(f"{C_RED}ERROR: Main CSV not found: {args.csv}{C_RESET}")
        sys.exit(1)
    lookup = na_load_csv(args.csv)
    csv_row_count = sum(len(v) for v in lookup.values())
    print(f"{C_CYAN}Main CSV      : {args.csv}  ({csv_row_count} usable rows){C_RESET}")

    # LOAD SUPPLEMENT CSV (optional)
    if args.supplement:
        if args.supplement.exists():
            supplement_lookup = na_load_csv(args.supplement)
            na_merge_supplement(lookup, supplement_lookup)
            sup_count = sum(len(v) for v in supplement_lookup.values())
            print(f"{C_CYAN}Supplement CSV: {args.supplement}  ({sup_count} rows merged){C_RESET}")
        else:
            print(f"{C_YELLOW}Supplement CSV not found (skipped): {args.supplement}{C_RESET}")

    # COLLECT ALL WCP project.json FILES
    pj_paths = na_collect_wcp_projects(WCP_PROJECTS_ROOT)
    print(f"{C_CYAN}WCP projects  : {len(pj_paths)} project.json files found{C_RESET}")
    print(f"{C_CYAN}Mode          : {'APPLY' if apply_mode else 'DRY-RUN'}{C_RESET}\n")

    # PROCESS EACH PROJECT
    matched_records   : List[dict] = []
    unmatched_records : List[dict] = []
    ambiguous_records : List[dict] = []

    for pj_path in pj_paths:
        data = na_read_project_json(pj_path)
        if data is None:
            continue

        folder_name  = pj_path.parent.name                  # <-- e.g. '62361__Gordon__Scheme-03'
        rel_folder   = str(pj_path.parent.relative_to(WCP_PROJECTS_ROOT))
        project_code = str(data.get('projectCode', '')).strip()
        project_name = str(data.get('projectName', '')).strip()
        pd_block     = data.get('productionData') or {}
        current_artist   = pd_block.get('conceptArtist') or ''
        additional_notes = pd_block.get('additionalNotes') or ''

        csv_row, status = na_resolve_match(folder_name, project_code, lookup)

        if status == 'unmatched':
            unmatched_records.append({
                'folder'          : rel_folder,
                'code'            : project_code,
                'project_name'    : project_name,
                'concept_artist'  : current_artist,
                'additional_notes': additional_notes,
            })
            continue

        if status == 'ambiguous':
            ambiguous_records.append({'folder': rel_folder, 'code': project_code})
            continue

        # Compute changes (and apply if in apply_mode)
        changes, has_changes = na_compute_and_apply(data, csv_row, apply=apply_mode)
        wrote = False
        if apply_mode and has_changes:
            wrote = na_write_project_json(pj_path, data)

        matched_records.append({
            'folder'   : rel_folder,
            'code'     : project_code,
            'changes'  : changes,
            'no_change': not has_changes,
            'wrote'    : wrote,
        })

    # PRINT REPORT
    na_print_report(matched_records, unmatched_records, ambiguous_records, apply_mode)

    # ALWAYS WRITE SUPPLEMENT TEMPLATE WHEN UNMATCHED PROJECTS REMAIN
    if unmatched_records:
        na_write_supplement_template(unmatched_records, SUPPLEMENT_OUT)
    # ------------------------------------------------------------

# endregion -------------------------------------------------------------------


if __name__ == '__main__':
    na_main()
