/* =============================================================================
   VGHLANTERN - ASSET REGISTRY
   =============================================================================

   FILE       : VghLantern__AppData__AssetRegistry__.js
   NAMESPACE  : VghLantern
   MODULE     : AppData - AssetRegistry
   AUTHOR     : Adam Noble - Noble Architecture
   PURPOSE    : Resolve any asset id, in either library, to the one file it names
   CREATED    : 21-Aug-2026

   DESCRIPTION:
   - The single address book for both data libraries. An asset id goes in, a
     record comes out: where the file is, what it is called, what it can do, and
     how big it is.
   - Also resolves the SYSTEM INDEXES themselves, so the ridge, hip, glaze bar,
     base frame and interior joinery loaders can each reach their own
     configuration without knowing which folder it sits in.
   - Reads VghLantern__AssetRegistry__.json, which is generated by
     60__Dev__WebBuildUtils/VghLantern__BuildUtil__AssetRegistry__.py and is never
     edited by hand.

   ---------------------------------------------------------------------------

   WHY THERE IS ONE OF THESE

   A product code used to be written down in up to eleven places and a folder
   path in seven, and nothing checked that any two of them agreed. Renaming
   45_1000__GlazeBars to 45_2000__GlazeBars__Profiles broke the glaze bar loader
   at a constant nobody was looking at, and left five urls in a system index
   aimed at deleted files. The application carried on and simply drew no bars.

   So the rule is now: A SYSTEM INDEX NAMES AN ID. THIS MODULE OWNS THE PATH.
   Move a file, rerun the builder, and every consumer follows with no code change
   at all. There is exactly one hardcoded path left in the application, which is
   this registry's own url below, and that is the one path a registry cannot
   resolve for itself.

   AN ID IS AN ADDRESS, NOT A HINT

   The builder refuses to write a registry containing a duplicate id, so a
   consumer may treat a resolved record as definitive. An id that resolves to
   nothing is a fault worth reporting rather than an absence worth tolerating,
   and Url() says so once per id rather than on every frame that asks.

   THE ASSET BODIES ARE NOT CACHED HERE

   This module answers WHERE, not WHAT. Fetching and holding a one to ten
   megabyte asset body is the job of whoever asked for it - the component asset
   cache trims to a byte budget, the system loaders memoise their stitched
   sections for the life of the page, and those two want different lifetimes. A
   convenience Fetch is offered for callers that want neither.

   ============================================================================= */

// =============================================================================
// REGION | Asset Registry Module
// =============================================================================

const VghLantern__AppData__AssetRegistry = (function() {

// -----------------------------------------------------------------------------
// REGION | Module Constants and State
// -----------------------------------------------------------------------------

    // MODULE CONSTANTS | The One Hardcoded Path
    // ------------------------------------------------------------
    // Served live by the Flask development server so the registry stays current
    // while assets are being authored, with the static file as the fallback that
    // the GitHub Pages build and a bare file server both take.
    const API_REGISTRY_PATH     =  '/api/asset-registry';
    const STATIC_REGISTRY_PATH  =  'VghLantern__AssetRegistry__.json';
    // ------------------------------------------------------------


    // MODULE CONSTANTS | Registry Field Names
    // ------------------------------------------------------------
    const KEY_META      =  'VghLantern__AssetRegistry__Meta';
    const KEY_LIBRARIES =  'VghLantern__AssetRegistry__Libraries';
    const KEY_INDEXES   =  'VghLantern__AssetRegistry__SystemIndexes';
    const KEY_ASSETS    =  'VghLantern__AssetRegistry__Assets';
    // ------------------------------------------------------------


    // MODULE VARIABLES | Memoised Registry and Lookups
    // ------------------------------------------------------------
    let VghLantern__AssetRegistry__Data         =  null;                     // <-- Parsed registry document
    let VghLantern__AssetRegistry__LoadPromise  =  null;                     // <-- In-flight load shared by concurrent callers
    let VghLantern__AssetRegistry__ById         =  {};                       // <-- AssetId -> record
    let VghLantern__AssetRegistry__IndexByKey   =  {};                       // <-- IndexKey -> system index record
    let VghLantern__AssetRegistry__Reported     =  {};                       // <-- Ids already complained about, so a miss logs once
    // ------------------------------------------------------------

// endregion -------------------------------------------------------------------


// -----------------------------------------------------------------------------
// REGION | Loading
// -----------------------------------------------------------------------------

    // HELPER FUNCTION | Build the Two Lookup Tables From a Loaded Registry
    // ------------------------------------------------------------
    function VghLantern__AssetRegistry__BuildLookups(data) {
        VghLantern__AssetRegistry__ById       =  {};
        VghLantern__AssetRegistry__IndexByKey =  {};

        var assets  =  (data && Array.isArray(data[KEY_ASSETS]))  ? data[KEY_ASSETS]  : [];
        var indexes =  (data && Array.isArray(data[KEY_INDEXES])) ? data[KEY_INDEXES] : [];
        var i;

        for (i = 0; i < assets.length; i++) {
            if (assets[i] && assets[i].AssetId) VghLantern__AssetRegistry__ById[assets[i].AssetId] = assets[i];
        }
        for (i = 0; i < indexes.length; i++) {
            if (indexes[i] && indexes[i].IndexKey) VghLantern__AssetRegistry__IndexByKey[indexes[i].IndexKey] = indexes[i];
        }
    }
    // ------------------------------------------------------------


    // FUNCTION | Load the Registry (memoised)
    // ------------------------------------------------------------
    // Every system loader awaits this before its first resolution, and they all
    // share the one in-flight promise, so a page that builds a ridge, four hips,
    // a base frame and forty glaze bars fetches the registry exactly once.
    //
    // A registry that will not load is fatal to asset resolution and is logged as
    // an error rather than a warning, because every downstream failure after it
    // will be a puzzling absence rather than an obvious cause.
    function VghLantern__AssetRegistry__Load() {
        if (VghLantern__AssetRegistry__LoadPromise) return VghLantern__AssetRegistry__LoadPromise;

        VghLantern__AssetRegistry__LoadPromise  =  (async function() {
            var data  =  await VghLantern__AssetRegistry__FetchFirstAvailable();

            VghLantern__AssetRegistry__Data  =  data;
            VghLantern__AssetRegistry__BuildLookups(data);

            if (data) {
                var meta  =  data[KEY_META] || {};
                console.log('[VghLantern__AssetRegistry] Registry loaded ('
                    + Object.keys(VghLantern__AssetRegistry__ById).length + ' assets, '
                    + Object.keys(VghLantern__AssetRegistry__IndexByKey).length + ' system indexes, generated '
                    + (meta.GeneratedDate || 'unknown') + ').');

                if (Array.isArray(meta.Warnings) && meta.Warnings.length > 0) {
                    console.warn('[VghLantern__AssetRegistry] Builder warnings:', meta.Warnings);
                }
            }

            return VghLantern__AssetRegistry__Data;
        })();

        return VghLantern__AssetRegistry__LoadPromise;
    }
    // ------------------------------------------------------------


    // HELPER FUNCTION | Try the Live Endpoint, Then the Static File
    // ------------------------------------------------------------
    // The same two step the component and profile index loaders take, and for the
    // same reason: while assets are being authored the development server serves a
    // freshly built registry no-store, and a static deployment has no such server.
    async function VghLantern__AssetRegistry__FetchFirstAvailable() {
        var paths  =  [API_REGISTRY_PATH, STATIC_REGISTRY_PATH];
        var i, response;

        for (i = 0; i < paths.length; i++) {
            try {
                response  =  await fetch(paths[i], { cache: 'no-store' });
                if (response.ok) return await response.json();
            } catch (error) {
                // Falls through to the next path. A missing /api route on a static
                // host is expected rather than exceptional and is not logged.
            }
        }

        console.error('[VghLantern__AssetRegistry] The asset registry could not be loaded from '
            + paths.join(' or ') + '. No asset will resolve. '
            + 'Rebuild it with 60__Dev__WebBuildUtils/VghLantern__BuildUtil__AssetRegistry__.py');
        return null;
    }
    // ------------------------------------------------------------

// endregion -------------------------------------------------------------------


// -----------------------------------------------------------------------------
// REGION | Resolution
// -----------------------------------------------------------------------------

    // FUNCTION | The Whole Record for an Asset Id (synchronous)
    // ------------------------------------------------------------
    // Null before the registry has loaded and null for an id it does not carry.
    // Callers that need to tell those apart ask IsLoaded.
    function VghLantern__AssetRegistry__Record(assetId) {
        if (!assetId) return null;
        return VghLantern__AssetRegistry__ById[assetId] || null;
    }
    // ------------------------------------------------------------


    // FUNCTION | The Url an Asset Id Resolves To (synchronous)
    // ------------------------------------------------------------
    // Empty string when the id is unknown, and the miss is reported ONCE per id.
    // An unknown id is a data fault - a system index naming something the builder
    // never saw - and it would otherwise be silent, because every consumer treats
    // a missing asset as a part it simply does not draw.
    function VghLantern__AssetRegistry__Url(assetId) {
        var record  =  VghLantern__AssetRegistry__Record(assetId);
        if (record) return record.Url || '';

        if (assetId && VghLantern__AssetRegistry__Data && !VghLantern__AssetRegistry__Reported[assetId]) {
            VghLantern__AssetRegistry__Reported[assetId]  =  true;
            console.error('[VghLantern__AssetRegistry] No asset is registered under the id "' + assetId
                + '". Either the id is wrong or the registry needs rebuilding.');
        }
        return '';
    }
    // ------------------------------------------------------------


    // FUNCTION | The Url of a System Index by Its Key (synchronous)
    // ------------------------------------------------------------
    // 'glazeBar', 'ridge', 'hip', 'baseFrame', 'interiorJoinery'. The key is
    // derived by the builder from the index's own file name, so adding a system
    // means adding its index file and nothing else.
    function VghLantern__AssetRegistry__SystemIndexUrl(indexKey) {
        var record  =  VghLantern__AssetRegistry__IndexByKey[indexKey];
        if (record) return record.Url || '';

        if (indexKey && VghLantern__AssetRegistry__Data && !VghLantern__AssetRegistry__Reported['index:' + indexKey]) {
            VghLantern__AssetRegistry__Reported['index:' + indexKey]  =  true;
            console.error('[VghLantern__AssetRegistry] No system index is registered under the key "'
                + indexKey + '". Expected a file named VghLantern__<Name>System__Index__.json.');
        }
        return '';
    }
    // ------------------------------------------------------------


    // FUNCTION | Whether the Registry Is Available
    // ------------------------------------------------------------
    function VghLantern__AssetRegistry__IsLoaded() {
        return VghLantern__AssetRegistry__Data !== null;
    }
    // ------------------------------------------------------------


    // FUNCTION | Every Registered Asset, or Every One in a Library
    // ------------------------------------------------------------
    // Returns the registry's own records rather than copies. They are generated,
    // read-only data and nothing in the application writes to one.
    function VghLantern__AssetRegistry__List(libraryKey) {
        var data    =  VghLantern__AssetRegistry__Data;
        var assets  =  (data && Array.isArray(data[KEY_ASSETS])) ? data[KEY_ASSETS] : [];
        if (!libraryKey) return assets;

        return assets.filter(function(record) { return record.LibraryKey === libraryKey; });
    }
    // ------------------------------------------------------------


    // FUNCTION | The Library Definitions the Registry Spans
    // ------------------------------------------------------------
    function VghLantern__AssetRegistry__Libraries() {
        var data  =  VghLantern__AssetRegistry__Data;
        return (data && Array.isArray(data[KEY_LIBRARIES])) ? data[KEY_LIBRARIES] : [];
    }
    // ------------------------------------------------------------


    // FUNCTION | The Registry's Own Provenance
    // ------------------------------------------------------------
    // For the inspector and for a diagnostic that wants to say WHEN the registry
    // on screen was built, which is the first question when an asset is missing.
    function VghLantern__AssetRegistry__Meta() {
        var data  =  VghLantern__AssetRegistry__Data;
        return (data && data[KEY_META]) ? data[KEY_META] : null;
    }
    // ------------------------------------------------------------

// endregion -------------------------------------------------------------------


// -----------------------------------------------------------------------------
// REGION | Convenience Fetch
// -----------------------------------------------------------------------------

    // FUNCTION | Fetch an Asset Body by Id
    // ------------------------------------------------------------
    // For callers with no cache of their own. Deliberately NOT memoised here: the
    // two callers that fetch repeatedly - the component asset cache and the system
    // loaders - already hold their results with lifetimes suited to what they hold,
    // and a third cache underneath them would double the memory a ten megabyte
    // finial costs for no gain.
    //
    // Resolves null rather than throwing on every failure, so a caller drawing a
    // lantern without one part still draws the rest.
    async function VghLantern__AssetRegistry__Fetch(assetId) {
        await VghLantern__AssetRegistry__Load();

        var url  =  VghLantern__AssetRegistry__Url(assetId);
        if (!url) return null;

        try {
            var response  =  await fetch(url, { cache: 'no-store' });
            if (!response.ok) throw new Error('HTTP ' + response.status);
            return await response.json();

        } catch (error) {
            console.error('[VghLantern__AssetRegistry] Asset ' + assetId + ' failed to load from '
                + url + ': ' + error.message);
            return null;
        }
    }
    // ------------------------------------------------------------

// endregion -------------------------------------------------------------------


// -----------------------------------------------------------------------------
// REGION | Public API
// -----------------------------------------------------------------------------

    // PUBLIC API
    // ------------------------------------------------------------
    return {
        VghLantern__AssetRegistry__Load            : VghLantern__AssetRegistry__Load,
        VghLantern__AssetRegistry__IsLoaded        : VghLantern__AssetRegistry__IsLoaded,
        VghLantern__AssetRegistry__Record          : VghLantern__AssetRegistry__Record,
        VghLantern__AssetRegistry__Url             : VghLantern__AssetRegistry__Url,
        VghLantern__AssetRegistry__SystemIndexUrl  : VghLantern__AssetRegistry__SystemIndexUrl,
        VghLantern__AssetRegistry__List            : VghLantern__AssetRegistry__List,
        VghLantern__AssetRegistry__Libraries       : VghLantern__AssetRegistry__Libraries,
        VghLantern__AssetRegistry__Meta            : VghLantern__AssetRegistry__Meta,
        VghLantern__AssetRegistry__Fetch           : VghLantern__AssetRegistry__Fetch
    };

// endregion -------------------------------------------------------------------

})();

// endregion ===================================================================

window.VghLantern__AppData__AssetRegistry  =  VghLantern__AppData__AssetRegistry;
