"""W3-99 - the end-of-Wave-3 port-order analysis: W2-99's working-tree copy of W0-05's script
(scratch/W2-99/pom/port_order_map__endW2.py) with only its output folder and file names changed, written into
scratch/W3-99/pom/. Every replacement is anchored and asserted to match exactly once. Read-only on both repositories.

Run:  python -B make_pom_endW3.py   then   python -B pom/port_order_map__endW3.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'W2-99', 'pom', 'port_order_map__endW2.py')
DST_DIR = os.path.join(HERE, 'pom')
DST = os.path.join(DST_DIR, 'port_order_map__endW3.py')

text = open(SRC, encoding='utf-8').read()
REPLACEMENTS = [
    ('SCRATCH = os.path.join(EXEC, "scratch", "W2-99", "pom")',
     'SCRATCH = os.path.join(EXEC, "scratch", "W3-99", "pom")'),
    ('    out1 = os.path.join(SCRATCH, "port_order_map__endW2.json")\n'
     '    out2 = os.path.join(SCRATCH, "port_order_map__endW2__copy.json")\n',
     '    out1 = os.path.join(SCRATCH, "port_order_map__endW3.json")\n'
     '    out2 = os.path.join(SCRATCH, "port_order_map__endW3__copy.json")\n'),
]
for old, new in REPLACEMENTS:
    n = text.count(old)
    if n != 1:
        raise SystemExit('anchor found %d times: %r' % (n, old[:80]))
    text = text.replace(old, new)
lines = text.split('\n')
assert lines[0].startswith('# GENERATED by scratch/W2-99/make_pom_endW2.py'), lines[0]
text = '\n'.join(lines[2:])
os.makedirs(DST_DIR, exist_ok=True)
with open(DST, 'w', encoding='utf-8', newline='\n') as fh:
    fh.write('# GENERATED by scratch/W3-99/make_pom_endW3.py from scratch/W2-99/pom/port_order_map__endW2.py - reads\n'
             '# the VV WORKING TREE (end of Wave 3) as its "after" tree and writes only into scratch/W3-99/pom/.\n')
    fh.write(text)
print('wrote', DST)
