from k3_common import *

# =============================================================================
# W2 - INDEPENDENT SUBSYSTEMS (parallel): drawing planes, depth fog, section
# adapter, Dev-menu rebuild, folder 50, viewports and render styles (ending
# in the whole-file viewport convergence), drafting aids and object snap,
# SheetTools leaves, drawing and vector tool modules, hatch panel,
# specification lockstep and margins, spell check, scrapbooks, panel fixes.
# Every W2 package starts after W1-99.
# =============================================================================

V20 = lambda f: VLE('20__System__Viewports/' + f)
T20 = lambda f: TLE('20__System__Viewports/' + f)
V25 = lambda f: VLE('25__System__RenderStyles/' + f)
T25 = lambda f: TLE('25__System__RenderStyles/' + f)

P('W2-01', 'W2', 'Drawing Planes (47__System__DrawingPlanes) with its start-up and stylesheet wiring',
  'Port the rest of the Drawing Planes system into TV\'s slot - Overlay, Grip, the Dev-menu controls and the stylesheet, which import the W2-40 core and the W1 render-loop overlays - and wire PlaneOverlay/PlaneGrip/PlaneUi initialisation in index.html and the stylesheet in the CSS index at TV\'s positions.',
  tv=[TVM('47__System__DrawingPlanes/Na__DrawingPlanes__DevMenu__Controls__.js'), TVM('47__System__DrawingPlanes/Na__DrawingPlanes__Grip__.js'),
      TVM('47__System__DrawingPlanes/Na__DrawingPlanes__Overlay__.js'), TVM('47__System__DrawingPlanes/Na__DrawingPlanes__Styles__DevMenu__.css'), 'TV/Index.html (47 init lines)'],
  vv=[NEW(VVM('47__System__DrawingPlanes/Na__DrawingPlanes__DevMenu__Controls__.js')), NEW(VVM('47__System__DrawingPlanes/Na__DrawingPlanes__Grip__.js')),
      NEW(VVM('47__System__DrawingPlanes/Na__DrawingPlanes__Overlay__.js')), NEW(VVM('47__System__DrawingPlanes/Na__DrawingPlanes__Styles__DevMenu__.css')),
      IDX, CSSIDX, NEW(TESTDIR + 'Na__Test__DrawingPlanes__.test.mjs')],
  hot=[IDX, CSSIDX],
  deps=['W2-40'],
  gated=['DR-01', 'DR-02', 'DR-32'],
  size='L', est=2300, est_note='TV 828 + 824 + 397 + 142 lines verbatim + 2 wiring hunks',
  adapt=['index.html: three inits after the LE block (TV positions); CSS after the elevation sheets.'],
  acc=['Na__Test__DrawingPlanes__ passes (47 checks); G1/G2 pass.',
       'On Doous the plane spans the building plus overshoot, not the site; the bottom edge sits 100 mm above the ground cut; a drag snaps the ABSOLUTE position to the chosen increment; Escape restores.',
       'With planes on, a thumbnail, a sheet 3D viewport and an image export contain no plane (W1-01 overlays).'],
  tests=['Na__Test__DrawingPlanes__.test.mjs'],
  src=['WP-S02a-07', 'WP-S09-12R'],
  risk='Category-token mismatch on older VV exports would size planes from the landscape: verify on real projects.',
  notes=['WP-S09-12R (index.html wiring per TV-only system) is realised as: 47 lines here, 49 lines in W2-03, 48 lines in W2-05; 66 ShareOpen goes through the loader (W4-08), never index.html; 27 is not wired on the 3D tab (DR-44).'])

P('W2-02', 'W2', 'Section adapter (DIV-2) completion in VV: Serialize/Apply, outline width, SetModelRoot stub, RenderDepthInto',
  'Give VV\'s SectionAdapter the four calls TV code reaches it for - Serialize/Apply over the Cross Sections tool, the outline width get/set, SetModelRoot as a no-op stub, and RenderDepthInto drawing the Cross Sections tool\'s cap meshes into a bound depth target - so SnapshotRenderer and 49\'s render layer never import a 41 folder.',
  tv=[TVM('40__System__DrawingViewCore/Na__DrawView__SectionAdapter__.js') + ' (interface)'],
  vv=[SADAPT, XSECT],
  hot=[SADAPT, XSECT],
  deps=['W1-99'],
  gated=['DR-01', 'DR-26', 'DR-41', 'DR-42'],
  size='S', est=260,
  adapt=['VV bodies (DIV-2): Serialize/Apply over Na__CrossSection__SerializeSections / ApplySerializedSections; outline width over Na__CrossSection__GetAppearance / SetLineWidth; RenderDepthInto renders CapRoot only into the bound target (autoClear off, no clear, no setRenderTarget), excluding HelperRoot gizmos.',
         'NAMESPACE stays Na__DrawSection (K2 H3); TV\'s half (pass-throughs) is WT-02 under DR-36.'],
  acc=['Section save/restore around a 3D render and the section outline width are unchanged.',
       'RenderDepthInto fills a depth target with the cap faces of an active section and nothing else (unit check with a scratch scene).',
       'G1/G2 pass.'],
  tests=[],
  src=['WP-S04a-15'],
  risk='Touches VV\'s live section tool: keep every adapter function a thin pass-through.')

P('W2-03', 'W2', 'Elevation Depth Fog core and 3D wiring (render layer, Dev row, composer and export hooks)',
  'Land 49\'s RenderLayer (cap depth through the VV SectionAdapter) and Dev row, call Na__ElevFog__RenderOverlay once after composer.render() in RenderPreset.RenderFrame (screen and card thumbnail), give GetExportOverrides a fog-only member that TiledRenderer calls per tile before the section overlay, set/clear the fog source in VV\'s elevation mode controller, and wire the init and stylesheet.',
  tv=[TVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__RenderLayer__.js'), TVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__DevMenu__Row__.js'),
      TVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__Styles__DevMenu__.css'), TVM('45__System__ElevationViews/Na__Elevation__ModeController__.js') + ' (fog-source hook)'],
  vv=[NEW(VVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__RenderLayer__.js')), NEW(VVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__DevMenu__Row__.js')),
      NEW(VVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__Styles__DevMenu__.css')), RPRESET, TILED, EVMC, IDX, CSSIDX],
  hot=[RPRESET, TILED, EVMC, IDX, CSSIDX],
  deps=['W2-01', 'W2-02'],
  gated=['DR-01', 'DR-15', 'DR-32'],
  size='M', est=1150,
  adapt=['RenderLayer: one changed import - Na__DrawView__SectionAdapter__RenderDepthInto instead of TV\'s 41 Na__SectionCut__RenderDepthInto (byte-identical once TV adopts the adapter, WT-02).',
         'DIV-1: the fog call sits after the composer and before drawOverlay; no LoadingSequence call; the projected-linework SVG overlay is not fogged (as TV).',
         'VV keeps its 45 mode controller (DR-32): only TV\'s fog-source hook (SetSource, clear on leaving) is added.',
         'index.html: import and Na__ElevFog__Initialise after the linework block; CSS @import before the DrawView dev sheet.'],
  acc=['Na__Test__ElevationDepthFog__ passes 68/68; a scratch link simulation shows no unresolved name in 49; G1/G2 pass.',
       'On screen with fog on (set by script until W2-05 adds the Dev row block): surfaces, fat SketchUp linework and VV\'s 2D profile lines behind the plane fade into the paper; a section\'s poche stays solid; a perspective camera gets no fog; the card thumbnail shows the fog.',
       'Image export: the raster carries the fog and the section overlay is drawn once per tile; projected vectors behave per DR-15 (exports (a) by default).',
       'VV FogPlane is still off in drawings and still works in 3D; a drawing with fog off renders byte-identical.'],
  tests=['Na__Test__ElevationDepthFog__.test.mjs (re-run with the render layer present)'],
  src=['WP-S02b-04R', 'WP-S09-08'],
  risk='DIV-1/DIV-2 adaptation; without W1-03\'s supersampler clamp baked fog layers are premultiplied-invalid.',
  notes=['WP-S09-08\'s fog-in-LoadingSequence step is superseded by WP-S02b-04R\'s verified design (one call in RenderFrame; S02b verifier); its na-app-scene-ready part is delivered by W0-13.'])

P('W2-04', 'W2', 'Floor Plans Dev menu rebuild (TV 2.0.0 editor and row builders) with VV\'s seams',
  'Take TV\'s floor plan DevMenu Editor 2.0.0 and RowBuilders 2.0.0 whole (drafts, planes, storey row, NOT UPDATED chip, Update dialog, Revert) and re-apply VV\'s seams.',
  tv=[TVM('42__System__FloorPlanViews/Na__FloorPlan__DevMenu__Editor__.js'), TVM('42__System__FloorPlanViews/Na__FloorPlan__DevMenu__RowBuilders__.js')],
  vv=[VVM('42__System__FloorPlanViews/Na__FloorPlan__DevMenu__Editor__.js'), VVM('42__System__FloorPlanViews/Na__FloorPlan__DevMenu__RowBuilders__.js'),
      FPCFG, FPCSS, THUMBBAKE],
  hot=[FPCFG, FPCSS, THUMBBAKE],
  deps=['W2-01'],
  gated=['DR-01', 'DR-32', 'DR-26'],
  size='L', est=1300,
  adapt=['VV seams (DR-32): SectionAdapter calls in place of TV\'s 41 Engine; PlanDim label from 44 ConfigState; SyncSceneGroup on mode change (D28); Styles/Exclusions rows + ApplyStyles (D33) in the Advanced fold; Ground Floor Plan quick action (D11) beside +; ThumbnailBake via SaveBlock and BakeBeforeSave on Update.',
         'AppConfig labels unioned; prove with the module graph that no TV-only import remains.'],
  acc=['TV DrawingMenus plan s.2 items 1-17 reproduced for floor plans: rows fold one at a time; NOT UPDATED chip; the Update dialog names the changes and the sheets drawn from the drawing; Revert restores in place; leaving a changed row asks; a Save Sheets while a row is changed writes the last-updated record (payload guard).',
       'Na__Test__DrawingDrafts__ re-run passes; G1/G2 pass; Adam tests on Doous on localhost.'],
  tests=['Na__Test__DrawingDrafts__.test.mjs (re-run)'],
  src=['WP-S02a-08'],
  risk='Losing a VV seam silently (SectionAdapter, SyncSceneGroup, bake) is the main risk.')

P('W2-05', 'W2', 'Elevations Dev menu rebuild (TV 2.1.0 editor and row builders, fog block included) and the Cross Sections placeholder (48)',
  'Take TV\'s elevation DevMenu Editor 2.1.0 and RowBuilders 2.1.0 whole (identity statement, Advanced bearing, auto names, planes, drafts and the fog block now that 49 exists), port the 48 Cross Sections placeholder panel with its Dev-menu item and init, and rename VV\'s own colliding Cross Section Tool ids.',
  tv=[TVM('45__System__ElevationViews/Na__Elevation__DevMenu__Editor__.js'), TVM('45__System__ElevationViews/Na__Elevation__DevMenu__RowBuilders__.js'),
      TVM('48__System__CrossSectionViews/Na__CrossSection__DevMenu__Editor__.js'), 'TV/Index.html (48 item and init)'],
  vv=[VVM('45__System__ElevationViews/Na__Elevation__DevMenu__Editor__.js'), EVROWB, EVCFG, EVCSS, THUMBBAKE,
      NEW(VVM('48__System__CrossSectionViews/Na__CrossSection__DevMenu__Editor__.js')), IDX, XSECTDEV],
  hot=[EVROWB, EVCFG, EVCSS, THUMBBAKE, IDX, XSECTDEV],
  deps=['W2-03', 'W2-04'],
  gated=['DR-01', 'DR-26', 'DR-32', 'DR-15'],
  size='L', est=1700,
  adapt=['Same VV seams as W2-04 for elevations (SectionAdapter, SyncSceneGroup, D28 filing kept as a temporary divergence with trigger "TV 48 past 0.1.0", Styles/Exclusions rows, bake on add/seed/Update; Elevation__SeededFrom per DR-32).',
         'DR-26 / K2 S4: VV renames its own colliding ids (VV index.html:855-866, 41 DevControls :79-83) to naCrossSectionToolDev* so TV\'s 48 file ports byte-for-byte; the <li> sits between Elevations and North Direction; init in the elevation mode .then.'],
  acc=['TV DrawingMenus plan s.2 items 1-17 reproduced for elevations; + adds an elevation centred on the BUILDING; a Section-mode elevation\'s card moves to Cross Sections; the fog block under View depth turns fog on and off with a render requested on change.',
       'The 48 panel lists the project\'s Section-type elevations and updates on Na__DrawData__CHANGED_EVENT; VV\'s Cross Section Tool Dev item still enables and saves; no DOM id collision in the Dev menu.',
       'G1/G2 pass; Adam tests on Doous on localhost.'],
  tests=[],
  src=['WP-S02a-09'],
  split=['WP-S02a-08'],
  risk='Largest drawing-menu file set (TV editor 1,475 lines): keep every VV seam; id collision if the rename is skipped.')

P('W2-06', 'W2', 'Projected linework (folder 50) to TV HEAD: flush joins, seams occlude, storeys, door pose, modifiers config',
  'Take 13 TV folder-50 files whole and add DoorPose (verbatim below a VV header) over the W2-43 leaves (FlushJoins, Storeys), take the folder\'s AppConfig whole with VV owner keys and a new BuildToken; Persistence stays with W0-14.',
  tv=[TVM('50__System__ProjectedLinework/Na__ProjectedLinework__AppConfig__.json'), TVM('50__System__ProjectedLinework/Na__ProjectedLinework__AuthoredEdges__.js'),
      TVM('50__System__ProjectedLinework/Na__ProjectedLinework__ClipKernel__.js'), TVM('50__System__ProjectedLinework/Na__ProjectedLinework__ConfigAccess__.js'),
      TVM('50__System__ProjectedLinework/Na__ProjectedLinework__CpuBackend__.js'), TVM('50__System__ProjectedLinework/Na__ProjectedLinework__DevMenu__Controls__.js'),
      TVM('50__System__ProjectedLinework/Na__ProjectedLinework__DoorPose__.js'), TVM('50__System__ProjectedLinework/Na__ProjectedLinework__EdgeExtractor__.js'),
      TVM('50__System__ProjectedLinework/Na__ProjectedLinework__ModelStage__.js'),
      TVM('50__System__ProjectedLinework/Na__ProjectedLinework__Pipeline__.js'), TVM('50__System__ProjectedLinework/Na__ProjectedLinework__Projector__.js'),
      TVM('50__System__ProjectedLinework/Na__ProjectedLinework__StageSampler__.js'),
      TVM('50__System__ProjectedLinework/Na__ProjectedLinework__ViewDefinition__.js'), TVM('50__System__ProjectedLinework/Na__ProjectedLinework__WebGpuBackend__.js')],
  vv=[VVM('50__System__ProjectedLinework/Na__ProjectedLinework__AppConfig__.json'), VVM('50__System__ProjectedLinework/Na__ProjectedLinework__AuthoredEdges__.js'),
      VVM('50__System__ProjectedLinework/Na__ProjectedLinework__ClipKernel__.js'), PLCFGACC,
      VVM('50__System__ProjectedLinework/Na__ProjectedLinework__CpuBackend__.js'), VVM('50__System__ProjectedLinework/Na__ProjectedLinework__DevMenu__Controls__.js'),
      NEW(VVM('50__System__ProjectedLinework/Na__ProjectedLinework__DoorPose__.js')), VVM('50__System__ProjectedLinework/Na__ProjectedLinework__EdgeExtractor__.js'),
      VVM('50__System__ProjectedLinework/Na__ProjectedLinework__ModelStage__.js'),
      VVM('50__System__ProjectedLinework/Na__ProjectedLinework__Pipeline__.js'), VVM('50__System__ProjectedLinework/Na__ProjectedLinework__Projector__.js'),
      VVM('50__System__ProjectedLinework/Na__ProjectedLinework__StageSampler__.js'),
      VVM('50__System__ProjectedLinework/Na__ProjectedLinework__ViewDefinition__.js'), VVM('50__System__ProjectedLinework/Na__ProjectedLinework__WebGpuBackend__.js'),
      NEW(TESTDIR + 'Na__Test__StoreyBand__.test.mjs')],
  hot=[PLCFGACC],
  deps=['W2-43'],
  gated=['DR-01', 'DR-31', 'DR-16', 'DR-09'],
  size='L', est=2010, est_note='~1,200 diff lines in 12 shared files + DoorPose 807 new lines',
  adapt=['Seams: VALEVISION3D headers and [ValeVision3D ...] prefix; ValeVision__LineworkModifier__* OwnerKeys in the JSON and the ConfigAccess fallbacks; a new BuildToken (e.g. 2026-10-xx-tv-parity) with the ConfigAccess fallback equal to it (DR-31 (4)); the self-contradicting "Exact match" sentence dropped; no folder-number seam after W0-02.',
         'VV-only integrations kept (S02b-V01): Na__PlExport__Apply (30), Na__PlOverlay__SyncFrame (01), Na__PlStore__BakeBeforeSave (42/45), the na-model-visibility-changed dispatch (26).',
         'Bake gate stays the localhost test (DR-31 (2)); the re-bake (Dev > Bake All to R2) is Adam\'s checklist item, not run by the swarm.'],
  acc=['Normalised code diff of VV 50 against TV 50 empty except identity strings, Persistence (owned by W0-14), OwnerKey prefix and BuildToken; G1/G2 exit 0.',
       'Na__Test__FlushJoins__ 8/8 (re-run) and Na__Test__StoreyBand__ 53/53 incl. "the fallback build token equals the shipped one".',
       'On a VV project with writes refused the Dev timings read "Linework first: off - every mesh crease / Seams occlude: on / Flush joins: hidden"; the same elevation with the rules on and off loses only flush-join and seam-leak segments and the ground line stays whole.',
       'Definitions built outside the Layout Editor carry DoorPose null and their record hashes are unchanged; Bake All to R2 on localhost uploads schema-2 assets with owner tags.'],
  tests=['Na__Test__FlushJoins__.test.mjs (re-run)', 'Na__Test__StoreyBand__.test.mjs'],
  src=['WP-S02b-02R'],
  notes=['Projector/Pipeline 1.5.0 import DoorPose and Storeys (TV import lines), so DoorPose lands with the shared units here; FlushJoins and Storeys import nothing and went first, inert, in W2-43.'],
  risk='The new BuildToken stales every baked VV asset (re-bake needed); existing elevations visibly lose flush-join lines (intended, DR-31 (1)).')

P('W2-07', 'W2', 'Progressive-render remainder of TV v2.58.2',
  'Bring ProgressiveRefine 1.0.2 (planFrame reads its own clock; VV floor kept) and the render-loop guards into VV: ArmNextFrame in a finally, the thrown-frame guard, the 2.5 s refinement watchdog and the engine-hold stand-down.',
  tv=[TVM('05__RenderPipeline/Na__RenderEffect__ProgressiveRefine__.js'), TVM('01__AppCore/Na__AppFlow__LoadingSequence.js') + ' (loop hunks)'],
  vv=[PROGREF, LS],
  hot=[PROGREF, LS],
  deps=['W1-99'],
  gated=['DR-01'],
  size='S', est=250,
  acc=['A fractional composer buffer converges 16/16 in two chunks; a frame that throws does not stop the render loop; with a sheet open and the engine held the refiner paints nothing; git diff --no-index -w of ProgressiveRefine against TV shows header lines only.'],
  tests=[],
  src=['WP-S11-05'],
  risk='VV\'s LoadingSequence differs heavily: hand-adapt the loop hunks; the only W2 LoadingSequence editor.')

P('W2-08', 'W2', 'Main config: profile-line keys aligned with TV for drawing bakes',
  'Align the RenderEffect__ProfileLines Drawing2d keys of Na__AppConfig__Main.json with TV once VV bakes take their width from the RenderComposites profileLinework weight; keep DrawingView__Config and ProjectedLinework__Config.',
  tv=[TVM('02__AppData/Na__AppConfig__Main.json')],
  vv=[MAINCFG],
  hot=[MAINCFG],
  deps=['W2-09'],
  gated=['DR-01'],
  size='S', est=40,
  adapt=['Confirm the live-view width under DIV-1 before dropping Drawing2dEdgeWidth; the two dead DrawingView Transition keys are deleted only by decision.'],
  acc=['Getter diff of Na__DrawCfg__* before and after (TV v2.30.2 method) shows only intended changes; existing VV sheets bake with unchanged outline weight; plan and elevation flights still take 1.4 s.'],
  tests=[],
  src=['WP-S09-09R'],
  risk='Low-medium: line weight on every sheet.')

P('W2-09', 'W2', 'Render-style quick wins: Enhance 1.1.0 strength and RenderComposites 1.3.0 percent weight',
  'Take Enhance 1.1.0 and RenderComposites 1.3.0 whole with the config\'s percent Enhance row; the enhancePct path through Frame/Viewport3d arrives with W2-16 and through SnapshotRenderer with W2-15; Panel__Styles\' % suffix with W2-36.',
  tv=[T25('Na__LayoutEditor__Enhance__.js'), T25('Na__LayoutEditor__RenderComposites__.js'), T25('Na__LayoutEditor__RenderComposites__Config__.json')],
  vv=[V25('Na__LayoutEditor__Enhance__.js'), V25('Na__LayoutEditor__RenderComposites__.js'), COMPCFG, NEW(TESTDIR + 'Na__Test__EnhanceWhitecardStrength__.test.mjs')],
  hot=[COMPCFG],
  deps=['W1-99'],
  gated=['DR-01'],
  size='S', est=200,
  adapt=['Enhance saved as CRLF as in TV; the depthFog config row is added by W2-12.'],
  acc=['Na__Test__EnhanceWhitecardStrength__ passes; G1/G2 pass (in-app strength checks run in W2-15/W2-16).'],
  tests=['Na__Test__EnhanceWhitecardStrength__.test.mjs'],
  src=['WP-S04a-02'],
  risk='Low.')

P('W2-10', 'W2', 'Viewport titles: ViewportTitleText 1.1.0 and the identity config (storey level, typed names)',
  'Take ViewportTitleText 1.1.0 verbatim and the ViewportIdentity config (Phase block, Words__GenericPlan); ViewportIdentity 1.1.0 itself is taken whole in W2-16.',
  tv=[T20('Na__LayoutEditor__ViewportTitleText__.js'), T20('Na__LayoutEditor__ViewportIdentity__Config__.json')],
  vv=[V20('Na__LayoutEditor__ViewportTitleText__.js'), V20('Na__LayoutEditor__ViewportIdentity__Config__.json'), TESTDIR + 'Na__Test__ViewportTitleText__.test.mjs'],
  hot=[],
  deps=['W1-99'],
  gated=['DR-01'],
  size='S', est=160,
  acc=['Na__Test__ViewportTitleText__ (TV version) passes on VV\'s copy; with no storey every title on VV sheets reads exactly as before; a plan with a storey letters PROPOSED GROUND FLOOR PLAN by TV\'s rules.'],
  tests=['Na__Test__ViewportTitleText__.test.mjs (TV version replaces VV\'s)'],
  src=['WP-S04a-09'],
  risk='Low.')

P('W2-11', 'W2', 'Plan doors leaf (PlanDoors 1.3.0, inert until the viewport convergence)',
  'Port PlanDoors__.js with VV config values (SwingCategoryKeys ValeVision__Linetype__DoorSwings, HideSwingsOnStoreys roof); its viewport hooks arrive with W2-16, its SnapshotRenderer door-pose hunk with W2-15, its click and menu with the W3-03 hub, its panel rows with W3-15.',
  tv=[T20('Na__LayoutEditor__PlanDoors__.js')],
  vv=[NEW(V20('Na__LayoutEditor__PlanDoors__.js'))],
  hot=[],
  deps=['W2-06'],
  gated=['DR-01', 'DR-16'],
  size='S', est=460,
  adapt=['Config values live in the LE AppConfig keys W0-15 added (app-token category keys per K2 K3).'],
  acc=['G1/G2 pass with the module present (imports resolve: Na__LeSnap__GetModelRoot, Na__FpData__GetStoreyLevel, Na__PlDoors__HitTest, Na__PlProjector__SCALE_DIVISOR, Na__LeVpRot__Contains).'],
  tests=[],
  src=['WP-S04a-06'],
  risk='VV has no storeys: the storey behaviours must stay inert, not error (checked in W2-16).')

P('W2-12', 'W2', 'Depth fog on sheets: Viewport2d__DepthFog leaf, the composites depthFog row and VV\'s TiledRenderer render-frame route',
  'Port Viewport2d__DepthFog (no path seam after W0-02), add the RenderComposites config depthFog row and an opt-in renderFrame callback route in VV\'s TiledRenderer for SnapshotRenderer\'s fog (reverses TV TiledRenderer\'s PORT NOTE on purpose, DIV-1).',
  tv=[T20('Na__LayoutEditor__Viewport2d__DepthFog__.js'), T25('Na__LayoutEditor__RenderComposites__Config__.json') + ' (depthFog row)'],
  vv=[NEW(V20('Na__LayoutEditor__Viewport2d__DepthFog__.js')), COMPCFG, TILED],
  hot=[COMPCFG, TILED],
  deps=['W2-03', 'W2-09'],
  gated=['DR-01', 'DR-15'],
  size='S', est=320,
  adapt=['Sheets (a) per DR-15: VV\'s composer path renders the underlay unfogged; the fog layer is TV\'s frame layer.'],
  acc=['G1/G2 pass; the TiledRenderer route is opt-in and a sheet bake without fog is byte-identical (in-app fog-on-sheet checks run in W2-16 and W3-16).'],
  tests=[],
  src=['WP-S04a-07R'],
  risk='The TiledRenderer route is new code on VV\'s DIV-1 renderer: keep it opt-in.')

P('W2-13', 'W2', 'Linework modifiers: VV LineworkSettings extension and the model-layers config',
  'Extend VV Na__LineworkSettings so SnapshotRenderer can apply TV\'s modifier rules, and take ModelLayers__Config__.json with the linework-modifiers group as ValeVision__LineworkModifier__*; the Line scale column and ModelLayers 1.4.0 arrive whole with W2-16.',
  tv=[T25('Na__LayoutEditor__ModelLayers__Config__.json')],
  vv=[LWSETTINGS, V25('Na__LayoutEditor__ModelLayers__Config__.json'), NEW(TESTDIR + 'Na__Test__LineworkModifiers__.test.mjs')],
  hot=[LWSETTINGS],
  deps=['W2-06'],
  gated=['DR-01', 'DR-31'],
  size='S', est=350,
  adapt=['VV-only test name (K2 F7 pattern); a fixture GLB with 76-79 tagged nodes (TV test model or synthetic) because no Vale project carries modifier tags today (S04a-V... Doous GLBs carry none).'],
  acc=['With no modifier tags every key and picture is unchanged; on the fixture switching a modifier row off removes it from both vectors and base image (run after W2-16).'],
  tests=['Na__Test__LineworkModifiers__.test.mjs (VV-only, new; fixture-based)'],
  src=['WP-S04a-08R'],
  risk='No Vale data exercises the modifier half today: the fixture is required.')

P('W2-14', 'W2', 'Site-plan client leaves, dormant: GlbParse, Store on the VV facade, Panel__SitePlanComposites',
  'Create LE/21__System__SitePlanData (GlbParse verbatim; Store with VV identity, R2-then-GitHub fallback, build token, WCP static path on localhost and stem renaming on read) and the site-plan composites panel, with a VV config gate keeping the Drawing Type row hidden until a Vale pipeline exists (DR-08 (B)).',
  tv=[TLE('21__System__SitePlanData/Na__SitePlan__GlbParse__.js'), TLE('21__System__SitePlanData/Na__SitePlan__Store__.js'),
      TLE('40__Ui__Panels/Na__LayoutEditor__Panel__SitePlanComposites__.js')],
  vv=[NEW(VLE('21__System__SitePlanData/Na__SitePlan__GlbParse__.js')), NEW(VLE('21__System__SitePlanData/Na__SitePlan__Store__.js')),
      NEW(VLE('40__Ui__Panels/Na__LayoutEditor__Panel__SitePlanComposites__.js')), AC,
      NEW(TESTDIR + 'Na__Test__SitePlanStore__.test.mjs'), NEW(TESTDIR + 'Na__Test__SitePlanComposites__.test.mjs'),
      NEW(TESTDIR + 'Na__Test__SitePlanComposites__Output__.html')],
  hot=[AC],
  deps=['W1-99'],
  gated=['DR-01', 'DR-08', 'DR-29'],
  size='M', est=1500,
  adapt=['Store over the W0-12 facade names (Na__CfApi__GetLoadedProjectData, CDN builders) - never cdn.noble-architecture.com/NaProjectPortal; identity from the URL token through the master index; TV folder names SitePlan__DrawingData__{Existing,Proposed}/ and project key SitePlan__DataStores inside VV\'s prefix; manifest stems TrueVision__SitePlan__ -> ValeVision__SitePlan__ on read (S04a-V04); both manifest names accepted.',
         'VV-only AppConfig key gating the Drawing Type row (offered to TV, DR-42 (8)); VV labels (SitePlanNoData names VV folders); OS licence items stay empty (DR-08).',
         'PORT NOTEs state the deliberate override of TV composites plan 3.5 ("surgical merge of the non-site-plan parts only").'],
  acc=['Na__Test__SitePlanStore__ and Na__Test__SitePlanComposites__ pass on VV modules; G1/G2 pass; with the gate off nothing on any VV sheet or panel changes.'],
  tests=['Na__Test__SitePlanStore__.test.mjs', 'Na__Test__SitePlanComposites__.test.mjs', 'Na__Test__SitePlanComposites__Output__.html'],
  src=['WP-S04a-10R'],
  risk='Store is the only adapted file; a wrong base would point VV at NA\'s portal - G6 and the naming lint catch it.')

P('W2-15', 'W2', 'SnapshotRenderer realignment to TV 1.13.0 (DIV-1 hunk replay, one owner)',
  'Replay every TV SnapshotRenderer hunk since 1.7.0 into VV\'s composer-based renderer in one package: design-phase lines, door pose, the fog route through the W2-12 TiledRenderer callback (underlays unfogged), modifier rules through the W2-13 LineworkSettings extension, enhancePct on both paths, and section save/restore through the W2-02 adapter.',
  tv=[T25('Na__LayoutEditor__SnapshotRenderer__.js') + ' (1.7.0 -> 1.13.0 hunks)'],
  vv=[SNAPR],
  hot=[SNAPR],
  deps=['W2-02', 'W2-06', 'W2-09', 'W2-11', 'W2-12', 'W2-13'],
  gated=['DR-01', 'DR-09', 'DR-15', 'DR-16', 'DR-31'],
  size='L', est=750, est_note='700 diff lines replayed by hand onto VV\'s DIV-1 body',
  adapt=['DIV-1 seams kept (S04a-F07): VV composer route, VV profile-line caches (InvalidateSceneCaches mapped to them), VV\'s own lighting; SnapshotRenderer stays a hunk-replayed file (never taken whole).',
         'Phase lines: EnterPhase / ExitPhase / PhaseFingerprints / OnPhaseChanged / GetModelRoot(id) over the uninitialised PhaseLibrary (W1-01).',
         'No import from any 41 folder (adapter only); entourage silhouettes stay in CONTEXT_CATEGORIES (VV already right; TV fix is WT-04).'],
  acc=['Neither VV SnapshotRenderer nor 49 imports from 41__; section save/restore around a 3D render and the outline width are unchanged.',
       'Every VV render key and picture on 3047__Doous is identical before and after with features off; Enhance strength 0 skips both passes and 100 is pixel-identical to the old pass; LE underlay renders stay unfogged (fog source nulled).',
       'G1/G2 pass.'],
  tests=[],
  src=[],
  split=['WP-S04a-02', 'WP-S04a-05R', 'WP-S04a-06', 'WP-S04a-07R', 'WP-S04a-08R', 'WP-S04a-15'],
  risk='One agent owns the whole file for W2 so six features\' hunks never collide; losing a DIV-1 seam would change every sheet bake.')

P('W2-16', 'W2', 'Viewport units whole-file convergence with Model Source and the site-plan painter (one import cycle)',
  'Take Viewport2d, Viewport2d__Frame, Viewport2d__Linework, Viewport2d__Window, Viewport3d, ViewportIdentity, EdgeStyles, ModelLayers and Panel__ModelLayers whole from TV HEAD, together with ModelSource and the Viewport2d__SitePlan painter (Linework -> ModelSource -> painter -> Linework), and wire Model Source and the site-plan composites in the ModeController; this is where plan doors, fog on sheets, modifiers, draft-mode render guards and dormant site plans go live.',
  tv=[T20('Na__LayoutEditor__Viewport2d__.js'), T20('Na__LayoutEditor__Viewport2d__Frame__.js'), T20('Na__LayoutEditor__Viewport2d__Linework__.js'),
      T20('Na__LayoutEditor__Viewport2d__Window__.js'), T20('Na__LayoutEditor__Viewport3d__.js'), T20('Na__LayoutEditor__ViewportIdentity__.js'),
      T25('Na__LayoutEditor__EdgeStyles__.js'), T25('Na__LayoutEditor__EdgeStyles__Config__.json'), T25('Na__LayoutEditor__ModelLayers__.js'),
      TLE('40__Ui__Panels/Na__LayoutEditor__Panel__ModelLayers__.js'), T20('Na__LayoutEditor__ModelSource__.js'), T20('Na__LayoutEditor__Viewport2d__SitePlan__.js'),
      TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (Model Source and site-plan composites hunks)'],
  vv=[V20('Na__LayoutEditor__Viewport2d__.js'), V20('Na__LayoutEditor__Viewport2d__Frame__.js'), V20('Na__LayoutEditor__Viewport2d__Linework__.js'),
      V20('Na__LayoutEditor__Viewport2d__Window__.js'), V20('Na__LayoutEditor__Viewport3d__.js'), V20('Na__LayoutEditor__ViewportIdentity__.js'),
      V25('Na__LayoutEditor__EdgeStyles__.js'), V25('Na__LayoutEditor__EdgeStyles__Config__.json'), V25('Na__LayoutEditor__ModelLayers__.js'),
      VLE('40__Ui__Panels/Na__LayoutEditor__Panel__ModelLayers__.js'), NEW(V20('Na__LayoutEditor__ModelSource__.js')), NEW(V20('Na__LayoutEditor__Viewport2d__SitePlan__.js')),
      MC, NEW(TESTDIR + 'Na__Test__SitePlanFaces__.test.mjs'), NEW(TESTDIR + 'Na__Test__HideSwings__.test.mjs')],
  hot=[MC, V20('Na__LayoutEditor__Viewport2d__.js'), V20('Na__LayoutEditor__Viewport2d__Frame__.js'), V20('Na__LayoutEditor__Viewport2d__Linework__.js'),
       V20('Na__LayoutEditor__Viewport2d__Window__.js'), V20('Na__LayoutEditor__Viewport3d__.js')],
  deps=['W2-15', 'W2-10', 'W2-14', 'W2-11', 'W2-12', 'W2-13', 'W2-35'],
  gated=['DR-01', 'DR-08', 'DR-09', 'DR-15', 'DR-16', 'DR-31', 'DR-40'],
  size='L', est=2400, est_note='~1,350 diff lines in 9 shared files + 938 new (ModelSource, painter)',
  adapt=['Whole-file takes re-apply only header, console prefix and ValeVision__ literals (no folder-number seams after W0-02); ModelSource verbatim (DR-09 (a), possible now that the site-plan leaves and PhaseLibrary exist - no adapted interim, no swap).',
         'ModeController hunks at TV positions: Na__LeSource__Initialize and the PhaseLib listener; Na__LeSpComp__Ready in the Ready Promise.all; Na__LePanelSpComp__Register after Styles (hidden off a site-plan sheet).',
         'Model Source row and menu items stay hidden exactly as TV hides them on one-model projects (DR-09); vector quality defaults to Medium already (W1-28).'],
  acc=['A normalised diff (prefix and header removed) of each of the nine files against TV is empty; G1/G2 pass.',
       'No visible change on any VV project for Model Source (row and menu hidden); PhaseLibrary reports no groups; Resolve().renderId is null for every viewport; every render key and picture on 3047__Doous identical before and after apart from plan doors.',
       'Plan doors (DR-16): on 3047__Doous a plan viewport draws doors open with swings; elevation and section viewports draw every door shut in linework, base image and PDF; Hide swings removes arcs and door-swing linework; the 3D view\'s doors never move; Na__Test__HideSwings__ and Na__Test__StoreyBand__ pass.',
       'Fog on sheets: the frame stack reads underlay, linework, fog, markup; turning a drawing\'s fog on or off re-renders neither underlay nor linework; viewports with no fog cost nothing; a section drawing\'s fog treats the cut faces as on the plane.',
       'Modifiers: a Line scale of 0.5 halves dash and gap lengths only; a non-dashed row\'s box is disabled; the W2-13 fixture switches a modifier row off in vectors and base image.',
       'Site plans dormant: with the gate off nothing changes; with the gate on and a test store a 1:500 block plan and a 1:1250 location plan paint, snap and print; a TV-written Viewport__SitePlan record round-trips unchanged apart from the category prefix; Na__Test__SitePlanFaces__ passes.',
       'Enhance: typing 40 stores Viewport__CompositeWeights { enhanceWhitecard: 40 } and re-keys both the 2D and 3D raster tokens.'],
  tests=['Na__Test__SitePlanFaces__.test.mjs', 'Na__Test__HideSwings__.test.mjs', 'Na__Test__StoreyBand__.test.mjs (re-run)', 'Na__Test__ElevationDepthFog__.test.mjs (sheet part)'],
  src=['WP-S04a-14', 'WP-S04a-05R'],
  split=['WP-S04a-10R', 'WP-S04a-06', 'WP-S04a-07R', 'WP-S04a-08R', 'WP-S04a-02', 'WP-S04b-04'],
  risk='Any missing import stops the whole editor (LE/01 loader import()): run G1 before committing; plan doors are a visible change Adam accepted under DR-16.',
  notes=['The S04a verifier planned hunk replays into these eight files until a final whole-file take (S04a-V01). Because every import they need now lands earlier (W1-14, W1-23, W2-06..W2-14), K3 takes them whole once, here, and drops the interim replays.'])

P('W2-17', 'W2', 'Layout Editor Dev menu: the live-phase bake filter and the Layout Mode row',
  'Keep VV\'s Dev menu 1.4.0 and add TV 1.2.0\'s live-phase bake filter through the loader (a literal modelSource import in ImportEditor) now that ModelSource exists, applying the Layout Mode decision (DR-25).',
  tv=[TLE('70__DevTools__DevMenu/Na__LayoutEditor__DevMenu__Controls__.js') + ' (1.2.0 live-phase filter)'],
  vv=[DEVMENU, LDR],
  hot=[DEVMENU, LDR],
  deps=['W2-16', 'W2-18'],
  gated=['DR-01', 'DR-09', 'DR-25'],
  size='S', est=80,
  acc=['Bake names a drawing for linework only when its viewport draws the live phase (when design phases exist); the Dev section still loads before the editor and opens on the first click.'],
  tests=[],
  src=['WP-S03a-08'],
  risk='Low.')

P('W2-18', 'W2', 'Drafting-aid modules: Draft mode, Drawing Grid, Ortho mode and Drawing Axes (inert until W3-05)',
  'Port LE/26 DraftMode (controller, config, CSS), LE/27 DrawingGrid (controller, panel, config, CSS), LE/32 OrthoMode (controller, config) and LE/33 DrawingAxes (controller, config, CSS) - the State leaves landed in W1-14 - and add the three stylesheets to Na__LeLoad__STYLESHEETS in TV\'s order around 28\'s.',
  tv=[TLE('26__System__DraftMode/Na__LayoutEditor__DraftMode__.js'), TLE('26__System__DraftMode/Na__LayoutEditor__DraftMode__Config__.json'),
      TLE('26__System__DraftMode/Na__LayoutEditor__Styles__DraftMode__.css'), TLE('27__System__DrawingGrid/Na__LayoutEditor__DrawingGrid__.js'),
      TLE('27__System__DrawingGrid/Na__LayoutEditor__Panel__DrawingGrid__.js'), TLE('27__System__DrawingGrid/Na__LayoutEditor__DrawingGrid__Config__.json'),
      TLE('27__System__DrawingGrid/Na__LayoutEditor__Styles__DrawingGrid__.css'), TLE('32__System__OrthoMode/Na__LayoutEditor__OrthoMode__.js'),
      TLE('32__System__OrthoMode/Na__LayoutEditor__OrthoMode__Config__.json'), TLE('33__System__DrawingAxes/Na__LayoutEditor__DrawingAxes__.js'),
      TLE('33__System__DrawingAxes/Na__LayoutEditor__DrawingAxes__Config__.json'), TLE('33__System__DrawingAxes/Na__LayoutEditor__Styles__DrawingAxes__.css')],
  vv=[NEW(VLE('26__System__DraftMode/Na__LayoutEditor__DraftMode__.js')), NEW(VLE('26__System__DraftMode/Na__LayoutEditor__DraftMode__Config__.json')),
      NEW(VLE('26__System__DraftMode/Na__LayoutEditor__Styles__DraftMode__.css')), NEW(VLE('27__System__DrawingGrid/Na__LayoutEditor__DrawingGrid__.js')),
      NEW(VLE('27__System__DrawingGrid/Na__LayoutEditor__Panel__DrawingGrid__.js')), NEW(VLE('27__System__DrawingGrid/Na__LayoutEditor__DrawingGrid__Config__.json')),
      NEW(VLE('27__System__DrawingGrid/Na__LayoutEditor__Styles__DrawingGrid__.css')), NEW(VLE('32__System__OrthoMode/Na__LayoutEditor__OrthoMode__.js')),
      NEW(VLE('32__System__OrthoMode/Na__LayoutEditor__OrthoMode__Config__.json')), NEW(VLE('33__System__DrawingAxes/Na__LayoutEditor__DrawingAxes__.js')),
      NEW(VLE('33__System__DrawingAxes/Na__LayoutEditor__DrawingAxes__Config__.json')), NEW(VLE('33__System__DrawingAxes/Na__LayoutEditor__Styles__DrawingAxes__.css')),
      LDR],
  hot=[LDR],
  deps=['W2-19'],
  gated=['DR-01', 'DR-40', 'DR-05'],
  size='M', est=2300,
  adapt=['Config Meta reworded for VV; Drawing Grid defaults are TV\'s (DR-40 item 5 adopted, from Adam\'s NA A2 LayOut template); Vale font token for the Draft CSS note if Adam chooses.',
         'Draft hunks into Viewport2d/Frame/Viewport3d are not replayed: those files came whole in W2-16 with the hunks (WP-S04b-04\'s module half only).'],
  acc=['Files present; G1/G2 pass with no import cycle (the viewports import only DraftMode__State); code regions identical to TV (diff shows header and console lines only); Na__Test__LoaderStylesheets__ passes with DraftMode, DrawingGrid, ObjectSnap, DrawingAxes in TV\'s order.',
       'Rule and controller sections of Na__Test__OrthoMode__ and the state section of Na__Test__DrawingGrid__ pass (full suites in W3-05).'],
  tests=['Na__Test__OrthoMode__.test.mjs (rule and controller sections)', 'Na__Test__DrawingGrid__.test.mjs (state section)', 'Na__Test__DrawingAxes__.test.mjs (module sections)'],
  src=['WP-S04b-03', 'WP-S04b-04', 'WP-S04b-05', 'WP-S04b-10'],
  risk='Low; DrawingGrid, OrthoMode, DrawingAxes import Measurements Say (W2-23) and DrawingAxes imports ObjectSnap Marker (W2-19).')

P('W2-19', 'W2', 'Object snap switch-over: Search, Moves, GridMoves, controller, Menu and stylesheet, with a cycle-free Snapping shim and the test bundle',
  'Port the remaining six core files of LE/28__System__ObjectSnap (Search, Moves, GridMoves, the controller, Menu, the stylesheet) over the W2-42 leaves with VV headers and link its stylesheet after Main__Paper; in the same commit delete VV\'s old snap-marker CSS, replace Snapping__.js with a shim importing only __Search__ and __State__ (TONE names as local constants, never the controller), and repoint Keyboard, Toolbar, SheetTools ContextMenu and ModeController to the controller/Search.',
  tv=[TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Search__.js'), TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Moves__.js'),
      TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__GridMoves__.js'), TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__.js'),
      TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Menu__.js'), TLE('28__System__ObjectSnap/Na__LayoutEditor__Styles__ObjectSnap__.css'),
      'TV/80__Testing__PrototypeEnvironment/Na__TestEnv__ObjectSnapBundle__.cjs'],
  vv=[NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Search__.js')), NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Moves__.js')),
      NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__GridMoves__.js')), NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__.js')),
      NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Menu__.js')), NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__Styles__ObjectSnap__.css')),
      SNAPPING, PAPER, LDR, ST_KEY, TOOLBAR, ST_CTX, MC,
      NEW(TESTDIR + 'Na__TestEnv__ObjectSnapBundle__.cjs'), NEW(TESTDIR + 'Na__Test__ObjectSnap__.test.mjs')],
  hot=[SNAPPING, PAPER, LDR, ST_KEY, TOOLBAR, ST_CTX, MC],
  deps=['W2-23', 'W2-20', 'W2-42'],
  gated=['DR-01', 'DR-05', 'DR-40', 'DR-07'],
  size='L', est=2420, est_note='TV 657 + 159 + 330 + 309 + 350 + 432 lines verbatim + shim + 4 one-line repoints + CSS deletion',
  adapt=['Shim (K2 FR-14): Snapping__.js imports ONLY __Search__ (Find, Snap, ShowMarker, HideMarker, Clear, IsEnabled, KIND_END, KIND_MID) and __State__ (CHANGED_EVENT), declares TONE_VERTEX/\'vertex\', TONE_DIMENSION/\'dimension\', TONE_VIEWPORT/\'viewport\' locally (TV did the same, ObjectSnap__.js:60-63); it is deleted by W3-08.',
         'Delete VV\'s old .na-le-osnap, tone, [hidden] and --mid rules (Styles__Main__Paper__.css:296-337, keeping .na-le-frame__progress) and .na-le-osnap--infer (:577-581); keep the storage key na-layouteditor-osnap and VV\'s F3 event name.',
         'Repoints: Keyboard__.js:123 (Toggle), Toolbar__.js:110 (CHANGED_EVENT, IsEnabled, Toggle), SheetTools__ContextMenu__.js:100 (Toggle, IsEnabled) -> ../28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__.js; ModeController__.js:228 (Clear) -> __Search__.',
         'Snap markers coloured by target (DR-40 item 2 adopted: orange changes meaning, named in the Port Record).'],
  acc=['The remaining Snapping__ importers (HitResolution, PointerDrag, Dimension/Shape/Rectangle/Leader tools) still link; G1/G2 exit 0; grep finds no import of Na__LayoutEditor__ObjectSnap__.js in Snapping__.js or in 35__System__DrawingTools.',
       'Markers are SVG glyphs coloured by target (purple linework, blue vector, orange text, red dimension, slate paper/grid) with no bordered box and no clipped triangle; at 32x the marker\'s middle sits on the vertex.',
       'F3, the toolbar Snap button and the context-menu row still switch snapping and echo <Osnap on>/<Osnap off>; text corners, the Modern title block and the notes-margin divider snap; Intersection and Centre are found; Nearest is off by default.',
       'Na__Test__ObjectSnap__ and the bundle pass; every name in S04b report b.11 resolves (WP-S04b-02R\'s check: Measurements Say, ZOOM_SETTLED_EVENT, GetSheetChrome, IsLayerSelectable, ShapeGeometry rings, GetSnappingSetup - all delivered by W0-15/W1 whole-file ports).'],
  tests=['Na__TestEnv__ObjectSnapBundle__.cjs', 'Na__Test__ObjectSnap__.test.mjs'],
  src=['WP-S04b-06R', 'WP-S04b-02R', 'WP-S01-04R', 'WP-S04b-14'],
  risk='Snap behaviour changes visibly in one step; Keyboard/Toolbar/ContextMenu/ModeController are also edited later by W3-03/W5-01/W3-05 (different waves).',
  notes=['The CSS deletion, the shim and the four repoints land in the same commit as the controller (S04b verifier: otherwise VV\'s snap marker breaks or a link cycle forms); the seven leaves went first, inert, in W2-42.',
         'WP-S04b-14 (the drafting-aid test harness) is realised by porting the path-generic bundle here and each suite with the package that lands last among its modules (DR-05): OrthoMode/DrawingGrid/DrawingAxes W3-05, GroupMoveSnapping/MoveRetype W3-03, PaintedOnThePoint W2-24, MoveAnchor W3-04.'])

P('W2-20', 'W2', 'Context menu 1.1.0 flyouts and the hover tooltip',
  'Take the context-menu renderer 1.1.0 verbatim, add SheetTools__HoverTooltip 1.1.0, and port their Paper CSS rules (flyout, hint, hinted, mixed, open, submenu; .na-le-hovertip, [hidden], __lead).',
  tv=[TLE('30__System__SheetTools/Na__LayoutEditor__ContextMenu__.js'), TLE('30__System__SheetTools/Na__LayoutEditor__SheetTools__HoverTooltip__.js'),
      TLE('10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__Paper__.css') + ' (menu and tooltip rules)'],
  vv=[VLE('30__System__SheetTools/Na__LayoutEditor__ContextMenu__.js'), NEW(VLE('30__System__SheetTools/Na__LayoutEditor__SheetTools__HoverTooltip__.js')), PAPER],
  hot=[PAPER],
  deps=['W1-99'],
  gated=['DR-01'],
  size='S', est=480,
  acc=['Every existing VV menu (sheet items, Custom Scrapbook panel, Parametric grips and noodle) opens, places and closes as before; a scripted Na__LeMenu__Open with a submenu item opens a flyout that Escape closes first; G2 passes.'],
  tests=[],
  src=['WP-S05a-03', 'WP-S10-11'],
  risk='Low; exports unchanged.',
  notes=['WP-S10-11\'s LayerMenu and NoteTooltip land in W2-21; its menu rows, hover pass and attach/detach arrive with the W3-03 hub, where its acceptance (Layer row flyout, 0.5 s note tooltip) is checked.'])

P('W2-21', 'W2', 'SheetTools leaf modules, first set: EditScope 1.4.0, ItemClipboard 1.7.0, SelectionSet, SelectionBox, Eyedropper, LayerMenu, NoteTooltip',
  'Take the SheetTools leaves whose exports are supersets of VV\'s whole (EditScope with WithAdoption, ItemClipboard with cut/cross-sheet/exact in-place paste, SelectionSet, SelectionBox, Eyedropper 1.9.0 + v2.152.0) and add LayerMenu and NoteTooltip, unused until the hub wires them.',
  tv=[TLE('30__System__SheetTools/Na__LayoutEditor__EditScope__.js'), TLE('30__System__SheetTools/Na__LayoutEditor__ItemClipboard__.js'),
      TLE('30__System__SheetTools/Na__LayoutEditor__SelectionSet__.js'), TLE('30__System__SheetTools/Na__LayoutEditor__SelectionBox__.js'),
      TLE('30__System__SheetTools/Na__LayoutEditor__Eyedropper__.js'), TLE('30__System__SheetTools/Na__LayoutEditor__LayerMenu__.js'),
      TLE('30__System__SheetTools/Na__LayoutEditor__SheetTools__NoteTooltip__.js')],
  vv=[VLE('30__System__SheetTools/Na__LayoutEditor__EditScope__.js'), VLE('30__System__SheetTools/Na__LayoutEditor__ItemClipboard__.js'),
      VLE('30__System__SheetTools/Na__LayoutEditor__SelectionSet__.js'), VLE('30__System__SheetTools/Na__LayoutEditor__SelectionBox__.js'),
      VLE('30__System__SheetTools/Na__LayoutEditor__Eyedropper__.js'), NEW(VLE('30__System__SheetTools/Na__LayoutEditor__LayerMenu__.js')),
      NEW(VLE('30__System__SheetTools/Na__LayoutEditor__SheetTools__NoteTooltip__.js')), NEW(TESTDIR + 'Na__Test__LayerMenu__.test.mjs')],
  hot=[],
  deps=['W2-20'],
  gated=['DR-01', 'DR-40'],
  size='L', est=1800,
  adapt=['VV\'s paste "kept on the paper" adaptation dropped (DR-40 item 1 adopted, named in the Port Record).'],
  acc=['G2 passes; Ctrl+C / Ctrl+V of text, a group and a vector on the same sheet and onto another sheet land in place; Scrapbook, Custom and Parametric drops still land through InsertSet; Na__Test__LayerMenu__ passes.'],
  tests=['Na__Test__LayerMenu__.test.mjs'],
  src=['WP-S05a-06'],
  risk='Visible clipboard behaviour change (Cut/Copy/Duplicate rows; exact in-place paste).')

P('W2-22', 'W2', 'Note-regions tool leaf (NoteRegions__Tool 1.0.0, inert ahead of the hub)',
  'Port the Region tool module verbatim so Measurements 1.10.0 and the hub can import it; no dispatch hunks.',
  tv=[TLE('50__Feature__Specification/Na__LayoutEditor__NoteRegions__Tool__.js')],
  vv=[NEW(VLE('50__Feature__Specification/Na__LayoutEditor__NoteRegions__Tool__.js'))],
  hot=[],
  deps=['W1-99'],
  gated=['DR-01', 'DR-05'],
  size='S', est=270,
  acc=['G1/G2 pass with the module present and not imported; imports resolve (SheetModel AddNoteRegion/UpdateNoteRegion, SheetRecords__NoteRegions NoteRegionById, SheetLayout Solve/ClampToPage, the seven RectangleTool exports); git diff --no-index -w against TV shows header and PORT NOTE only.'],
  tests=[],
  src=['WP-S06b-07a'],
  risk='Very low.')

P('W2-23', 'W2', 'Measurements box 1.10.0 (with the Say echo line the drafting aids import)',
  'Take the Measurements box 1.10.0 whole: settle on zoom, Na__LeMeasure__Say, live retype, arrays, area and region tool readings; every new context call is typeof-guarded so it runs on VV\'s pre-hub orchestrator.',
  tv=[TLE('30__System__SheetTools/Na__LayoutEditor__Measurements__.js')],
  vv=[VLE('30__System__SheetTools/Na__LayoutEditor__Measurements__.js')],
  hot=[],
  deps=['W2-22'],
  gated=['DR-01'],
  size='M', est=400,
  acc=['G1/G2 pass; the box still reads and types for Draw, Rectangle and Dimension and for vertex, dimension-end and frame drags on VV\'s pre-hub orchestrator; a zoom places the box once, when it settles.'],
  tests=[],
  src=['WP-S05a-07Ra'],
  risk='Na__Test__MoveRetype__ needs the hub: checked in W3-03.')

P('W2-24', 'W2', 'Grips 1.12.0 and its Paper CSS (painted on the point)',
  'Take Grips 1.12.0 whole with its CSS in one commit (free/bound/online states, picked box-shadow, 2 px rubber band and box, insert diamond without rotate(45deg)), and run the cross-slice "painted on the point" gate.',
  tv=[TLE('30__System__SheetTools/Na__LayoutEditor__Grips__.js'), TLE('10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__Paper__.css') + ' (grip rules)'],
  vv=[VLE('30__System__SheetTools/Na__LayoutEditor__Grips__.js'), PAPER, NEW(TESTDIR + 'Na__Test__PaintedOnThePoint__.test.mjs')],
  hot=[PAPER],
  deps=['W2-19', 'W2-21'],
  gated=['DR-01'],
  size='M', est=450,
  adapt=['Console prefixes [ValeVision3D LayoutEditor] re-applied at TV :445 and :459.'],
  acc=['At 32x on a 150% display the marker, the painted wall corner and a snapped grip coincide within 0.3 device px; a vertex grip sits on its vertex and the band is one line on the line it stands for.',
       'An open vector\'s vertices on drawing points are solid green, those on a line a green ring, free ones blue; a picked vertex is red and readable at any zoom; the insert diamond is still a diamond.',
       'Na__Test__PaintedOnThePoint__ passes; G1/G2 pass.'],
  tests=['Na__Test__PaintedOnThePoint__.test.mjs'],
  src=['WP-S05a-07Rb', 'WP-S04b-13'],
  risk='CSS and JS must ship in one commit.')

P('W2-25', 'W2', 'Move anchor and viewport snap move modules (inert; gestures switched on by W3-04)',
  'Port MoveAnchor (and config) and ViewportSnapMove 1.6.0 so the hub can import them, with the carry CSS and TV\'s INTEGRATION paragraph in VV\'s AxisLock header; the press, drag and key wiring arrives with the W3-03 hub and the gestures are held until DR-40 items 9-10 are confirmed.',
  tv=[TLE('28__System__ObjectSnap/Na__LayoutEditor__MoveAnchor__.js'), TLE('28__System__ObjectSnap/Na__LayoutEditor__MoveAnchor__Config__.json'),
      TLE('28__System__ObjectSnap/Na__LayoutEditor__ViewportSnapMove__.js'), TLE('10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__Paper__.css') + ' (carry rules :824-887)'],
  vv=[NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__MoveAnchor__.js')), NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__MoveAnchor__Config__.json')),
      NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ViewportSnapMove__.js')), PAPER, VLE('30__System__SheetTools/Na__LayoutEditor__AxisLock__.js')],
  hot=[PAPER],
  deps=['W2-24', 'W2-23'],
  gated=['DR-01', 'DR-40'],
  size='M', est=1450,
  acc=['G1/G2 pass with both modules present and unwired; the carry config keys (ViewportCarry, ViewportTracking, AcquireDwellMs, AcquireMax, TrackMarkerSizePx) and MoveAnchorModifier resolve from W0-15 config.'],
  tests=[],
  src=['WP-S04b-12', 'WP-S04b-11R'],
  risk='Low while unwired; the in-app gestures (DR-40 items 9-10) are W3-04\'s.')

P('W2-26', 'W2', 'Drawing tools onto object snap, grid and ortho (DimensionTool 1.12.0, RectangleTool 1.4.0, TextTool 1.4.0, LeaderTool 1.2.0)',
  'Take the four drawing tools whole below VV headers - they import ObjectSnap Search instead of VV Snapping, use target constants, pass options.from, resolve Ortho and grid snap; ShapeTool lands with the vector tools in W3-07.',
  tv=[TLE('35__System__DrawingTools/Na__LayoutEditor__DimensionTool__.js'), TLE('35__System__DrawingTools/Na__LayoutEditor__RectangleTool__.js'),
      TLE('35__System__DrawingTools/Na__LayoutEditor__TextTool__.js'), TLE('35__System__DrawingTools/Na__LayoutEditor__LeaderTool__.js')],
  vv=[VLE('35__System__DrawingTools/Na__LayoutEditor__DimensionTool__.js'), VLE('35__System__DrawingTools/Na__LayoutEditor__RectangleTool__.js'),
      VLE('35__System__DrawingTools/Na__LayoutEditor__TextTool__.js'), VLE('35__System__DrawingTools/Na__LayoutEditor__LeaderTool__.js')],
  hot=[],
  deps=['W2-19', 'W2-23'],
  gated=['DR-01', 'DR-37'],
  size='S', est=330,
  adapt=['DimensionTool 1.12.0 + the unlogged v2.152 hunk, logged as 1.13.0 in VV; the four hatch-default lines ported exactly as TV until Adam confirms intent (DR-37 item 3).'],
  acc=['Header-stripped code diff of the four files against TV is empty; no Snapping__ or TONE import left in 35__System__DrawingTools; G2 exits 0.',
       'Snap markers coloured by target; a dimension\'s end can snap Perpendicular from its first point; with Ortho on (console until W3-05) the Draw band is held horizontal or vertical and Shift frees it; with Grid Snap on text and leader heads land on the grid; with them off behaviour is unchanged.'],
  tests=[],
  src=['WP-S05b-07', 'WP-S04b-07'],
  risk='Low.')

P('W2-27', 'W2', 'Vector tools pure leaves (State, Setup, Config, Geometry, Offset, Boolean)',
  'Land LE/37\'s pure leaves verbatim (Curves landed in W1-14) so the interactive units can follow.',
  tv=[TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__State__.js'), TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Setup__.js'),
      TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Config__.json'), TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Geometry__.js'),
      TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Offset__.js'), TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Boolean__.js')],
  vv=[NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__State__.js')), NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Setup__.js')),
      NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Config__.json')), NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Geometry__.js')),
      NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Offset__.js')), NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Boolean__.js'))],
  hot=[],
  deps=['W1-99'],
  gated=['DR-01', 'DR-18'],
  size='M', est=2370,
  acc=['G2 exits 0; the pure-module part of Na__Test__VectorTools__ passes against VV\'s Geometry/Curves/Offset; editor first open unchanged (modules unreferenced).'],
  tests=['Na__Test__VectorTools__.test.mjs (pure-module part)'],
  src=[],
  split=['WP-S05b-01'],
  risk='Low. Clipper2 already vendored in VV.')

P('W2-28', 'W2', 'Vector tools interactive units, part 1, landed inert: Preview, Targets, Circle, Arc, Trim, Join',
  'Land LE/37\'s Preview and Targets units and the Circle, Arc, Trim and Join tools verbatim (they import only the W2-27 pure leaves and each other) with no registration, hub edit or ShapeTool change; nothing imports them until W2-41\'s adapter and W3-07.',
  tv=[TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Preview__.js'), TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Targets__.js'),
      TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__CircleTool__.js'), TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__ArcTool__.js'),
      TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__TrimTool__.js'), TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__JoinTool__.js')],
  vv=[NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Preview__.js')), NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Targets__.js')),
      NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__CircleTool__.js')), NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__ArcTool__.js')),
      NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__TrimTool__.js')), NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__JoinTool__.js'))],
  hot=[],
  deps=['W2-27', 'W2-19', 'W2-26'],
  gated=['DR-01', 'DR-18', 'DR-37'],
  size='M', est=2310, est_note='TV 218 + 504 + 353 + 470 + 380 + 382 lines verbatim',
  acc=['G2 exits 0 (it checks unreachable modules too); G1 result unchanged (units not reachable yet); the editor behaves exactly as before; header-stripped diff of every file against TV is empty apart from console prefixes.'],
  tests=[],
  src=['WP-S05b-V3'],
  risk='Needs ObjectSnap Search, SheetModel AddGroupMember/AnnounceShapes/IsLayerSelectable/InsertShape afterId, ShapeGeometry Rings, Ortho State, ViewportRotation and PaintOrder - all landed by W1/W2-19.')

P('W2-29', 'W2', 'Patterns panel and the hatch ready chain',
  'Port Panel__Patterns 1.1.0 verbatim (site plans dormant, DR-08 (B)), add Na__LeHatch__Ready to the Ready Promise.all and Na__LePanelPatterns__Register after the scrapbook registrations (Properties tab), and add "patterns" to AccordionSections.',
  tv=[TLE('36__System__HatchPatternTools/Na__LayoutEditor__Panel__Patterns__.js'), TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (hatch ready and Patterns registration hunks)'],
  vv=[NEW(VLE('36__System__HatchPatternTools/Na__LayoutEditor__Panel__Patterns__.js')), MC, AC],
  hot=[MC, AC],
  deps=['W2-14', 'W2-19'],
  gated=['DR-01', 'DR-19', 'DR-08'],
  size='S', est=520,
  acc=['The Patterns section appears on the Properties tab, hidden until the library loads, with the Construction tiles drawn in #333333; the first sheet paints only after Na__LeHatch__Ready resolves; a missing library leaves an empty hidden section and no error; G2 exits 0.'],
  tests=[],
  src=['WP-S05b-V2'],
  risk='Never ship an adapted panel and re-port it verbatim later (DR-19).')

P('W2-30', 'W2', 'Specification lockstep core and transport over the VV facade, with SpecLinks 1.2.0',
  'Port the Statement Writer lockstep leaf and SpecData State 1.2.0, Document 1.1.0, Draft 1.1.0, Editing 1.1.0, Lockstep 1.0.0, Transport 1.3.0 and the barrel 1.5.0 - transport through the W0-12 facade (Na__CfApi__ReadProjectFile/WriteProjectFile, Na__LocalMirror__WriteSiblingFile) - plus SpecLinks 1.2.0 (broken and note resolvers, locate), closing VV\'s two live specification data-safety faults.',
  tv=[TLE('52__Feature__StatementWriter/01__Core__Data/Na__LayoutEditor__Statement__Lockstep__.js'),
      TLE('50__Feature__Specification/Na__LayoutEditor__SpecData__State__.js'), TLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Document__.js'),
      TLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Draft__.js'), TLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Editing__.js'),
      TLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Lockstep__.js'), TLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Transport__.js'),
      TLE('50__Feature__Specification/Na__LayoutEditor__SpecData__.js'), TLE('50__Feature__Specification/Na__LayoutEditor__SpecLinks__.js')],
  vv=[NEW(VLE('52__Feature__StatementWriter/01__Core__Data/Na__LayoutEditor__Statement__Lockstep__.js')),
      VLE('50__Feature__Specification/Na__LayoutEditor__SpecData__State__.js'), VLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Document__.js'),
      VLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Draft__.js'), VLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Editing__.js'),
      NEW(VLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Lockstep__.js')), VLE('50__Feature__Specification/Na__LayoutEditor__SpecData__Transport__.js'),
      VLE('50__Feature__Specification/Na__LayoutEditor__SpecData__.js'), VLE('50__Feature__Specification/Na__LayoutEditor__SpecLinks__.js'),
      NEW(TESTDIR + 'Na__Test__SpecLockstep__.test.mjs'), NEW(TESTDIR + 'Na__Test__StatementLockstep__.test.mjs')],
  hot=[],
  deps=['W1-99'],
  gated=['DR-01', 'DR-27', 'DR-10'],
  size='L', est=2200,
  adapt=['K3 resolution of DR-27\'s interim: the facade lands in W0, so SpecData__Transport 1.3.0 ports verbatim over Na__CfApi/Na__LocalMirror and the Na__R2Notes__* adaptation (R2DrawingNotes 1.1.0) is skipped; W2-33 then deletes R2DrawingNotes.',
         'File name ValeVision__DrawingNotes__.json (K2 F9) through config; the Statement lockstep leaf is the first file of LE/52 (its own folder path verbatim).'],
  acc=['Na__Test__SpecLockstep__ (VV-adapted fixture) passes every case incl. "file moved during Sync R2 write is not written over" and "Reload Local leaves an agent\'s file unsynced"; Na__Test__StatementLockstep__ passes on VV\'s copy.',
       'With LockstepEnabled false the previous behaviour holds; off localhost nothing calls Flask; no spec unit calls the two-phase Na__R2Notes__Write; R2 is written by WriteCloud only and the local file by the lockstep only.',
       'Na__LeSpec__WriteLocalCopy, LOCATE_EVENT and the Lockstep API are exported by the SpecData barrel; a bubble linked to a deleted note reads broken (IsBroken) and draws its red halo; NoteFor(leader) answers {noteId, code, title, linked, locate}; locate() dispatches na-layouteditor-spec-locate.',
       'AutoSave\'s direct import of SpecData__Document__ (IsDirty) gains no cycle; G1/G2 pass.'],
  tests=['Na__Test__SpecLockstep__.test.mjs', 'Na__Test__StatementLockstep__.test.mjs'],
  src=['WP-S06b-01', 'WP-S06b-04'],
  risk='Highest-value package of the specification: test on a copy of a project\'s notes file; without W0-09\'s Last-Modified the lockstep falls back to UpdatedIso (correct but coarser).')

P('W2-31', 'W2', 'Specification lockstep question card, bar status 1.3.0 and their wiring',
  'Port SpecLockstep 1.0.0, SpecEditor Bar 1.3.0 (disk-first status, hover, out-of-step alert) and the Lockstep Question CSS region; ModeController mounts the card when editable, StartWatch on Enter (non-viewer), StopWatch on Leave; the Save Sheets "specification held" toast arrives with Toolbar 1.24.0 (W5-01).',
  tv=[TLE('50__Feature__Specification/Na__LayoutEditor__SpecLockstep__.js'), TLE('50__Feature__Specification/Na__LayoutEditor__SpecEditor__Bar__.js') + ' (1.3.0)',
      TLE('50__Feature__Specification/Na__LayoutEditor__Styles__Specification__.css') + ' (Lockstep Question region)', TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (lockstep hunks)'],
  vv=[NEW(VLE('50__Feature__Specification/Na__LayoutEditor__SpecLockstep__.js')), SPECBAR, SPECCSS, MC],
  hot=[SPECBAR, SPECCSS, MC],
  deps=['W2-30', 'W2-29'],
  gated=['DR-01'],
  size='M', est=500,
  adapt=['SpecEditor Bar 1.3.0 now, 1.4.0 (Share) with W4-08 (DR-05).'],
  acc=['The card mounts only in editable sessions and never in the web viewer; the watch starts when the editor opens from the 3D view and stops when it closes (not when returning from the spec page).',
       'With lockstep on the bar shows Out of step / Saving / Unsaved changes / Saved to file, not synced, with the file-date hover; the old wording when off; G1/G2 pass.'],
  tests=[],
  src=['WP-S06b-03'],
  risk='Apply ModeController hunks at VV\'s sites, never the TV file (W5-03 converges later).')

P('W2-32', 'W2', 'Notes margin layout: regions placement, the leaderless panel file and MarginGrip 1.3.0',
  'Port SpecMargin__Column and NoteRegions (Place/Push) as new files, SpecMargin 1.5.0, the Panel__MarginNotes__Leaderless file (registered by W3-11), MarginGrip 1.3.0 (its IsMoveAuto line arrives with the W3-03 hub) and the Specification Notes stylesheet whole.',
  tv=[TLE('50__Feature__Specification/Na__LayoutEditor__SpecMargin__Column__.js'), TLE('50__Feature__Specification/Na__LayoutEditor__NoteRegions__.js'),
      TLE('50__Feature__Specification/Na__LayoutEditor__SpecMargin__.js'), TLE('50__Feature__Specification/Na__LayoutEditor__Panel__MarginNotes__Leaderless__.js'),
      TLE('50__Feature__Specification/Na__LayoutEditor__MarginGrip__.js'), TLE('50__Feature__Specification/Na__LayoutEditor__Styles__Specification__Notes__.css')],
  vv=[NEW(VLE('50__Feature__Specification/Na__LayoutEditor__SpecMargin__Column__.js')), NEW(VLE('50__Feature__Specification/Na__LayoutEditor__NoteRegions__.js')),
      VLE('50__Feature__Specification/Na__LayoutEditor__SpecMargin__.js'), NEW(VLE('50__Feature__Specification/Na__LayoutEditor__Panel__MarginNotes__Leaderless__.js')),
      MARGRIP, VLE('50__Feature__Specification/Na__LayoutEditor__Styles__Specification__Notes__.css'),
      NEW(TESTDIR + 'Na__Test__NoteRegions__.test.mjs'), NEW(TESTDIR + 'Na__Test__LeaderlessNotes__.test.mjs')],
  hot=[MARGRIP],
  deps=['W1-99'],
  gated=['DR-01', 'DR-05'],
  size='L', est=2400,
  adapt=['The PdfExporter overflow condition comes with PdfExporter 1.12.0 (W3-16), not as a hunk here.',
         'Na__Test__LeaderlessNotes__\'s RB05 fixture replaced by a VV fixture or skipped with a reason.'],
  acc=['Na__Test__NoteRegions__ (53 checks) and Na__Test__LeaderlessNotes__ (51 checks) pass on VV modules; a sheet with no regions and no leaderless groups draws primitive-for-primitive as before (compare Na__LeMargin__Push output on a VV project); MarginGrip\'s badge shows only the margin\'s own lost notes; G1/G2 pass.'],
  tests=['Na__Test__NoteRegions__.test.mjs', 'Na__Test__LeaderlessNotes__.test.mjs'],
  src=['WP-S06b-06'],
  risk='SpecMargin 1.5.0 re-plans more work per render.')

P('W2-33', 'W2', 'Retire VV\'s per-document notes client (R2DrawingNotes)',
  'Delete Na__AppUtils__R2DrawingNotes__.js once W2-30 leaves no importer (K2 FR-18); optionally move the nine VV dev savers to Na__CfApi__MergeAndSaveKeys (TV pattern).',
  tv=[],
  vv=[R2NOTES + ' (deleted)'],
  hot=[R2NOTES],
  deps=['W2-30'],
  gated=['DR-27'],
  size='S', est=60,
  adapt=['R2SaveProjectJson stays for VV Dev menus (DIV-4); the optional dev-saver migration edits only VV-only files (11 CameraUtils, 21 ScenePersistence, 28/29/31/41/70 dev controls) and each saver then writes only its own key.'],
  acc=['No VV module imports R2DrawingNotes; G1 passes; if the option is taken each dev saver writes only its own key.'],
  tests=[],
  src=['WP-S12-16'],
  risk='Low.')

P('W2-34', 'W2', 'Spell check (55__Feature__SpellCheck) with the Vale dictionary route',
  'Create VVM/55__Feature__SpellCheck (Dictionary and Config adapted: dictionary file, /api/valevision/user-config/spellings, K_GROUPS, /api/check-localhost probe, labels; Field, WordBar and Styles verbatim) and @import its stylesheet in the CSS index at TV\'s position.',
  tv=[TVM('55__Feature__SpellCheck/Na__SpellCheck__.js'), TVM('55__Feature__SpellCheck/Na__SpellCheck__Dictionary__.js'), TVM('55__Feature__SpellCheck/Na__SpellCheck__Field__.js'),
      TVM('55__Feature__SpellCheck/Na__SpellCheck__WordBar__.js'), TVM('55__Feature__SpellCheck/Na__SpellCheck__Config__.json'), TVM('55__Feature__SpellCheck/Na__SpellCheck__Styles__.css')],
  vv=[NEW(VVM('55__Feature__SpellCheck/Na__SpellCheck__.js')), NEW(VVM('55__Feature__SpellCheck/Na__SpellCheck__Dictionary__.js')), NEW(VVM('55__Feature__SpellCheck/Na__SpellCheck__Field__.js')),
      NEW(VVM('55__Feature__SpellCheck/Na__SpellCheck__WordBar__.js')), NEW(VVM('55__Feature__SpellCheck/Na__SpellCheck__Config__.json')), NEW(VVM('55__Feature__SpellCheck/Na__SpellCheck__Styles__.css')),
      NEW(VVM('55__Feature__SpellCheck/README__SpellCheck__.md')), CSSIDX, NEW(TESTDIR + 'Na__Test__SpellCheckDictionary__.test.mjs'), NEW(TESTDIR + 'Na__Test__SpellCheckField__.html')],
  hot=[CSSIDX],
  deps=['W2-03'],
  gated=['DR-01', 'DR-20'],
  size='M', est=1700,
  acc=['A server without the route reads as "restart" (via /api/check-localhost), no server as read-only, and off localhost the static file is read; Na__Test__SpellCheckDictionary__ and Na__Test__SpellCheckField__.html pass on VV.'],
  tests=['Na__Test__SpellCheckDictionary__.test.mjs', 'Na__Test__SpellCheckField__.html'],
  src=['WP-S06b-09'],
  risk='Invisible until the Specification Scrapbook (W2-35) uses it.')

P('W2-35', 'W2', 'Specification Scrapbook (LE/58) and the left Specification tab',
  'Create LE/58__Feature__ScrapbookSpecification (library, panel and CSS verbatim; config wording adapted; RowEditor over the W2-30 local-copy write), register the left "document" tab, the Specification tab right after it and the section after ModelLayers.',
  tv=[TLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__ScrapbookSpecification__.js'), TLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__Panel__ScrapbookSpecification__.js'),
      TLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__ScrapbookSpecification__RowEditor__.js'), TLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__ScrapbookSpecification__Config__.json'),
      TLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__Styles__ScrapbookSpecification__.css'), TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (left tabs)'],
  vv=[NEW(VLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__ScrapbookSpecification__.js')), NEW(VLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__Panel__ScrapbookSpecification__.js')),
      NEW(VLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__ScrapbookSpecification__RowEditor__.js')), NEW(VLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__ScrapbookSpecification__Config__.json')),
      NEW(VLE('58__Feature__ScrapbookSpecification/Na__LayoutEditor__Styles__ScrapbookSpecification__.css')), MC,
      NEW(TESTDIR + 'Na__Test__SpecInlineEdit__.test.mjs')],
  hot=[MC],
  deps=['W2-30', 'W2-31', 'W2-34', 'W2-21', 'W2-37'],
  gated=['DR-01', 'DR-20'],
  size='M', est=2300,
  adapt=['Config wording: ValeVision__DrawingNotes__.json and the VV dictionary folder.'],
  acc=['The left Specification tab lists every note by group with its code bubble; dragging a row drops a linked bubble centred under the pointer, tail aimed at the nearest viewport, in one undo step; filter "rf" matches only codes starting RF.',
       'F2 edits a row; Enter writes ValeVision__DrawingNotes__.json through WCP, reads it back and lights Save Sheets; "Show in Specification" on a bubble centres its row and pulses the halo three times (after the W3-03 hub wires the menu row).',
       'Na__Test__SpecInlineEdit__ passes; G1/G2 pass.'],
  tests=['Na__Test__SpecInlineEdit__.test.mjs'],
  src=['WP-S06a-06'],
  risk='The panel statically imports the RowEditor, which imports SpellCheck: the whole folder lands together.')

P('W2-36', 'W2', 'Dependency-free panel fixes (Text 1.4.0, Styles 1.7.0, Shapes 1.8.x hunks, Layers labels and Off-red, Leaders header)',
  'Take Panel__Text 1.4.0 and Panel__Styles 1.7.0 whole (readout fix; % suffix and hint), port the Panel__Shapes 1.8.1/1.8.2 hunks, the Panel__Leaders header, the Panel__Layers 1.1.1 labels and 1.3.0 Off-red (no Ref switch yet), the ScrapbookCustom Shape__Area hunk, and correct the multi-select notes in config.',
  tv=[TLE('40__Ui__Panels/Na__LayoutEditor__Panel__Text__.js'), TLE('40__Ui__Panels/Na__LayoutEditor__Panel__Styles__.js'), TLE('40__Ui__Panels/Na__LayoutEditor__Panel__Shapes__.js') + ' (1.8.1, 1.8.2 hunks)',
      TLE('40__Ui__Panels/Na__LayoutEditor__Panel__Leaders__.js'), TLE('40__Ui__Panels/Na__LayoutEditor__Panel__Layers__.js') + ' (1.1.1 labels, 1.3.0 Off-red)',
      TLE('56__Feature__ScrapbookCustom/Na__LayoutEditor__ScrapbookCustom__.js') + ' (Shape__Area hunk)'],
  vv=[VLE('40__Ui__Panels/Na__LayoutEditor__Panel__Text__.js'), VLE('40__Ui__Panels/Na__LayoutEditor__Panel__Styles__.js'), P_SHAPES,
      VLE('40__Ui__Panels/Na__LayoutEditor__Panel__Leaders__.js'), P_LAYERS, VLE('56__Feature__ScrapbookCustom/Na__LayoutEditor__ScrapbookCustom__.js'), AC],
  hot=[P_SHAPES, P_LAYERS, AC],
  deps=['W2-29'],
  gated=['DR-01'],
  size='S', est=300,
  acc=['Select 3 text items of different sizes: the Size box shows the first item\'s size and the note reads "Editing 3 selected text items: a change here goes to all of them."; with several dimensions or vectors selected the note no longer says "Click one ... on its own".',
       'Select a coloured room and a plain line, untick Edges: both fills unchanged, edges off; a hidden layer\'s On/Off button is faint red (#9b3b3b on #fbf3f3) matching a locked layer\'s Unlock; the Render Composites panel shows % aligned with the x and px boxes.',
       'node --check on every touched .js; G1/G2 clean.'],
  tests=[],
  src=['WP-S06a-01'],
  risk='Low; Panel__Shapes and Panel__Layers are taken whole later (W3-12, W3-13).')

P('W2-37', 'W2', 'Parametric Scrapbook engine and core types to TV (engine 1.7.0, ScaleBar, DrawingTitle, Grips 1.6.0, LinkNoodle, ViewportLink 1.4.0, Styles, TileDrag)',
  'Take the parametric engine 1.7.0 and its core element modules whole (slide, choices, Refit, adopt, base point, bar to the right, 5 mm underline rule, corner and base grips) with TileDrag 1.2.0 and the parametric stylesheet, and the config blocks for those types; the panel 1.8.0 and the new element types follow in W3-14/W2-38.',
  tv=[TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__.js'), TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__ScaleBar__.js'),
      TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__DrawingTitle__.js'), TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__Grips__.js'),
      TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__LinkNoodle__.js'), TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__ViewportLink__.js') + ' (1.4.0 hunks)',
      TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__Styles__ScrapbookParametric__.css'), TLE('55__Feature__Scrapbook/Na__LayoutEditor__Scrapbook__TileDrag__.js'),
      TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__Config__.json') + ' (blocks for these types)'],
  vv=[VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__.js'), VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__ScaleBar__.js'),
      VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__DrawingTitle__.js'), VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__Grips__.js'),
      VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__LinkNoodle__.js'), VPLINK,
      VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__Styles__ScrapbookParametric__.css'), VLE('55__Feature__Scrapbook/Na__LayoutEditor__Scrapbook__TileDrag__.js'),
      PARAMCFG, TESTDIR + 'Na__Test__ScrapbookScaleBar__.test.mjs', TESTDIR + 'Na__Test__ScrapbookDrawingTitle__.test.mjs'],
  hot=[VPLINK, PARAMCFG],
  deps=['W2-19', 'W2-10', 'W2-21', 'W2-24'],
  gated=['DR-01', 'DR-42'],
  size='L', est=2000,
  adapt=['Config port_adapted: bar-right keys, Grips and Labels keys, DrawingTitleBarRight element, ScaleBar fill #858585; VV\'s phase, site-plan and three-scales wording kept; CabinetInfill, ProjectQr, AreaSchedule and SiteLegend blocks/elements wait for W3-14.',
         'Engine seam: type=\'architectural\' (VV :240) recorded; VV\'s adapted panel keeps working on the superset engine until W3-14.'],
  acc=['The Scrapbook tab shows Title + Scale Bar, Title + Scale Bar to the Right, Title and Scale Bar; a bar to the right slides in 50 mm steps, lands exactly on a snapped corner with a dashed guide, and keeps its far end fixed while stretched backwards.',
       'A title underline runs UnderlinePastTextMm (5 mm) past the measured width (exactly 5 mm on screen with Open Sans after W1-25); undo and redo are byte-for-byte; a viewport named with two spaces round a dash no longer marks the sheet dirty on every visit; scale bar checker cells are #858585.',
       'Na__Test__ScrapbookScaleBar__ and Na__Test__ScrapbookDrawingTitle__ (TV 1.3.0 versions) pass; G1/G2 pass after every file.'],
  tests=['Na__Test__ScrapbookScaleBar__.test.mjs (TV version)', 'Na__Test__ScrapbookDrawingTitle__.test.mjs (TV version)'],
  src=['WP-S06a-05v'],
  risk='The editor fails to link if any file statically imports something VV lacks: DrawingTitle lands before or with Grips (PLACE_BELOW/PLACE_RIGHT).')

P('W2-38', 'W2', 'New parametric element types landed inert: Cabinet Infill and the Project QR element',
  'Land CabinetInfill 1.2.0 (universal) and the ProjectQr element (switched off, DR-12) verbatim and inert - both import nothing - so the parametric panel 1.8.0 (W3-14) links; the site-plan legend pair is W2-39.',
  tv=[TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__CabinetInfill__.js'), TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__ProjectQr__.js')],
  vv=[NEW(VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__CabinetInfill__.js')), NEW(VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__ProjectQr__.js')),
      NEW(TESTDIR + 'Na__Test__ScrapbookCabinetInfill__.test.mjs'), NEW(TESTDIR + 'Na__Test__ScrapbookProjectQr__.test.mjs')],
  hot=[],
  deps=['W2-37'],
  gated=['DR-01', 'DR-12', 'DR-43'],
  size='M', est=1800, est_note='TV 990 + 810 lines verbatim (both import nothing)',
  adapt=['Verbatim below VALEVISION3D headers; the Portal/QR element wording waits for Adam (DR-43) and ships off; no NA URL (R9).'],
  acc=['Na__Test__ScrapbookCabinetInfill__ and Na__Test__ScrapbookProjectQr__ pass on scratch copies; G2 passes; nothing imports the modules until W3-14.'],
  tests=['Na__Test__ScrapbookCabinetInfill__.test.mjs', 'Na__Test__ScrapbookProjectQr__.test.mjs'],
  src=[],
  split=['WP-S06a-05v'],
  risk='Low.',
  notes=['No raw package ported ScrapbookParametric__ProjectQr__ or SiteLegend/Link: WP-S06a-05v omitted them under its pre-K1 assumptions. K1 DR-12 (A) ("keeps ... the parametric scrapbook verbatim") and DR-08 (B) (site plans dormant) make the panel 1.8.0 whole-file port possible only if these modules exist, so K3 adds this package (S06a-F38/F43/F44 evidence).'])

P('W2-40', 'W2', 'Drawing Planes core leaves landed inert: Maths, ConfigState, AppConfig, Bounds, PlaneMesh',
  'Land the Drawing Planes modules that import only each other, 04 MathUtils and three (Maths, ConfigState, the AppConfig with VV bounds values, Bounds, PlaneMesh) verbatim into TV\'s 47 slot; nothing imports them until W2-01.',
  tv=[TVM('47__System__DrawingPlanes/Na__DrawingPlanes__Maths__.js'), TVM('47__System__DrawingPlanes/Na__DrawingPlanes__ConfigState__.js'),
      TVM('47__System__DrawingPlanes/Na__DrawingPlanes__AppConfig__.json'), TVM('47__System__DrawingPlanes/Na__DrawingPlanes__Bounds__.js'),
      TVM('47__System__DrawingPlanes/Na__DrawingPlanes__PlaneMesh__.js')],
  vv=[NEW(VVM('47__System__DrawingPlanes/Na__DrawingPlanes__Maths__.js')), NEW(VVM('47__System__DrawingPlanes/Na__DrawingPlanes__ConfigState__.js')),
      NEW(VVM('47__System__DrawingPlanes/Na__DrawingPlanes__AppConfig__.json')), NEW(VVM('47__System__DrawingPlanes/Na__DrawingPlanes__Bounds__.js')),
      NEW(VVM('47__System__DrawingPlanes/Na__DrawingPlanes__PlaneMesh__.js'))],
  hot=[],
  deps=['W1-99'],
  gated=['DR-01', 'DR-02', 'DR-32'],
  size='M', est=1780, est_note='TV 411 + 356 + 76 + 382 + 551 lines',
  adapt=['Bounds tokens checked against VV models (D37 Doous and an older export); VV values in the AppConfig only; category tokens use ValeVision__ (K2 K3).'],
  acc=['G2 passes with the five files present and unimported (ConfigState resolves 04 Na__Math__Units; PlaneMesh resolves three/addons lines); node --check passes.'],
  tests=[],
  src=[],
  split=['WP-S02a-07'],
  risk='Category-token mismatch on older VV exports would size planes from the landscape: verified when W2-01 switches the system on.')

P('W2-41', 'W2', 'Vector tools part 2 landed inert: Offset and Boolean tools, the adapter, the Vector Tools panel and stylesheet',
  'Land the Offset and Boolean tools, the VectorTools adapter (which imports every tool), the Vector Tools panel and its stylesheet verbatim with no registration, hub edit or ShapeTool change; nothing imports them until W3-03/W3-07.',
  tv=[TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__OffsetTool__.js'), TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__BooleanTool__.js'),
      TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__.js'), TLE('37__System__VectorTools/Na__LayoutEditor__Panel__VectorTools__.js'),
      TLE('37__System__VectorTools/Na__LayoutEditor__Styles__VectorTools__.css')],
  vv=[NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__OffsetTool__.js')), NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__BooleanTool__.js')),
      NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__.js')), NEW(VLE('37__System__VectorTools/Na__LayoutEditor__Panel__VectorTools__.js')),
      NEW(VLE('37__System__VectorTools/Na__LayoutEditor__Styles__VectorTools__.css'))],
  hot=[],
  deps=['W2-28'],
  gated=['DR-01', 'DR-18', 'DR-37'],
  size='M', est=2320, est_note='TV 419 + 690 + 709 + 424 + 77 lines verbatim',
  acc=['G2 exits 0 (it checks unreachable modules too); G1 result unchanged (units not reachable yet); the editor behaves exactly as before; header-stripped diff of every file against TV is empty apart from console prefixes.'],
  tests=[],
  src=[],
  split=['WP-S05b-V3'],
  risk='Needs ObjectSnap Search, SheetModel AddGroupMember/AnnounceShapes/IsLayerSelectable/InsertShape afterId, ShapeGeometry Rings, Ortho State, ViewportRotation and PaintOrder - all landed by W1/W2-19.')

P('W2-39', 'W2', 'Site-plan legend element and its link landed inert (dormant with site plans)',
  'Land SiteLegend (imports nothing) and SiteLegendLink (imports SheetModel, SheetSurface, Viewport2d, the site-plan Store and SitePlanComposites, HatchPatterns, PanelHost and the parametric engine) verbatim and inert so the parametric panel 1.8.0 (W3-14) links; dormant with site plans (DR-08 (B)).',
  tv=[TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__SiteLegend__.js'), TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__SiteLegendLink__.js')],
  vv=[NEW(VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__SiteLegend__.js')), NEW(VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__SiteLegendLink__.js')),
      NEW(TESTDIR + 'Na__Test__ScrapbookSiteLegend__.test.mjs')],
  hot=[],
  deps=['W2-37', 'W2-16', 'W2-14'],
  gated=['DR-01', 'DR-08', 'DR-43'],
  size='M', est=1340, est_note='TV 894 + 442 lines verbatim',
  adapt=['Verbatim below VALEVISION3D headers; no NA URL (R9).'],
  acc=['Na__Test__ScrapbookSiteLegend__ passes on a scratch copy; G2 passes; nothing imports the modules until W3-14.'],
  tests=['Na__Test__ScrapbookSiteLegend__.test.mjs'],
  src=[],
  split=['WP-S06a-05v'],
  risk='Low (inert, dormant).')

P('W2-42', 'W2', 'Object snap leaves landed inert: State, Geometry, Glyphs, Index, Sources, Marker, Config',
  'Land the seven LE/28__System__ObjectSnap modules that do not import the snap search or controller - State, Geometry and Glyphs (import nothing), Index, Sources, Marker and the Config JSON - verbatim with VV headers; nothing imports them until W2-19.',
  tv=[TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__State__.js'), TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Geometry__.js'),
      TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Glyphs__.js'), TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Index__.js'),
      TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Sources__.js'), TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Marker__.js'),
      TLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Config__.json')],
  vv=[NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__State__.js')), NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Geometry__.js')),
      NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Glyphs__.js')), NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Index__.js')),
      NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Sources__.js')), NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Marker__.js')),
      NEW(VLE('28__System__ObjectSnap/Na__LayoutEditor__ObjectSnap__Config__.json'))],
  hot=[],
  deps=['W1-99'],
  gated=['DR-01', 'DR-05'],
  size='M', est=1920, est_note='TV 337 + 219 + 157 + 296 + 565 + 265 + 79 lines verbatim',
  acc=['G2 passes with the seven files present and unimported (Index resolves ConfigState and Viewport2d; Sources resolves SheetLayout, SheetModel, SheetSurface, MarkupBridge, ShapeGeometry and VectorTools__Curves from W1; Marker resolves ConfigState and SheetSurface); VV\'s snap marker is untouched.'],
  tests=[],
  src=[],
  split=['WP-S04b-06R'],
  risk='Low (inert).')

P('W2-43', 'W2', 'Projected linework new leaves landed inert: FlushJoins and Storeys',
  'Add folder 50\'s two new leaf modules that import nothing - FlushJoins and Storeys - verbatim below a VV header, with the FlushJoins suite; DoorPose, which imports the shared folder-50 units, lands with them in W2-06.',
  tv=[TVM('50__System__ProjectedLinework/Na__ProjectedLinework__FlushJoins__.js'), TVM('50__System__ProjectedLinework/Na__ProjectedLinework__Storeys__.js')],
  vv=[NEW(VVM('50__System__ProjectedLinework/Na__ProjectedLinework__FlushJoins__.js')), NEW(VVM('50__System__ProjectedLinework/Na__ProjectedLinework__Storeys__.js')),
      NEW(TESTDIR + 'Na__Test__FlushJoins__.test.mjs')],
  hot=[],
  deps=['W1-99'],
  gated=['DR-01', 'DR-31', 'DR-16'],
  size='M', est=640, est_note='TV 308 + 320 lines verbatim',
  acc=['Na__Test__FlushJoins__ 8/8 against VV\'s copy; G2 passes with the two files unimported.'],
  tests=['Na__Test__FlushJoins__.test.mjs'],
  src=[],
  split=['WP-S02b-02R'],
  risk='Low (inert).')

P('W2-99', 'W2', 'Parity Scribe pass for Wave 2',
  'S11 B10 procedure for W2, including the S02a and S02b ledger work (return-trip rows, phase 2/4 notes, the dimension split recorded as "VV split; TV copied, not wired", Lantern Designer rows moved, the version-number convention, the S02a back-port memo for TV) and S04a\'s VV header fixes.',
  vv=[DEVLOG, LEDGER, VVPLAN],
  hot=[DEVLOG, LEDGER, VVPLAN],
  deps=[],
  gated=['DR-35', 'DR-34'],
  size='S', est=600,
  acc=['Every W2 Port Record has its devlog entry and Module Register rows; zero {{VVREL tokens; DR-31 re-bake reminder in the devlog entry for W2-06; SHARED SERVICE WORKER decision recorded; harness counts from a fresh run.',
       'Rows from WP-S02a-13, WP-S02b-09 and WP-S04a-12 (VV half) written; their TV-side items queued for WT-08.'],
  src=['WP-S02a-13', 'WP-S02b-09', 'WP-S04a-12'],
  risk='Single writer of the two documents.')
