from k3_common import *

# =============================================================================
# W4 - DOCUMENTS: published schema and reader, publisher, sharing, the
# published-only web viewer, the Drawing Register, and the Statement Writer
# (last, behind LayoutEditor__Statement__Enabled per DR-10).
# Every W4 package starts after W3-99.
# Splits follow the TV import graph read at TV HEAD (from '...' lines):
#   reader leaves (Paint, Urls, Config, Styles, LoadingScreen, Unpublished) before
#   Document/Sheet/Elements/Viewports; register core (Data, DeleteDialog,
#   Transactions, Notes, Preview, Pdf) before Editor/Export; the Statement
#   Writer's markdown engine (imports only itself) before the modules that
#   import it (Editor__Typing, Publish__Page, Reader, the standard sections).
# =============================================================================

T52 = lambda f: TVM('52__System__Layout__PublishedDocuments/' + f)
V52 = lambda f: VVM('52__System__Layout__PublishedDocuments/' + f)
T65 = lambda f: TLE('65__Feature__DocumentPublishing/' + f)
V65 = lambda f: VLE('65__Feature__DocumentPublishing/' + f)
T66 = lambda f: TLE('66__Feature__DocumentSharing/' + f)
V66 = lambda f: VLE('66__Feature__DocumentSharing/' + f)
T51 = lambda f: TLE('51__Feature__DrawingRegister/' + f)
V51 = lambda f: VLE('51__Feature__DrawingRegister/' + f)
TSW = lambda f: TLE('52__Feature__StatementWriter/' + f)
VSW = lambda f: VLE('52__Feature__StatementWriter/' + f)

P('W4-01', 'W4', 'Published schema (53__Data__Layout__PublishedSchema) and the VV fixture',
  'Create the shared publish/read contract at TV\'s path - keys verbatim, SchemaRef/MinReader/ByApp/reasons adapted - seed a VV example folder from TV\'s AA00 example (schema data only) linked both ways from the README, and port the schema test.',
  tv=[TVM('53__Data__Layout__PublishedSchema/Na__PublishedSchema__.json'), TVM('53__Data__Layout__PublishedSchema/Na__PublishedSchema__Paths__.js'),
      TVM('53__Data__Layout__PublishedSchema/Na__PublishedSchema__Version__.js'), TVM('53__Data__Layout__PublishedSchema/README__PublishedSchema__.md')],
  vv=[NEW(VVM('53__Data__Layout__PublishedSchema/Na__PublishedSchema__.json')), NEW(VVM('53__Data__Layout__PublishedSchema/Na__PublishedSchema__Paths__.js')),
      NEW(VVM('53__Data__Layout__PublishedSchema/Na__PublishedSchema__Version__.js')), NEW(VVM('53__Data__Layout__PublishedSchema/README__PublishedSchema__.md')),
      NEW(TESTDIR + 'Na__Test__PublishedSchema__.test.mjs')],
  hot=[],
  deps=['W3-99'],
  gated=['DR-01', 'DR-22', 'DR-29'],
  size='M', est=1050,
  acc=['Na__Test__PublishedSchema__ passes against the VV fixture; Version__Schema is 1 in both apps and every folder and file name is identical (06__Layout__PublishedDocuments, 05__Layout__DrawingDocs__Images); the README and the example ReadMe point at each other.'],
  tests=['Na__Test__PublishedSchema__.test.mjs'],
  src=['WP-S08-07'],
  risk='Low; TV\'s example is not yet final (S08-F46): treat the seed as provisional.')

P('W4-17', 'W4', 'Published reader leaves landed inert: Paint, Urls, Config, Styles, LoadingScreen, Unpublished',
  'Create the reader\'s leaf modules at TV\'s path (52__System__Layout__PublishedDocuments): Paint, LoadingScreen and Unpublished verbatim, Urls and Config adapted, and the unlinked Styles__Main as TV has it; nothing imports them until W4-02.',
  tv=[T52('Na__PubDoc__Paint__.js'), T52('Na__PubDoc__Urls__.js'), T52('Na__PubDoc__Config__.json'), T52('Na__PubDoc__Styles__Main__.css'),
      T52('Na__PubDoc__LoadingScreen__.js'), T52('Na__PubDoc__Unpublished__.js')],
  vv=[NEW(V52('Na__PubDoc__Paint__.js')), NEW(V52('Na__PubDoc__Urls__.js')), NEW(V52('Na__PubDoc__Config__.json')), NEW(V52('Na__PubDoc__Styles__Main__.css')),
      NEW(V52('Na__PubDoc__LoadingScreen__.js')), NEW(V52('Na__PubDoc__Unpublished__.js'))],
  hot=[],
  deps=['W4-01'],
  gated=['DR-01', 'DR-22', 'DR-21'],
  size='M', est=1940, est_note='TV 522 + 340 + 133 + 123 + 596 + 226 lines',
  adapt=['Na__PubDoc__Urls__: FromPage from ?project=; on localhost the Flask copy first (http://127.0.0.1:8000/Projects/{folderId}/06__...), live the VaApps CDN.',
         'Na__PubDoc__Config__: Sheet__FontFamily = the VV authoring face (Open Sans after W1-25); prefixes; PubDoc__Loading__Config block verbatim.',
         'Styles__Main stays unlinked as in TV (TV\'s decision on the orphan is WT-12).'],
  acc=['G2 passes with the six files present and unimported (Urls resolves ProjectLoader; Unpublished resolves Paint); node --check passes on every .js.'],
  tests=[],
  src=[],
  split=['WP-S08-08'],
  risk='Low (inert).')

P('W4-02', 'W4', 'Published reader document closure: Document, Sheet, Elements, Viewports, and the reader test',
  'Land the rest of the reader at TV\'s path (Document, Sheet, Elements, Viewports verbatim; they import the W4-17 leaves and the 53 schema) and port the reader test and harness; the web viewer wires it in W4-09.',
  tv=[T52('Na__PubDoc__Document__.js'), T52('Na__PubDoc__Sheet__.js'), T52('Na__PubDoc__Elements__.js'), T52('Na__PubDoc__Viewports__.js')],
  vv=[NEW(V52('Na__PubDoc__Document__.js')), NEW(V52('Na__PubDoc__Sheet__.js')), NEW(V52('Na__PubDoc__Elements__.js')), NEW(V52('Na__PubDoc__Viewports__.js')),
      NEW(TESTDIR + 'Na__Test__PublishedReader__.test.mjs'), NEW(TESTDIR + 'Na__Test__PublishedReader__Harness__.html')],
  hot=[],
  deps=['W4-17'],
  gated=['DR-01', 'DR-22'],
  size='M', est=2000, est_note='TV 621 + 298 + 653 + 426 lines, verbatim',
  acc=['Every fixture document builds; an unpublished drawing fetches nothing beyond the shared unpublished file; the import walk reaches no renderer, projection, model loader or image exporter; the tier ladder steps up, holds one tier, respects the byte budget and never retries a failed tier.',
       'Na__Test__PublishedReader__ and its harness pass; dimension arrangement checked against an editor screenshot (Elements header).'],
  tests=['Na__Test__PublishedReader__.test.mjs', 'Na__Test__PublishedReader__Harness__.html'],
  src=['WP-S08-08', 'WP-S10-13'],
  risk='Dimension arrangement is implemented independently of Na__LeDim__.')

P('W4-03', 'W4', 'Publisher bakers and transport (65: Raster, Sheet, Viewports, Transport, Config)',
  'Port the publisher\'s bakers and its transport at TV\'s paths: Raster verbatim, Viewports verbatim, Sheet adapted (SchemaRef and "Published by" meta), Transport over the VV facade and Flask blueprint, Config adapted; inert until W4-07.',
  tv=[T65('Na__LayoutEditor__Publish__Raster__.js'), T65('Na__LayoutEditor__Publish__Sheet__.js'), T65('Na__LayoutEditor__Publish__Viewports__.js'),
      T65('Na__LayoutEditor__Publish__Transport__.js'), T65('Na__LayoutEditor__Publish__Config__.json')],
  vv=[NEW(V65('Na__LayoutEditor__Publish__Raster__.js')), NEW(V65('Na__LayoutEditor__Publish__Sheet__.js')), NEW(V65('Na__LayoutEditor__Publish__Viewports__.js')),
      NEW(V65('Na__LayoutEditor__Publish__Transport__.js')), NEW(V65('Na__LayoutEditor__Publish__Config__.json'))],
  hot=[],
  deps=['W4-01'],
  gated=['DR-01', 'DR-22', 'DR-29', 'DR-06'],
  size='M', est=1650,
  adapt=['Publish__Sheet: Meta__SchemaRef (:271, :408) to VV\'s schema reference and the "Published by TrueVision" note (:272) to ValeVision; IMAGES_DIR stays 05__Layout__DrawingDocs__Images (DR-29, :81).',
         'Publish__Transport over Na__CfApi__* (worker F-PUB family) and /api/valevision/published/* (W0-19); a published write never bumps the build manifest (S08-F10).'],
  acc=['G2 passes with the five files present and unimported (imports resolve: PaintOrder, BuildLayerPrimitives, BuildViewportFrame, ShapeRings, FloorAreas, SpecMargin, SpecData__Document, Viewport2d/3d, 53 Paths).'],
  tests=[],
  src=['WP-S08-09'],
  risk='Publishing must run in Chrome or Edge (S08-F06).')

P('W4-04', 'W4', 'Statement Writer markdown engine (inert): Tokenise, Inline, Render, Serialise, Figure',
  'Port the five 02 markdown modules to TV-identical paths under LE/52 (they import only each other) with the DR-37 CRLF decision applied to the tokeniser, and port the two markdown suites.',
  tv=[TSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Tokenise__.js'), TSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Inline__.js'),
      TSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Render__.js'), TSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Serialise__.js'),
      TSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Figure__.js')],
  vv=[NEW(VSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Tokenise__.js')), NEW(VSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Inline__.js')),
      NEW(VSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Render__.js')), NEW(VSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Serialise__.js')),
      NEW(VSW('02__Core__Markdown/Na__LayoutEditor__Statement__Md__Figure__.js')),
      NEW(TESTDIR + 'Na__Test__StatementRoundTrip__.test.mjs'), NEW(TESTDIR + 'Na__Test__StatementFigureTitle__.test.mjs')],
  hot=[],
  deps=['W3-99'],
  gated=['DR-01', 'DR-10', 'DR-37'],
  size='M', est=2080, est_note='TV 501 + 421 + 397 + 287 + 474 lines',
  adapt=['Tokeniser: CRLF-tolerant while keeping source lines byte-exact (DR-37 item 1 as a declared VV seam unless WT-03 lands TV\'s fix first); never normalise on read.',
         'Ported from a pinned TV commit (b2aa9151 or later), recorded in each PORT NOTE (DR-10).'],
  acc=['node --check passes on every file; Na__Test__StatementRoundTrip__ and Na__Test__StatementFigureTitle__ pass on a committed VV fixture and on its CRLF twin; G1/G2 pass and nothing outside the feature imports these files.'],
  tests=['Na__Test__StatementRoundTrip__.test.mjs', 'Na__Test__StatementFigureTitle__.test.mjs'],
  src=['WP-S07b-05A'],
  risk='Low (inert); the CRLF behaviour depends on DR-37.')

P('W4-05', 'W4', 'Statement Writer pure modules (inert): data index, images, editor move and typing, page publisher',
  'Port 01 Data__Index (description adapted) and Images, 04 Editor__Move and Editor__Typing, and 07 Publish__Page (generator meta adapted) to TV-identical paths; Editor__Typing and Publish__Page import the W4-04 engine.',
  tv=[TSW('01__Core__Data/Na__LayoutEditor__Statement__Data__Index__.js'), TSW('01__Core__Data/Na__LayoutEditor__Statement__Images__.js'),
      TSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__Move__.js'), TSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__Typing__.js'),
      TSW('07__Export__Publish/Na__LayoutEditor__Statement__Publish__Page__.js')],
  vv=[NEW(VSW('01__Core__Data/Na__LayoutEditor__Statement__Data__Index__.js')), NEW(VSW('01__Core__Data/Na__LayoutEditor__Statement__Images__.js')),
      NEW(VSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__Move__.js')), NEW(VSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__Typing__.js')),
      NEW(VSW('07__Export__Publish/Na__LayoutEditor__Statement__Publish__Page__.js'))],
  hot=[],
  deps=['W4-04'],
  gated=['DR-01', 'DR-10', 'DR-43'],
  size='M', est=2010, est_note='TV 361 + 352 + 323 + 570 + 401 lines',
  adapt=['Keep the UK-planning field names and replace only people and company names (DR-10); no "Noble Architecture" or "TrueVision" runtime string in Publish__Page\'s generator meta or the Data__Index description.'],
  acc=['node --check passes on every file; G1/G2 pass and nothing outside the feature imports these files; the naming lint finds no NA runtime string in the adapted files.'],
  tests=[],
  src=[],
  split=['WP-S07b-05A'],
  risk='Low (inert).')

P('W4-15', 'W4', 'Statement Writer stylesheets (inert, verbatim)',
  'Copy the two 08 stylesheets verbatim (Styles__Statement, Styles__Statement__Document); the Page and the publisher link them by relative path (TV Page :827-828, Publish :130), so no index or loader line is added.',
  tv=[TSW('08__Style__Stylesheets/Na__LayoutEditor__Styles__Statement__.css'), TSW('08__Style__Stylesheets/Na__LayoutEditor__Styles__Statement__Document__.css')],
  vv=[NEW(VSW('08__Style__Stylesheets/Na__LayoutEditor__Styles__Statement__.css')), NEW(VSW('08__Style__Stylesheets/Na__LayoutEditor__Styles__Statement__Document__.css'))],
  hot=[],
  deps=['W3-99'],
  gated=['DR-10', 'DR-43'],
  size='L', est=2380, est_note='TV 1,049 + 1,330 lines, verbatim',
  adapt=['NA Typora house style kept (olive #555041); a Vale navy token layer only if Adam wants it (DR-43).'],
  acc=['Byte-identical to TV apart from the header block; nothing links them until W4-12.'],
  tests=[],
  src=[],
  split=['WP-S07b-05A'],
  risk='Low (inert).')

P('W4-16', 'W4', 'Statement Writer standard sections (inert): Contents, Drawing Schedule, Finishes, Header, Footer and their config',
  'Port the 09 standard sections at TV\'s paths - DrawingSchedule and Finishes verbatim (they import the W4-04 engine), Contents, Header and Footer with Vale defaults, and the Standard Config JSON with Vale words; the Registry and the Hub land with W4-12 (DR-43).',
  tv=[TSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Contents__.js'), TSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__DrawingSchedule__.js'),
      TSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Finishes__.js'), TSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Header__.js'),
      TSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Footer__.js'), TSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Config__.json')],
  vv=[NEW(VSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Contents__.js')), NEW(VSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__DrawingSchedule__.js')),
      NEW(VSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Finishes__.js')), NEW(VSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Header__.js')),
      NEW(VSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Footer__.js')), NEW(VSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Config__.json'))],
  hot=[],
  deps=['W4-04'],
  gated=['DR-10', 'DR-43'],
  size='M', est=2300, est_note='TV 248 + 579 + 644 + 324 + 311 + 191 lines',
  adapt=['Keep the UK-planning field names and replace only people and company names (DR-10); no "Noble Architecture" or "TrueVision" runtime string in Header, Footer, Contents or the Config JSON.'],
  acc=['node --check passes on every file; G2 passes with the files unimported; the naming lint finds no NA runtime string in the adapted files.'],
  tests=[],
  src=[],
  split=['WP-S07b-05A'],
  risk='Low (inert).')

P('W4-06', 'W4', 'Statement data, transport binding, reader and manager',
  'Port 01 Data__ (Na__ValeVision__ storage prefixes, Vale starter, folder/name/{code} derivation per S07b-V02 using the document code) and Data__Transport verbatim over the facade (DR-27 (A), D-S07b-10 (a)), 05 Reader and 03 Manager.',
  tv=[TSW('01__Core__Data/Na__LayoutEditor__Statement__Data__.js'), TSW('01__Core__Data/Na__LayoutEditor__Statement__Data__Transport__.js'),
      TSW('05__Ui__Reader/Na__LayoutEditor__Statement__Reader__.js'), TSW('03__Ui__Page/Na__LayoutEditor__Statement__Manager__.js')],
  vv=[NEW(VSW('01__Core__Data/Na__LayoutEditor__Statement__Data__.js')), NEW(VSW('01__Core__Data/Na__LayoutEditor__Statement__Data__Transport__.js')),
      NEW(VSW('05__Ui__Reader/Na__LayoutEditor__Statement__Reader__.js')), NEW(VSW('03__Ui__Page/Na__LayoutEditor__Statement__Manager__.js'))],
  hot=[],
  deps=['W4-05'],
  gated=['DR-01', 'DR-10', 'DR-27', 'DR-29', 'DR-11'],
  size='L', est=2220,
  adapt=['{code} = the document code (W1-12), never the ?project= folderId with its "/" (S07b-V02); storage keys Na__ValeVision__StatementDraft__<id> (K2 B2); ValeVision__StatementDocs__.json index name from config (DR-29).'],
  acc=['On a throwaway VV project through WCP Flask: create, rename, save and read back a statement; the file is named like 3047_T01_S01__Doous__<Title>__.md inside 10__StatementDocs/<NN>__<Title>/ with no "/" in the name.',
       'A missing statement reads as missing, never as index.html; an outside edit of the .md is seen by the lockstep watch (Last-Modified flows through); G2 passes.'],
  tests=['Na__Test__StatementServer__.py (re-run against these modules)'],
  src=['WP-S07b-05B'],
  risk='Built behind LayoutEditor__Statement__Enabled = false (DR-10 default) until Adam answers DR-10; no NA-framed tab reaches Vale users meanwhile.')

P('W4-07', 'W4', 'Publish orchestration and the share-link record (65 Publish__ and Panel; 66 Links and Manifest; Na__LeModel__GetDocumentId)',
  'Port Publish__ and Publish__Panel (verbatim), 66 Share__Links (CurrentProject from the master index, VV project-token pattern, VV link base) and Share__Manifest (VV APP_VERSION and SCHEMA_REF), and add VV Na__LeModel__GetDocumentId - so a project can be published (from the register bar, W4-10) with its share-link record written just before the index.',
  tv=[T65('Na__LayoutEditor__Publish__.js'), T65('Na__LayoutEditor__Publish__Panel__.js'), T66('Na__LayoutEditor__Share__Links__.js'), T66('Na__LayoutEditor__Share__Manifest__.js')],
  vv=[NEW(V65('Na__LayoutEditor__Publish__.js')), NEW(V65('Na__LayoutEditor__Publish__Panel__.js')), NEW(V66('Na__LayoutEditor__Share__Links__.js')),
      NEW(V66('Na__LayoutEditor__Share__Manifest__.js')), SM],
  hot=[SM],
  deps=['W4-02', 'W4-03', 'W4-06'],
  gated=['DR-01', 'DR-22', 'DR-23', 'DR-11', 'DR-06'],
  size='M', est=1950,
  adapt=['Share__Links: CODE_PATTERN replaced by a project-token pattern admitting "/", "_", "-", "." and the three space-containing legacy folders; the NA built-in base and "Noble Architecture" fallback replaced; document keys and the ?open= parameter verbatim; never a bare code while codes collide (DR-23).',
         'GetDocumentId per DR-11 (document code accessor) as a VV-only facade export if TV\'s 1.35.1 lacks it (D-S08-06).',
         'K3: no interim "Publish drawings..." Dev entry (D-S08-04): the Register (W4-10) lands in the same wave and hosts TV\'s Publish button.'],
  acc=['By harness (or console) on localhost: 2026/3047__Doous publishes with no failures and every manifest file exists at its stated size; re-publishing the same revision overwrites and prunes; a new revision writes 00__Archive__Revisions/<id>__Revision__<old>.zip and never overwrites it.',
       'With the R2 tick (after W0-07 is applied): list-back sizes match before the manifest goes up; the index goes up last; the build manifest is untouched; only that document\'s stale keys are removed; PublishedDocuments__ShareLinks__.json is written locally and on R2 just before the index.',
       'The baked PDF opens in Chrome without garbling; reader harness pictures of the published sheets match the editor.'],
  tests=[],
  src=[],
  split=['WP-S08-09', 'WP-S08-11'],
  risk='High: first R2 write of published content (R8); keys are permanent once a link is sent (settle DR-23 first).')

P('W4-08', 'W4', 'Document sharing: Share buttons and Open (66), SpecEditor Bar 1.4.0 and the loader\'s boot-time share check',
  'Port Share__Button (statement and register kinds kept per DR-23; Vale share-title fallback), Share__Open (started by the loader, never index.html), the share stylesheet (loader STYLESHEETS before WebViewer), Config and README adapted; take SpecEditor Bar 1.4.0 with its Share button; add a boot-time check of ?open= in the loader that imports nothing from the editor and calls the facade (OpenStatements / OpenSpecification / OpenRegister).',
  tv=[T66('Na__LayoutEditor__Share__Button__.js'), T66('Na__LayoutEditor__Share__Open__.js'), T66('Na__LayoutEditor__Styles__Share__.css'),
      T66('Na__LayoutEditor__Share__Config__.json'), T66('README__DocumentSharing__.md'), TLE('50__Feature__Specification/Na__LayoutEditor__SpecEditor__Bar__.js') + ' (1.4.0)'],
  vv=[NEW(V66('Na__LayoutEditor__Share__Button__.js')), NEW(V66('Na__LayoutEditor__Share__Open__.js')), NEW(V66('Na__LayoutEditor__Styles__Share__.css')),
      NEW(V66('Na__LayoutEditor__Share__Config__.json')), NEW(V66('README__DocumentSharing__.md')), SPECBAR, LDR, NEW(TESTDIR + 'Na__Test__ShareLinks__.test.mjs')],
  hot=[SPECBAR, LDR],
  deps=['W4-07'],
  gated=['DR-01', 'DR-23', 'DR-24', 'DR-43'],
  size='M', est=1300,
  adapt=['Share__Open runs inside the loaded editor; the shared link itself triggers the lazy load through the loader facade (S07b-F35, verifier) - VV never starts Share__Open from index.html.',
         'Na__Test__ShareLinks__ ported without the s/ resolver region.'],
  acc=['Every Share button copies the configured live link (never localhost) before any await; a drawing link opens its Read view in the viewer before the 3D model loads and the loading screen returns on the 3D Model tab.',
       'The specification link opens Read; a deleted sheet\'s link opens the first sheet or the specification with a toast; Na__Test__ShareLinks__ (VV) passes; a cold load with no ?open= fetches no editor module.'],
  tests=['Na__Test__ShareLinks__.test.mjs'],
  src=['WP-S08-11'],
  risk='Medium: keys are permanent once a link is sent.')

P('W4-18', 'W4', 'Drawing Register core landed inert: Data, DeleteDialog, Transactions, Notes, Preview, Pdf',
  'Port the register\'s core modules at TV\'s path (51__Feature__DrawingRegister) over the facade - they import the facade, ConfirmDialog, ProjectData, ConfigState, SheetModel, SheetLayout, AutoSave, PdfExporter/PdfFilename/PdfFonts and Numbering (W1-13), all present by W4 - with the Register__Pdf seams; nothing imports them until W4-10.',
  tv=[T51('Na__LayoutEditor__Register__Data__.js'), T51('Na__LayoutEditor__Register__DeleteDialog__.js'), T51('Na__LayoutEditor__Register__Transactions__.js'),
      T51('Na__LayoutEditor__Register__Notes__.js'), T51('Na__LayoutEditor__Register__Preview__.js'), T51('Na__LayoutEditor__Register__Pdf__.js')],
  vv=[NEW(V51('Na__LayoutEditor__Register__Data__.js')), NEW(V51('Na__LayoutEditor__Register__DeleteDialog__.js')), NEW(V51('Na__LayoutEditor__Register__Transactions__.js')),
      NEW(V51('Na__LayoutEditor__Register__Notes__.js')), NEW(V51('Na__LayoutEditor__Register__Preview__.js')), NEW(V51('Na__LayoutEditor__Register__Pdf__.js')),
      NEW(TESTDIR + 'Na__Test__RegisterNumbering__.test.mjs')],
  hot=[],
  deps=['W3-99'],
  gated=['DR-01', 'DR-11', 'DR-37', 'DR-21'],
  size='M', est=2120, est_note='TV 377 + 64 + 425 + 196 + 204 + 846 lines',
  adapt=['Register__Pdf: project name through Na__CfApi__GetProjectDisplayName (TV :213); Vale author fallback; the yellow -> amber fix (DR-37 item 2, TV :644) as a declared seam unless WT-08 fixes TV first.',
         'Register__Preview loads PDF.js from VV vendor 07 (vendored by W0-16; config path set by W0-15; K2 TF-R07, offered to TV).'],
  acc=['G2 passes with the six files present and unimported; node --check passes; Na__Test__RegisterNumbering__ (VV-authored, over the W1-13 Numbering leaf) passes.'],
  tests=['Na__Test__RegisterNumbering__.test.mjs (VV-only, new)'],
  src=[],
  split=['WP-S07a-03'],
  risk='Low while inert; the transactions write R2 once W4-10 wires them.')

P('W4-10', 'W4', 'Drawing Register on: Editor, Export, stylesheet, the Document Register tab, Panel__Sheet 1.4.0 and the wiring',
  'Port Register__Editor and Register__Export (they import the W4-18 core, 31 DocumentKeys, 65 Publish__Panel and 66 Share__Button) and the self-linked register stylesheet; wire VIEW_REGISTER/OpenRegister/Hide/Initialize in the ModeController and the loader facade; add the Document Register tab; take Panel__Sheet 1.4.0 (typed Drawing No. row retired; Drawing Type row behind the DR-08 gate); remove the interim Drawings-menu reorder (DR-38).',
  tv=[T51('Na__LayoutEditor__Register__Editor__.js'), T51('Na__LayoutEditor__Register__Export__.js'), T51('Na__LayoutEditor__Styles__DrawingRegister__.css'),
      TLE('40__Ui__Panels/Na__LayoutEditor__Panel__Sheet__.js'), TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (register hunks)'],
  vv=[NEW(V51('Na__LayoutEditor__Register__Editor__.js')), NEW(V51('Na__LayoutEditor__Register__Export__.js')), NEW(V51('Na__LayoutEditor__Styles__DrawingRegister__.css')),
      P_SHEET, MC, LDR, TABS],
  hot=[P_SHEET, MC, LDR, TABS],
  deps=['W4-08', 'W4-18'],
  gated=['DR-01', 'DR-11', 'DR-38', 'DR-08'],
  size='M', est=1700, est_note='TV 688 + 171 + 575 lines plus Panel__Sheet and the wiring hunks',
  adapt=['The register stylesheet self-links (TV Register__Editor :596, new URL(..., import.meta.url)), so no index or loader line is added.',
         'Panel__Sheet 1.4.0 routes the drawing number to the register; the Drawing Type row hidden behind the W2-14 config gate (one-line VV seam, DR-08).',
         'TabStrip: the Document Register tab appears via the loader\'s feature-presence answer; the VV drag-to-reorder on Drawings menu rows is removed (DR-38: TV reorders from the register).'],
  acc=['The Document Register tab opens from the 3D view and from a drawing and hides on Leave, Enter and OpenSpecification; the Edit table shows DWG No., PHASE, DOCUMENT CODE, DOCUMENT NAME, SCALE, SIZE, REVISION, STATUS with drag handle and expand.',
       'A phase change asks "Its document code becomes <code>_T02_D01."; renumber, jump, move, status, name, revision and typed-number delete each confirm and write once to R2 and locally, and restore on an R2 failure (fetch-guarded test); revision notes survive a reload as a browser draft; Save to R2 asks when R2 changed since load.',
       'Read view rasterises the same bytes as Export register PDF, named with code DR and the VV document code; Download entire pack yields every sheet PDF, the register and the specification; a read-only web session sees Read only; the bar\'s Publish drawings opens 65\'s panel and Share opens 66\'s box.',
       'Na__Test__DocumentKeys__ re-run passes; G1/G2 pass.'],
  tests=['Na__Test__DocumentKeys__.test.mjs (re-run)'],
  src=['WP-S07a-03'],
  risk='Register transactions write R2 on confirmation: test with a fetch guard; check R2 for typed numbers before enabling renumber (DR-11).')

P('W4-09', 'W4', 'The web viewer shows published drawings (WebViewer 1.2.0, viewer guards, published loading screen wiring)',
  'Take WebViewer 1.2.0 whole now that the register and the reader exist, add the ModeController viewer guards (never SetSheet in the viewer; WaitForFirstDrawing resolves at once there), the loader wait seam, and wire TV\'s published loading screen (Begin, Progress, WatchPaint, Finish, CancelAll).',
  tv=[TLE('80__Feature__WebViewer/Na__LayoutEditor__WebViewer__.js'), TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (viewer guards)'],
  vv=[WEBVIEW, MC, LDR],
  hot=[WEBVIEW, MC, LDR],
  deps=['W4-10'],
  gated=['DR-01', 'DR-22', 'DR-25'],
  size='M', est=500,
  adapt=['Keep VV\'s Documents() divergence only if Adam keeps Layout Mode (DR-25 re-decided here); SheetSurface ShowPublished already came with SheetSurface 1.13.0 (W1-28).',
         'Publish before deploying: until a project is published every drawing shows the grey "not published" panel.'],
  acc=['With ?authoring=off, opening every drawing makes 0 WebGL draw calls and 0 snapshot renders; the PDF button opens the baked PDF (200, application/pdf) or toasts that none is published; tiers swap on zoom with no draws; the previous drawing\'s images are released.',
       'On a published VV drawing the cover rises at once; after 350 ms "D02 - Front Elevation is now loading" appears with a faint status stepping through real jobs; the cover lifts only when every picture and font is in; another tab mid-load takes the cover over without a blink; 3D Model drops it; the loader screen does not wait 2.5 s for renders.',
       'With authoring on the editor path is unchanged; Na__Test__PublishedReader__ re-run passes.'],
  tests=['Na__Test__PublishedReader__.test.mjs (re-run)'],
  src=['WP-S08-10'],
  split=['WP-S10-13'],
  risk='Medium; DR-25 is revisited at this port (retire Layout Mode once clients only see published files).')

P('W4-11', 'W4', 'Context-menu renderer leaf and stylesheet (27__System__ContextMenuSystem, renderer only)',
  'Port Na__ContextMenuSystem__Ui__MenuRenderer__ and its stylesheet verbatim at TV\'s path for the Statement Writer; the 3D right-click menu (SystemLogic, RightClickGuard, HitResolver, Sections) is not ported (DR-44).',
  tv=[TVM('27__System__ContextMenuSystem/Na__ContextMenuSystem__Ui__MenuRenderer__.js'), TVM('27__System__ContextMenuSystem/Na__ContextMenuSystem__Styles__.css')],
  vv=[NEW(VVM('27__System__ContextMenuSystem/Na__ContextMenuSystem__Ui__MenuRenderer__.js')), NEW(VVM('27__System__ContextMenuSystem/Na__ContextMenuSystem__Styles__.css')), CSSIDX],
  hot=[CSSIDX],
  deps=['W3-99'],
  gated=['DR-10', 'DR-44'],
  size='S', est=560,
  adapt=['Stylesheet @imported from the CSS index at TV\'s position (TV CSS index :103).'],
  acc=['node --check and G2 pass; a harness calling Na__ContextMenu__Ui__Open with a title and two sections shows a styled menu that closes on an outside click and on Escape; no 3D right-click behaviour is added to VV.'],
  tests=[],
  src=['WP-S07b-11'],
  risk='Low.')

P('W4-12', 'W4', 'Statement writing surface, standard registry, PDF, publish and the Statements page (one landing)',
  'Port the statically interlocked rest of LE/52 in one change: 09 Registry, TrueVisionHub (per DR-43) and DrawingSchedule__Live; 04 Editor, Editor__Cards and Editor__Figure; 06 Pdf; 07 Publish and Publish__Images (verbatim over the facade); 03 Page (Na__ValeVision__ keys, neutral Standard Sections title).',
  tv=[TSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Registry__.js'), TSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__TrueVisionHub__.js'),
      TSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__DrawingSchedule__Live__.js'), TSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__.js'),
      TSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__Cards__.js'), TSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__Figure__.js'),
      TSW('06__Export__Pdf/Na__LayoutEditor__Statement__Pdf__.js'), TSW('07__Export__Publish/Na__LayoutEditor__Statement__Publish__.js'),
      TSW('07__Export__Publish/Na__LayoutEditor__Statement__Publish__Images__.js'), TSW('03__Ui__Page/Na__LayoutEditor__Statement__Page__.js')],
  vv=[NEW(VSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__Registry__.js')), NEW(VSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__TrueVisionHub__.js')),
      NEW(VSW('09__Standard__Sections/Na__LayoutEditor__Statement__Standard__DrawingSchedule__Live__.js')), NEW(VSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__.js')),
      NEW(VSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__Cards__.js')), NEW(VSW('04__Ui__Editor/Na__LayoutEditor__Statement__Editor__Figure__.js')),
      NEW(VSW('06__Export__Pdf/Na__LayoutEditor__Statement__Pdf__.js')), NEW(VSW('07__Export__Publish/Na__LayoutEditor__Statement__Publish__.js')),
      NEW(VSW('07__Export__Publish/Na__LayoutEditor__Statement__Publish__Images__.js')), NEW(VSW('03__Ui__Page/Na__LayoutEditor__Statement__Page__.js')),
      NEW(TESTDIR + 'Na__Test__StatementStandard__.test.mjs'), NEW(TESTDIR + 'Na__Test__StatementSchedule__.test.mjs'),
      NEW(TESTDIR + 'Na__Test__StatementFinishes__.test.mjs'), NEW(TESTDIR + 'Na__Test__StatementPublish__.test.mjs')],
  hot=[],
  deps=['W4-06', 'W4-08', 'W4-10', 'W4-11', 'W4-15', 'W4-16'],
  gated=['DR-01', 'DR-10', 'DR-43', 'DR-37', 'DR-42'],
  size='XL', est=5700, est_note='5,676 lines in 10 new files (mostly verbatim)',
  split_justification='Cannot be split without throwaway stubs (S07b-V05 and its verifier): Page imports Publish and the Registry; Editor and Cards import the Registry; the Registry imports TrueVisionHub and the standard sections, and TrueVisionHub imports the QR modules. Everything they import that can land alone already has (markdown engine W4-04, pure modules W4-05, stylesheets W4-15, standard sections W4-16, QR W1-15, sharing W4-08, register W4-10, menu renderer W4-11, keyboards W1-29/W1-30), so this is a single mechanical copy with listed seams.',
  adapt=['TrueVisionHub: excluded from VV\'s DEFINITIONS via config (DR-43 default), file kept at TV\'s path so the Registry links; reads Na__CfApi__GetProjectDisplayName instead of window.TrueVision__Pwa__ProjectContext (TV :206).',
         'Editor__Cards picture store via the facade (or TV\'s Transport unit after WT-03); Publish/Publish__Images verbatim over the facade; DrawingSchedule__Live reads the register (W4-10).',
         'If WT-03 (TV preparation: all IO through Transport, branding into config, DEFINITIONS filter) has landed, re-pin to that TV commit and port the then-identical files verbatim (DR-42 (6)).'],
  acc=['Na__Test__StatementStandard__, __Schedule__, __Finishes__ and __Publish__ node suites pass on the VV fixture; Na__Test__StatementTyping__.html passes in a browser served by WCP Flask.',
       'Adam\'s checklist on a throwaway VV project: create a statement; typed r, t, d, o, 1, Delete and Escape land in the text and the 3D camera is untouched; Ctrl+S writes the file; Ctrl+/ and Ctrl+. each switch once; an outside edit raises the lockstep sheet within one poll; the PDF has zero extractable text.',
       'Publish with worker writes faked: every linked picture is written at its link key under VaApps/Projects/{folderId}/10__StatementDocs/ with the correct content type, the index stamped last, the build manifest not written per picture; a project sync afterwards deletes no key under 10__StatementDocs/ (W0-07).',
       'The Read view, served from a *.localhost host on a port other than 8000/8090, loads every picture from the CDN copies; G1 passes.'],
  tests=['Na__Test__StatementStandard__.test.mjs', 'Na__Test__StatementSchedule__.test.mjs', 'Na__Test__StatementFinishes__.test.mjs', 'Na__Test__StatementPublish__.test.mjs'],
  src=['WP-S07b-05C'],
  risk='The largest feature landing of W4; NA framing must not reach Vale users - the feature stays behind LayoutEditor__Statement__Enabled = false until Adam answers DR-10.')

P('W4-13', 'W4', 'Statement Writer wiring: ModeController, loader facade and the Design Statements tab (behind the Enabled switch)',
  'Wire the statements view at TV\'s positions (VIEW_STATEMENT, Initialize and Mount before the viewer branch, Hide in Enter/Leave/OpenSpecification/OpenRegister, OpenStatements through EnterUnder, OPEN_EVENT listener), the loader (VIEW_STATEMENT, CheckNames row, OpenStatements via WithEditor) and the Design Statements tab through the facade, honouring LayoutEditor__Statement__Enabled.',
  tv=[TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (statement hunks)', TLE('05__Core__ModeController/Na__LayoutEditor__TabStrip__.js') + ' (Design Statements tab)'],
  vv=[MC, LDR, TABS],
  hot=[MC, LDR, TABS],
  deps=['W4-12', 'W4-09'],
  gated=['DR-10', 'DR-38', 'DR-24'],
  size='S', est=200,
  acc=['With the switch on (test config): from the 3D view the Design Statements tab loads the editor behind the loading screen, opens the first sheet quietly underneath and shows the page; 3D -> Drawings -> Specification -> Statements -> Register keeps exactly one page visible; a reader session (?authoring=off) sees only Read, only published statements and no Manage.',
       'With the switch off (default) no statement tab or module is requested; loader CheckNames reports no mismatch; no statement module is fetched before the first tab press; G1 passes.'],
  tests=[],
  src=['WP-S07b-08'],
  risk='The SW token note for the new modules goes in the Port Record (R6); no bump here.')

P('W4-14', 'W4', 'Statement tests, fixtures and the statement test server',
  'Port the remaining statement test files and the reference Typora CSS, commit a VV fixture statement folder (headings, #### N.N sections, dividers, figures with titles and a crop, a comparison table, the house header and footer, plus a CRLF twin) and complete the adapted Na__Test__StatementServer__.py.',
  tv=['TV/80__Testing__PrototypeEnvironment/Na__Test__StatementDomRoundTrip__.html', 'TV/80__Testing__PrototypeEnvironment/Na__Test__StatementTyping__.html',
      'TV/80__Testing__PrototypeEnvironment/Na__Test__StatementFigure__.html', 'TV/80__Testing__PrototypeEnvironment/Na__Test__StatementTypography__.html',
      'TV/80__Testing__PrototypeEnvironment/Na__Test__StatementStandard__.html', 'TV/80__Testing__PrototypeEnvironment/Na__Test__StatementFinishes__.html',
      'TV/80__Testing__PrototypeEnvironment/Na__Test__Reference__TyporaTheme__.css'],
  vv=[NEW(TESTDIR + 'Na__Test__StatementDomRoundTrip__.html'), NEW(TESTDIR + 'Na__Test__StatementTyping__.html'), NEW(TESTDIR + 'Na__Test__StatementFigure__.html'),
      NEW(TESTDIR + 'Na__Test__StatementTypography__.html'), NEW(TESTDIR + 'Na__Test__StatementStandard__.html'), NEW(TESTDIR + 'Na__Test__StatementFinishes__.html'),
      NEW(TESTDIR + 'Na__Test__Reference__TyporaTheme__.css'), TESTDIR + 'Na__Test__StatementServer__.py'],
  hot=[],
  deps=['W4-13'],
  gated=['DR-10', 'DR-37'],
  size='M', est=1600,
  acc=['All 7 node suites green in VV and independent of any live project file; browser harnesses green on WCP Flask (they answer VV\'s styled confirm modal instead of stubbing window.confirm); the test server never writes outside its temp copy.'],
  tests=['Na__Test__StatementDomRoundTrip__.html', 'Na__Test__StatementTyping__.html', 'Na__Test__StatementFigure__.html', 'Na__Test__StatementTypography__.html',
         'Na__Test__StatementStandard__.html', 'Na__Test__StatementFinishes__.html', 'Na__Test__Reference__TyporaTheme__.css', 'Na__Test__StatementServer__.py'],
  src=['WP-S07b-09'],
  risk='Low.',
  notes=['The fixture folder name follows TV\'s frozen fixture once WT-03 lands it; until then the package names it and records the name in its Port Record.'])

P('W4-99', 'W4', 'Parity Scribe pass for Wave 4',
  'S11 B10 procedure for W4, including the S07a, S07b and S08 ledger work (rows 86, 121, 125, 126, 220, 321-339, 1176-1177; the Statement Writer return-trip section; VV/ValeVision__NOTES__StatementWriter__.md; the DIV-4 transport rows; row 1189; VV README notes on Chrome/Edge publishing and rename behaviour).',
  vv=[DEVLOG, LEDGER, NEW('VV/ValeVision__NOTES__StatementWriter__.md'), 'VV/ValeVision__README__.md'],
  hot=[DEVLOG, LEDGER, 'VV/ValeVision__README__.md'],
  deps=[],
  gated=['DR-35', 'DR-34', 'DR-25'],
  size='S', est=700,
  acc=['Every W4 Port Record has its devlog entry (the worker redeploy and Flask restart Adam must run are named); zero {{VVREL tokens; the DR-25 re-decision recorded; SHARED SERVICE WORKER decision recorded; harness counts from a fresh run.',
       'Rows from WP-S07a-08, WP-S07b-10 and WP-S08-13 (VV halves) written; their TV notes queued for WT-08.'],
  src=['WP-S07a-08', 'WP-S07b-10', 'WP-S08-13'],
  risk='Single writer of the two documents.')
