from k3_common import *

# =============================================================================
# W1 - CORE HUBS: 3D shared prerequisites, drawing-core data, LE leaves, the
# sheet data/record/model hubs, chrome and paint order, PDF fonts, the
# controller layer (keys, loader facade, mode controller core, veil, fold,
# tab strip) and the panel host. Every W1 package starts after W0-99.
# =============================================================================

P('W1-01', 'W1', 'Render-loop overlays registry, IsPaused, model-toggle exports and the design-phase library (uninitialised)',
  'Port TV\'s InteractiveOverlays registry with Begin/EndFrame on VV\'s interactive 3D path only, add TV\'s Na__RenderLoop__IsPaused beside VV\'s pause events, add ModelToggle SetCategoryVisibleByKey / BorrowRegistry / RestoreRegistry, and land TV\'s PhaseLibrary verbatim and uninitialised.',
  tv=[TVM('05__RenderPipeline/Na__RenderLoop__InteractiveOverlays__.js'), TVM('05__RenderPipeline/Na__RenderLoop__Invalidation.js'),
      TVM('26__System__ToggleModelElements/Na__UiFeature__ModelToggle__Controls.js'), TVM('26__System__ToggleModelElements/Na__ModelGroup__PhaseLibrary__.js')],
  vv=[NEW(VVM('05__RenderPipeline/Na__RenderLoop__InteractiveOverlays__.js')), INVALID, LS, MODELTOG,
      NEW(VVM('26__System__ToggleModelElements/Na__ModelGroup__PhaseLibrary__.js'))],
  hot=[INVALID, LS, MODELTOG],
  deps=['W0-99'],
  gated=['DR-01', 'DR-09', 'DR-32'],
  size='M', est=900, est_note='InteractiveOverlays 170 + PhaseLibrary 602 verbatim; hunks in Invalidation, LoadingSequence, ModelToggle',
  adapt=['BeginFrame on VV\'s interactive 3D branch only - after the drawing branch and after the Video Studio preview branch (guard !Na__VideoStudio__Preview__IsPlaying(), DR-32); EndFrame in the tick\'s finally.',
         'IsPaused mirrors VV\'s hold reasons; VV\'s na-pause/resume-render-loop events stay (K2 X3/E2).',
         'ModelToggle keeps the na-model-visibility-changed dispatch (VV-only integration, S02b-V01); TV names with VV bodies where internals differ (K2 X3).',
         'PhaseLibrary verbatim, never initialised: IsLive(undefined) answers true, WaitFor(null) resolves true (DR-09 (a), S09-F23); no hand-written shim.'],
  acc=['G2 resolves Na__RenderLoop__IsPaused, the three ModelToggle names and every PhaseLibrary import for TV\'s North CompassGizmo, DrawingPlanes, LE SnapshotRenderer and ModelSource.',
       'With nothing registered, a thumbnail, a sheet 3D viewport and an image export are byte-identical to before (spot check); a registered test group shows only in live 3D frames, never in a sheet render, thumbnail, export or Video Studio preview.',
       'IsPaused() is true while the Layout Editor holds the loop and false otherwise; toggling a model layer still refreshes linework and snapshot fingerprints.'],
  tests=[],
  src=['WP-S01-10', 'WP-S02a-02', 'WP-S09-07'],
  split=['WP-S04a-05R'],
  risk='Render-loop edits affect every frame; VV renders more paths than TV (Video Studio, Export Render Layers).',
  notes=['The DoorAnim exports and FindDoorGroups named by WP-S01-10/WP-S09-07 are delivered by W1-02.'])

P('W1-02', 'W1', 'Door module to the TV 1.9.0 contract, plus FindDoorGroups',
  'Merge TV door module 1.8.0/1.9.0 onto VV 1.7.1 (MOD constants, ComputePanelLocalPose, ApplyPanelTransform, GetLiveProgress, DescribeDoors, ScanGroupsInto, FindAdrAncestor, ResolveHitPanel, IsDoorOpen, left-button-only clicks) keeping VV\'s Video Studio exports, and add Na__DoorAnimation__FindDoorGroups.',
  tv=[TVM('25__System__3dObject__InteractionSystem/3dObjectIInteraction__Animation__ClickToOpenDoors__.js'),
      TVM('25__System__3dObject__InteractionSystem/Na__DoorAnimation__FindDoorGroups.js')],
  vv=[DOORS, NEW(VVM('25__System__3dObject__InteractionSystem/Na__DoorAnimation__FindDoorGroups.js')),
      VVM('25__System__3dObject__InteractionSystem/3dObjectIInteraction__Animation__ClickToOpenDoors__README__.md')],
  hot=[DOORS],
  deps=['W0-99'],
  gated=['DR-01', 'DR-16'],
  size='M', est=420,
  adapt=['Keep VV\'s SnapAllClosed, Get/SetSpeedScale, GetBaseDurationMs, bootstrap and thresholds (Video Studio); a wholesale copy of TV\'s file would break Video Studio.'],
  acc=['Export set = TV 1.9.0\'s set plus VV\'s four Video Studio exports; G1/G2 pass.',
       'Orbit left-click opens and closes doors; a stationary right click no longer toggles one; walk-mode proximity doors and Video Studio "start with doors shut" unchanged.',
       'Na__DoorAnim__DescribeDoors on a loaded VV project returns the registry\'s own records for registered doors.'],
  tests=[],
  src=['WP-S02b-01'],
  risk='Must land before folder 50 (W2-06): DoorPose\'s 7 imports fail to link without it (S02b-F26 critical).')

P('W1-03', 'W1', 'Drawing-quality prerequisites: ortho depth bias and the supersampler clamp',
  'Bring VV MultiModel to TV 1.3.0\'s orthographic depth bias (RenderConfig__Linework__OrthoDepthBiasMm = 2 mm) and the supersampler present pass to min(rgb, a) (TV v2.103.0), the two fixes depth fog and the base images need.',
  tv=[TVM('15__ModelLoader/Na__ModelLoader__MultiModel.js'), TVM('02__AppData/Na__AppConfig__Main.json'), TVM('05__RenderPipeline/Na__RenderEffect__Supersampler__.js')],
  vv=[MULTIMODEL, MAINCFG, SUPERSAMP],
  hot=[MULTIMODEL, MAINCFG, SUPERSAMP],
  deps=['W0-99'],
  gated=['DR-01'],
  size='S', est=60,
  acc=['Elevation base images lose the fascia and parapet line bleed (pixel diff against before, as TV row X); a perspective render is unchanged to the pixel.',
       'A supersampled premultiplied layer has colour no greater than alpha at every pixel; opaque frames are byte-identical.'],
  tests=[],
  src=['WP-S02b-11'],
  risk='MultiModel and the Main config are high-traffic files: hunks only.')

P('W1-04', 'W1', 'Transitions 1.1.0: the walk exit only when asked',
  'Port ReturnToOrbit and the options.returnToOrbit gate onto VV Transitions (VV orbit setter, MaxEngine culling, Initialize kept) and pass the option from VV\'s floor plan and elevation entries; the LE ModeController line lands in W1-32.',
  tv=[TVM('40__System__DrawingViewCore/Na__DrawView__Transitions__.js')],
  vv=[TRANSIT, FPMC, EVMC],
  hot=[TRANSIT, FPMC, EVMC],
  deps=['W0-99'],
  gated=['DR-01', 'DR-32'],
  size='S', est=120,
  adapt=['VV keeps its own 42/45 mode controllers (DR-32): only the returnToOrbit option is added to their entries (S03a-V03); Na__NavToolbar__SetOrbitMode is the exit.'],
  acc=['Walking in 3D while a scene save restamps sheet viewports stays in Walk with the toolbar on Walk (Adam).',
       'Opening a sheet while walking leaves Walk and lights Orbit (verified after W1-32 lands the LE line).',
       'Transitions sections of Na__Test__SheetPagingWalkExit__ pass (suite ported whole in W1-36).'],
  tests=[],
  src=['WP-S02a-11'],
  risk='Low.')

P('W1-05', 'W1', 'Drawings data module: TV ProjectData 1.6.0 whole over the VV facade',
  'Take TV Na__DrawView__ProjectData__ 1.6.0 whole (payload guard, save steps before/payload/after, IsLoaded, SAVED_ISO_KEY, GetBase/WhenBaseKnown/LearnBase/CheckBase, Save(showToast, report, registerKeys) through Na__CfApi__MergeAndSaveKeys and the guarded Flask POST) and re-apply VV\'s LayoutModeEnabled and section-block provider seams; North gains Save(showToast, report).',
  tv=[TVM('40__System__DrawingViewCore/Na__DrawView__ProjectData__.js'), TVM('46__System__NorthDirection/Na__North__ProjectJson__Data__.js')],
  vv=[PD, NORTHDATA, XSECTSD],
  hot=[PD, NORTHDATA, XSECTSD],
  deps=['W0-99'],
  gated=['DR-01', 'DR-27', 'DR-30', 'DR-41'],
  size='M', est=900, est_note='TV 976 vs VV 496 lines; whole-file port with seams',
  adapt=['Re-apply LayoutModeEnabled (key, getter, setter, skeleton, normalise; DR-25 (a)); VV description; migration region inert.',
         'VV 41 CrossSectionView SceneData registers Na__SectSceneData__GetProjectBlock through Na__DrawData__RegisterSectionBlockProvider (DIV-2); TV 41 SceneData/Serialize never ported (DR-41).',
         'R2 judging behind its flag, off until Adam switches it on (DR-30).'],
  acc=['Save writes R2 through merge-keys then disk through the guarded Flask POST and reports report.local; a disk block changed since load refuses the save before R2 with the v2.146 toast.',
       'Node check (stubbed fetch): a registered payload guard changes the written copy but not the live block; save steps run before/payload/after in order; a throwing step is noted and does not fail the save; one toast per save with a report.',
       'The block is stamped LayoutEditor__DrawingsData__SavedIso; LayoutModeEnabled survives a save; section bindings ride when present.',
       'Existing VV callers (LE SheetModel, Loader, RenameDrawing, Dev editors, North) still save (Adam: Save Sheets, Save North on localhost); G2 shows IsLoaded, RegisterPayloadGuard, RegisterSaveStep, SAVED_ISO_KEY.'],
  tests=[],
  src=['WP-S12-07', 'WP-S02a-03'],
  split=['WP-S03b-05', 'WP-S07a-02'],
  risk='Every drawing save path depends on it: test on a copy of 2026/3047__Doous.')

P('W1-06', 'W1', 'Draft core and the shared Dev-row shell',
  'Port the drawing-draft system\'s pure and shell modules (DraftMaths, DrawingUsage, DevRowShell, DraftGuard), RowAccordion whole, RenameDrawing staged holders, the DrawView dev CSS "Drawing Panel Shell" region (its CSS-index @import moved last, as TV) and the Presentation modal 1.2.0 with its CSS.',
  tv=[TVM('40__System__DrawingViewCore/Na__DrawView__DraftMaths__.js'), TVM('40__System__DrawingViewCore/Na__DrawView__DrawingUsage__.js'),
      TVM('40__System__DrawingViewCore/Na__DrawView__DevRowShell__.js'), TVM('40__System__DrawingViewCore/Na__DrawView__DraftGuard__.js'),
      TVM('40__System__DrawingViewCore/Na__DrawView__RowAccordion__.js'), TVM('40__System__DrawingViewCore/Na__DrawView__RenameDrawing__.js'),
      TVM('40__System__DrawingViewCore/Na__DrawView__Styles__DevMenu__.css'), TVM('21__System__PresentationMode/Na__PresentationMode__DevMenu__Modal__.js')],
  vv=[NEW(VVM('40__System__DrawingViewCore/Na__DrawView__DraftMaths__.js')), NEW(VVM('40__System__DrawingViewCore/Na__DrawView__DrawingUsage__.js')),
      NEW(VVM('40__System__DrawingViewCore/Na__DrawView__DevRowShell__.js')), NEW(VVM('40__System__DrawingViewCore/Na__DrawView__DraftGuard__.js')),
      VVM('40__System__DrawingViewCore/Na__DrawView__RowAccordion__.js'), VVM('40__System__DrawingViewCore/Na__DrawView__RenameDrawing__.js'),
      DRAWDEVCSS, MODAL, 'VV/03__Style__AppStylesheets/Na__PresentationMode__Styles__SceneCarousel__.css', CSSIDX,
      NEW(TESTDIR + 'Na__Test__DrawingDrafts__.test.mjs')],
  hot=[MODAL, DRAWDEVCSS, CSSIDX, 'VV/03__Style__AppStylesheets/Na__PresentationMode__Styles__SceneCarousel__.css'],
  deps=['W1-05'],
  gated=['DR-01'],
  size='M', est=1950, est_note='4 new verbatim files (1,379) + RowAccordion/Rename/CSS/Modal deltas',
  adapt=['RenameDrawing: StageHolders/StageFloorPlan/StageElevation on VV\'s loader restamp route.',
         'DraftGuard registers guards at import time: never imported before ProjectData exposes RegisterPayloadGuard (W1-05).'],
  acc=['Na__Test__DrawingDrafts__ (ported) passes against VV modules; G1/G2 pass.',
       'Existing VV floor plan and elevation panels still fold and open (callers of SetOpenId/Wrap unchanged).',
       'The modal shows a details list, footnote and green commit button (manual test page); the DrawView dev CSS @import sits where TV\'s CSS index has it.'],
  tests=['Na__Test__DrawingDrafts__.test.mjs'],
  src=['WP-S02a-04'],
  risk='Low; the Modal is also wanted by W1-07 (AutoSave 1.5.0 altLabel) - this package is its single owner.')

P('W1-07', 'W1', 'AutoSave 1.5.0 and the project-file draft guard',
  'Port AutoSave 1.5.0 (IsLoaded-gated key, base in each draft, JudgeDraft with Apply / Discard / Decide Later, Suspend, Resume, DiscardSavedDraft, register-updated ignored) on VV\'s late-start SheetModel and the W1-05 ProjectData base functions.',
  tv=[TLE('07__Core__SheetData/Na__LayoutEditor__AutoSave__.js')],
  vv=[AUTOSAVE],
  hot=[AUTOSAVE],
  deps=['W1-05', 'W1-06', 'W1-21'],
  gated=['DR-01', 'DR-30', 'DR-07'],
  size='M', est=420,
  adapt=['Re-apply the W0-08 seam: window.Na__Pwa__HasUnsavedWork published from Na__LeAuto__HasUnsavedWork (TV publishes window.TrueVision__Pwa__HasUnsavedWork; K2 K4).',
         'Labels DraftApplied / DraftDiscarded / DraftLeftAside already exist (W0-15).'],
  acc=['Na__Test__DraftRestore__ (27 checks) and Na__Test__DraftGuard__ (11 tests) pass against VV modules.',
       'A pre-upgrade VV draft (no base) is asked about once; Discard leaves the saved sheets; nothing writes the draft while the question is open.',
       'Two windows on 3047__Doous: the second window\'s save is refused before R2 is written and its draft is offered on reload.'],
  tests=['Na__Test__DraftRestore__.test.mjs', 'Na__Test__DraftGuard__.test.cjs'],
  src=['WP-S12-08', 'WP-S03b-05'],
  risk='A server not restarted leaves saves unjudged (TV notes the same); the worker stays unjudged until DR-30\'s flag.')

P('W1-08', 'W1', 'Floor plan storey level and TV\'s data-module convention',
  'Port StoreyLevel, the StoreyRow Dev row and ConfigState 1.1.0 verbatim and take ProjectJson__Data__ 1.1.0 whole (records via Na__DrawData__GetFloorPlansArray; first argument = sceneConfig), re-adding VV\'s extras; add the StoreyLevels config block, labels and the storey-note CSS.',
  tv=[TVM('42__System__FloorPlanViews/Na__FloorPlan__StoreyLevel__.js'), TVM('42__System__FloorPlanViews/Na__FloorPlan__DevMenu__StoreyRow__.js'),
      TVM('42__System__FloorPlanViews/Na__FloorPlan__ConfigState__.js'), TVM('42__System__FloorPlanViews/Na__FloorPlan__ProjectJson__Data__.js'),
      TVM('42__System__FloorPlanViews/Na__FloorPlan__AppConfig__.json'), TVM('42__System__FloorPlanViews/Na__FloorPlan__Styles__DevMenu__.css')],
  vv=[NEW(VVM('42__System__FloorPlanViews/Na__FloorPlan__StoreyLevel__.js')), NEW(VVM('42__System__FloorPlanViews/Na__FloorPlan__DevMenu__StoreyRow__.js')),
      VVM('42__System__FloorPlanViews/Na__FloorPlan__ConfigState__.js'), FPDATA, FPCFG, FPCSS,
      NEW(TESTDIR + 'Na__Test__FloorPlanStoreyLevel__.test.mjs')],
  hot=[FPDATA, FPCFG, FPCSS],
  deps=['W1-05'],
  gated=['DR-01', 'DR-16'],
  size='M', est=1100,
  adapt=['Re-add VV extras in the data module: STYLE_KEYS export, Dimensions default, trimmed tokens (D33 rows stay, DR-32).',
         'Every VV caller passes null today (18 sites): check each for a block argument before the signature switch.'],
  acc=['Na__Test__FloorPlanStoreyLevel__ passes (36 checks incl. shipped JSON vs fallback).',
       'Na__FpData__CreatePlan(presentationConfigObject, {}) adds to LayoutEditor__DrawingsData__FloorPlans and leaves the presentation object without new keys.',
       'GetStoreyLevel on a plan named "Roof Plan" answers roof from the name and writes nothing; SetStoreyLevel dispatches na-floorplan-storey-changed; G2 lists GetStoreyLevel, IsStoreyLevelSet, GetStoreyLevelChoices, SetStoreyLevel, STOREY_CHANGED_EVENT.'],
  tests=['Na__Test__FloorPlanStoreyLevel__.test.mjs'],
  src=['WP-S02a-05'],
  risk='A missed caller passing a block would silently read the wrong object.')

P('W1-09', 'W1', 'Elevation depth-fog pure modules (49 leaves, inert)',
  'Land TV\'s 49 AppConfig, ConfigState, Maths, RecordData and Shader verbatim so the elevation data module 1.1.0 can be taken whole; the render layer, Dev row and wiring come in W2-03.',
  tv=[TVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__AppConfig__.json'), TVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__ConfigState__.js'),
      TVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__Maths__.js'), TVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__RecordData__.js'),
      TVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__Shader__.js')],
  vv=[NEW(VVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__AppConfig__.json')), NEW(VVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__ConfigState__.js')),
      NEW(VVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__Maths__.js')), NEW(VVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__RecordData__.js')),
      NEW(VVM('49__System__ElevationDepthFog/Na__ElevationDepthFog__Shader__.js')), NEW(TESTDIR + 'Na__Test__ElevationDepthFog__.test.mjs')],
  hot=[],
  deps=['W0-99'],
  gated=['DR-01', 'DR-15'],
  size='M', est=1150,
  adapt=['Verbatim below a VALEVISION3D header; Shader header logs v2.103.0.'],
  acc=['Na__Test__ElevationDepthFog__ passes 68/68 against VVM/49/...Maths__.js (pure part); nothing imports the modules yet; G2 passes (they link).'],
  tests=['Na__Test__ElevationDepthFog__.test.mjs'],
  src=[],
  split=['WP-S02b-04R'],
  risk='Very low (inert).',
  notes=['Split out of WP-S02b-04R because TV Na__Elevation__ProjectJson__Data__.js 1.1.0 imports 49 RecordData (TV :84-89), so the elevation data port (W1-10) needs these leaves first (DR-05 leaves first).'])

P('W1-10', 'W1', 'Elevation auto-name, identity statement and data module 1.1.0 (with the fog accessors)',
  'Port AutoNameText and AutoName verbatim and take the elevation ProjectJson__Data__ 1.1.0 whole (TV first-argument convention, GetDepthFog/SetDepthFog/GetDepthFogPlane, Ensure in the normaliser and creator), apply VV\'s SeededFrom seam, union the AppConfig labels and add the identity/compass-mark CSS.',
  tv=[TVM('45__System__ElevationViews/Na__Elevation__AutoName__.js'), TVM('45__System__ElevationViews/Na__Elevation__AutoNameText__.js'),
      TVM('45__System__ElevationViews/Na__Elevation__ProjectJson__Data__.js'), TVM('45__System__ElevationViews/Na__Elevation__AppConfig__.json'),
      TVM('45__System__ElevationViews/Na__Elevation__Styles__DevMenu__.css')],
  vv=[NEW(VVM('45__System__ElevationViews/Na__Elevation__AutoName__.js')), NEW(VVM('45__System__ElevationViews/Na__Elevation__AutoNameText__.js')),
      EVDATA, EVCFG, EVCSS, NEW(TESTDIR + 'Na__Test__ElevationGeometry__.html')],
  hot=[EVDATA, EVCFG, EVCSS],
  deps=['W1-05', 'W1-09'],
  gated=['DR-01', 'DR-32', 'DR-15'],
  size='M', est=900,
  adapt=['Elevation__SeededFrom kept as a VV seam per DR-32; labels unioned (VV-only labels kept).'],
  acc=['With north set, a new elevation is named "<Word> Elevation" and a second facing the same way "<Word> Elevation 2"; a typed name sets Elevation__NameIsAuto false and survives turning.',
       'Na__ElevData__CreateElevation(presentationConfigObject, {}) writes only to LayoutEditor__DrawingsData__Elevations; every elevation record gains Elevation__DepthFog (off) on first read; a drawing with fog off renders byte-identical.',
       'Na__Test__ElevationGeometry__.html (ported) renders its checks green; G1/G2 pass.'],
  tests=['Na__Test__ElevationGeometry__.html'],
  src=['WP-S02a-06'],
  split=['WP-S02b-04R'],
  risk='The elevation data file is later read by W2-03 (fog) and W2-05 (Dev menu); this package is its single owner.')

P('W1-11', 'W1', 'North: Show Compass (TV 1.1.0 whole)',
  'Take CompassGizmo 1.1.0 and the North Dev editor 1.1.0 whole on the overlays registry, add ShownByDefault and the Show Compass labels, and drop VV\'s compass listeners on sheet open and in the snapshot queue.',
  tv=[TVM('46__System__NorthDirection/Na__North__CompassGizmo__.js'), TVM('46__System__NorthDirection/Na__North__DevMenu__Editor__.js'), TVM('46__System__NorthDirection/Na__North__AppConfig__.json')],
  vv=[VVM('46__System__NorthDirection/Na__North__CompassGizmo__.js'), VVM('46__System__NorthDirection/Na__North__DevMenu__Editor__.js'), VVM('46__System__NorthDirection/Na__North__AppConfig__.json')],
  hot=[],
  deps=['W1-01', 'W1-05'],
  gated=['DR-01', 'DR-32'],
  size='S', est=250,
  acc=['Na__Test__NorthCompass__ passes; Show Compass on, panel closed, reload: compass back with no panel opened.',
       'A sheet render, a thumbnail and an export while the compass is kept contain no compass (Adam).'],
  tests=['Na__Test__NorthCompass__.test.mjs (re-run)'],
  src=['WP-S02a-10'],
  risk='Relies on W1-01\'s overlay registry being wired on every VV render path.')

P('W1-12', 'W1', 'Project identity accessors: the document code and ProjectRecord\'s root facts',
  'Add VV\'s document-code accessor Na__DrawData__GetDocumentCode() (projectCode of the loaded project.json, falling back to the master index entry for the ?project= token) as a VV-only export of ProjectData, and make ProjectRecord read clientDrawingName and siteAddress from the loaded project root.',
  tv=[TLE('07__Core__SheetData/Na__LayoutEditor__ProjectRecord__.js')],
  vv=[PD, PROJREC, NEW(TESTDIR + 'Na__Test__ProjectRecordAddress__.html')],
  hot=[PD, PROJREC],
  deps=['W1-05'],
  gated=['DR-01', 'DR-11'],
  size='S', est=300,
  adapt=['Accessor reads Na__CfApi__GetLoadedProjectData() (set by W0-13), so no further LoadingSequence edit is needed (K3 resolution of WP-S07a-09\'s hand-over; same value, one fewer LoadingSequence editor).',
         'Na__DrawData__GetProjectCode() stays the transport token (/api/projects/<token>); only DOCUMENT uses take the accessor: SheetRecords DrawingNumber default (W1-19), SpecPdf number, PdfExporter Na__LePdf__Filename, Register__Pdf, Sheet Images (one marked seam each unless TV adopts the accessor).',
         'ProjectRecord keeps its VV PORT NOTE divergence (no admin system).'],
  acc=['Opened as ?project=2026/3047__Doous, ?project=3047 and ?project=3047__Doous, the title block default, the specification number and the PDF file names all read 3047..., never the folderId.',
       'A project.json with root siteAddress and clientDrawingName seeds the Common fields; the presentation block is not read for these facts.',
       'Drawings, register and specification saves still reach /api/projects/<token> and R2 unchanged.'],
  tests=['Na__Test__ProjectRecordAddress__.html'],
  src=['WP-S07a-09', 'WP-S12-10'],
  risk='Touches the one drawings save module: must not change the transport token.')

P('W1-13', 'W1', 'Layout Editor pure leaves A: markup, records, numbering, scales, site-plan composites',
  'Land the import-free (or config-only) leaves the record and markup hubs import: ShapeRings, DimensionRounding, PaintOrder, MeasureParse 1.1.0, SheetRecords__NoteRegions, SheetRecords__LeaderlessNotes, Register__Numbering, ScaleManager 1.2.1 and SitePlanComposites with its config - verbatim and inert.',
  tv=[TLE('15__Core__Markup/Na__LayoutEditor__ShapeRings__.js'), TLE('15__Core__Markup/Na__LayoutEditor__DimensionRounding__.js'),
      TLE('15__Core__Markup/Na__LayoutEditor__PaintOrder__.js'), TLE('15__Core__Markup/Na__LayoutEditor__MeasureParse__.js'),
      TLE('07__Core__SheetData/Na__LayoutEditor__SheetRecords__NoteRegions__.js'), TLE('07__Core__SheetData/Na__LayoutEditor__SheetRecords__LeaderlessNotes__.js'),
      TLE('51__Feature__DrawingRegister/Na__LayoutEditor__Register__Numbering__.js'), TLE('07__Core__SheetData/Na__LayoutEditor__ScaleManager__.js'),
      TLE('25__System__RenderStyles/Na__LayoutEditor__SitePlanComposites__.js'), TLE('25__System__RenderStyles/Na__LayoutEditor__SitePlanComposites__Config__.json')],
  vv=[NEW(VLE('15__Core__Markup/Na__LayoutEditor__ShapeRings__.js')), NEW(VLE('15__Core__Markup/Na__LayoutEditor__DimensionRounding__.js')),
      NEW(VLE('15__Core__Markup/Na__LayoutEditor__PaintOrder__.js')), VLE('15__Core__Markup/Na__LayoutEditor__MeasureParse__.js'),
      NEW(VLE('07__Core__SheetData/Na__LayoutEditor__SheetRecords__NoteRegions__.js')), NEW(VLE('07__Core__SheetData/Na__LayoutEditor__SheetRecords__LeaderlessNotes__.js')),
      NEW(VLE('51__Feature__DrawingRegister/Na__LayoutEditor__Register__Numbering__.js')), SCALEMGR,
      NEW(VLE('25__System__RenderStyles/Na__LayoutEditor__SitePlanComposites__.js')), NEW(VLE('25__System__RenderStyles/Na__LayoutEditor__SitePlanComposites__Config__.json')),
      NEW(TESTDIR + 'Na__Test__DimensionRoundUp__.test.mjs')],
  hot=[SCALEMGR],
  deps=['W0-99'],
  gated=['DR-01', 'DR-08', 'DR-11'],
  size='M', est=2000, est_note='~1,950 verbatim lines in 10 files',
  adapt=['Verbatim below VALEVISION3D headers; PORT NOTEs "Nothing here is app-specific" where TV says so; SitePlanComposites lands dormant (DR-08 (B)).',
         'ShapeRings and DimensionRounding carry TV notes that the VV port waits for Adam\'s sign-off: DR-01 covers them (default (c)).'],
  acc=['Every module loads with no consumer; G1/G2 pass.',
       'NoteRegions and LeaderlessNotes normalise a fixture margin record exactly as TV\'s do; Na__Test__DimensionRoundUp__ passes 21/21 on VV\'s copy.',
       'Existing 1:20/1:50/1:100 viewports unchanged with ScaleManager 1.2.1 (site plan list inert).'],
  tests=['Na__Test__DimensionRoundUp__.test.mjs', 'Na__Test__NoteRegions__.test.mjs (record part)', 'Na__Test__LeaderlessNotes__.test.mjs (record part)'],
  src=['WP-S03b-02R'],
  split=['WP-S05b-01', 'WP-S03b-10', 'WP-S07a-01', 'WP-S04a-10R'],
  risk='Very low: no consumer until later packages.')

P('W1-14', 'W1', 'Layout Editor pure leaves B: rotation, curves, drafting-aid state, vector quality',
  'Land ViewportRotation 1.0.0, VectorTools__Curves 1.0.0, DraftMode__State, DrawingGrid__State, OrthoMode__State and VectorQuality verbatim and inert (all import nothing or config only).',
  tv=[TLE('20__System__Viewports/Na__LayoutEditor__ViewportRotation__.js'), TLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Curves__.js'),
      TLE('26__System__DraftMode/Na__LayoutEditor__DraftMode__State__.js'), TLE('27__System__DrawingGrid/Na__LayoutEditor__DrawingGrid__State__.js'),
      TLE('32__System__OrthoMode/Na__LayoutEditor__OrthoMode__State__.js'), TLE('20__System__Viewports/Na__LayoutEditor__VectorQuality__.js')],
  vv=[NEW(TESTDIR + 'Na__Test__ViewportRotation__.test.mjs'), NEW(VLE('20__System__Viewports/Na__LayoutEditor__ViewportRotation__.js')), NEW(VLE('37__System__VectorTools/Na__LayoutEditor__VectorTools__Curves__.js')),
      NEW(VLE('26__System__DraftMode/Na__LayoutEditor__DraftMode__State__.js')), NEW(VLE('27__System__DrawingGrid/Na__LayoutEditor__DrawingGrid__State__.js')),
      NEW(VLE('32__System__OrthoMode/Na__LayoutEditor__OrthoMode__State__.js')), NEW(VLE('20__System__Viewports/Na__LayoutEditor__VectorQuality__.js'))],
  hot=[],
  deps=['W0-99'],
  gated=['DR-01', 'DR-05'],
  size='M', est=1620,
  adapt=['Verbatim; header and PORT NOTE only (git diff --no-index -w shows header/port-note lines only).'],
  acc=['The six files exist at TV\'s paths and export exactly TV\'s names; G1/G2 pass; ortho and grid snapping report off with no UI present; no visible change; existing sheets re-save byte-identical.',
       'Leaf checks of Na__Test__ViewportRotation__ pass against VV\'s copy (suite completed in W3-06).'],
  tests=['Na__Test__ViewportRotation__.test.mjs (leaf section)'],
  src=['WP-S04b-01', 'WP-S05b-02'],
  split=['WP-S04a-01R', 'WP-S04a-04'],
  risk='Low. Curves must land before any ObjectSnap port (S05b-F08 load-order trap).')

P('W1-15', 'W1', 'Project QR code (53) switched off, with a VV ProjectLink',
  'Port LE/53__Feature__ProjectQrCode (Encoder and Painter verbatim; Symbol fail-closed; ProjectLink adapted to VV identity; Config with ProjectQr__Enabled false and BaseUrl \'\'; README rewritten) so ShapeGeometry, the QR title-block cell and the parametric scrapbook link verbatim while no code ever prints.',
  tv=[TLE('53__Feature__ProjectQrCode/Na__ProjectQr__Encoder__.js'), TLE('53__Feature__ProjectQrCode/Na__ProjectQr__Painter__.js'),
      TLE('53__Feature__ProjectQrCode/Na__ProjectQr__Symbol__.js'), TLE('53__Feature__ProjectQrCode/Na__ProjectQr__ProjectLink__.js'),
      TLE('53__Feature__ProjectQrCode/Na__ProjectQr__Config__.json'), TLE('53__Feature__ProjectQrCode/README__ProjectQrCode__.md')],
  vv=[NEW(VLE('53__Feature__ProjectQrCode/Na__ProjectQr__Encoder__.js')), NEW(VLE('53__Feature__ProjectQrCode/Na__ProjectQr__Painter__.js')),
      NEW(VLE('53__Feature__ProjectQrCode/Na__ProjectQr__Symbol__.js')), NEW(VLE('53__Feature__ProjectQrCode/Na__ProjectQr__ProjectLink__.js')),
      NEW(VLE('53__Feature__ProjectQrCode/Na__ProjectQr__Config__.json')), NEW(VLE('53__Feature__ProjectQrCode/README__ProjectQrCode__.md')),
      NEW(TESTDIR + 'Na__Test__ProjectQr__.test.mjs'), NEW(TESTDIR + 'Na__Test__ProjectQr__Decode__.py')],
  hot=[],
  deps=['W0-99'],
  gated=['DR-01', 'DR-12', 'DR-43'],
  size='M', est=1900,
  adapt=['ProjectLink reads VV identity (master index via W0-11 helpers, resolver key per DR-12) - never TV\'s URL parameters; Symbol fails CLOSED (no symbol) when the config cannot be read (S07a-V02); no NA address anywhere (R9).'],
  acc=['Na__Test__ProjectQr__ sections 1-3 and 5-6 and Na__Test__ProjectQr__Decode__ pass in VV; with the QR config unreadable Na__ProjectQr__GetSymbol answers no symbol.',
       'G1/G2 pass with the modules present and nothing importing them yet; no VV file contains noble-architecture.com/q/.'],
  tests=['Na__Test__ProjectQr__.test.mjs', 'Na__Test__ProjectQr__Decode__.py'],
  src=['WP-S07a-04'],
  split=['WP-S07a-10'],
  risk='Printed codes outlive the repository: ship disabled until W5-05 provides a Vale resolver (DR-12).')

P('W1-16', 'W1', 'Sheet Images render leaves (54), ahead of the shared-core ports',
  'Port the render half of LE/54__Feature__SheetImages (Setup adapted, Geometry, Painter, Paint, Pdf, Encode verbatim, Source on the VV facade, Config adapted) so SheetRecords, SheetChrome, ShapeGeometry and PdfExporter can be taken whole.',
  tv=[TLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Setup__.js'), TLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Geometry__.js'),
      TLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Painter__.js'), TLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Paint__.js'),
      TLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Source__.js'), TLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Pdf__.js'),
      TLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Encode__.js'), TLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Config__.json')],
  vv=[NEW(VLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Setup__.js')), NEW(VLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Geometry__.js')),
      NEW(VLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Painter__.js')), NEW(VLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Paint__.js')),
      NEW(VLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Source__.js')), NEW(VLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Pdf__.js')),
      NEW(VLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Encode__.js')), NEW(VLE('54__Feature__SheetImages/Na__LayoutEditor__SheetImages__Config__.json'))],
  hot=[],
  deps=['W0-99'],
  gated=['DR-01', 'DR-13', 'DR-29'],
  size='M', est=2000,
  adapt=['Setup: VV Pages-base and frame fallbacks; fails CLOSED to no address (S07a-V02).',
         'Source reads through the facade (Na__CfApi__SheetImageLocation, IsConfigured) and Na__AppUtils__IsRunningOnLocalhost; folder 05__Layout__DrawingDocs__Images (DR-29).'],
  acc=['Geometry and painter parts of Na__Test__SheetImages__ pass in VV; G1/G2 pass with nothing importing the modules yet.',
       'Every file has a VALEVISION3D header, PORT NOTE and [ValeVision3D ...] console prefix; no NA address appears with the config unreadable.'],
  tests=['Na__Test__SheetImages__.test.mjs (geometry and painter parts; full suite in W3-09)'],
  src=['WP-S07a-10'],
  risk='Low (new files), but upstream of W1-19, W1-26 and W3-17.')

P('W1-17', 'W1', 'Hatch patterns leaf and the app-root hatch library',
  'Add LE/36 HatchPatterns and Styles__Patterns.css and the app-root 52__LayoutEditor__HatchPatternLibrary (adapted root index, Construction pack first; Site Plan pack shared because site plans port dormant, DR-08/DR-19) with no wiring.',
  tv=[TLE('36__System__HatchPatternTools/Na__LayoutEditor__HatchPatterns__.js'), TLE('36__System__HatchPatternTools/Na__LayoutEditor__Styles__Patterns__.css'),
      'TV/52__LayoutEditor__HatchPatternLibrary/ (24 files)'],
  vv=[NEW(VLE('36__System__HatchPatternTools/Na__LayoutEditor__HatchPatterns__.js')), NEW(VLE('36__System__HatchPatternTools/Na__LayoutEditor__Styles__Patterns__.css')),
      NEW('VV/52__LayoutEditor__HatchPatternLibrary/HatchLibrary__Index__.json'), NEW('VV/52__LayoutEditor__HatchPatternLibrary/02__ConstructionMaterialHatches/ (verbatim)'),
      NEW('VV/52__LayoutEditor__HatchPatternLibrary/ (Site Plan pack, verbatim)')],
  hot=[],
  deps=['W0-99'],
  gated=['DR-01', 'DR-19', 'DR-08'],
  size='M', est=1100,
  adapt=['Root index adapted only for pack order (Construction first, Brickwork stays default); VV headers, console prefix.'],
  acc=['52__LayoutEditor__HatchPatternLibrary/HatchLibrary__Index__.json fetches 200 on localhost Flask and on the live host; the editor\'s first open is unchanged (module unreferenced); G2 passes.'],
  tests=[],
  src=['WP-S05b-01'],
  split=['WP-S01-07'],
  risk='Low. The library name and location are load-bearing (S05b-F03).',
  notes=['WP-S05b-01\'s 15__Core__Markup leaves are in W1-13 and its 37 pure leaves in W2-26 (split for size and order).'])

P('W1-18', 'W1', 'GradientTool 1.1.0 and LineStyleTool 1.1.0',
  'Take the two drawing-tool leaves whole (DrawPdf with holes and an even-odd clip; BuildRows/RefreshRows/RegisterControls taking { prefix, dashedLabel, dashedTitle }) before SheetChrome 1.14.0 and Panel__Dimensions 1.7.0 need them.',
  tv=[TLE('35__System__DrawingTools/Na__LayoutEditor__GradientTool__.js'), TLE('35__System__DrawingTools/Na__LayoutEditor__LineStyleTool__.js')],
  vv=[VLE('35__System__DrawingTools/Na__LayoutEditor__GradientTool__.js'), VLE('35__System__DrawingTools/Na__LayoutEditor__LineStyleTool__.js')],
  hot=[],
  deps=['W1-13'],
  gated=['DR-01'],
  size='S', est=130,
  acc=['G2 exits 0; the Vectors panel\'s Dashed edges rows are unchanged (prefix defaults to "shape"); a gradient on a shape without holes prints with the same PDF clip as before; both config JSONs stay byte-identical.'],
  tests=[],
  src=['WP-S05b-V1'],
  risk='Low.')

P('W1-19', 'W1', 'Sheet record schema: SheetRecords 1.39.0 with the layer-stack restack',
  'Bring SheetRecords to TV 1.39.0 plus the 29-Sep edge fields (commit 55014c6a): every TV record field, the one-time RestackLegacyLayers, GROUP_KINDS, NoteRegions/LeaderlessNotes normalisers, image/QR/area/site-plan/rotation/fog fields - VV seams only.',
  tv=[TLE('07__Core__SheetData/Na__LayoutEditor__SheetRecords__.js')],
  vv=[SREC, DRAWCODE],
  hot=[SREC, DRAWCODE],
  deps=['W1-12', 'W1-13', 'W1-14', 'W1-16', 'W1-17'],
  gated=['DR-01', 'DR-11', 'DR-14', 'DR-08', 'DR-17'],
  size='L', est=1250, est_note='TV 1,763 vs VV 836 lines (1,229 diff)',
  adapt=['DrawingCode leaf imports kept (VV loader tab-code leaf, DR-24); DrawingNumber default through the W1-12 document-code accessor (DR-11); Na__LeRec__SheetShortCode stays exported until W1-21; ValeVision__SitePlan__ prefix constant (DR-08 (B)); ValeVision console prefix.',
         'Folder paths need no seam after W0-02.'],
  acc=['A golden fixture carrying every field in S03b b2 (rows 1-44) normalises in VV byte-identical to TV\'s SheetRecords, apart from the documented VV seams.',
       'The 4 local VV sheets (3047__Doous, 44371__Gill, 57994__Harris__Scheme-02 x2) each restack once and a second normalise is byte-identical; compared with VV\'s CURRENT normalised output the only changes are Layer__Order (restack), Sheet__LayerStack 2, Viewport__ModelSourceId null on every viewport, Asset__Samples null on every snapshot asset and Viewport__Styles.depthFog once DefaultStyles.depthFog is configured.',
       'Screen and PDF of those sheets show no visible change (VV still paints all markup over all viewports until W1-28); an R2 sample is checked before release.',
       'G1/G2 pass with VV\'s old facade and Sheets unit still in place.'],
  tests=['Na__Test__LayerStack__.test.mjs (record part)', 'Na__Test__HideSwings__.test.mjs (record part)', 'Na__Test__HatchLineControls__.test.mjs (records part)'],
  src=['WP-S03b-03R'],
  risk='High blast radius: every sheet is re-normalised. Mitigated by the golden fixture and the restack whitelist test on real data (S03b-V04).')

P('W1-20', 'W1', 'SheetModel units to TV level, with AreaGroups',
  'Take SheetModel State 1.2.0, Layers 1.4.0, Shapes 1.6.0, Viewports 1.4.0, TextAndDimensions 1.2.0, Leaders 1.2.0 and Groups 1.3.0 whole, add AreaGroups 1.0.0, and re-sync the DrawOrder and Common headers.',
  tv=[TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__State__.js'), TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Layers__.js'),
      TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Shapes__.js'), TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Viewports__.js'),
      TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__TextAndDimensions__.js'), TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Leaders__.js'),
      TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Groups__.js'), TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__AreaGroups__.js'),
      TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__DrawOrder__.js'), TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Common__.js')],
  vv=[VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__State__.js'), VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Layers__.js'),
      VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Shapes__.js'), VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Viewports__.js'),
      VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__TextAndDimensions__.js'), VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Leaders__.js'),
      VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Groups__.js'), NEW(VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__AreaGroups__.js')),
      VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__DrawOrder__.js'), VLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Common__.js')],
  hot=[],
  deps=['W1-19'],
  gated=['DR-01', 'DR-14'],
  size='L', est=1300,
  adapt=['VV console prefix; GROUP_KINDS, the Groups-unit PruneGroups and the per-kind delete prunes land together with W1-19.'],
  acc=['A group holding a leader, a dimension or a viewport survives a delete elsewhere and a reload; deleting a layer that holds a vector moves the vector to the Vectors layer (VV bug fixed by Layers 1.1.0+).',
       'Margin regions, leaderless groups, depthFog, Category__LineTypeScale and a 1:200 viewport (when configured) survive a reload; a scrapbook drop naming a missing layer lands with Shape__LayerId set to an existing layer.',
       'G1/G2 pass; Na__Test__LayerMenu__ model part passes.'],
  tests=['Na__Test__LayerMenu__.test.mjs (model part)'],
  src=[],
  split=['WP-S03b-03R'],
  risk='Sequential behind W1-19; together they are one schema change released in one wave.',
  notes=['Split from WP-S03b-03R (XL) at the records/units seam to stay within one agent sitting; both land in W1 and are released together (Adam commits per wave).'])

P('W1-21', 'W1', 'SheetModel facade 1.35.1, Sheets 1.4.0, History 1.7.0 and the late start (one change)',
  'Take the SheetModel facade, the Sheets unit and History whole together (AnnounceRestore moves to the facade, RenumberSheets reads the register block, margin patch keys and note-region functions, "margin"/"areas"/"register-updated" step reasons) and delete VV\'s Na__LeLoad__AnnounceProjectLoad in the same change.',
  tv=[TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__.js'), TLE('07__Core__SheetData/Na__LayoutEditor__SheetModel__Sheets__.js'),
      TLE('07__Core__SheetData/Na__LayoutEditor__History__.js')],
  vv=[SM, SM_SHEETS, HIST, LDR, NEW(TESTDIR + 'Na__Test__SheetsNormaliseOnce__.test.mjs')],
  hot=[SM, SM_SHEETS, HIST, LDR],
  deps=['W1-20', 'W1-13', 'W1-34'],
  gated=['DR-01', 'DR-11', 'DR-14', 'DR-40'],
  size='M', est=1050,
  adapt=['RenumberSheets is a no-op without a LayoutEditor__DrawingRegister block and reads it through Na__CfApi__GetLoadedProjectData (VV facade, S11-V02 row 111 seam resolved by W0-12).',
         'VV loader seam: the late start replaces the loader\'s replayed "loaded" announcement (delete Na__LeLoad__AnnounceProjectLoad and its call).'],
  acc=['On the first editor open of a session "loaded" is announced exactly once, the History baseline is taken and SeedCommonFields runs; a second drawings load in the same page is heard once; a restored draft keeps the model dirty with the close guard active.',
       'GetSheets does not renormalise between announcements (Na__Test__SheetsNormaliseOnce__); creating, duplicating, deleting or reordering a sheet leaves every stored Sheet__Fields__DrawingNumber untouched while no register block exists.',
       'Every existing VV margin record normalises byte-identical; each margin patch key and region function makes one "margin" announcement and one undo step; silent region updates announce nothing; a notes-margin change is one undo step; undoing a vector delete still writes nothing to R2.'],
  tests=['Na__Test__SheetsNormaliseOnce__.test.mjs', 'Na__Test__NoteRegions__.test.mjs (model part)', 'Na__Test__LeaderlessNotes__.test.mjs (model part)'],
  src=['WP-S03b-04', 'WP-S06b-05'],
  risk='Load-order regressions (double or missing "loaded") and unwanted renumbering; DraftRestore late-start checks (W1-07) cover them.',
  notes=['WP-S06b-05\'s record and model hunks are delivered by the whole-file ports W1-13/W1-19/W1-21 and the W0-15 config; its acceptance lives here.'])

P('W1-22', 'W1', 'Sheet identity: Document ID values, title blocks (Cells 1.2.0, Modern 1.5.0, QR cell) and the 1:200 scale',
  'Switch the title block row to TV\'s Document ID with VV register values, port TitleBlock Cells 1.2.0, Modern 1.5.0 (logo stand-in text in config) and the new QrCell (switched off), add 1:200, rename PDF files on the Document ID and re-sync the code-identical headers.',
  tv=[TLE('10__Core__SheetSurface/Na__LayoutEditor__TitleBlock__Cells__.js'), TLE('10__Core__SheetSurface/Na__LayoutEditor__TitleBlock__Modern__.js'),
      TLE('10__Core__SheetSurface/Na__LayoutEditor__TitleBlock__QrCell__.js'), TLE('60__Feature__PdfExport/Na__LayoutEditor__PdfFilename__.js'),
      TLE('07__Core__SheetData/Na__LayoutEditor__DrawingScale__.js'), TLE('07__Core__SheetData/Na__LayoutEditor__SheetLayout__.js'),
      TLE('10__Core__SheetSurface/Na__LayoutEditor__TitleBlock__Classic__.js'), TLE('10__Core__SheetSurface/Na__LayoutEditor__Styles__Surfaces__.css')],
  vv=[VLE('10__Core__SheetSurface/Na__LayoutEditor__TitleBlock__Cells__.js'), VLE('10__Core__SheetSurface/Na__LayoutEditor__TitleBlock__Modern__.js'),
      NEW(VLE('10__Core__SheetSurface/Na__LayoutEditor__TitleBlock__QrCell__.js')), PDFNAME, AC, CS_SS, T_TBCELLS, T_TBCHTML,
      VLE('07__Core__SheetData/Na__LayoutEditor__DrawingScale__.js'), VLE('07__Core__SheetData/Na__LayoutEditor__SheetLayout__.js'),
      VLE('10__Core__SheetSurface/Na__LayoutEditor__TitleBlock__Classic__.js'), VLE('10__Core__SheetSurface/Na__LayoutEditor__Styles__Surfaces__.css')],
  hot=[AC, CS_SS, PDFNAME, T_TBCELLS, T_TBCHTML],
  deps=['W1-21', 'W1-15', 'W1-12', 'W1-35'],
  gated=['DR-01', 'DR-11', 'DR-12', 'DR-17', 'DR-43'],
  size='M', est=1000,
  adapt=['Config: Rows DocumentId ("Document ID") flipped from the W0-15 withhold; register values per DR-11 (DocumentCodeFormat {project}_{drawing} until Adam supplies Vale phases; LetterheadLogoAspect 4.5; PDF.js path to VV vendor 07); VV-only key LayoutEditor__TitleBlock__LogoFallbackText with Vale text (DR-43, offered to TV under DR-42 (9)); 1:200 in Scales and the SheetSetup fallback list (DR-17).',
         'ProjectQr__Enabled false and LayoutEditor__TitleBlock__QrCellEnabled false (DR-12 (A)); PdfFilename uses the document code (W1-12).'],
  acc=['Na__Test__TitleBlockCells__ (VV fixture plus Widen cases) passes; with QR off the A3 strip is pixel-identical to today except "Document ID" / "Revision A" (Adam approves the visible change).',
       'On A2/A1 the fixed cells are a fifth wider and the Drawing Title is not cut; A4 portrait drops the prefix before cutting the date; with QR on (test config only) a 56 mm end cell appears, compact on A4.',
       'A never-numbered VV pack composes <code>_D01 (or <code>_T01_D01 once phases exist) and its tabs read D01 - <name>; v2.71.0 ComposeDocumentId cases pass in node; 2026/3047__Doous, 2026/44371__Gill and 2026/57994__Harris__Scheme-02 load unchanged.',
       'With 1:200 configured a 1:200 viewport survives a reload; headers read "Parity: verbatim" where the code is identical; no VV file contains noble-architecture.com.'],
  tests=['Na__Test__TitleBlockCells__.test.mjs (update)', 'Na__Test__TitleBlockCells__.html (update)'],
  src=['WP-S07a-01', 'WP-S03b-08', 'WP-S03b-10'],
  risk='Changes issued drawings\' appearance (Document ID, wider cells): Adam approves; the first renumber rewrites stored numbers - check R2 for typed numbers first (DR-11).')

P('W1-23', 'W1', 'Render signature alignment and the Describe stub (no behaviour change)',
  'Give VV\'s render entry points TV\'s positional signatures (Render2d weights/modelSourceId/stillWanted/depthFog, Render3d .../viewWindow/stillWanted, EnsureLinework .../modelSource/waited, optional modelSourceId on the fingerprint functions) and make Na__LeVp2d__Describe return a Resolve-shaped modelSource stub, never null.',
  tv=[TLE('25__System__RenderStyles/Na__LayoutEditor__SnapshotRenderer__.js') + ' (signatures)', TLE('20__System__Viewports/Na__LayoutEditor__Viewport2d__.js') + ' (Describe)'],
  vv=[SNAPR, VLE('20__System__Viewports/Na__LayoutEditor__Viewport2d__.js'), VLE('20__System__Viewports/Na__LayoutEditor__Viewport2d__Frame__.js'),
      VLE('20__System__Viewports/Na__LayoutEditor__Viewport2d__Linework__.js'), VLE('20__System__Viewports/Na__LayoutEditor__Viewport2d__Window__.js'),
      VLE('20__System__Viewports/Na__LayoutEditor__Viewport3d__.js'), PDFX],
  hot=[SNAPR, PDFX, VLE('20__System__Viewports/Na__LayoutEditor__Viewport2d__.js'), VLE('20__System__Viewports/Na__LayoutEditor__Viewport2d__Frame__.js'),
       VLE('20__System__Viewports/Na__LayoutEditor__Viewport2d__Linework__.js'), VLE('20__System__Viewports/Na__LayoutEditor__Viewport3d__.js')],
  deps=['W1-14'],
  gated=['DR-01', 'DR-09'],
  size='S', est=220,
  adapt=['Stub { groupId: null, label: \'\', storedId: null, explicit: false, missing: false, isLive: true, renderId: null, status: \'live\' } (S04a verifier).',
         'Only the VV callers change: Viewport2d, Frame, Linework, Viewport3d and PdfExporter :213; no whole-file take.'],
  acc=['G1/G2 pass; a 3D viewport zoomed to 150% still renders only its window (stillWanted and viewWindow not swapped); render keys of every viewport on 3047__Doous byte-identical before and after; described.modelSource.renderId reads null (no TypeError) for every 2D viewport.'],
  tests=[],
  src=['WP-S04a-01R'],
  risk='SnapshotRenderer and the viewport units are hot for W2-15 and W3-01: keep it small and land it first.')

P('W1-24', 'W1', 'PdfExporter interim parity: FAST picture packing, strict mode and the LoadLibrary split',
  'Port TV 1.11.0\'s Na__LePdf__AddPicture (FAST unless options.pictureCompression), the options {strict, pictureCompression} through BuildDocument / DrawViewport / ExportSheet, the LoadLibrary/EnsureJsPdf split with its export and the awaited save, keeping VV\'s paint path until W1-28/W3-17.',
  tv=[TLE('60__Feature__PdfExport/Na__LayoutEditor__PdfExporter__.js') + ' (1.11.0 hunks)'],
  vv=[PDFX],
  hot=[PDFX],
  deps=['W1-23'],
  gated=['DR-01'],
  size='S', est=200,
  acc=['A sheet with a plan underlay over 60 MB decoded opens in Chrome\'s PDF viewer with no black blocks or streaks; viewport picture streams use the Sub predictor.',
       'options.strict throws on a missing drawing source or 3D render; the default path still exports; G2 shows EnsureJsPdf, LoadLibrary, BuildDocument, ExportSheet.'],
  tests=[],
  src=['WP-S08-02'],
  risk='Low: larger PDFs (TV PS01 D01 744 KB -> 972 KB), same pixels.')

P('W1-25', 'W1', 'Embedded PDF fonts (PdfFonts) and Open Sans Medium',
  'Port PdfFonts, point FontCdnBase and Fonts[].FileName at the Open Sans TTFs VV\'s @font-face already loads, switch LayoutEditor__Style__FontFamily to Open Sans first, add the Medium (500) face, and wire SpecPdf and the exporter (EnsureLoaded, Install, putOnlyUsedFonts).',
  tv=[TLE('60__Feature__PdfExport/Na__LayoutEditor__PdfFonts__.js'), 'TV/03__Style__AppStylesheets/Na__CoreUi__Styles__Fonts__.css'],
  vv=[NEW(VLE('60__Feature__PdfExport/Na__LayoutEditor__PdfFonts__.js')), AC, FONTSCSS, SPECPDF, PDFX],
  hot=[AC, FONTSCSS, SPECPDF, PDFX],
  deps=['W1-24', 'W1-22'],
  gated=['DR-01', 'DR-21'],
  size='M', est=500,
  adapt=['DR-21 default: no new hosting - the AD04 TTFs already used by VV\'s @font-face (www.noble-architecture.com/assets is VV\'s own, allow-listed); move CSS and PDF together to a Vale-owned copy when Adam names it (TV two-source pattern).',
         'SheetChrome\'s measuring document and ApplyPdfFont arrive with SheetChrome 1.14.0 in W1-26 (single owner).'],
  acc=['A sheet PDF and the specification PDF each declare OpenSans as an embedded Type0 Identity-H subset (PyMuPDF or pdf.js); text still extracts as Unicode.',
       'document.fonts.check(\'500 1em "Open Sans"\') is true after load; a toast and a dropdown heading render in Medium; fonts load from the configured host first.'],
  tests=['Na__Test__SpecificationPdf__.html (re-run)'],
  src=['WP-S08-03', 'WP-S10-09'],
  risk='Changes the printed face of every Vale drawing (Adam\'s sign-off, DR-21); title-block re-measure follows in W1-26.')

P('W1-26', 'W1', 'Chrome primitives and markup geometry: SheetChrome 1.14.0, ShapeGeometry 1.9.0, DimensionGeometry 1.6.0, LeaderGeometry 1.3.0',
  'Take the four sheet-chrome and markup-geometry hubs whole now that every leaf they import exists (rings, hatch, PdfFonts, QR and picture painters, rotation, gradient holes), and re-measure the title block and captions in Open Sans in the same change.',
  tv=[TLE('10__Core__SheetSurface/Na__LayoutEditor__SheetChrome__.js'), TLE('15__Core__Markup/Na__LayoutEditor__ShapeGeometry__.js'),
      TLE('15__Core__Markup/Na__LayoutEditor__DimensionGeometry__.js'), TLE('15__Core__Markup/Na__LayoutEditor__LeaderGeometry__.js')],
  vv=[CHROME, VLE('15__Core__Markup/Na__LayoutEditor__ShapeGeometry__.js'), VLE('15__Core__Markup/Na__LayoutEditor__DimensionGeometry__.js'),
      VLE('15__Core__Markup/Na__LayoutEditor__LeaderGeometry__.js'), T_TBCELLS, NEW(TESTDIR + 'Na__Test__TitleBlockScaleCell__.html')],
  hot=[CHROME, T_TBCELLS],
  deps=['W1-25', 'W1-13', 'W1-14', 'W1-15', 'W1-16', 'W1-17', 'W1-18', 'W1-20'],
  gated=['DR-01', 'DR-12', 'DR-21'],
  size='M', est=1000, est_note='433 + 281 + 131 + 153 diff lines + fixture',
  adapt=['Verbatim; ShapeGeometry 1.9.0 whole is now safe because 53 Symbol/ProjectLink (VV, W1-15) and 54 Paint (W1-16) exist (the S04b verifier\'s hunk-only warning applied before those leaves existed).'],
  acc=['The PDF of each local VV sheet is identical apart from embedded Open Sans and the re-measured fits, which Adam approves; Na__Test__TitleBlockCells__ passes with Open Sans numbers on A4 to A1; screen caption truncation and PDF glyph widths agree.',
       'Viewport__ShowFrame false hides frame and caption on screen and in the PDF; a holed fixture vector shows its hole on screen and in the PDF (even-odd).',
       'A QR primitive paints when 53 is enabled in a test config; no QR in production config; a bubble whose note is deleted shows a red halo on screen only, never in a PDF (once W2-29 registers the resolver).',
       'G1 links ShapeGeometry through 53 Symbol and VV\'s ProjectLink.'],
  tests=['Na__Test__TitleBlockScaleCell__.html', 'Na__Test__TitleBlockCells__.test.mjs (Open Sans re-measure)'],
  src=['WP-S03b-06R'],
  split=['WP-S06b-04'],
  risk='On-screen and PDF text measurement moves from Helvetica to Open Sans.')

P('W1-27', 'W1', 'Floor Areas core modules (inert, ahead of the hub and MarkupBridge)',
  'Port Floor Areas Geometry, FloorAreas__, Tool, Menu, Paint and the config verbatim with no registration, toolbar, key or panel, so MarkupBridge 1.20.0, Measurements 1.10.0 and the SheetTools hub can import them.',
  tv=[TLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Geometry__.js'), TLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__.js'),
      TLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Tool__.js'), TLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Menu__.js'),
      TLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Paint__.js'), TLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Config__.json')],
  vv=[NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Geometry__.js')), NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__.js')),
      NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Tool__.js')), NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Menu__.js')),
      NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Paint__.js')), NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Config__.json')),
      NEW(TESTDIR + 'Na__Test__FloorAreas__.test.mjs')],
  hot=[],
  deps=['W1-26', 'W1-20', 'W1-14'],
  gated=['DR-01', 'DR-14'],
  size='M', est=2400,
  adapt=['Verbatim (VALEVISION3D header, PORT NOTE, [ValeVision3D LayoutEditor] prefix); the A key stays disabled until W3-10 (S06b verifier).'],
  acc=['Na__Test__FloorAreas__ passes on VV\'s copy of Geometry and the config; G1/G2 pass with the modules present and unregistered.',
       'Every imported name resolves: SheetModel LayerIndexAboveDrawings, AnnounceAreas, GetAreaGroups, AddAreaGroup, AreaGroupKey; Na__LeVpRot__Contains; DrawingScale SheetDenominator/Label; VV ShapeTool/RectangleTool exports (checked 01-Oct-2026).',
       'git diff --no-index -w against TV: header, PORT NOTE and console-prefix lines only.'],
  tests=['Na__Test__FloorAreas__.test.mjs'],
  src=['WP-S06b-10a'],
  risk='FloorAreas__Paint imports SheetChrome 1.14.0, so it waits for W1-26.')

P('W1-28', 'W1', 'Paint order: the Layers list is the stack (SheetSurface 1.13.0, MarkupBridge 1.20.0, Groups 1.4.0, Paper CSS regions, PDF paint plan, vector quality)',
  'In one change switch screen and PDF to TV\'s paint order: MarkupBridge 1.20.0, markup Groups 1.4.0 and SheetSurface 1.13.0 whole (zoom settle, translate placement, published view, vector-quality hold), the Paper CSS stack/zoom/fog/frame/per-slot-fade/vector-hold regions, and PdfExporter painting by Na__LePaint__Plan with BuildLayerPrimitives and BuildViewportFrame.',
  tv=[TLE('15__Core__Markup/Na__LayoutEditor__MarkupBridge__.js'), TLE('15__Core__Markup/Na__LayoutEditor__Groups__.js'),
      TLE('10__Core__SheetSurface/Na__LayoutEditor__SheetSurface__.js'), TLE('10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__Paper__.css') + ' (regions)',
      TLE('60__Feature__PdfExport/Na__LayoutEditor__PdfExporter__.js') + ' (paint-plan hunks)'],
  vv=[MB, VLE('15__Core__Markup/Na__LayoutEditor__Groups__.js'), SURF, PAPER, PDFX, NEW(TESTDIR + 'Na__Test__LayerStack__.test.mjs'),
      NEW(TESTDIR + 'Na__Test__VectorQuality__.test.mjs')],
  hot=[MB, SURF, PAPER, PDFX],
  deps=['W1-26', 'W1-27', 'W1-13', 'W1-14', 'W1-21', 'W1-25'],
  gated=['DR-01', 'DR-40'],
  size='L', est=1500,
  adapt=['Paper CSS: take TV\'s regions only (S03b-11 rule); VV\'s old .na-le-osnap* snap-marker block and VV\'s current grip rules stay until W2-18/W2-24 replace them.',
         'Vector quality defaults to Medium (DR-40 item 6 adopted, named in the Port Record).'],
  acc=['Every local VV sheet looks identical on screen and in the PDF before and after (pixel diff at Fit); a markup layer dragged under the Viewports layer draws under the drawing on screen and in the PDF.',
       'Clicks find the top-most item; a reference layer passes clicks through; an open group keeps its viewports at full strength; an AtScale dimension prints the figure the Measurements box reads.',
       'A wheel zoom adds na-le-paper--zooming and settles once (ZOOM_SETTLED_EVENT); Medium vector quality holds while redraws keep coming and lets go 1,200 ms after the last; High never holds; Low holds from Ready; at rest Medium vs High: no pixel differs.',
       'Na__Test__LayerStack__ (paint plan) and Na__Test__VectorQuality__ pass; G1/G2 pass.'],
  tests=['Na__Test__LayerStack__.test.mjs', 'Na__Test__VectorQuality__.test.mjs'],
  src=['WP-S03b-07R', 'WP-S04a-04'],
  risk='Highest visual risk: if W1-19\'s restack has not run every note is buried under the drawings; screen and PDF must switch together.')

P('W1-29', 'W1', 'Key scope and the 3D hotkey guard',
  'Port 03__AppUtils/Na__AppUtils__KeyScope__.js 1.1.0 verbatim and gate VV\'s 3D hotkey handler through it (MODEL scope first, IsTypingTarget, skip bindings with no registered callback before preventDefault), so 3D keys stop firing under drawing and document tabs.',
  tv=[TVM('03__AppUtils/Na__AppUtils__KeyScope__.js'), TVM('10__NavigationAndCameras/Na__Hotkeys__Manager.js') + ' (reference for the gate)'],
  vv=[NEW(VVM('03__AppUtils/Na__AppUtils__KeyScope__.js')), HKHANDLER],
  hot=[HKHANDLER],
  deps=['W0-99'],
  gated=['DR-01', 'DR-33'],
  size='S', est=330,
  adapt=['VV keeps its own 3D handler, dictionary root key and ValeVision__ actions (DR-33); the KeyScope header names VV\'s handler and key files.'],
  acc=['On the 3D Model tab R still resets the view and T still enters Walk where enabled; a contenteditable keeps its letters; D, O and Escape on the 3D tab no longer log "No callback for action"; before the editor loads the scope reads as model.',
       'With a drawing open (after W1-32 wires Follow) T/R/V/B/Y/1-9/PageUp/PageDown leave the hidden camera, Walk and the carousel untouched.'],
  tests=['Na__Test__DocumentKeys__.test.mjs (scope and 3D-hotkey sections, adapted to VV\'s handler; full suite in W1-32)'],
  src=['WP-S03a-V03'],
  risk='Low: KeyScope has no imports; the guard only removes actions on non-3D tabs.')

P('W1-30', 'W1', 'Document keyboard (31__System__DocumentKeys)',
  'Port LE/31__System__DocumentKeys (the document tabs\' own keyboard and Na__Hotkeys__DocumentTabs__.json) inert until the Specification registers its actions; the ModeController Ready/Initialize lines land in W1-32.',
  tv=[TLE('31__System__DocumentKeys/Na__LayoutEditor__DocumentKeys__.js'), TLE('31__System__DocumentKeys/Na__Hotkeys__DocumentTabs__.json')],
  vv=[NEW(VLE('31__System__DocumentKeys/Na__LayoutEditor__DocumentKeys__.js')), NEW(VLE('31__System__DocumentKeys/Na__Hotkeys__DocumentTabs__.json'))],
  hot=[],
  deps=['W1-29'],
  gated=['DR-01', 'DR-33'],
  size='S', est=460,
  acc=['G2 passes; once W1-32 lands: on the Specification tab bare letters type and Ctrl+S reaches the editor save; a held key acts once; Command counts as Ctrl on a Mac.'],
  tests=[],
  src=['WP-S03a-09'],
  risk='Low (inert until wired).')

P('W1-31', 'W1', 'Loader facade 1.2: TV\'s editor entry points, view names and the registration pattern',
  'Extend VV\'s lazy-loader facade (kept per DR-24) with TV\'s entry points - VIEW_REGISTER / VIEW_STATEMENT copies, OpenRegister / OpenStatements (refusing cleanly until those features land), IsSitePlanSheet (pre-load reads Sheet__DrawingType), Ready and a feature-presence answer - with CheckNames rows, and document the registration pattern in the loader header.',
  tv=[TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (names the facade mirrors)'],
  vv=[LDR, LDRSCR, NEW(TESTDIR + 'Na__Test__LoaderFacade__.test.mjs')],
  hot=[LDR, LDRSCR],
  deps=['W0-99'],
  gated=['DR-24', 'DR-25', 'DR-38'],
  size='M', est=450,
  adapt=['Only literal import() from the loader (a static import would put the editor back on start-up); Layout Mode visibility through Na__LeLoad__IsAvailable (DR-25 (a)); loading-screen wording aligned with the LE config veil labels (finalised by W1-33).'],
  acc=['Every loader copy of an event or view name equals the editor\'s real constant (CheckNames is silent); the facade answers identically before and after the first editor load.',
       'A project without sheets still loads no editor module at start-up (network panel); Na__Test__LoaderFacade__ passes.'],
  tests=['Na__Test__LoaderFacade__.test.mjs (VV-only, new)'],
  src=['WP-S03a-05', 'WP-S09-03'],
  risk='Medium: the facade must answer identically before and after the load.',
  notes=['WP-S03a-05\'s first-open wait contract (WaitForFirstDrawing via TV\'s FirstOpen jobs) is delivered by W1-33 with the veil.'])

P('W1-32', 'W1', 'ModeController core realignment (feature-independent TV hunks)',
  'Port TV\'s feature-independent ModeController hunks: EnterUnder with the Quiet flag, VIEW_REGISTER/VIEW_STATEMENT, OpenRegister/OpenStatements refusing while absent, PreloadMetrics returning its promise, the Leave ordering, SectionForKind/FocusPanelFor/FocusPanelForSelection with the viewport FOLD_GROUP rule and FocusSection, the KeyScope reader and Follow, DocumentKeys Ready/Initialize, SuspendThreeD({ returnToOrbit: true }), and the column-tab hover hints.',
  tv=[TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (feature-independent hunks)', TLE('55__Feature__Scrapbook/Na__LayoutEditor__Panel__Scrapbook__.js')],
  vv=[MC, AC, VLE('55__Feature__Scrapbook/Na__LayoutEditor__Panel__Scrapbook__.js')],
  hot=[MC, AC],
  deps=['W1-04', 'W1-29', 'W1-30', 'W1-31'],
  gated=['DR-01', 'DR-24', 'DR-25'],
  size='M', est=500,
  adapt=['Keep the VV seams: console prefix, Layout Mode IsAvailable, WaitForFirstDrawing, the scene-broadcast listeners (VV 1.15.1 Add Viewport refresh), the loader INTEGRATION header, the Snapping path until W2-18, VV-only exports (Na__LeMode__IsLayoutModeOn etc., DR-25).',
         'AppConfig: LayoutEditor__Panels__FocusNote reworded to TV\'s viewport sentence without the Floor Areas, Patterns and site-plan clauses (those clauses arrive with their features).',
         'Panel__Scrapbook 1.2.1 (the Scrapbook tab hint).'],
  acc=['Selecting a viewport folds Text, Dimensions, Vectors and Leaders; selecting text opens Text alone; clearing the selection leaves the folds alone; hovering the Properties and Scrapbook tabs shows their hover text.',
       'Non-regression: opening a drawing, a plan or an elevation while walking leaves Walk and the toolbar reads Orbit; after W1-04 re-stamping or baking a viewport picture from the 3D tab while walking does not leave Walk.',
       'The Viewport panel\'s scene-broadcast refresh is still present; git diff --no-index -w against TV shows only the listed VV seams plus the hunks of features not yet ported; Na__Test__DocumentKeys__ passes.'],
  tests=['Na__Test__DocumentKeys__.test.mjs'],
  src=['WP-S03a-V04', 'WP-S06a-04v'],
  split=['WP-S10-06'],
  risk='The ModeController is the most contended file of the port: W1 order W1-32 -> W1-33 -> W1-34 -> W1-36.')

P('W1-33', 'W1', 'First-open veil and the header fold exactly as TV (Adam\'s "top nav bar animation")',
  'Make VV\'s first drawing open look like TV\'s: the 3D furniture hides at the click, the header holds then glides with the strip welded to it over an opaque cover below the strip (TV wording "Your Drawings Are Loading"), handing over to TV\'s in-host LoadingVeil 1.1.0 with no blink; plus TV\'s two-mode veil CSS region.',
  tv=[TLE('05__Core__ModeController/Na__LayoutEditor__LoadingVeil__.js'), TLE('10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__.css') + ' (furniture block reference)',
      'TV/03__Style__AppStylesheets/Na__UiFeature__Styles__LoadingOverlays__.css (Layout Editor Loading Veils region 256-339)'],
  vv=[VEIL, LDR, LDRSCR, BOOTCSS, MAINCSS, OVERLAYCSS, MC],
  hot=[VEIL, LDR, LDRSCR, BOOTCSS, MAINCSS, OVERLAYCSS, MC],
  deps=['W1-32', 'W1-31'],
  gated=['DR-01', 'DR-39', 'DR-24'],
  size='M', est=700,
  adapt=['Move the 3D-furniture hiding block (VV LE/10 Styles__Main__.css 30-50) verbatim into LE/01 Styles__Boot__.css (DR-39; else menus show over the boot veil, S10-V01).',
         'LoadingVeil 1.1.0 whole, keeping VV\'s DrawingSettled export and adding an "immediate" option to FirstOpen; the loader\'s screen restyled as .na-le-veil.na-le-veil--boot (fixed; top calc(var(--Vale_HeaderHeight) + var(--Vale_LayoutTabStripHeight)); opaque #ffffff; z 600) with body.na-layout-editor--active .na-le-veil--boot { top: var(--Vale_LayoutTabStripHeight) }; VV\'s two pre-load lines first, then TV\'s job lines; VV-only error state kept.',
         'Loader: add na-layout-editor--active before the import for a non-quiet press that will enter; remove it on load failure, editor off in config, Na__LeMode__Enter false and Back to 3D Model; WaitForFirstDrawing resolves at once off the sheet view (the WP-S03a-05 wait contract).',
         'LoadingOverlays: replace VV region "Layout Editor Return-to-Model Veil" (269-344) with TV\'s "Layout Editor Loading Veils" region verbatim (in-host base + --over-model); keep VV-only Load Error State, --opaque and __status--error regions; --Vale_HeaderFold* tokens are already identical (K2 S1).',
         'Header lines from WP-S10-08R for ModeController/Loader/LoadingVeil are written here.'],
  acc=['Cold first press of a drawing tab: the Tools & Settings menu, nav toolbar, help panel and carousel vanish AT THE CLICK; strip and header stay visible; the header holds 1 s then glides 1 s with the strip welded to it over an opaque white cover below the strip with the spinner and "Your Drawings Are Loading"; no 3D model visible through it.',
       'The cover hands over to the in-host veil with no blink and lifts only when every viewport img is decoded; editor already loaded: the in-host veil after 550 ms only if still drawing; leaving still shows "Loading Your 3D Model" over the canvas under the strip and header.',
       'Forced load failure: full-screen error state; Back to 3D Model returns with the header down and no body class; Layout Mode switched off during the load leaves no body class.',
       'Na__Verify__UiParity__ checks (1) AppHeader fold region and (3) LoadingOverlays veil region pass; G1/G2 pass.'],
  tests=[],
  src=['WP-S10-01', 'WP-S10-03R'],
  split=['WP-S03a-05', 'WP-S10-08R'],
  risk='Medium: two covers in sequence; every failure path must drop the early body class.')

P('W1-34', 'W1', 'Tab strip 2.0.0 with the Drawings menu, through the loader',
  'Port TV TabStrip 2.0.0 whole with VV seams: facade-only imports, visibility from Na__LeLoad__IsAvailable, immediate render re-rendered on Na__LeLoad__STATE_EVENT, document tabs gated on feature presence, CloseMenu exported, TV\'s tab-strip CSS region and menu rules in Styles__Boot, TV tab labels, and VV\'s drag-to-reorder kept on the Drawings menu rows until the Register lands.',
  tv=[TLE('05__Core__ModeController/Na__LayoutEditor__TabStrip__.js'), TLE('10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__.css') + ' (tab-strip and menu regions)'],
  vv=[TABS, BOOTCSS, LDR, MC, AC, SPECCSS, DEVMENU],
  hot=[TABS, BOOTCSS, LDR, MC, AC, SPECCSS, DEVMENU],
  deps=['W1-33'],
  gated=['DR-01', 'DR-38', 'DR-25', 'DR-24'],
  size='L', est=900,
  adapt=['D-S10-12 / DR-38: keep VV\'s drag-to-reorder on the Drawings menu rows (localhost, editable) as a recorded divergence until W4-10 lands the Register.',
         '"+ New sheet" awaits Na__LeLoad__CreateSheet (a promise in VV) before Na__LeLoad__Enter; TV\'s Na__LeMode__Ready().then(Render) dropped (VV renders at once).',
         'ModeController: OpenSpecification through EnterUnder; a cold document-tab press gets the loader\'s early body class but no drawing wait.',
         'AppConfig: TV tab labels and rewordings (SpecificationTab, TabsPreviousTitle, TabsNextTitle, NoSheets) with code fallbacks equal to TV\'s config; Boot gains TV\'s 10 menu rules and loses the 6 rename/add rules; the dead --spec rule dropped; Dev menu NoSheets fallback follows; TabStrip/Toolbar PORT NOTE lines of WP-S10-08R.'],
  acc=['From the 3D view the strip reads 3D Model | Drawings (caret) | Specification (+ Document Register | Design Statements when present), all tabs at the same weight; the menu hangs under the strip during and after the header fold.',
       'Drawings opens a menu: every sheet as "D0n - Name" in order, the open sheet bold and focused, "+ New sheet" only when editable; Escape shuts it and refocuses the tab; Up/Down/Home/End walk rows; an outside press or any document change shuts it; a sheet can still be reordered.',
       'Specification pressed from the 3D view folds the bar and shows the page with no drawing veil (cold and warm); at 375 px the end arrows appear and next from 3D Model opens a drawing without the menu; tab labels do not change when the editor finishes loading; with no sheets or Layout Mode off the strip hides.',
       'Na__Verify__UiParity__ check (2) (Boot tab-strip region equals TV\'s) passes; a cold load fetches no editor module before a tab is pressed; G1/G2 pass.'],
  tests=[],
  src=['WP-S03a-06', 'WP-S10-04R'],
  risk='Medium-high: a static import of an editor module in the strip would put the whole editor back on start-up.')

P('W1-35', 'W1', 'Toolbar subtractive phase (TV 1.17.0/1.19.0)',
  'Remove Notes, Undo, Redo, Fit and 100% from VV\'s toolbar with their imports, listeners and margin sync, delete the MarginToggle labels and reword the MarginNotes description; keys and right-click entries stay; VV\'s Select/Move tooltips stay until auto-Move is confirmed.',
  tv=[TLE('40__Ui__Panels/Na__LayoutEditor__Toolbar__.js') + ' (1.17.0, 1.19.0)'],
  vv=[TOOLBAR, AC],
  hot=[TOOLBAR, AC],
  deps=['W1-34'],
  gated=['DR-01', 'DR-40'],
  size='S', est=150,
  acc=['The editable strip reads: name | Select ... Eyedropper | Snap | hints | Raster | Save Sheets, Download PDF; the read-only strip: name | Raster | read-only note | Download PDF; no doubled separator.',
       'Ctrl+Z, Ctrl+Y and Ctrl+Shift+Z still undo and redo; right-click on bare paper offers Zoom to fit (editable and read-only); Nav__ZoomFit and Nav__ZoomActualSize keys work; "Show notes margin" in the Margin Notes panel still switches the margin; grep of VVM for MarginToggle finds nothing.'],
  tests=[],
  src=['WP-S06a-03v', 'WP-S10-02'],
  risk='Low: removals only (DR-40 item 3 adopted, named in the Port Record).')

P('W1-36', 'W1', 'Navigation 1.3.0 and Controls 1.4.0/1.1.0 with the ModeController keyboard hunks',
  'Take Navigation 1.3.0, Controls__Pc 1.4.0 and Controls__TouchScreen 1.1.0 whole (zoom gesture, authoring zoom, Page Up/Down, keyboard focus) and wire the ModeController\'s RestartSheetKeys, StepSheet with its STEP_SHEET_EVENT listener and TakeKeyboard on drawing open.',
  tv=[TLE('10__Core__SheetSurface/Na__LayoutEditor__Navigation__.js'), TLE('10__Core__SheetSurface/Na__LayoutEditor__Controls__Pc__.js'),
      TLE('10__Core__SheetSurface/Na__LayoutEditor__Controls__TouchScreen__.js'), TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (keyboard hunks)'],
  vv=[NAV, CTL_PC, CTL_TOUCH, MC, NEW(TESTDIR + 'Na__Test__AuthoringZoomMax__.test.mjs'), NEW(TESTDIR + 'Na__Test__SheetPagingWalkExit__.test.mjs'),
      NEW(TESTDIR + 'Na__Test__DrawingTabKeys__.test.mjs')],
  hot=[NAV, CTL_PC, CTL_TOUCH, MC],
  deps=['W1-28', 'W1-29', 'W1-34'],
  gated=['DR-01', 'DR-33'],
  size='M', est=450,
  adapt=['Na__Test__SheetPagingWalkExit__ reads 40__System__DrawingViewCore (no seam after W0-02).'],
  acc=['Na__Test__AuthoringZoomMax__, Na__Test__SheetPagingWalkExit__ and Na__Test__DrawingTabKeys__ (588 presses at TV HEAD) pass on VV.',
       'Page Down turns to the next drawing and stops at the last without scrolling the stage; returning from the specification restarts the sheet keyboard (a held key or half-typed value is dropped, the stage has focus).',
       'After ticking a panel checkbox, a click on the paper then M picks Move; a touchpad produces one zoom per frame; authoring zoom reaches 6400% and the web viewer stops at 800%.',
       'With a drawing open R, B, T, Y, V, 1-9, PageUp and PageDown change nothing in the 3D view; on the 3D tab they work as today.'],
  tests=['Na__Test__AuthoringZoomMax__.test.mjs', 'Na__Test__SheetPagingWalkExit__.test.mjs', 'Na__Test__DrawingTabKeys__.test.mjs'],
  src=['WP-S03b-09R'],
  risk='Keyboard scoping touches every key: test the 3D tab, a drawing tab and the specification.')

P('W1-37', 'W1', 'Colour palette (54__Feature__ColourPalette)',
  'Create VVM/54__Feature__ColourPalette with TV\'s six files (palette name per DR-20, VV console prefix, README wording), attach it to the plan-annotation toolbar swatch, and @import its stylesheet in the app CSS index at TV\'s position; PanelHost\'s attach line arrives with W1-38.',
  tv=[TVM('54__Feature__ColourPalette/Na__ColourPalette__.js'), TVM('54__Feature__ColourPalette/Na__ColourPalette__Manager__.js'),
      TVM('54__Feature__ColourPalette/Na__ColourPalette__Picker__.js'), TVM('54__Feature__ColourPalette/Na__ColourPalette__Config__.json'),
      TVM('54__Feature__ColourPalette/Na__ColourPalette__Styles__.css'), TVM('54__Feature__ColourPalette/README__ColourPalette__.md')],
  vv=[NEW(VVM('54__Feature__ColourPalette/Na__ColourPalette__.js')), NEW(VVM('54__Feature__ColourPalette/Na__ColourPalette__Manager__.js')),
      NEW(VVM('54__Feature__ColourPalette/Na__ColourPalette__Picker__.js')), NEW(VVM('54__Feature__ColourPalette/Na__ColourPalette__Config__.json')),
      NEW(VVM('54__Feature__ColourPalette/Na__ColourPalette__Styles__.css')), NEW(VVM('54__Feature__ColourPalette/README__ColourPalette__.md')),
      PATOOLBAR, CSSIDX],
  hot=[PATOOLBAR, CSSIDX],
  deps=['W1-06'],
  gated=['DR-01', 'DR-20'],
  size='M', est=1700,
  adapt=['Identical groups with the Vale palette name now (DR-20 (2)); a Vale group later is an additive config edit.'],
  acc=['The 3D tab dimension colour opens the palette; a pick fires input then change and lets go of focus; a disabled field gets the browser menu only (panel colour fields verified in W1-38).'],
  tests=[],
  src=['WP-S06b-08'],
  risk='Low; the browser\'s own mixer cannot be seen headless - Adam checks the stacking.')

P('W1-38', 'W1', 'PanelHost 1.6.0 and the panel stylesheet (TV Styles__Panels verbatim)',
  'Take TV PanelHost__.js 1.6.0 whole (LinkedPairRow, ShowLink, tab hint, slider number box, palette attach) and TV Styles__Panels__.css whole (Linked Pair, rangebox, range-suffix, toggle-group wrap and --tight, inline-check, ref and red rules).',
  tv=[TLE('40__Ui__Panels/Na__LayoutEditor__PanelHost__.js'), TLE('40__Ui__Panels/Na__LayoutEditor__Styles__Panels__.css')],
  vv=[PANELHOST, PANELCSS, NEW(TESTDIR + 'Na__Test__ColourPalette__.test.mjs')],
  hot=[PANELHOST, PANELCSS],
  deps=['W1-37'],
  gated=['DR-01', 'DR-17'],
  size='M', est=420,
  acc=['Every opacity slider row has a number box (typing 40 + Enter sets 40 and moves the slider); column tabs show hover text; G2 finds Na__LePanels__LinkedPairRow and Na__LePanels__ShowLink.',
       'All 8 VV panel colour fields open the palette; Na__Test__ColourPalette__ (adapted) passes (SSOT greys, Dimensions hexes, placement, zoom, wiring rule, CSS index import).',
       'Scale buttons wrap in a narrow right column instead of clipping; the Scrapbook and Column Tabs CSS regions are unchanged; Na__Verify__UiParity__ check (4) (Styles__Panels) passes.'],
  tests=['Na__Test__ColourPalette__.test.mjs'],
  src=['WP-S06a-02', 'WP-S10-06'],
  risk='PanelHost is imported by every panel: no other W1 package edits LE/40 panels.')

P('W1-99', 'W1', 'Parity Scribe pass for Wave 1',
  'S11 B10 procedure for W1, including the S03a and S03b ledger corrections (stale VV per-file logs: ScaleManager, SheetChrome, LeaderGeometry, History; "no PWA worker" rows; QR folder name; loader contradiction; plan D22 and line-242 comment).',
  vv=[DEVLOG, LEDGER, VVPLAN],
  hot=[DEVLOG, LEDGER, VVPLAN],
  deps=[],
  gated=['DR-35', 'DR-34'],
  size='S', est=500,
  acc=['Every W1 Port Record has a devlog entry naming its TV releases and flagging those Adam has not confirmed (DR-01); Module Register and Release Watermark rows flipped; zero {{VVREL tokens; SHARED SERVICE WORKER decision recorded; harness counts from a fresh run.',
       'Rows from WP-S03a-10 (VV half) and WP-S03b-12 corrected; TV-side notes from those packages queued for WT-08.'],
  src=['WP-S03a-10', 'WP-S03b-12'],
  risk='Single writer of the two documents.')
