from k3_common import *

# =============================================================================
# W0 - FOUNDATIONS: decisions recorded, renumber, names, gates, ledger, sync
# fix, shared service worker, transport scaffolding (Flask, worker, facade),
# LE config foundation, vendor copies, start-up order.
# =============================================================================

P('W0-01', 'W0', 'Decision record and swarm rules published',
  'Record Adam\'s answers (or the K1 defaults) to DR-01..DR-44 as new VV D-numbers in the VV port plan, settle the cross-slice values every later package reads (document id rule, sheet-image folder, share-link token, PDF face), confirm the VV devlog version step, and publish the swarm rules and the shared-service-worker note format.',
  tv=[],
  vv=[VVPLAN],
  hot=[VVPLAN],
  deps=[],
  gated=['DR-01', 'DR-02', 'DR-03', 'DR-04', 'DR-05', 'DR-06', 'DR-07', 'DR-35'],
  size='S', est=200, est_note='documentation only',
  adapt=['VV D-numbers continue VV plan D01-D40 (DR-35); each records the DR id, the option chosen, the date and the constant or config key it sets.'],
  acc=[
      'VV/ValeVision__PLAN__TrueVisionPort__LayoutEditor__.md has a dated Decisions block with one VV D-number per K1 DR (DR-01..DR-44), each naming the option chosen (or "default, unanswered") and the key or constant it sets.',
      'The four cross-slice values of WP-S08-15 are recorded with the constant each sets: Sheet__FontFamily and the PdfFonts source (DR-21); the GetDocumentId rule {project}_{phase}_{drawing} or {project}_{drawing} (DR-11); Link__QueryPattern and the share-link project token (DR-23); Na__LePubSheet__IMAGES_DIR = 05__Layout__DrawingDocs__Images (DR-29).',
      'The VV devlog version step is confirmed: Adam\'s own memory note asks for patch bumps in ValeVision__DEVLOG__.md, while K1 DR-34 and S11 B10 assume minor releases from v2.72.0; the Parity Scribe follows the recorded answer.',
      'The swarm rules R1-R11 and the standard gates G1-G7 (wp_canonical.json) are copied into the plan, with the SHARED SERVICE WORKER note format of WP-S04b-16 (never "n/a"; token "Adam\'s call").',
      'Adam\'s DR-40 answer for gesture items 7-10 is recorded; if unanswered, W3-04 lands them held (W3-05 switches them on later).',
  ],
  tests=[],
  src=['WP-S08-15', 'WP-S04b-16'],
  risk='Low effort, high leverage: without it agents pick different answers for the same seam (S08-V05).',
  notes=['Wave 0 itself depends only on DR-02, DR-03, DR-04, DR-05, DR-06 and DR-07 (K1 urgency "before Wave 0"); DR-01 gates W1 onward.'])

P('W0-02', 'W0', 'Drawing-folder renumber to TV numbers (atomic, scripted, alone)',
  'Run K2\'s scripted W1 change: legacy 40__System__2dElevationsView -> 91, VV 42..47 -> TV 40, 42..46, 2dProfileLines -> 05__RenderPipeline, ComposerPreset -> RenderPreset (DIV-1 body kept), SnapshotHistory -> TV file name, DistanceCulling -> 05__RenderPipeline; every specifier, CSS @import, config path string and false PORT NOTE line rewritten in one commit.',
  tv=[TVM('40__System__DrawingViewCore/Na__DrawView__RenderPreset__.js')],
  vv=['VVM/40__System__2dElevationsView/ -> VVM/91__System__2dElevationsView/',
      'VVM/42__System__DrawingViewCore/ -> VVM/40__System__DrawingViewCore/',
      'VVM/43__System__FloorPlanViews/ -> VVM/42__System__FloorPlanViews/',
      'VVM/44__System__PlanAnnotations/ -> VVM/43__System__PlanAnnotations/',
      'VVM/45__System__PlanDimensions/ -> VVM/44__System__PlanDimensions/',
      'VVM/46__System__ElevationViews/ -> VVM/45__System__ElevationViews/',
      'VVM/47__System__NorthDirection/ -> VVM/46__System__NorthDirection/',
      'VVM/40__System__2dElevationsView/Na__RenderEffect__2dProfileLines__.js -> VVM/05__RenderPipeline/Na__RenderEffect__2dProfileLines__.js',
      'VVM/42__System__DrawingViewCore/Na__DrawView__ComposerPreset__.js -> ' + RPRESET,
      'VVM/03__AppUtils/Na__AppUtils__SnapshotHistory__.js -> VVM/03__AppUtils/Na__AppUtils__SnapshotHistory.js',
      'VVM/05__RenderPipeline/02__Engine__MaxEngine/Na__RenderEffect__DistanceCulling__.js -> VVM/05__RenderPipeline/Na__RenderEffect__DistanceCulling__.js'],
  hot=[IDX, CSSIDX, LS, MAINCFG, MC, LDR, SNAPR, MB, SREC, SM, HIST, AUTOSAVE, ASSETS, P_VPSET, SPECPDF, PDFX, FPMC, EVMC,
       VVM('50__System__ProjectedLinework/Na__ProjectedLinework__Pipeline__.js'), PERSIST, PLCFGACC],
  deps=['W0-01'],
  gated=['DR-02', 'DR-03', 'DR-04'],
  size='L', est=1049, est_note='scripted: 332 replacements in 94 files plus 11 git mv (K2 W1 preview diff = 1,049 lines)',
  split_justification='One atomic scripted change by design (K2 section 9): a partial rewrite blanks the page; the script was proven on a full copy (ModuleGraph 517/0, Exports PASS, 6/6 node tests, path gate PASS).',
  adapt=['RenderPreset keeps VV\'s composer body and private Na__DrawPreset namespace; the PORT NOTE is rewritten by hand (K2 rulebook section 3 filled example); RenderFrame gains an optional camera argument (S02a-F14) - the one non-mechanical edit allowed.',
         'History documents (devlog, ledger, plans) are never rewritten; the W0 Parity Scribe adds the dated "Folder renumbering" ledger section and the D05 revision note.',
         'The shared WCP precache line for DistanceCulling (logic :318) is NOT touched (DR-07); W0-08 fixes it.'],
  acc=['Step 0 preflight per K2 section 9: clean git status for WebApps/ValeVision3D and WebApps/Whitecardopedia; fresh read of the VV devlog top; baseline ModuleGraph 517/0 and Exports PASS; dry run prints RETIRED NAMES LEFT ... : 0.',
       'Applied with python parity/report/tools/k2_renumber_apply.py --mode git --report parity/k2work/renumber_git_report.json.',
       'G1, G2 and G3 (k2_path_gate.py with the default retired-name list) pass; every 80__Testing__PrototypeEnvironment/*.test.mjs passes (6/6 on 01-Oct-2026).',
       'git diff -M --stat shows every moved file as a rename; the pairing report shows 70 drawing files paired with TV by identical relative path (16+10+8+15+13+8).',
       'No hit for 42__System__DrawingViewCore, 43__System__FloorPlanViews, 44__System__PlanAnnotations, 45__System__PlanDimensions, 46__System__ElevationViews, 47__System__NorthDirection, 40__System__2dElevationsView or Na__DrawView__ComposerPreset__ in VV src, styles, tests or index.html (history exempt).',
       'Adam\'s smoke test (localhost, Flask): app loads; Tools > Elevation View (legacy, now 91) works; a floor plan, an elevation and a section open from the carousel; North compass and Dev-menu drawing panels open; a sheet renders, a viewport bakes, Save Sheets works, PDF downloads; the Specification tab opens.'],
  tests=['(none new) run Na__Verify__ModuleGraph__.mjs, Na__Verify__Exports__.mjs and every existing Na__Test__*.test.mjs; Na__Test__NorthCompass__.test.mjs:53 names the folder'],
  src=['WP-S01-01R', 'WP-S02a-01', 'WP-S02a-12'],
  split=['WP-S09-10'],
  risk='Highest-contention package: no other package may be in flight on VV while it runs. Deploy hazard (stale SW-cached LoadingSequence next to a new index.html) is handled by W0-08 and Adam\'s DR-07 token decision, not here.',
  notes=['K2 calls this phase "W1"; in K3 it is package W0-02. The SnapshotHistory rename of WP-S09-10 (FR-10) is executed here.',
         'Besides the 11 moves listed in vv_targets, the script rewrites 94 files (touch list: parity/k2work/renumber_touch_k2.tsv); the hot files listed are the ones other packages also edit.'])

P('W0-03', 'W0', 'Hotkey file names (name only) and identity hygiene',
  'Rename the two VV key files to TV\'s names without changing content (FR-12, FR-13) and remove the two known TrueVision identity leaks.',
  tv=[TLE('03__Core__Config/Na__Hotkeys__DrawingTabs__.json'), TVM('02__AppData/Na__Hotkeys__3dModelTab__.json')],
  vv=['VVM/51__System__LayoutEditor/03__Core__Config/Na__LayoutEditor__KeyMappings__.json -> ' + KEYS2D,
      'VVM/02__AppData/Na__ValeVision__HotkeysDictionary__.json -> ' + HOTKEY3D,
      CS_KM, CS, AC, HKHANDLER, HELPPANEL, IDX, CTL_PC, CTL_TOUCH, VLE('30__System__SheetTools/Na__LayoutEditor__Measurements__.js'), SPECPDF,
      VVM('44__System__PlanDimensions/Na__PlanDimensions__Styles__.css')],
  hot=[CS_KM, CS, AC, HKHANDLER, HELPPANEL, IDX, SPECPDF, CTL_PC, CTL_TOUCH],
  deps=['W0-02'],
  gated=['DR-33'],
  size='S', est=60,
  adapt=['Internal JSON keys stay (TV kept LayoutEditor__KeyMappings__*); the 3D file keeps root key Na__ValeVision__HotkeysDictionary and ValeVision__ actions (K2 F4).',
         'Only fetch constants and comments change: ConfigState__KeyMap__.js:63; HotkeyHandler :116 (+ :13, :28); NavigationHelpPanel :84 (+ :22); index.html comments :1261, :1776; comments at ConfigState__.js:154, ConfigState__KeyMap__.js:13,154, Controls__Pc :19, Controls__TouchScreen :29, Measurements :56; AppConfig descriptions :277, :457.',
         'Identity: console prefix at LE/50 SpecPdf :431 -> [ValeVision3D LayoutEditor]; the PlanDimensions styles banner (line 8) -> VALEVISION3D, PORT NOTE after the banner.'],
  acc=['Drawing-tab keys (V, M, T, D, L, R, Delete, Escape, arrows) and 3D keys (R, B, T, Y, 1-9, Page Up/Down) work as before; the navigation help panel lists the 3D keys.',
       'No reference to the FILE names Na__LayoutEditor__KeyMappings__.json or Na__ValeVision__HotkeysDictionary__.json outside history.',
       'No "[TrueVision3D" prefix and no "TRUEVISION3D" banner in VV src or styles (PORT NOTE "Ported from" lines excepted).',
       'G1-G3 pass.'],
  tests=[],
  src=['WP-S01-03R'],
  risk='Low. TV drawing-tab key CONTENT must not land before ConfigState__KeyMap__ 1.11.0 (W0-15): T would resolve to Trim.')

P('W0-04', 'W0', 'Swarm gates: naming lint, port-note verifier, UI parity gate, loader-stylesheet test, harness fixes',
  'Give every later package machine checks for the rules it must keep: identity and NA-marker lint, PORT NOTE and log-order verifier with {{VVREL}} detection, UI parity of the fold/veil/tab/panel CSS, loader stylesheet order against TV\'s CSS index, and the ModuleGraph string false positive plus a loader facade-name check.',
  tv=['TV/80__Testing__PrototypeEnvironment/Na__Verify__ModuleGraph__.mjs', 'TV/03__Style__AppStylesheets/Na__CoreUi__Styles__Index__.css'],
  vv=[NEW(TESTDIR + 'Na__Verify__ParityNaming__.mjs'), NEW(TESTDIR + 'Na__Verify__PortNotes__.mjs'),
      NEW(TESTDIR + 'Na__Verify__UiParity__.mjs'), NEW(TESTDIR + 'Na__Test__LoaderStylesheets__.test.mjs'),
      VERIFY_MG, VERIFY_EX],
  hot=[VERIFY_MG, VERIFY_EX],
  deps=['W0-03', 'W0-06'],
  gated=['DR-05', 'DR-34', 'DR-43'],
  size='M', est=1300, est_note='four new node scripts (~250-400 lines each) plus two harness fixes',
  adapt=['Allow-list VV\'s own NA-hosted infrastructure: cdn.noble-architecture.com/VaApps/ and www.noble-architecture.com/assets/ (DR-43); PORT NOTE "Ported from" lines and history are exempt.',
         'The folder-number check reads the registry written by W0-06 (ValeVision__NOTES__FolderNumberRegistry__.md).',
         'Na__Verify__PortNotes__ accepts an explicit "legacy" marker; with --tv <TV root> it lists TV log entries dated after VV\'s last port (S11 c.1 algorithm).'],
  acc=['Na__Verify__ParityNaming__ runs clean on VV after W0-02/W0-03; it FAILS on a planted TrueVision__ literal, a planted window.TrueVision__ read, a planted NaProjectPortal string and an unregistered folder number; it PASSES VV\'s cdn.noble-architecture.com/VaApps and font URLs.',
       'Na__Verify__PortNotes__ reports today\'s History/Toolbar log-order faults and missing Source version lines; a planted {{VVREL:x}} token and a planted out-of-order log entry are both caught; with --tv it reproduces the S11 c.1 column for LE/07__Core__SheetData.',
       'Na__Verify__UiParity__ (TV root as argument) prints PASS/FAIL per check (AppHeader fold region, Boot tab-strip region vs TV Styles__Main, LoadingOverlays veil region, Styles__Panels, stylesheet order, no prefers-reduced-motion in AppHeader, SW token warning) and fails on a one-character mutation of any guarded rule (in-memory copy).',
       'Na__Test__LoaderStylesheets__ asserts Na__LeLoad__STYLESHEETS holds TV\'s CSS-index LE sequence for files that exist in VV (Surfaces first, WebViewer last); it passes today and after every feature landing.',
       'VV ModuleGraph exits 0 with a copy of TV\'s 21 SceneEditor string case present; the facade-name check passes on HEAD and fails on a deliberately misspelt Na__LeMode__ name; both harnesses run in under a minute and write nothing.'],
  tests=['Na__Test__LoaderStylesheets__.test.mjs (VV-only, new)'],
  src=['WP-S01-08R', 'WP-S11-03', 'WP-S09-02', 'WP-S10-05', 'WP-S03a-07'],
  risk='Low (read-only checkers); false positives on legacy headers are handled by the legacy marker.',
  notes=['The UI parity gate is expected to FAIL on the fold/veil/tab checks until W1-30/W1-31 land; it is run as a report until then and as a gate from W1-31 on.'])

P('W0-05', 'W0', 'Port-order map from TV\'s import graph (leaves first, hubs last)',
  'For every TV module the swarm takes whole, compute the closure of imports missing in VV after W0-02 and emit the blocked-by list and a leaves-first order that the planner and the Parity Scribe use; flag every 80__CloudflareIntegration / LocalProjectMirror / NAAPPS import as a transport seam (resolved by the W0-12 facade).',
  tv=['TVM/ (read-only import walk)'],
  vv=[],
  hot=[],
  deps=['W0-02'],
  gated=['DR-05'],
  size='S', est=300, est_note='analysis script (start from parity/work_s11v/prereq.py)',
  acc=['Reproduces S11 Appendix D for the 62 c.1 port_whole rows (44 blocked before the swarm starts).',
       'Every TV import of 80__CloudflareIntegration or LocalProjectMirror__ is labelled "transport seam (DIV-4) - resolved by VV facade W0-12".',
       'The emitted order agrees with this catalogue\'s DAG: no canonical package takes a file whole before every module it imports is landed by an earlier package (any disagreement is reported to the planner as a defect in wp_canonical.json).'],
  tests=[],
  src=['WP-S11-08'],
  risk='None to either app (read-only).',
  notes=['Output: parity/data/port_order_map.json, an analysis artifact outside both repositories, handed to the planner; the ledger Module Register "blocked-by" column is written from it by the W0 Parity Scribe (W0-99), never by this package.'])

P('W0-06', 'W0', 'Ledger restructure, folder-number registry and records hygiene',
  'Restructure the VV parity ledger (Module Register, Release Watermark, Decisions, back-ports, Archive), add the folder-number registry and the renumber map, mirror TV\'s realign plan name, fix every stale row the slices found, and tidy module log order - comment and documentation edits only.',
  tv=[TVPLAN],
  vv=[LEDGER, DEVLOG, NEW('VV/ValeVision__PLAN__TrueVisionRealign__DrawingSystems__.md'), NEW('VV/ValeVision__NOTES__FolderNumberRegistry__.md'),
      VVPLAN, HIST, TOOLBAR, VVM('21__System__PresentationMode/Na__PresentationMode__DevMenu__SceneRowBuilders__.js'),
      VVM('21__System__PresentationMode/Na__PresentationMode__DevMenu__SceneReorder__.js'),
      VVM('21__System__PresentationMode/Na__PresentationMode__DevMenu__SceneEditor.js'), R2ASSET],
  hot=[LEDGER, DEVLOG, VVPLAN, HIST, TOOLBAR, R2ASSET],
  deps=['W0-02'],
  gated=['DR-35', 'DR-02', 'DR-03'],
  size='M', est=900, est_note='documentation; comment-only edits in six modules',
  adapt=['History is never rewritten: superseded narrative moves to an Archive section under a dated note (DR-35).',
         'Decisions section cross-references VV D01-D40 as current / superseded / permanent and the W0-01 D-numbers.'],
  acc=['Ledger sections: Header (roots; DIV-1..DIV-4 permanent, DIV-5 closed), Folder map with the dated "Folder renumbering" old->new table and the four file moves, Module Register (one row per module in scope; its blocked-by column is filled by W0-99 from the W0-05 map), Release Watermark (177 rows, classification counts 55/6/14/83/6/7/4/2 as S11 B3), Decisions, VV->TV back-ports (B5 statuses), Archive.',
       'No live row says ValeVision has no service worker (the 19 rows of WP-S10-08R and the 14 of S11-F22 corrected); the loader appears with one status (DR-24 (a)); rows 1219, 1220, 1225 stay OPEN (S11-V03).',
       'Registry lists every top-level number in TV, VV and WCP as shared / TV-only / VV-reserved / legacy / burnt, per K2 section 8.',
       'Devlog gets a dated Records note (not a version) naming commit 66937440 (Specification port, TV v2.36.0) and the duplicate v2.54.0 headings.',
       'git diff -w of every touched module shows comment lines only; VV plan D05 carries a dated revision note.'],
  tests=[],
  src=['WP-S11-01', 'WP-S11-02', 'WP-S01-05', 'WP-S09-13', 'WP-S10-08R'],
  risk='Losing history; never delete narrative. TV plan edits only through the WT lane (DR-36).',
  notes=['WP-S10-08R\'s header-line items for ModeController/Loader/TabStrip/Toolbar are folded into W1-29/W1-30/W1-31 (they edit those files); its ledger rows are done here.'])

P('W0-07', 'W0', 'Whitecardopedia sync pipeline safety (prepared, dry-run; Adam applies)',
  'Stop the project sync deleting sub-folder pictures on R2 and make every sync preserve editor-owned keys from R2, with one editor-owned key list shared by the worker merge guard and the localhost overlay.',
  tv=['NAAPPS/05__ProjectVision__CoreAppCode/CloudflareR2__ModelSync__Main__.py (reference only)'],
  vv=[SYNC, AUDIT, R2COMMON, MAINCFG],
  hot=[SYNC, AUDIT, R2COMMON, MAINCFG],
  deps=['W0-02'],
  gated=['DR-06', 'DR-30'],
  size='M', est=450,
  adapt=['ProjectData__EditorOwnedKeys added to VV Na__AppConfig__Main.json is THE list (DR-06, DR-30); the worker (W0-10) and the localhost overlay (W0-13) read the same list.'],
  acc=['na_purge_stale_r2_images lists with Delimiter="/" and paginates; the GLB purge is scoped the same way.',
       'With an in-memory S3 stub: PresentationMode/Thumbnails/x.webp, LayoutEditor/Snapshots/y.webp, 05__Layout__DrawingDocs__Images/D01/z__0123456789.webp and keys under 06__Layout__PublishedDocuments/ survive a full sync while a superseded top-level IMG01 png is purged; listing follows continuation tokens past 1,000 keys.',
       'R2\'s LayoutEditor__DrawingsData survives a sync from a local project.json that lacks it and the local file receives it; a repointed IMG-slot thumbnail lands in R2\'s PresentationMode__SavedCameraScenes; hand-authored PresentationMode/Thumbnails paths are untouched.',
       'Dry run on 2026/3047__Doous only; no live sync is run by the swarm; Adam signs off and runs it (DR-06). Until then rule R8 holds.'],
  tests=['a stub-client Python test beside the sync scripts (new; Flask/S3 stubs, no network)'],
  src=['WP-S12-01', 'WP-S08-04'],
  risk='Runs on live projects from the SketchUp Cloud Sync plugin; a wrong merge overwrites R2. Shared with Whitecardopedia.')

P('W0-08', 'W0', 'Shared Whitecardopedia service-worker package (prepared, not bumped)',
  'One package for every change the shared worker needs: registrar up to TV 1.1.0-1.3.0 with the unsaved-work hold (neutral window.Na__Pwa__HasUnsavedWork), the stale-while-revalidate refresh fix, precache of the lazily linked LE stylesheets and the DistanceCulling path, cache classes for sheet pictures and published documents, and the manifest-bump classification.',
  tv=[TVM('62__Feature__AppInstallability/TrueVision__Pwa__ServiceWorker__Registrar__.js'), TVM('62__Feature__AppInstallability/TrueVision__Pwa__ServiceWorker__Logic__.js')],
  vv=[SWLOGIC, SWREG, AUTOSAVE],
  hot=[SWLOGIC, SWREG, AUTOSAVE],
  deps=['W0-02'],
  gated=['DR-07'],
  size='M', est=650,
  adapt=['VV AutoSave publishes window.Na__Pwa__HasUnsavedWork = Na__LeAuto__HasUnsavedWork (K2 K4); the registrar check is a no-op where the flag is absent (Whitecardopedia pages).',
         'Buckets wpwa-images-<token> (VV picture path under 05__Layout__DrawingDocs__Images, cache-first, LRU 160) and wpwa-published-<token> (hashed assets cache-first capped, JSON network-first, PDF passthrough), both in the owned prefixes and the activate keep-list.',
         'No PWA_SW_VERSION_TOKEN bump: Adam bumps at deploy (DR-07); the token rule decided in W0-01 is written into the logic file header.'],
  acc=['A fresh origin\'s first load registers the worker and does NOT reload; a second controllerchange on a controlled page reloads once; with unsaved sheets open the reload waits and gives up after the registrar timeout; Whitecardopedia pages behave as before.',
       'After a deploy a warm client gets a changed LE stylesheet on its first load (cache:"no-cache" refresh, TV SW 1.9.54); the 8 loader sheets and the 56/57 self-linked scrapbook sheets are precached; the stale DistanceCulling entry (:318) points at 05__RenderPipeline.',
       'A picture fetched twice from cdn.noble-architecture.com is served from the images bucket; a .png picture no longer lands in the shell cache; hashed published files are served from cache on a second visit and a re-published index is seen on the next load.',
       'Gallery thumbnail, full-image, data and model rules unchanged; Whitecardopedia gallery still works offline.'],
  tests=[],
  src=['WP-S10-15', 'WP-S09-11R', 'WP-S07a-11', 'WP-S08-12', 'WP-S12-15', 'WP-S01-11'],
  risk='Shared by every Vale web app; a token bump evicts every cache including models - Adam\'s call only.',
  notes=['WP-S01-11 part 2 (project display-name accessor) is delivered by W0-12 (facade Na__CfApi__GetProjectDisplayName), not by ProjectData, because ProjectData is taken whole in W1-05 (K3 resolution).',
         'W1-07 (AutoSave 1.5.0 whole) re-applies the flag line as a recorded VV seam.'])

P('W0-09', 'W0', 'Flask persistence core and shared helper',
  'Give WCP/server.py the guarded project save (drawings fingerprint, 409 on a stale base, backups outside the repo, atomic writes), JSON 404s, /api/health, files/<name> with Last-Modified, and harden the drawing-notes route; all helpers in one shared library.',
  tv=['NAAPPS/ProjectVision__LocalServer__Main__.py', 'NAAPPS/ProjectVision__TrueVisionUserConfig__Api__.py'],
  vv=[SERVER, NEW('WCP/Server__ValeVisionShared__Lib__.py'), NEW(TESTDIR + 'Na__Test__ProjectDataSaveGuard__.test.py'),
      NEW(TESTDIR + 'Na__Test__DrawingNotesRoute__.test.py')],
  hot=[SERVER],
  deps=['W0-02'],
  gated=['DR-28', 'DR-29', 'DR-30'],
  size='M', est=900,
  adapt=['VV routes and headers (K2 R5): POST /api/projects/<folder_id> with X-ValeVision-Drawings-Base; /api/projects/<folder_id>/drawing-notes kept as an alias of files/<name>; allow-list ValeVision__DrawingNotes__.json, ValeVision__StatementDocs__.json.',
         'Backups outside D:/10_CoreLib__ValeCodebase (keep 30), backup root in config for Adam to confirm (DR-30); realpath containment fixes get_project_path.'],
  acc=['Ported ProjectDataSaveGuard checks pass against WCP: fingerprint invariant to formatting and keys outside the block; matching base lands and answers the new fingerprint; stale base refused with the file untouched and no backup; hand-edited file refuses; no header is never judged; "none" matches only a file without a block; backups byte-identical, outside the repo, capped at 30.',
       'GET /api/does-not-exist answers 404 JSON, not index.html; files/<name> refuses names off the allow-list and ".." folder ids.',
       'Drawing notes GET sends Last-Modified (file mtime) and Cache-Control no-store, keeps 404 {missing:true}; POST writes atomically (temp + os.replace); bytes written are 4-space JSON, LF, final newline (Na__Test__DrawingNotesRoute__).',
       'Existing callers without the header behave as before; validate_project_json kept; Whitecardopedia\'s Project Editor unaffected.'],
  tests=['Na__Test__ProjectDataSaveGuard__.test.py (retargeted to WCP/server.py)', 'Na__Test__DrawingNotesRoute__.test.py (VV-only, new)'],
  src=['WP-S12-03', 'WP-S06b-02'],
  risk='server.py is shared with Whitecardopedia\'s Project Editor; Flask does not reload routes (restart needed).')

P('W0-10', 'W0', 'VV worker 1.6.0: project GET, merge-keys and the guarded project-files family (built under wrangler dev; Adam deploys)',
  'One worker release with server-side family rules for every new VV content type (siblings, thumbnails, assets, sheet images, published documents, statements), merge-keys with the editor-owned key list and an optional drawings-base 409, folderId validation on every /projects/ route, JSON 404 for unknown /api/*, and a health route listing capabilities the facade feature-detects.',
  tv=['TV/80__CloudflareIntegration/CloudflareWorker/src/handlers/CloudflareHandler__R2__.js (reference: TV generic /r2/* is NOT copied)'],
  vv=[WORKER, NEW('WCP/CloudflareWorker/src/handlers/CloudflareHandler__ProjectFiles__.js'),
      NEW('WCP/CloudflareWorker/src/handlers/CloudflareHandler__ProjectMerge__.js'),
      NEW('WCP/CloudflareWorker/src/CloudflareHelper__PathGuards__.js'), WCORS],
  hot=[WORKER, WCORS],
  deps=['W0-07'],
  gated=['DR-28', 'DR-29', 'DR-06', 'DR-27'],
  size='L', est=1500,
  adapt=['Families F-SIB, F-THUMB, F-ASSET, F-IMG (05__Layout__DrawingDocs__Images, hash-checked names, immutable cache), F-PUB (06__Layout__PublishedDocuments, raw streamed writes ~95 MB, list by cursor, document-scoped delete, never the build manifest), F-STMT (10__StatementDocs, TV segment/suffix/depth rules, 25 MB cap) - one handler, one deploy (DR-28); X-Editor-Api-Key on every write (VV keeps authenticated semantic routes, S08-F17).',
         'Every key under VaApps/Projects/<folderId>/ (bucket noble-architecture-cdn is shared with TV: never NaProjectPortal/).'],
  acc=['Node tests with a Map-backed env.R2_BUCKET: each family accepts its own paths and refuses project.json, 00__Archive folders, "..", cross-family copies, deletes outside one published document and unmanaged sheet-image names.',
       'merge-keys refuses pipeline-owned keys, answers 409 on a stale drawingsBase and on a missing project.json, and never writes VaApps/Index/Na__BuildVersion__Manifest__.json unless bumpBuild is true; files routes never touch the build manifest.',
       'Every existing master-index folderId passes the new validation; calls without X-Editor-Api-Key return 401; unknown /api/* returns JSON 404.',
       'Proved under wrangler dev; after Adam\'s deploy GET /api/editor/health reports version 1.6.0 and the route list.'],
  tests=['worker node tests with a Map-backed R2 binding (new, beside the worker)'],
  src=['WP-S12-04'],
  split=['WP-S07a-06', 'WP-S07b-03', 'WP-S08-05'],
  risk='Needs Adam\'s wrangler deploy; folderId validation must not refuse any existing project; keep routes backward compatible.')

P('W0-11', 'W0', 'ProjectLoader identity helpers and the localhost repository fallback',
  'Add TV\'s Na__AppUtils__GetProjectFolderFromUrl and Na__AppUtils__GetYearFromUrl with VV meaning (master index; never project.json folderId) and a localhost fallback in ResolveAssetUrl; additive only.',
  tv=[TVM('03__AppUtils/Na__AppUtils__ProjectLoader.js')],
  vv=[PLDR],
  hot=[PLDR],
  deps=['W0-02'],
  gated=['DR-27'],
  size='S', est=160,
  adapt=['VV meaning (S12-V02): honour ?project-folder= and &year=, else derive from ?project= through the master index; 4-digit year; unknown code gives folder null.',
         'Under DR-27 the per-feature client Na__AppUtils__R2PublishedDocs__ of WP-S08-06 is NOT created: the facade (W0-12) serves publishing.'],
  acc=['?project=3047 gives "3047__Doous" and "2026"; ?project=2026/3047__Doous gives the same; ?project-folder=X&year=2026 is honoured; an unknown code gives folder null.',
       'ResolveAssetUrl on localhost returns the Flask copy as fallback; web unchanged.',
       'G2 passes; the ~30 VV importers are unaffected (additive exports only).'],
  tests=[],
  src=['WP-S12-02', 'WP-S08-06'],
  risk='Imported by about 30 VV modules: additive only.')

P('W0-12', 'W0', 'VV transport facade at TV\'s paths: Na__CfApi and Na__LocalMirror (VV bodies)',
  'Create TV\'s client files at TV\'s paths with every exported name TV modules import (33 Na__CfApi__*, 8 Na__LocalMirror__*) and VV bodies over whitecardopedia-editor-api and the WCP Flask server, so ported TV files link unchanged; add the project display-name accessor that replaces window.TrueVision__Pwa__ProjectContext.',
  tv=[TVM('80__CloudflareIntegration/Na__CloudflareIntegration__ApiClient__.js') + ' (names and signatures only)',
      TVM('03__AppUtils/Na__AppUtils__LocalProjectMirror__.js') + ' (names and signatures only)'],
  vv=[NEW(FACADE), NEW(LOCALMIR), NEW(TESTDIR + 'Na__Test__TransportFacade__.test.mjs'), SPECPDF],
  hot=[SPECPDF],
  deps=['W0-09', 'W0-10', 'W0-11', 'W0-03'],
  gated=['DR-27', 'DR-28', 'DR-29', 'DR-30'],
  size='L', est=1800, est_note='TV ApiClient 1,221 + LocalProjectMirror 447 lines of interface, VV bodies',
  adapt=['PORT NOTE "Parity: diverged (identical names and signatures, different transport)" (K2 H3, R6); private namespace may stay VV\'s.',
         'Project folder resolved only from the URL token through the master index; writes refused on a miss; never project.json folderId (S12-V02); never a TV key builder.',
         'Pre-fetch the worker config at load so Na__CfApi__IsConfigured answers synchronously (S06b-V04); feature-detect the W0-10 routes and fall back to the existing save / assets / drawing-notes routes; every function resolves {ok:false,...} instead of throwing.',
         'Na__CfApi__GetProjectDisplayName() (VV-only additive export, K2 X2; K3 adopts the VerbNoun form of WP-S12-V18\'s Na__CfApi__ProjectDisplayName) reads root projectName / displayName / projectNameAlias of the loaded project data; used wherever TV reads window.TrueVision__Pwa__ProjectContext (SpecPdf :141-148 now; SpecDocument :161, Register__Pdf :213, Panel__ScrapbookParametric :290, Statement TrueVisionHub :206 on arrival).'],
  acc=['G2 resolves every Na__CfApi__ and Na__LocalMirror__ name imported by TV drawing and LE files (S01-F13, S09-F27/F28 lists).',
       'Stubbed-fetch node test: R2 keys VaApps/Projects/2026/3047__Doous/..., CDN URLs and app-root-relative repository URLs correct for a Flask origin and the GitHub Pages sub-path.',
       'MergeAndSaveKeys is queued, uses merge-keys when the worker lists it and falls back to a whole-document save on a fresh Flask base otherwise; IsConfigured is false off localhost.',
       'On localhost a drawings save reaches WCP/server.py and the repo copy of project.json; on the live site reads work with no Flask.',
       'The specification PDF of 2026/3047__Doous prints the project name; no VV module reads window.TrueVision__Pwa__ProjectContext; no literal NaProjectPortal, 30__TrueVision__AppContent or /api/truevision in VV.'],
  tests=['Na__Test__TransportFacade__.test.mjs (VV-only, new: stubbed fetch)'],
  src=['WP-S12-05', 'WP-S01-06R', 'WP-S09-06', 'WP-S07a-02', 'WP-S12-V18'],
  risk='Holds the editor API key in memory (as today). Must not copy TV\'s transport; a save-path bug loses data - test on a copy of 2026/3047__Doous.',
  notes=['SpecPdf is edited here only for the display-name accessor (one line), after W0-02 and W0-03 (serial order); W1-25 later edits it for the embedded fonts.',
         'WP-S07a-02\'s ProjectData half (Save(showToast, report, registerKeys), save steps) is delivered by W1-05 (TV ProjectData 1.6.0 whole over this facade).'])

P('W0-13', 'W0', 'Loading-sequence transport wiring, the editor-owned overlay and na-app-scene-ready',
  'Initialise the facade at load, overlay editor-owned keys from R2 onto the Flask copy on localhost, register the loaded project data with the facade before the drawings dispatch, pass sceneConfig in the drawings-loaded detail and dispatch TV\'s na-app-scene-ready once per load.',
  tv=[TVM('01__AppCore/Na__AppFlow__LoadingSequence.js')],
  vv=[LS],
  hot=[LS],
  deps=['W0-12'],
  gated=['DR-30', 'DR-27'],
  size='S', est=200,
  adapt=['Hand-adapted hunks only (VV LoadingSequence differs by ~1,900 lines); keep VV\'s dispatch keys and order; the overlay is localhost-only and non-fatal.',
         'na-app-scene-ready (S09-F49/S08-F15) is dispatched at the end of VV Na__UiFeature__ShowScene, so W4-08 Share__Open and later ports need no LoadingSequence edit.'],
  acc=['On localhost, with R2 holding a newer LayoutEditor__DrawingsData than disk, the session loads R2\'s block and logs the overlay.',
       'Na__CfApi__GetLoadedProjectData() returns the document the session runs; web (GitHub Pages) load path unchanged; no worker call is made off localhost.',
       'na-app-scene-ready fires once per load, after the canvas becomes visible.'],
  tests=[],
  src=['WP-S12-06'],
  split=['WP-S09-08'],
  risk='LoadingSequence is touched by W0-02, W1-01 and W2-07 too: edit only the project-data region and the ShowScene tail.')

P('W0-14', 'W0', 'Asset upload contract, VV-gated asset modules and TV\'s thumbnail call shape',
  'Adopt TV\'s non-throwing upload contract in VV R2AssetUpload (silent skip off localhost), take TV Assets 1.0.1 and Persistence 1.2.1 with VV\'s localhost gate, and let the thumbnail renderer accept TV\'s CaptureAndUpload call shape (fixing VV\'s Update All Thumbnails).',
  tv=[TLE('07__Core__SheetData/Na__LayoutEditor__Assets__.js'), TVM('50__System__ProjectedLinework/Na__ProjectedLinework__Persistence__.js'),
      TVM('03__AppUtils/Na__AppUtils__R2AssetUpload__.js'), TVM('21__System__PresentationMode/Na__PresentationMode__Thumbnail__Renderer.js')],
  vv=[ASSETS, PERSIST, R2ASSET, THUMB],
  hot=[ASSETS, PERSIST, R2ASSET, THUMB],
  deps=['W0-11', 'W0-06'],
  gated=['DR-27', 'DR-28'],
  size='M', est=650,
  adapt=['CanUpload and bake-before-save keep Na__AppUtils__IsRunningOnLocalhost() (VV D24), not Na__DevGate__IsAuthoringEnabled (TD01).',
         'Persistence keeps IndexedDB name ValeVision3D__ProjectedLinework, console prefix and stored Description ("one ValeVision drawing"); FolderId from W0-11 helpers; this package is the single owner of Persistence (W2-06 does not touch it).',
         'R2AssetUpload: {r2Success:false, localSuccess:false, publicUrl:null, relUrl:null, error} on failure, relUrl on success; silent skipped result off localhost; path guard extended per asset kind.',
         'Thumbnail Renderer: CaptureAndUpload(sceneId, second, showToast) resolves the project code itself when "second" is not a string (Na__PresentationMode__ProjectJson__GetActiveProjectCode, fallback Na__AppUtils__GetProjectCodeFromUrl); numeric second = targetWidthPx; tests r2Success.'],
  acc=['A refused or failed upload never reports a stored snapshot, linework block or thumbnail; on the live site with authoring unlocked no upload or bake-for-upload is attempted and no toast is shown.',
       'Snapshots and linework read back from VaApps/Projects/{folderId}/LayoutEditor/... on the web and from the Flask copy on localhost.',
       'Node stub test: CaptureAndUpload(id) and CaptureAndUpload(id, 512) call R2AssetUpload with PresentationMode/Thumbnails/<id>.webp; CaptureAndUpload(id, code, toast) unchanged; Adam: Presentation Scenes > Update All Thumbnails writes every eligible thumbnail.',
       'PORT NOTEs record the gate, DB name and Description divergences.'],
  tests=[],
  src=['WP-S12-V09R', 'WP-S02a-16'],
  risk='The renderer is shared by the scene editor, ThumbnailBake and the drawing editors; the three-argument form must stay byte-compatible.')

P('W0-15', 'W0', 'Layout Editor config foundation: AppConfig additive pass, ConfigState units and KeyMap 1.11.0 with TV key content',
  'Take every TV-only key, block, note and label into VV\'s LE AppConfig (VV values for NA paths and brand, behaviour-changing values withheld), port ConfigState barrel 1.29.0, SheetSetup 1.9.0, ToolSetup 1.5.0, EditorSetup 1.6.0 and KeyMap 1.11.0 with TV\'s drawing-tab key content in ONE change, so every later package reads its config and no later package adds keys.',
  tv=[TLE('03__Core__Config/Na__LayoutEditor__AppConfig__.json'), TLE('03__Core__Config/Na__LayoutEditor__ConfigState__.js'),
      TLE('03__Core__Config/Na__LayoutEditor__ConfigState__Readers__.js'), TLE('03__Core__Config/Na__LayoutEditor__ConfigState__SheetSetup__.js'),
      TLE('03__Core__Config/Na__LayoutEditor__ConfigState__ToolSetup__.js'), TLE('03__Core__Config/Na__LayoutEditor__ConfigState__EditorSetup__.js'),
      TLE('03__Core__Config/Na__LayoutEditor__ConfigState__KeyMap__.js'), TLE('03__Core__Config/Na__Hotkeys__DrawingTabs__.json')],
  vv=[AC, CS, CS_RD, CS_SS, CS_TS, CS_ES, CS_KM, KEYS2D, NEW(TESTDIR + 'Na__Test__AppConfigParity__.test.mjs')],
  hot=[AC, CS, CS_SS, CS_TS, CS_ES, CS_KM, KEYS2D],
  deps=['W0-03'],
  gated=['DR-33', 'DR-43', 'DR-10', 'DR-21'],
  size='L', est=2700, est_note='AppConfig 2,083 diff lines (much formatting) + ConfigState units ~1,100 diff + key file 1,267',
  split_justification='The barrel ConfigState__ 1.29.0 statically imports ReloadKeyMap/GetCopyDragModifier/GetMoveAnchorModifier/IsCopyDragKey from KeyMap 1.11.0, and TV\'s key content resolves T to Trim on VV\'s KeyMap 1.0.0: the units, the key file and the barrel must land together or the editor fails to link (S03a-V01, WP-S03a-02).',
  adapt=['TV\'s compact formatting; VV values for NA paths (PDF.js -> VV vendor 07 path, no NA PlanVision fallback), 16 brand values; TV\'s three Selection-block Measure labels NOT copied (TV defect, fixed TV-side by WT-08).',
         'Withheld until their feature lands (each owner flips them): title block Rows/DocumentId (W1-22), AccordionSections entries (W2-29 patterns, W3-07 vector-tools, W3-09 images, W3-10 floor-areas), Style FontFamily (W1-25), the label rewordings (W1-32, W1-34, W1-35, W5-01).',
         'Statement block (WP-S07b-04): FolderName 10__StatementDocs, IndexFileName ValeVision__StatementDocs__.json, StylesheetUrl on VV\'s public origin, Html2CanvasScriptPath (VV vendor 06), lockstep and PDF presets; VV-only LayoutEditor__Statement__Enabled = false (DR-10).',
         'Pdf JsPdfScriptPath and TitleBlock ClassicScanAssets stay on the 35 paths until W0-16.'],
  acc=['A Python key-tree diff of VV against TV shows only the allow-listed seams (brand values, NA-path values with VV replacements, VV-only labels and keys, withheld values) - Na__Test__AppConfigParity__.',
       'With the key file blocked (404) M arms Move, space arms Select and Ctrl+S saves without the browser dialog; T still selects Text on a sheet; Shift+T, C, A, K and F6-F9 cause no regression (unknown actions are ignored by VV\'s old keyboard switch).',
       'The KeyMap fallback resolves every key exactly as the shipped file does (Na__Test__DrawingTabKeys__ fallback-parity and ReloadKeyMap sections).',
       'G1/G2 pass; the editor loads through the loader with no module-link error; node --check passes on every changed module; an existing VV sheet opens, renders and exports its PDF unchanged; GetScaleSetup returns each key once; GetStatementSetup returns VV values.'],
  tests=['Na__Test__AppConfigParity__.test.mjs (VV-only, new)', 'Na__Test__DrawingTabKeys__.test.mjs (fallback parity and ReloadKeyMap sections; full suite in W1-36)', 'Na__Test__AuthoringZoomMax__.test.mjs (config half)'],
  src=['WP-S03a-V01', 'WP-S03a-02', 'WP-S07b-04'],
  risk='A barrel name ahead of its unit stops the whole editor at link time: run G2 before anything else.',
  notes=['Retired alias WP-S05a-04 (config readers) and WP-S05a-05 (key map) are covered here.'])

P('W0-16', 'W0', 'Vendor and asset copies: jsPDF 4.1.0, html2canvas 1.4.1, PDF.js 3.11.174, Vale\'s Classic title-block scan',
  'Copy (never move) jsPDF and VALE\'s own Classic scan out of legacy 35__System__PageLayoutSystem into TV\'s vendor and asset folders, vendor html2canvas and PDF.js (VV vendor 07, K2 TF-R07: TV loads PDF.js from PlanVision\'s NA path, TV AppConfig :1200-1201, which VV cannot use), and repoint the LE config, the SheetSetup fallback and the two test pages; the 35 copies stay for the legacy Create Drawing page until W6-03.',
  tv=['TV/04__Lib__ThirdParty__VersionLocked/05__Vendor__JsPdf__v4.1.0/jspdf.umd.js', 'TV/04__Lib__ThirdParty__VersionLocked/06__Vendor__Html2Canvas__v1.4.1/html2canvas.umd.js',
      'TV/01__AppAssets__TrueVision/06__AppAssets__TitleBlocks/TitleBlock__ClassicScan__A3__.png (path convention only - NA scan never copied)',
      'NAAPPS/20__PlanVision__CoreAppCode/01__AppDependencies__VersionLocked/PdfJs__3.11.174/build/pdf.min.js', 'NAAPPS/20__PlanVision__CoreAppCode/01__AppDependencies__VersionLocked/PdfJs__3.11.174/build/pdf.worker.min.js'],
  vv=[NEW('VV/04__Lib__ThirdParty__VersionLocked/05__Vendor__JsPdf__v4.1.0/jspdf.umd.js'),
      NEW('VV/04__Lib__ThirdParty__VersionLocked/06__Vendor__Html2Canvas__v1.4.1/html2canvas.umd.js'),
      NEW('VV/04__Lib__ThirdParty__VersionLocked/07__Vendor__PdfJs__v3.11.174/build/pdf.min.js'), NEW('VV/04__Lib__ThirdParty__VersionLocked/07__Vendor__PdfJs__v3.11.174/build/pdf.worker.min.js'),
      NEW('VV/01__AppAssets__ValeVision/06__AppAssets__TitleBlocks/TitleBlock__ClassicScan__A3__.png'),
      AC, CS_SS, VENDIDX, VENDRM, T_TBCHTML, T_SPECPDF],
  hot=[AC, CS_SS, VENDIDX, VENDRM, T_TBCHTML, T_SPECPDF],
  deps=['W0-15'],
  gated=['DR-03', 'DR-43'],
  size='S', est=60,
  adapt=['FR-20 copies VALE\'s scan (md5 59777a65), never TV\'s NA scan; jsPDF noted as a UMD script, not an import-map entry; 05/06/07 are not part of the coordinated 3D vendor set (README).',
         'K3 moves TF-R07 (PDF.js; K2 placed it with LE/51) here so the PDF.js path W0-15 writes into the LE config resolves from Wave 0 (k2_path_gate G4); the Register (W4-10) is its first user; 07 is offered to TV (K2 rulebook).'],
  acc=['Every jsPDF path string in VV resolves to a real file; Download PDF works on a sheet and on the Specification; a Classic-style sheet prints the real Vale scan from the new path.',
       'Na__Test__TitleBlockCells__.html and Na__Test__SpecificationPdf__.html load jsPDF from the new path.',
       'No Layout Editor module or LE config references 35__System__PageLayoutSystem; Image Export\'s legacy "send to drawing document" tab still loads jsPDF and its title block with no 404.'],
  tests=['Na__Test__SpecificationPdf__.html (re-run)'],
  src=['WP-S03a-V02', 'WP-S01-02', 'WP-S08-01', 'WP-S09-10'],
  risk='Low, provided nothing is deleted from 35 (Image Export loads it by relative path).',
  notes=['WP-S09-10\'s SnapshotHistory rename is executed by W0-02.'])

P('W0-17', 'W0', 'index.html start-up order aligned with TrueVision',
  'Move Na__DevGate__Initialize, Na__DrawView__ProjectData__Initialize, a direct Na__SectSceneData__Initialize and Na__DrawCfg__SetAppConfig/Load above Na__AppFlow__StartLoadingSequence, mirroring TV Index.html:1535-1571; nothing else.',
  tv=['TV/Index.html'],
  vv=[IDX],
  hot=[IDX],
  deps=['W0-03'],
  gated=[],
  size='S', est=40,
  acc=['G1/G2 pass; a project with drawings and one without both open; drawings listed in the Dev menu; section bindings restore on scene change; Dev menu builds on localhost and stays hidden with ?authoring=off.'],
  tests=[],
  src=['WP-S09-01'],
  risk='Low: listeners are idempotent; ordering only.')

P('W0-18', 'W0', 'Flask blueprints and app-root content: sheet images and user config (spellings)',
  'Port TV\'s sheet-images and user-config APIs onto the shared helper as VV blueprints registered in WCP/server.py, create the app-root user-config folder and spellings file, and allow-list hashed picture names in the ValeCodebase .gitignore.',
  tv=['NAAPPS/ProjectVision__TrueVisionSheetImages__Api__.py', 'NAAPPS/ProjectVision__TrueVisionUserConfig__Api__.py', 'TV/50__TrueVision__UserConfig/TrueVision__UserSpellings__.json'],
  vv=[NEW('WCP/Server__ValeVisionSheetImages__Api__.py'), NEW('WCP/Server__ValeVisionUserConfig__Api__.py'), SERVER,
      NEW('VV/50__ValeVision__UserConfig/ValeVision__UserSpellings__.json'), GITIGNORE,
      NEW(TESTDIR + 'Na__Test__SheetImagesApi__.test.py'), NEW(TESTDIR + 'Na__Test__UserSpellingsApi__.test.py')],
  hot=[SERVER, GITIGNORE],
  deps=['W0-09'],
  gated=['DR-13', 'DR-20', 'DR-29'],
  size='M', est=1100, est_note='TV APIs 478 + 418 lines rebased on the shared helper + tests',
  adapt=['Routes /api/valevision/sheet-images/{list,upload,reconcile} and /api/valevision/user-config/spellings (K2 R5); root Whitecardopedia/Projects/{yyyy}/{folder}/05__Layout__DrawingDocs__Images/ (DR-29 TV names inside VV storage), 00__Archive local only, never delete; query project-folder + 4-digit year (or folder-id).',
         'Spellings file: TV schema, Vale word list curated by Adam (DR-20), root key per D-S01-04; hand-broken dictionary reported, never overwritten; BOM read and written back without it.',
         '.gitignore allow-list for hashed picture names, excluding 00__Archive (DR-29: JSON committed, rasters per Adam).'],
  acc=['Adapted Na__Test__SheetImagesApi__ (24 checks, sys.dont_write_bytecode set) and Na__Test__UserSpellingsApi__ pass against a temporary Projects root.',
       'Uploads land only in the images folder; reconcile archives unused pictures locally; GET spellings answers {status:"ok", writable:true, document} on the local server; Add/Remove round-trip byte-for-byte; a word already in any group is not added twice.',
       'git status shows only hashed picture names under the images folder.'],
  tests=['Na__Test__SheetImagesApi__.test.py', 'Na__Test__UserSpellingsApi__.test.py'],
  src=['WP-S12-11', 'WP-S07a-06', 'WP-S12-14', 'WP-S01-07'],
  risk='server.py registration serialised with W0-09 and W0-19; Flask restart needed.',
  notes=['WP-S07a-06\'s worker half is in W0-10 and its client half in the W0-12 facade (SheetImageLocation/List/Upload/Copy/Delete/IsConfigured/SHEET_IMAGES_DIR).',
         'WP-S01-07\'s hatch-library copy is delivered by W1-17; its SpellCheck config pointing at the route by W2-34.'])

P('W0-19', 'W0', 'Flask blueprints: published documents and statements; .gitignore and .gitattributes for both',
  'Port TV\'s published-documents and statements APIs as VV blueprints (guarded resolvers, atomic sniffed writes, archive never overwritten, prune scoped to one document, statement delete to quarantine), give /Projects/ real 404s, and add the repository rules for published rasters, archives and LF-only statement files.',
  tv=['NAAPPS/ProjectVision__TrueVisionPublished__Api__.py', 'NAAPPS/ProjectVision__TrueVisionStatements__Api__.py'],
  vv=[NEW('WCP/Server__ValeVisionPublished__Api__.py'), NEW('WCP/Server__ValeVisionStatements__Api__.py'), SERVER, GITIGNORE, NEW(GITATTR),
      NEW(TESTDIR + 'Na__Test__PublishedApi__.test.py'), NEW(TESTDIR + 'Na__Test__StatementServer__.py')],
  hot=[SERVER, GITIGNORE],
  deps=['W0-18'],
  gated=['DR-22', 'DR-10', 'DR-29', 'DR-37'],
  size='M', est=1200, est_note='TV APIs 448 + 451 lines rebased on the shared helper + tests',
  adapt=['Routes /api/valevision/published/{file,list,archive,prune} and /api/valevision/statements/{tree,file,image,folder,move,delete} (K2 R5); roots .../06__Layout__PublishedDocuments/ (00__Archive__Revisions local only) and .../10__StatementDocs/; nothing reads through serve_static; missing files answer 404 JSON.',
         '.gitignore: 00__Archive__Revisions/ and, unless Adam chooses otherwise, published rasters and PDFs (DR-29); .gitattributes eol=lf for md/html/json under 10__StatementDocs (DR-37 item 1).',
         'Under DR-27 no per-document client (Na__AppUtils__R2StatementDocs__ / R2PublishedDocs__) is created: the W0-12 facade serves both.'],
  acc=['Na__Test__PublishedApi__ (VV pattern from Na__Test__ScrapbookApi__): writes refused into 00__Archive__Revisions; archive zips a document folder without overwriting an older zip; prune touches one document only; GET file answers a real 404 for a missing manifest; ".." / archive segment / bad extension / seventh segment return 400.',
       'Adapted Na__Test__StatementServer__.py imports the VV blueprint against a temp Projects root, answers /api/check-localhost and /api/editor-config with a fake key, blocks worker writes, and proves fencing (.., absolute, symlink, depth, bad segment, wrong suffix), size caps, never-overwrite of a picture (__02), delete refused without confirm, 404 JSON for a missing file.',
       'git check-ignore: a .png under a statement folder is ignored and the .md is not; git ls-files --eol shows w/lf for a statement after checkout.'],
  tests=['Na__Test__PublishedApi__.test.py (VV-only, new)', 'Na__Test__StatementServer__.py (adapted)'],
  src=['WP-S12-12', 'WP-S08-05', 'WP-S12-13', 'WP-S07b-03'],
  risk='Large files (PDF, print tiers): keep TV\'s size caps. Statements blueprint is scaffolding; the feature stays behind LayoutEditor__Statement__Enabled (DR-10).',
  notes=['WP-S08-05 and WP-S07b-03 worker halves are in W0-10 (families F-PUB, F-STMT).'])

P('W0-99', 'W0', 'Parity Scribe pass for Wave 0',
  'Run the S11 B10 procedure for W0: fresh devlog read, version allocation per W0-01, devlog entries from the Port Records (renumber, transport, config, service worker), ledger "Folder renumbering" and "Transport (DIV-4)" sections, Module Register rows, the SHARED SERVICE WORKER decision for the wave, harness counts.',
  vv=[DEVLOG, LEDGER],
  hot=[DEVLOG, LEDGER],
  deps=[],  # filled by the builder: every W0 package
  gated=['DR-35', 'DR-34'],
  size='S', est=400,
  acc=['Every W0 Port Record has a devlog entry ("## ValeVision3D v2.N.x - DD-Mon-YYYY - Title", step per W0-01) and Module Register rows; zero {{VVREL tokens left (G4).',
       'Ledger "Transport (DIV-4)" section: facade name map, worker 1.6.0 routes and deploy state (version reported by /api/editor/health or "not deployed"), Flask routes and blueprints, editor-owned key list (WP-S12-17).',
       'Harness counts in the devlog entry match a fresh run (G1/G2).'],
  src=['WP-S11-04', 'WP-S12-17'],
  risk='Must never run concurrently with another writer of the two documents.',
  notes=['WP-S11-04 is the recurring procedure: W1-99..W5-99 and W6-04 are its later instances.'])
