from k3_common import *

# =============================================================================
# W3 - FEATURES: the SheetTools hub (two sub-waves around the Sheet Images
# editing set), the gesture switch-on, feature activation (drafting aids,
# vector tools, Sheet Images, Floor Areas, note regions), rotation, panels
# to TV, the parametric panel and the PdfExporter re-sync.
# Every W3 package starts after W2-99.
# =============================================================================

T30 = lambda f: TLE('30__System__SheetTools/' + f)
V30 = lambda f: VLE('30__System__SheetTools/' + f)
T54 = lambda f: TLE('54__Feature__SheetImages/' + f)
V54 = lambda f: VLE('54__Feature__SheetImages/' + f)

P('W3-01', 'W3', 'SheetTools hub sub-wave A: SheetTools__State 1.8.0 and ToolState 1.7.0',
  'Take the two hub units whose exports are supersets of VV\'s (State 1.8.0: MoveRetype, LastPress, TOOL_REGION ...; ToolState 1.7.0 + v2.152.0 + v2.90.0 hatch defaults: PickUpMove, IsMoveAuto, atScale no longer hard-coded) ahead of the rest of the hub, so the Sheet Images editing set can link before the atomic sub-wave B.',
  tv=[T30('Na__LayoutEditor__SheetTools__State__.js'), T30('Na__LayoutEditor__SheetTools__ToolState__.js')],
  vv=[ST_STATE, ST_TOOL],
  hot=[ST_STATE, ST_TOOL],
  deps=['W2-99'],
  gated=['DR-01', 'DR-05', 'DR-40'],
  size='S', est=310,
  adapt=['Verbatim; banners and PORT NOTEs only (S05a-F55 amendment: "State 1.8.0 + ToolState 1.7.0 land first as a sub-wave").'],
  acc=['G1/G2 pass with VV\'s older HitResolution/PointerPress/PointerDrag/Keyboard still in place (supersets: the only VV export TV drops in the slice is HitResolution\'s SnapShapeTranslation, untouched here).',
       'Existing tools still arm from the toolbar and keys; nothing visible changes.'],
  tests=[],
  src=[],
  split=['WP-S05a-08R'],
  risk='Low; it exists to break the hub <-> Sheet Images link cycle (S05a-V01).')

P('W3-02', 'W3', 'Sheet Images editing set (inert): Crop, Menu, Insert, Handles, Panel and the core',
  'Port the editing modules of LE/54__Feature__SheetImages verbatim (the core adapted for the document code) over the W3-18 storage units, so the hub\'s static imports (Crop, Menu) and the toolbar\'s (Insert) resolve; activation (ModeController, loader stylesheet line) is W3-09.',
  tv=[T54('Na__LayoutEditor__SheetImages__Crop__.js'), T54('Na__LayoutEditor__SheetImages__Menu__.js'), T54('Na__LayoutEditor__SheetImages__Insert__.js'),
      T54('Na__LayoutEditor__SheetImages__Handles__.js'), T54('Na__LayoutEditor__Panel__SheetImages__.js'), T54('Na__LayoutEditor__SheetImages__.js')],
  vv=[NEW(V54('Na__LayoutEditor__SheetImages__Crop__.js')), NEW(V54('Na__LayoutEditor__SheetImages__Menu__.js')), NEW(V54('Na__LayoutEditor__SheetImages__Insert__.js')),
      NEW(V54('Na__LayoutEditor__SheetImages__Handles__.js')), NEW(V54('Na__LayoutEditor__Panel__SheetImages__.js')), NEW(V54('Na__LayoutEditor__SheetImages__.js'))],
  hot=[],
  deps=['W3-01', 'W3-18'],
  gated=['DR-01', 'DR-13', 'DR-29', 'DR-06'],
  size='M', est=1790, est_note='TV 525 + 118 + 382 + 259 + 309 + 196 lines',
  adapt=['Pictures filed under the document code (W1-12), never the ?project= token (S07a-V01); Insert, Menu and Crop import each other and the hub\'s PickUpMove (W3-01), so the six land as one set.',
         'R2 writes only after Adam has run the W0-07 sync fix (R8).'],
  acc=['G2 passes with the set present (imports resolve: ToolState SetTool/PickUpMove, EditScope WithAdoption, Grips RegisterShapeProvider, ObjectSnap Search, ContextMenu leaf, the W1-16 render leaves).',
       'Nothing imports the set until W3-03/W3-09; the editor behaves as before.'],
  tests=[],
  src=['WP-S07a-07'],
  risk='Blocked until 28 ObjectSnap, ToolState PickUpMove, EditScope WithAdoption and Grips RegisterShapeProvider exist (S07a-F50) - all landed by W2/W3-01.')

P('W3-03', 'W3', 'SheetTools hub sub-wave B (atomic): HitResolution 1.11.0, PointerPress 1.10.0, PointerDrag 1.19.0, Keyboard 1.18.0, SheetTools 1.39.0, ContextMenu 1.7.0, CopyDrag 1.2.0',
  'Take the rest of the SheetTools hub whole in one commit (the units cross-import each other\'s new exports), with AxisLock and ContentEditing header syncs and MarginGrip\'s IsMoveAuto line; Sheet Images, region, area, vector, drafting-aid, door and model rows link to modules already landed. Until Adam confirms DR-40 items 7-10 the four gestures land held behind recorded one-line guards.',
  tv=[T30('Na__LayoutEditor__SheetTools__HitResolution__.js'), T30('Na__LayoutEditor__SheetTools__PointerPress__.js'), T30('Na__LayoutEditor__SheetTools__PointerDrag__.js'),
      T30('Na__LayoutEditor__SheetTools__Keyboard__.js'), T30('Na__LayoutEditor__SheetTools__.js'), T30('Na__LayoutEditor__SheetTools__ContextMenu__.js'),
      T30('Na__LayoutEditor__SheetTools__CopyDrag__.js'), T30('Na__LayoutEditor__AxisLock__.js'), T30('Na__LayoutEditor__SheetTools__ContentEditing__.js')],
  vv=[ST_HIT, ST_PRESS, ST_DRAG, ST_KEY, ST_MAIN, ST_CTX, NEW(V30('Na__LayoutEditor__SheetTools__CopyDrag__.js')),
      V30('Na__LayoutEditor__AxisLock__.js'), V30('Na__LayoutEditor__SheetTools__ContentEditing__.js'), MARGRIP,
      NEW(TESTDIR + 'Na__Test__MoveRetype__.test.mjs'), NEW(TESTDIR + 'Na__Test__CopyDrag__.test.cjs'), NEW(TESTDIR + 'Na__Test__CrossSheetClipboard__.test.cjs'),
      NEW(TESTDIR + 'Na__Test__SetMoveLeaderTips__.test.cjs'), NEW(TESTDIR + 'Na__Test__BubbleNoteTooltip__.test.mjs'), NEW(TESTDIR + 'Na__Test__GroupMoveSnapping__.test.cjs')],
  hot=[ST_HIT, ST_PRESS, ST_DRAG, ST_KEY, ST_MAIN, ST_CTX, MARGRIP, V30('Na__LayoutEditor__AxisLock__.js')],
  deps=['W3-02'],
  gated=['DR-01', 'DR-05', 'DR-13', 'DR-14', 'DR-16', 'DR-18', 'DR-40'],
  size='XL', est=3500, est_note='TV ~5,600 lines in 7 files; ~3,100 diff lines + CopyDrag 494 new; verbatim copies',
  split_justification='Atomic by necessity (S05a-F55): State/ToolState already went first (W3-01); the remaining seven units cross-import each other\'s new exports (HitResolution PicksUpMove/CarryTarget/DoorAt, PointerDrag GetMoveRetype/TypeMoveArray/RerunViewportDrag, PointerPress SettleAutoMove, Keyboard CopyKey), so no partial hub links. The work is mechanical whole-file copying with header re-application, gated by G1/G2 and five ported suites.',
  adapt=['Verbatim; banners and PORT NOTEs only; Snapping imports become 28__System__ObjectSnap imports (already TV\'s); MarginGrip gains || Na__LeTools__IsMoveAuto().',
         'If DR-40 items 7-10 are unconfirmed: one recorded guard per gesture, each a VV-only constant at the entry point and listed in the PORT NOTE - (7) auto-Move pick-up (HitResolution/PointerPress), (8) CopyDrag start (PointerPress/PointerDrag), (9) viewport carry GrabAt (PointerPress), (10) move-anchor Arm (PointerPress); W3-04 removes them. With Adam\'s yes before W3 starts, no guard is written and W3-04 is a no-op.',
         'S05a is the only owner of these files: interim hunks planned elsewhere (WP-S04b-08/09/11R/12, WP-S07a-07 hooks, WP-S10-11 rows) are subsumed (D-S05a-V1).'],
  acc=['G1 walks every LE module (baseline 139+) with 0 failures and G2 passes with a non-zero count; diff against TV HEAD b2aa9151 shows only banners, PORT NOTEs and the recorded gesture guards.',
       'Ported suites pass: Na__Test__MoveRetype__, Na__Test__CopyDrag__ (guarded parts skipped while held), Na__Test__CrossSheetClipboard__, Na__Test__SetMoveLeaderTips__, Na__Test__BubbleNoteTooltip__, Na__Test__GroupMoveSnapping__.',
       'A vector moved whole keeps a held axis (Shift or an arrow) through a snap; a group move snaps one member\'s point and moves every member by the same delta; with Grid Snap on a text item moves by its grab point in whole grid steps; a typed length is exact (no snap, grid or Ortho).',
       'A typed length after the mouse lets go lands the move again; arrow keys lock a viewport frame move; Ctrl+X then Ctrl+V on another sheet lands in place with its layer; right-click Layer moves an item (flyout of layers in list order, holder dotted, mixed selection ringed); a box started over an unlocked viewport takes the vectors on it; a picture\'s rows and double-click crop work.',
       'Resting on a linked bubble for 0.5 s shows "CODE  Note title" beside the pointer (off on press, wheel, key or drag); Escape closes a flyout first, then the menu; the notes-margin handle stays up under an automatic Move (when item 7 is on).',
       'F6-F9, K, A and the vector keys reach their handlers (their features switch on in W3-05/W3-07/W3-10); a plan door toggles on a left click after the double-click window as one undo step.'],
  tests=['Na__Test__MoveRetype__.test.mjs', 'Na__Test__CopyDrag__.test.cjs', 'Na__Test__CrossSheetClipboard__.test.cjs', 'Na__Test__SetMoveLeaderTips__.test.cjs',
         'Na__Test__BubbleNoteTooltip__.test.mjs', 'Na__Test__GroupMoveSnapping__.test.cjs'],
  src=['WP-S05a-08R', 'WP-S04b-08'],
  risk='Largest single landing; any missing module or name fails the editor at link time. One agent, one commit, G1/G2/G6.')

P('W3-04', 'W3', 'Gesture changes switched on (DR-40 items 7-10): auto-Move, Ctrl-drag copy, viewport carry, move anchor',
  'After Adam\'s explicit yes, remove the W3-03 guards so Select picks Move up, Ctrl-drag copies (and arrays), a press on viewport linework carries the viewport onto another drawing\'s point, and Ctrl+click arms a move anchor (after Ctrl-drag copy, so Ctrl means what it means in TV); update the Select/Move tooltips.',
  tv=[T30('Na__LayoutEditor__SheetTools__HitResolution__.js') + ' (unguarded)', T30('Na__LayoutEditor__SheetTools__PointerPress__.js') + ' (unguarded)',
      T30('Na__LayoutEditor__SheetTools__PointerDrag__.js') + ' (unguarded)'],
  vv=[ST_HIT, ST_PRESS, ST_DRAG, NEW(TESTDIR + 'Na__Test__MoveAnchor__.test.mjs')],
  hot=[ST_HIT, ST_PRESS, ST_DRAG],
  deps=['W3-03'],
  gated=['DR-40', 'DR-01'],
  size='S', est=60,
  adapt=['A no-op when DR-40 items 7-10 were confirmed before W3-03 (then W3-03 carries this acceptance).'],
  acc=['Diff of the hub against TV HEAD shows banners and PORT NOTEs only (no guard left).',
       'Select picks Move up for text, vector, leader and group and not for a viewport or dimension; a fast double click on text opens it without nudging; Ctrl-drag copies and 3x arrays.',
       'Hovering a 2D viewport\'s linework under Select shows the purple endpoint marker; pressing there carries the viewport so the point lands exactly on another drawing\'s corner; resting on another viewport\'s point acquires a tracking cross with red level and green plumb guides; with LayoutEditor__Snapping__ViewportCarry false the plain frame move returns; a press on a crop handle, the rotate grip, a locked viewport or one member of a multi-selection never carries; an arrow key holds the carry to an axis; F3 off restores the plain move; one undo step per carry.',
       'Ctrl+click on one item arms the red cross in the middle of its box and picks up Move; Ctrl+click added to another selection, a plain click and a Ctrl-drag copy do not; dragging the cross snaps it (object snap, its own box, the grid); a double click recentres it; dragging the item lands the cross exactly on the snap in one undo step; arming writes nothing.',
       'Na__Test__MoveAnchor__ passes; Na__Test__CopyDrag__ passes in full.'],
  tests=['Na__Test__MoveAnchor__.test.mjs', 'Na__Test__CopyDrag__.test.cjs (full)'],
  src=[],
  split=['WP-S05a-08R', 'WP-S04b-11R', 'WP-S04b-12'],
  risk='Changes mouse gestures Vale authors already use: only on Adam\'s explicit yes (DR-01, DR-40); never blocks another package.')

P('W3-05', 'W3', 'Drafting aids switched on: Drawing Grid panel and attach, Drawing Axes attach, Ortho and Draft live',
  'Wire the drafting aids into the ModeController at TV\'s positions (grid panel registered after Sheet; Grid and Axes Attach/Detach with the tools) now that the hub\'s Keyboard 1.18.0 carries the F6/F7/F8/F9/K cases and the key rows exist; the toolbar buttons arrive with W5-01.',
  tv=[TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (grid panel registration, Grid/Axes Attach/Detach)'],
  vv=[MC, NEW(TESTDIR + 'Na__Test__OrthoMode__.test.mjs'), NEW(TESTDIR + 'Na__Test__DrawingGrid__.test.mjs'), NEW(TESTDIR + 'Na__Test__DrawingAxes__.test.mjs')],
  hot=[MC],
  deps=['W3-03'],
  gated=['DR-01', 'DR-40'],
  size='S', est=120,
  acc=['F3, F6, F7, F8, F9 and K each switch once per press: not on repeat, not from a text box, yes from a focused panel checkbox; the browser\'s own F6/F7/F9 are taken; the echo line shows <Osnap on>, <Ortho on>, <Grid on>, <Grid snap on>, <Drawing axes on>.',
       'K draws one-device-pixel hairlines in their own colours with no dashes or fills and hides rasters; changing the raster level in Draft books 0 renders; K off shows the held pictures at once then exactly one render where stale; the PDF export is byte-for-byte as before.',
       'F6 draws 1 mm points crisp at zooms 0.5x-6x with heavier 10 mm points; F7 snaps the Draw tool to the nearest grid point; panel changes redraw at once; "Draw grid on top" off puts the canvas under the drawings; nothing appears in the PDF.',
       'Drawing axes run edge to edge in whole device pixels at any zoom, cross on the snap marker when one shows, and hide over panels and for touch.',
       'Na__Test__OrthoMode__, Na__Test__DrawingGrid__ and Na__Test__DrawingAxes__ pass in full.'],
  tests=['Na__Test__OrthoMode__.test.mjs', 'Na__Test__DrawingGrid__.test.mjs', 'Na__Test__DrawingAxes__.test.mjs'],
  src=['WP-S04b-09'],
  risk='Low once the hub has landed; the Snapping__ deletion of WP-S04b-09 is W3-08.')

P('W3-06', 'W3', 'Rotatable viewports: ViewportHandles 1.5.0, Viewport3dZoom 1.1.0, ViewportClipboard 1.4.0',
  'Take the three viewport units whole now that the hub (rotate hit first, RotateStart, RotateTo, Shift steps), the converged Window/Viewport2d (turned frames), SheetChrome, Groups and the rotate config exist, so the rotate grip appears only with its wiring.',
  tv=[TLE('20__System__Viewports/Na__LayoutEditor__ViewportHandles__.js'), TLE('20__System__Viewports/Na__LayoutEditor__Viewport3dZoom__.js'), TLE('20__System__Viewports/Na__LayoutEditor__ViewportClipboard__.js')],
  vv=[VLE('20__System__Viewports/Na__LayoutEditor__ViewportHandles__.js'), VLE('20__System__Viewports/Na__LayoutEditor__Viewport3dZoom__.js'), VLE('20__System__Viewports/Na__LayoutEditor__ViewportClipboard__.js'),
      TESTDIR + 'Na__Test__ViewportRotation__.test.mjs'],
  hot=[],
  deps=['W3-03'],
  gated=['DR-01', 'DR-40'],
  size='S', est=340,
  acc=['Shift lands 0, 90, 180 and -90 (never -180); without Shift the turn settles on a right angle within 2 degrees; cropping a 30-degree frame keeps the opposite edge within 0.01 mm; level viewports save byte-identical (no Viewport__RotationDeg key).',
       'The PDF draws a turned viewport (frame line, caption and linework) and a level frame writes no cm operator (with W3-16); the context menu offers Rotate 90 cw/ccw and Reset rotation.',
       'Na__Test__ViewportRotation__ passes in full.'],
  tests=['Na__Test__ViewportRotation__.test.mjs (full)'],
  src=['WP-S04a-03R'],
  risk='Low now; the S04a verifier\'s hot-file list collapses because every other rotation consumer was taken whole earlier.')

P('W3-07', 'W3', 'Vector tools and Booleans switched on: ShapeTool 1.10.0 and the ModeController wiring',
  'Take ShapeTool 1.10.0 whole and register the Vector Tools panel straight after Vectors and Na__LeVec__Initialize after the history; the hub already carries the dispatch, keys and holes-aware edits; Circle/Arc toolbar buttons come with W5-01.',
  tv=[TLE('35__System__DrawingTools/Na__LayoutEditor__ShapeTool__.js'), TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (vector tools hunks)'],
  vv=[VLE('35__System__DrawingTools/Na__LayoutEditor__ShapeTool__.js'), MC, AC,
      NEW(TESTDIR + 'Na__Test__VectorTools__.test.mjs'), NEW(TESTDIR + 'Na__Test__VectorBooleans__.test.mjs')],
  hot=[MC, AC],
  deps=['W3-05'],
  gated=['DR-01', 'DR-18', 'DR-37'],
  size='S', est=200,
  adapt=['AccordionSections gains the vector-tools section at TV\'s position.'],
  acc=['TV PLAN__VectorTools section 7 script passes with writes blocked: C + two clicks + 750 Enter; 6s hexagon; four arc modes.',
       'T on the sheet is Text; inside a group T is Trim and the group stays open; Shift+T Extend; a three-line fence undoes in one Ctrl+Z; three wall rectangles Shift+U into one outline; Subtract cuts a hole; Shift+O fills it; a capital U typed in a text box leaves shapes alone.',
       'Inserting a point on a holed outline keeps the hole; deleting two of its corners removes it; a click in a hole selects what is under it; right-clicking a plain vector shows "Vector tools >" opening a flyout.',
       'Na__Test__VectorTools__ 138/138 and Na__Test__VectorBooleans__ 148/148 against VV files.'],
  tests=['Na__Test__VectorTools__.test.mjs', 'Na__Test__VectorBooleans__.test.mjs'],
  src=['WP-S05b-V4'],
  risk='Coordination risk removed: the five cross-slice packages of the old plan are now W3-03 (hub) plus this package.')

P('W3-08', 'W3', 'Retire VV\'s Snapping__.js (K2 FR-15)',
  'Delete the W2-19 shim once the hub, the drawing tools and ShapeTool no longer import it.',
  tv=[],
  vv=[SNAPPING + ' (deleted)'],
  hot=[SNAPPING],
  deps=['W3-07'],
  gated=['DR-05'],
  size='S', est=10,
  acc=['grep -r "Na__LayoutEditor__Snapping__\\|Na__LeOsnap__TONE_" 02__Src__AppModules returns nothing; G1/G2 pass.'],
  tests=[],
  src=['WP-S05a-10'],
  risk='Low.')

P('W3-09', 'W3', 'Sheet Images switched on: ModeController wiring, the Images panel and the loader stylesheet line',
  'Wire Sheet Images at TV\'s positions (Na__LeImg__Ready, Initialize, AttachInput/DetachInput, Images panel after Vector Tools), add its stylesheet to Na__LeLoad__STYLESHEETS before WebViewer and "images" to AccordionSections.',
  tv=[TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (images hunks)'],
  vv=[MC, LDR, AC, NEW(TESTDIR + 'Na__Test__SheetImages__.test.mjs')],
  hot=[MC, LDR, AC],
  deps=['W3-07'],
  gated=['DR-01', 'DR-13', 'DR-06', 'DR-29'],
  size='S', est=120,
  acc=['Na__Test__SheetImages__ (90 checks) passes; a 14 MB PNG dropped on a sheet shows at once and nothing is written.',
       'Save Sheets cuts it to 300 dpi for its placed size and files it under the sheet\'s Document ID on disk and R2 before the drawings, then archives what nothing uses (only after Adam ran W0-07, R8); a register renumber moves the picture on the next save (W4-10).',
       'The read-only web build reads the picture from R2, then GitHub Pages; Download PDF prints a 300 dpi JPEG with the shadow PNG and the 1.5 pt rule (with W3-16).',
       'Na__Test__LoaderStylesheets__ passes with SheetImages before WebViewer.'],
  tests=['Na__Test__SheetImages__.test.mjs'],
  src=[],
  split=['WP-S07a-07'],
  risk='Low once W3-02/W3-03 exist.')

P('W3-10', 'W3', 'Floor Areas switched on',
  'Port Panel__FloorAreas 1.2.1, FloorAreas__Table 1.1.0, FloorAreas__LabelGrip 1.0.0 and Styles__FloorAreas (self-linked) verbatim and wire the ModeController (panel last in the right column, Na__LeArea__Ready, Na__LeAreaTable__Attach, "areas" routed to floor-areas, an area selection opening the section) with "floor-areas" in AccordionSections.',
  tv=[TLE('59__Feature__FloorAreas/Na__LayoutEditor__Panel__FloorAreas__.js'), TLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Table__.js'),
      TLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__LabelGrip__.js'), TLE('59__Feature__FloorAreas/Na__LayoutEditor__Styles__FloorAreas__.css'),
      TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (floor areas hunks)'],
  vv=[NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__Panel__FloorAreas__.js')), NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__Table__.js')),
      NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__FloorAreas__LabelGrip__.js')), NEW(VLE('59__Feature__FloorAreas/Na__LayoutEditor__Styles__FloorAreas__.css')),
      MC, AC],
  hot=[MC, AC],
  deps=['W3-09'],
  gated=['DR-01', 'DR-14'],
  size='M', est=1990, est_note='1,905 verbatim lines in 4 new files + ModeController hunks at TV\'s lines (:553, :1003, :1028, :1059, :1193, :1208)',
  acc=['Na__Test__FloorAreas__ re-run passes on VV; every sheet saved before the port loads and saves byte-identical.',
       'A room reports at the scale of the drawing under it with nothing stored; hiding the Viewports layer does not change an area; "areas" edits are single undo steps with correct redo; schedules follow without dirtying idle sheets.',
       'Paste keeps a room on the Floor Areas layer; a Custom Scrapbook item drops Area__Group and Area__ScaleDenominator; the Floor Areas panel is the last right-column section, folds with the others and links its own stylesheet; A arms the Area tool (W5-01 adds the button).',
       ],
  tests=['Na__Test__FloorAreas__.test.mjs (re-run)'],
  src=['WP-S06b-10b'],
  risk='The intended look (a room tint under the linework) needs the W1-28 paint order - already in.')

P('W3-11', 'W3', 'Overspill note regions UI: region grips, the regions panel and Margin Notes panel 1.2.0',
  'Port NoteRegions__Grips 1.0.0, Panel__MarginNotes__Regions 1.0.0 and Panel__MarginNotes 1.2.0 (registers the Regions and Leaderless sub-panels) verbatim and attach the region grips beside the margin grip in the ModeController (TV :576-584).',
  tv=[TLE('50__Feature__Specification/Na__LayoutEditor__NoteRegions__Grips__.js'), TLE('50__Feature__Specification/Na__LayoutEditor__Panel__MarginNotes__Regions__.js'),
      TLE('50__Feature__Specification/Na__LayoutEditor__Panel__MarginNotes__.js'), TLE('05__Core__ModeController/Na__LayoutEditor__ModeController__.js') + ' (region grip hunks)'],
  vv=[NEW(VLE('50__Feature__Specification/Na__LayoutEditor__NoteRegions__Grips__.js')), NEW(VLE('50__Feature__Specification/Na__LayoutEditor__Panel__MarginNotes__Regions__.js')),
      VLE('50__Feature__Specification/Na__LayoutEditor__Panel__MarginNotes__.js'), MC],
  hot=[MC],
  deps=['W3-10'],
  gated=['DR-01', 'DR-40'],
  size='M', est=1150,
  acc=['Add region arms the tool; a dragged, clicked or typed box becomes a region, Select returns and the new fold opens; a box is never under RegionMinSizeMm and stays on the paper.',
       'Grips snap (object snap, Grid Snap, perpendicular to the margin divider), Shift/Ortho hold an axis, one undo step per drag, Escape restores; hovering a fold highlights its region; Delete is undoable; the Leaderless Notes section appears in the Margin Notes panel.',
       'Na__Test__ObjectSnap__ region checks pass; G1/G2 pass.'],
  tests=['Na__Test__ObjectSnap__.test.mjs (re-run with region checks)'],
  src=['WP-S06b-07b'],
  risk='Never adapt the grips onto VV\'s Snapping__ shim (W3-08 retires it).')

P('W3-12', 'W3', 'Dimensions and Vectors panels to TV (Panel__Dimensions 1.7.0, Panel__Shapes 1.9.0)',
  'Take both panels whole now that ToolState stores Dimension__AtScale, the dimension records carry extension/RoundUp/LinePt/LineStyle, DimensionRounding and SheetDimensionPt exist, LineStyleTool takes the "dim" prefix and Shape__Hatch exists.',
  tv=[TLE('40__Ui__Panels/Na__LayoutEditor__Panel__Dimensions__.js'), TLE('40__Ui__Panels/Na__LayoutEditor__Panel__Shapes__.js')],
  vv=[VLE('40__Ui__Panels/Na__LayoutEditor__Panel__Dimensions__.js'), P_SHAPES, NEW(TESTDIR + 'Na__Test__HatchLineControls__.test.mjs')],
  hot=[P_SHAPES],
  deps=['W3-03'],
  gated=['DR-01', 'DR-19'],
  size='M', est=610,
  acc=['With Measure at scale unticked a dimension reads paper mm and the Measures line says so; the Ext. lines padlock links Start and End; open, each keeps its own length; Round up shows 1205* for a 1201 mm dimension; an empty Line pt field means the sheet\'s Dimension pt; ticking Hatch on a closed vector picks Brickwork first.',
       'Na__Test__HatchLineControls__ and Na__Test__DimensionRoundUp__ pass.'],
  tests=['Na__Test__HatchLineControls__.test.mjs', 'Na__Test__DimensionRoundUp__.test.mjs (re-run)'],
  src=['WP-S06a-07'],
  risk='Thin panels; the record and geometry changes are already in.')

P('W3-13', 'W3', 'Layers panel 1.3.0 with the Ref switch, and ViewportLink 1.5.1',
  'Take Panel__Layers 1.3.0 whole (reference layers: drawn and printed but not picked, boxed or snapped to) and ViewportLink 1.5.1 (Nearest skips reference layers; rotation leaf).',
  tv=[TLE('40__Ui__Panels/Na__LayoutEditor__Panel__Layers__.js'), TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__ViewportLink__.js')],
  vv=[P_LAYERS, VPLINK],
  hot=[P_LAYERS, VPLINK],
  deps=['W3-03'],
  gated=['DR-01', 'DR-17'],
  size='S', est=210,
  acc=['With Ref on, a layer\'s items are drawn and printed but cannot be picked, boxed or snapped to; the Ref button shows the shared faint red; a scale bar dropped beside a viewport on a Ref layer does not bind to it.',
       'Na__Test__LayerMenu__ and Na__Test__LayerStack__ re-run pass.'],
  tests=['Na__Test__LayerMenu__.test.mjs (re-run)', 'Na__Test__LayerStack__.test.mjs (re-run)'],
  src=['WP-S06a-09'],
  risk='Only meaningful with hit testing (W3-03) and snapping (W2-19) honouring reference layers - both in.')

P('W3-14', 'W3', 'Parametric Scrapbook panel 1.8.0 and config to TV (all element types registered)',
  'Take Panel__ScrapbookParametric 1.8.0 whole now that every type it imports exists (AreaSchedule, CabinetInfill, ProjectQr element off, SiteLegend/Link dormant, PdfFonts, ProjectLink, the facade), re-apply the project display-name accessor, and take the config whole with VV values (QR off, Standard Scrapbook empty, Custom not seeded).',
  tv=[TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__Panel__ScrapbookParametric__.js'), TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__Config__.json')],
  vv=[PARAMPNL, PARAMCFG],
  hot=[PARAMPNL, PARAMCFG],
  deps=['W3-10', 'W3-13', 'W3-17'],
  gated=['DR-01', 'DR-12', 'DR-08', 'DR-42', 'DR-43'],
  size='M', est=1300,
  adapt=['One seam: window.TrueVision__Pwa__ProjectContext (TV :290) -> Na__CfApi__GetProjectDisplayName() (W0-12); Na__CfApi__GetLoadedProjectData resolves to VV\'s facade (S11-V02 row 217).',
         'If Adam excludes site plans or the QR element (DR-08/DR-12), the panel stays port_adapted with VV\'s type set as WP-S06a-05v describes, recorded under DR-42 (5).',
         'VV wording kept for phase, site-plan and three-scales values; ProjectQr block present with its switch off; metricsReady waits on PdfFonts (every title refits once more - recorded).'],
  acc=['The Scrapbook tab shows 5+ tiles incl. Cabinet Infill (QR and Site Legend tiles hidden while their features are off/dormant); the Cabinet Infill drops by its bottom-left base onto a snapped corner; each corner grip holds its opposite corner; a fill recoloured inside the group survives a corner drag.',
       'The Project Floor Areas form totals every group across sheets; an Area Schedule tile drops a live schedule.',
       'Diff against TV shows only the display-name seam and config values; G1/G2 pass.'],
  tests=[],
  src=[],
  split=['WP-S06a-05v', 'WP-S06a-13'],
  risk='1,346-line panel with nine static imports: land last among the scrapbook packages.')

P('W3-15', 'W3', 'Viewport panel to TV 1.10.0 (Frame, Rotation, Doors, Hide swings, adoption)',
  'Take Panel__ViewportSettings 1.10.0 whole (no folder-number seams after W0-02), re-apply VV\'s 1.4.1 Add Viewport list rebuild, and bring Frame, Rotation, WithAdoption, Doors and Hide swings rows live; Model Source and site-plan rows stay hidden as TV hides them.',
  tv=[TLE('40__Ui__Panels/Na__LayoutEditor__Panel__ViewportSettings__.js')],
  vv=[P_VPSET],
  hot=[P_VPSET],
  deps=['W3-06'],
  gated=['DR-01', 'DR-16', 'DR-09', 'DR-08'],
  size='M', est=600,
  adapt=['VV 1.4.1 seam (:308-313): the Add Viewport list rebuilt on every refresh, keeping the choice in progress (offered back to TV, WT-04).'],
  acc=['Unticking Frame hides the frame and caption on screen and in the PDF; Caption greys out; Rotation +90 turns the viewport about its middle in one undo step; a viewport added while a group is open joins that group.',
       'A plan added in Dev Tools appears in Add Viewport without a reload (the VV fix is kept); the Doors and Hide swings rows work on 3047__Doous; G1/G2 pass.'],
  tests=['Na__Test__HideSwings__.test.mjs (re-run)'],
  src=['WP-S06a-08v'],
  risk='Losing VV\'s 1.4.1 hunk would bring back a fixed bug.')

P('W3-16', 'W3', 'PdfExporter full re-sync to TV 1.12.0',
  'Take PdfExporter 1.12.0 whole once every export it calls exists (paint plan, layer primitives, viewport frames, rings, hatches, picture PDF prep, rotation, fog, site-plan drawings, Model Source, floor areas, margin regions overflow) and re-apply only the VV seams.',
  tv=[TLE('60__Feature__PdfExport/Na__LayoutEditor__PdfExporter__.js')],
  vv=[PDFX],
  hot=[PDFX],
  deps=['W3-09', 'W3-06'],
  gated=['DR-01', 'DR-21', 'DR-11'],
  size='M', est=400,
  adapt=['Seams: console prefix, subject string, PDF file names on the document code (W1-12), never the ?project= token.'],
  acc=['The diff against TV is header and listed seams only; G2 passes.',
       'The PDF prints in Layers-list order with each frame over its viewport; turned viewports, pictures, note regions, fog (PNG with soft mask between vectors and markup) and site plans (where present) print as the screen shows; the PDF toast counts notes that fit nowhere whatever the margin switch.'],
  tests=[],
  src=['WP-S08-14'],
  risk='Landing it early breaks module linking - it is last among the PDF consumers.')

P('W3-17', 'W3', 'Area Schedule parametric element (registered by the W3-14 panel)',
  'Take the 57 AreaSchedule element 1.1.0 (new, pure: it imports nothing) verbatim with its test; the config AreaSchedule block, its three elements and the panel registration arrive with the parametric panel and config (W3-14); the Custom Scrapbook portability hunk already landed with W2-36.',
  tv=[TLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__AreaSchedule__.js')],
  vv=[NEW(VLE('57__Feature__ScrapbookParametric/Na__LayoutEditor__ScrapbookParametric__AreaSchedule__.js')), NEW(TESTDIR + 'Na__Test__AreaSchedule__.test.mjs')],
  hot=[],
  deps=['W3-10'],
  gated=['DR-01', 'DR-14'],
  size='M', est=700, est_note='TV 668 lines verbatim + test',
  acc=['Na__Test__AreaSchedule__ passes on VV; G2 passes.',
       'After W3-14: an Area Schedule dropped on a sheet with measured rooms lists them by group with subtotals and a total; renaming a room rewrites one text record; the Project Floor Areas form totals every group across sheets.'],
  tests=['Na__Test__AreaSchedule__.test.mjs'],
  src=['WP-S06a-13'],
  risk='Meaningless without Floor Areas\' data hook (W3-10, landed first).')

P('W3-18', 'W3', 'Sheet Images storage and publish units and the stylesheet (inert)',
  'Port Store and Publish onto the VV facade and DR-29 folders and copy the Sheet Images stylesheet; they import only ProjectLoader, ProjectData, the facade, SheetRecords and the W1-16 render leaves (Encode, Geometry, Setup, Source), so they land inert before the editing set.',
  tv=[T54('Na__LayoutEditor__SheetImages__Store__.js'), T54('Na__LayoutEditor__SheetImages__Publish__.js'), T54('Na__LayoutEditor__Styles__SheetImages__.css')],
  vv=[NEW(V54('Na__LayoutEditor__SheetImages__Store__.js')), NEW(V54('Na__LayoutEditor__SheetImages__Publish__.js')), NEW(V54('Na__LayoutEditor__Styles__SheetImages__.css'))],
  hot=[],
  deps=['W2-99'],
  gated=['DR-01', 'DR-13', 'DR-29', 'DR-06'],
  size='M', est=910, est_note='TV 208 + 464 + 236 lines',
  adapt=['Store and Publish over the facade (SheetImageLocation, ListSheetImages, UploadSheetImage, CopySheetImage, DeleteSheetImage, IsConfigured); folder 05__Layout__DrawingDocs__Images under VaApps/Projects/{folderId}/ (DR-29).',
         'R2 writes only after Adam has run the W0-07 sync fix (R8).'],
  acc=['G2 passes with the three files present and unimported; no window.TrueVision__ read and no TV key builder (G4/G6).'],
  tests=[],
  src=[],
  split=['WP-S07a-07'],
  risk='Low while inert; the picture writes go live with W3-09.')

P('W3-99', 'W3', 'Parity Scribe pass for Wave 3',
  'S11 B10 procedure for W3, including the S04b, S05a, S05b, S06a and S06b ledger work (return-trip sections per TV release, subfolder rows 1120-1136 incl. 28/36/37, rows 75-76 closed, row 1165 superseded, the stale harness claim at 44-49, VV per-file logs, Phase 5 rows 1069-1072, permanent divergences ModelLayers/SiteLegend/scrapbook transport, the retrospective 14-Sep specification entry, the "margin" undo row).',
  vv=[DEVLOG, LEDGER],
  hot=[DEVLOG, LEDGER],
  deps=[],
  gated=['DR-35', 'DR-34', 'DR-40'],
  size='S', est=700,
  acc=['Every W3 Port Record has its devlog entry naming the behaviour changes (DR-40 items 1-6 adopted; items 7-10 stated as held or switched on); zero {{VVREL tokens; SHARED SERVICE WORKER decision recorded; harness counts from a fresh run.',
       'Rows from WP-S04b-15, WP-S05a-11, WP-S05b-11, WP-S06a-12 and WP-S06b-13 (VV halves) written; their TV notes queued for WT-08.'],
  src=['WP-S04b-15', 'WP-S05a-11', 'WP-S05b-11', 'WP-S06a-12', 'WP-S06b-13'],
  risk='Single writer of the two documents.')
