# R4 helper: declaration-by-declaration comparison of the CSS regions that make the Layout Editor's
# top-bar fold, veils, tab strip, 3D-furniture hiding block and editor host, TV against VV.
# Read-only on both apps. Writes report/tools/r4_fold_tables.md (markdown tables) and prints a summary.
#
# Usage: python r4_fold_diff.py
import os, re

TV = r"D:/11_RefLib__StudioRepository__RemoteSystem/NaWeb/na-apps/30__TrueVision__CoreAppCode"
VV = r"D:/10_CoreLib__ValeCodebase/WebApps/ValeVision3D"
LE = "02__Src__AppModules/51__System__LayoutEditor"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "r4_fold_tables.md")

# (label, tv file, tv line range, vv file, vv line range)
REGIONS = [
    ("Header base rule", "03__Style__AppStylesheets/Na__UiFeature__Styles__AppHeader__.css", (40, 58),
                         "03__Style__AppStylesheets/Na__UiFeature__Styles__AppHeader__.css", (40, 58)),
    ("Narrow screen (<=600px)", "03__Style__AppStylesheets/Na__UiFeature__Styles__AppHeader__.css", (125, 164),
                                "03__Style__AppStylesheets/Na__UiFeature__Styles__AppHeader__.css", (125, 164)),
    ("Fold region", "03__Style__AppStylesheets/Na__UiFeature__Styles__AppHeader__.css", (167, 310),
                    "03__Style__AppStylesheets/Na__UiFeature__Styles__AppHeader__.css", (166, 265)),
    ("3D-furniture hiding block", LE + "/10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__.css", (20, 59),
                                  LE + "/10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__.css", (20, 58)),
    ("Tab strip region", LE + "/10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__.css", (62, 262),
                         LE + "/01__Core__Loader/Na__LayoutEditor__Styles__Boot__.css", (18, 193)),
    ("Editor host", LE + "/10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__.css", (265, 283),
                    LE + "/10__Core__SheetSurface/Na__LayoutEditor__Styles__Main__.css", (61, 79)),
    ("Loading veil region", "03__Style__AppStylesheets/Na__UiFeature__Styles__LoadingOverlays__.css", (253, 339),
                            "03__Style__AppStylesheets/Na__UiFeature__Styles__LoadingOverlays__.css", (266, 344)),
]


def strip_comments_keep_lines(text):
    # Replace comments with spaces, keeping newlines so line numbers survive.
    def repl(m):
        return re.sub(r"[^\n]", " ", m.group(0))
    return re.sub(r"/\*.*?\*/", repl, text, flags=re.S)


def parse(path, lo, hi):
    raw = open(path, encoding="utf-8", errors="replace").read()
    text = strip_comments_keep_lines(raw)
    lines = text.split("\n")
    # Walk characters, tracking line numbers, block stack and selectors.
    decls = []
    stack = []          # list of selector/at-rule strings
    buf = ""
    buf_line = None
    line_no = 1
    for ch in text:
        if ch == "\n":
            line_no += 1
            buf += " "
            continue
        if ch == "{":
            sel = re.sub(r"\s+", " ", buf).strip()
            stack.append(sel)
            buf, buf_line = "", None
            continue
        if ch == "}":
            stmt = buf.strip()
            if stmt and ":" in stmt and stack:
                _record(decls, stack, stmt, buf_line or line_no)
            if stack:
                stack.pop()
            buf, buf_line = "", None
            continue
        if ch == ";":
            stmt = buf.strip()
            if stmt and ":" in stmt and stack:
                _record(decls, stack, stmt, buf_line or line_no)
            buf, buf_line = "", None
            continue
        if not ch.isspace() and buf_line is None:
            buf_line = line_no
        buf += ch
    return [d for d in decls if lo <= d[3] <= hi]


def _record(decls, stack, stmt, line):
    prop, _, val = stmt.partition(":")
    sel = " / ".join(s for s in stack)
    decls.append((sel, prop.strip(), re.sub(r"\s+", " ", val.strip()), line))


def main():
    md = ["# R4 fold / veil / strip declaration tables (generated by r4_fold_diff.py)", ""]
    summary = []
    for label, tvf, tvr, vvf, vvr in REGIONS:
        t = parse(os.path.join(TV, tvf), *tvr)
        v = parse(os.path.join(VV, vvf), *vvr)
        tk = {}
        for sel, prop, val, ln in t:
            tk.setdefault((sel, prop), []).append((val, ln))
        vk = {}
        for sel, prop, val, ln in v:
            vk.setdefault((sel, prop), []).append((val, ln))
        keys = []
        for k in [(s, p) for s, p, _, _ in t] + [(s, p) for s, p, _, _ in v]:
            if k not in keys:
                keys.append(k)
        md.append(f"## {label}")
        md.append(f"TV `{tvf}` lines {tvr[0]}-{tvr[1]}; VV `{vvf}` lines {vvr[0]}-{vvr[1]}")
        md.append("")
        md.append("| Selector | Property | TV value (line) | VV value (line) | State |")
        md.append("|---|---|---|---|---|")
        counts = {"same": 0, "differs": 0, "tv-only": 0, "vv-only": 0}
        for k in keys:
            tvals = tk.get(k, [])
            vvals = vk.get(k, [])
            tv_s = "; ".join(f"`{a}` ({b})" for a, b in tvals) or "-"
            vv_s = "; ".join(f"`{a}` ({b})" for a, b in vvals) or "-"
            if tvals and vvals:
                st = "same" if [a for a, _ in tvals] == [a for a, _ in vvals] else "differs"
            elif tvals:
                st = "tv-only"
            else:
                st = "vv-only"
            counts[st] += 1
            md.append(f"| `{k[0]}` | `{k[1]}` | {tv_s} | {vv_s} | {st} |")
        md.append("")
        md.append(f"Counts: {counts}")
        md.append("")
        summary.append((label, counts))
    open(OUT, "w", encoding="utf-8").write("\n".join(md))
    for label, c in summary:
        print(f"{label:28s} {c}")
    print("written", OUT)


if __name__ == "__main__":
    main()
