# W1-13 scratch: lift the RECORD sections of TrueVision's Na__Test__NoteRegions__ and Na__Test__LeaderlessNotes__
# (read at the pin into tv/) out VERBATIM, with the fixture helpers they use, into one generated module that
# record_parity.mjs runs against both trees. Nothing in the lifted lines is edited; each is wrapped in a function
# that receives the modules the test's own preamble would have loaded.
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TV = os.path.join(HERE, 'tv')
OUT = os.path.join(HERE, 'record_checks__generated.mjs')


def lines_of(name):
    with open(os.path.join(TV, name), 'r', encoding='utf-8') as fh:
        return fh.read().split('\n')


def helper(lines, prefix):
    hits = [line for line in lines if line.lstrip().startswith(prefix)]
    if len(hits) != 1:
        raise SystemExit('expected one line starting %r, found %d' % (prefix, len(hits)))
    return hits[0]


def record_region(lines):
    start = next(i for i, line in enumerate(lines) if 'REGION | The Record' in line)
    end = next(i for i in range(start, len(lines)) if lines[i].startswith('// endregion'))
    body = lines[start + 2:end]                                  # <-- After the region's own rule line
    return body


def block(name, func, helpers):
    lines = lines_of(name)
    out = ['export async function ' + func + '(env) {',
           '    const { Records, RegionRec, LeadRec, Setup, check } = env;']
    for prefix in helpers:
        out.append(helper(lines, prefix))
    out.extend(record_region(lines))
    out.append('}')
    return out


def main():
    parts = ['// GENERATED by make_record_checks.py from TrueVision\'s tests read at b2aa9151 - the record sections, verbatim.', '']
    parts += block('Na__Test__NoteRegions__.test.mjs', 'NoteRegionsRecord',
                   [ 'const sheetWith = ', 'const margin = ', 'const region = ', 'const BIG   = ' ])
    parts.append('')
    parts += block('Na__Test__LeaderlessNotes__.test.mjs', 'LeaderlessRecord',
                   [ 'const IN = ', 'const sheetWith = ', 'const margin    = ', 'const region    = ', 'const BIG       = ' ])
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(parts) + '\n')
    text = '\n'.join(parts)
    print('wrote %s: %d lines, %d check() calls' % (OUT, len(parts), len(re.findall(r'\bcheck\(', text))))


if __name__ == '__main__':
    sys.exit(main())
