# GENERATED by scratch/W3-99/make_pom_endW3.py from scratch/W2-99/pom/port_order_map__endW2.py - reads
# the VV WORKING TREE (end of Wave 3) as its "after" tree and writes only into scratch/W3-99/pom/.
#!/usr/bin/env python3
"""
W0-05 - Port-order map from TrueVision's import graph (leaves first, hubs last).

READ-ONLY analysis (no repository is written):
  - TrueVision is read only at the pin b2aa9151 through `git ls-tree` / `git cat-file`
    (never TV's working tree, which moves under the swarm).
  - ValeVision "before the swarm" = commit 7b4e593a (git ls-tree), used to reproduce
    S11 Appendix D exactly as the S11 verifier computed it (old folder map applied).
  - ValeVision "after W0-02" = the git index of D:/10_CoreLib__ValeCodebase: W0-02's 81
    `git mv` renames are the only staged changes over 7b4e593a (checked at run time), so the
    index path set is exactly the post-renumber tree. Export names come from the index blobs
    with W0-02's one export rename applied (T6: Na__DrawView__ComposerPreset__* ->
    Na__DrawView__RenderPreset__*); W0-02's other rewrites touch specifiers and comments only.
  - The live working tree is consulted only for an informational "exists now" column
    (concurrent W0 packages may already have landed files).

Inputs: parity/data/wp_canonical.json (packages, DAG), parity/slices/S11 (c.1 table and
Appendix D), the S11 verifier's own output work_s11v/prereq.json when present.

Outputs:
  parity/data/port_order_map.json            (the package's named output)
  execution/port_order_map.json + .md        (orchestrator copy + human summary)
  execution/scratch/W0-05/*                  (working data)
"""
import json, os, re, subprocess, sys, posixpath, collections, datetime, hashlib

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
NAWEB   = r"D:\11_RefLib__StudioRepository__RemoteSystem\NaWeb"
VCB     = r"D:\10_CoreLib__ValeCodebase"
PIN     = "b2aa9151"
VV_BASE = "7b4e593a"
TV_PFX  = "na-apps/30__TrueVision__CoreAppCode/"
VV_PFX  = "WebApps/ValeVision3D/"
VV_ROOT = os.path.join(VCB, "WebApps", "ValeVision3D")
EVID    = os.path.join(VV_ROOT, "ValeVision__AUDIT__TrueVisionParity__Evidence__")
PARITY  = os.path.join(EVID, "parity")
EXEC    = os.path.join(EVID, "execution")
SCRATCH = os.path.join(EXEC, "scratch", "W3-99", "pom")
PREREQ_JSON = (r"C:\Users\adamw\AppData\Local\Temp\claude\C--Users-adamw-AppData-Roaming-SketchUp-SketchUp-2026-SketchUp-Plugins"
               r"\a1674149-918e-4d62-a79a-e7961f105155\scratchpad\parity\work_s11v\prereq.json")
S11_MD  = os.path.join(PARITY, "slices", "S11__Ledger_Release_Watermark.md")
WP_JSON = os.path.join(PARITY, "data", "wp_canonical.json")

SRC = "02__Src__AppModules/"
LE  = SRC + "51__System__LayoutEditor/"

# The S11 verifier's folder map (TV -> VV before the renumber), copied from work_s11v/prereq.py.
OLD_MAP = {'40__System__DrawingViewCore': '42__System__DrawingViewCore', '42__System__FloorPlanViews': '43__System__FloorPlanViews',
           '43__System__PlanAnnotations': '44__System__PlanAnnotations', '44__System__PlanDimensions': '45__System__PlanDimensions',
           '45__System__ElevationViews': '46__System__ElevationViews', '46__System__NorthDirection': '47__System__NorthDirection'}

LABEL_TRANSPORT = "transport seam (DIV-4) - resolved by VV facade W0-12"
LABEL_DIV2 = ("section seam (DIV-2) - TV 41__System__SectionCutEngine is never ported; the import becomes a "
              "Na__DrawView__SectionAdapter__* name (R3 C.1 row 1, C.4 S4; W2-02 adds the four calls)")
LABEL_DIV1 = ("render seam (DIV-1) - TV Na__DrawView__ProfileLines__ is never ported; the import is dropped "
              "(VV composer route, R3 C.1 row 1)")
TRANSPORT_FILES = {SRC + "80__CloudflareIntegration/Na__CloudflareIntegration__ApiClient__.js",
                   SRC + "03__AppUtils/Na__AppUtils__LocalProjectMirror__.js"}
LABEL_PLANDIM = ("PlanDimensions split seam (VV ahead, S11-V03; DR-42 item 7 / WT-01): the Na__PlanDim__* names TV imports from "
                 "44 Data__/Editor__ are imported from VV's split 44 ConfigState__ / EditorPreview__ (as W1-37, W2-03 and W2-04 declare)")
PLANDIM_SPLIT_FROM = {SRC + "44__System__PlanDimensions/Na__PlanDimensions__Data__.js",
                      SRC + "44__System__PlanDimensions/Na__PlanDimensions__Editor__.js"}
PLANDIM_SPLIT_HOMES = [SRC + "44__System__PlanDimensions/Na__PlanDimensions__ConfigState__.js",
                       SRC + "44__System__PlanDimensions/Na__PlanDimensions__EditorPreview__.js"]
EXEC_STATE = os.path.join(r"D:\10_CoreLib__ValeCodebase\WebApps\ValeVision3D\ValeVision__AUDIT__TrueVisionParity__Evidence__",
                          "execution", "execution_state.json")


def _load_held():
    """Packages the orchestrator holds until Adam answers (execution_state.json status 'held')."""
    try:
        stt = json.load(open(EXEC_STATE, encoding="utf-8"))
        return {k for k, v in stt.get("packages", {}).items() if (v.get("status") if isinstance(v, dict) else v) == "held"}
    except Exception:
        return {"W3-04", "W5-04", "W5-05", "W5-06", "W5-07", "W6-03"} | {"WT-%02d" % i for i in range(1, 13)}


HELD = _load_held()

WAVE_IDX = {"W0": 0, "W1": 1, "W2": 2, "W3": 3, "W4": 4, "W5": 5, "W6": 6, "WT": 99}


# -----------------------------------------------------------------------------
# git helpers (read-only)
# -----------------------------------------------------------------------------
def run(args, input_bytes=None):
    p = subprocess.run(args, input=input_bytes, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if p.returncode != 0:
        raise RuntimeError("command failed: %s\n%s" % (" ".join(args), p.stderr.decode("utf-8", "replace")))
    return p.stdout


def ls_tree(repo, rev, prefix):
    out = run(["git", "-C", repo, "ls-tree", "-r", "-z", rev, "--", prefix])
    res = {}
    for rec in out.split(b"\0"):
        if not rec:
            continue
        meta, path = rec.split(b"\t", 1)
        mode, typ, sha = meta.split()
        if typ != b"blob":
            continue
        p = path.decode("utf-8")
        if p.startswith(prefix):
            res[p[len(prefix):]] = sha.decode()
    return res


def ls_index(repo, prefix):
    out = run(["git", "-C", repo, "ls-files", "-s", "-z", "--", prefix])
    res = {}
    for rec in out.split(b"\0"):
        if not rec:
            continue
        meta, path = rec.split(b"\t", 1)
        mode, sha, stage = meta.split()
        p = path.decode("utf-8")
        if p.startswith(prefix) and stage == b"0":
            res[p[len(prefix):]] = sha.decode()
    return res


def cat_blobs(repo, shas):
    shas = sorted(set(shas))
    if not shas:
        return {}
    out = run(["git", "-C", repo, "cat-file", "--batch"], input_bytes=("\n".join(shas) + "\n").encode())
    res, i = {}, 0
    for sha in shas:
        nl = out.index(b"\n", i)
        head = out[i:nl].split()
        if len(head) < 3 or head[1] != b"blob":
            raise RuntimeError("cat-file: unexpected header %r" % head)
        size = int(head[2])
        start = nl + 1
        res[sha] = out[start:start + size]
        i = start + size + 1
    return res


def decode(b):
    s = b.decode("utf-8", errors="replace")
    return s[1:] if s.startswith("\ufeff") else s


# -----------------------------------------------------------------------------
# JavaScript source preparation: strip comments (string, template and regex aware)
# -----------------------------------------------------------------------------
_REGEX_PREV = set("(,=:[!&|?{};+-*%<>~^")
_KW_BEFORE_REGEX = {"return", "typeof", "case", "in", "of", "new", "delete", "void", "throw",
                    "instanceof", "else", "do", "yield", "await"}


def strip_comments(src):
    """Return (code, masked): comments removed; in `masked` every string, template and regex
    literal keeps its delimiters but its interior is replaced by 'x' (same length), so statement
    regexes never match text inside a literal while spans still index into `code`."""
    out, msk = [], []
    i, n = 0, len(src)
    prev = ""          # last significant (non-space) character emitted
    word = []          # identifier being emitted
    last_word = ""     # last complete identifier emitted
    while i < n:
        c = src[i]
        nx = src[i + 1] if i + 1 < n else ""
        if c in "\"'`":
            q = c
            j = i + 1
            while j < n:
                d = src[j]
                if d == "\\":
                    j += 2
                    continue
                if d == q:
                    break
                if q != "`" and d == "\n":       # unterminated plain string: stop at the line end
                    break
                j += 1
            lit = src[i:j + 1]
            out.append(lit)
            if len(lit) >= 2 and lit[-1] == q:
                msk.append(q + re.sub(r"[^\n]", "x", lit[1:-1]) + q)
            else:
                msk.append(q + re.sub(r"[^\n]", "x", lit[1:]))
            i = j + 1
            prev = q
            word, last_word = [], ""
            continue
        if c == "/" and nx == "/":
            while i < n and src[i] != "\n":
                i += 1
            continue
        if c == "/" and nx == "*":
            j = src.find("*/", i + 2)
            i = n if j < 0 else j + 2
            out.append(" ")
            msk.append(" ")
            continue
        if c == "/":
            is_regex = (prev == "" or prev in _REGEX_PREV or
                        ((prev.isalnum() or prev in "_$") and last_word in _KW_BEFORE_REGEX))
            if is_regex:
                j = i + 1
                in_class = False
                while j < n:
                    d = src[j]
                    if d == "\\":
                        j += 2
                        continue
                    if d == "\n":
                        break
                    if in_class:
                        if d == "]":
                            in_class = False
                    elif d == "[":
                        in_class = True
                    elif d == "/":
                        break
                    j += 1
                j += 1
                while j < n and (src[j].isalnum() or src[j] in "_$"):
                    j += 1
                lit = src[i:j]
                out.append(lit)
                msk.append("/" + re.sub(r"[^\n]", "x", lit[1:]))
                i = j
                prev = "/"
                word, last_word = [], ""
                continue
        out.append(c)
        msk.append(c)
        if c.isalnum() or c in "_$":
            word.append(c)
            last_word = "".join(word)
        else:
            word = []
            if not c.isspace():
                last_word = ""
        if not c.isspace():
            prev = c
        i += 1
    code, masked = "".join(out), "".join(msk)
    assert len(code) == len(masked)
    return code, masked


# -----------------------------------------------------------------------------
# Import / export parsing
# -----------------------------------------------------------------------------
ID = r"[A-Za-z_$][\w$]*"
RE_IMPORT_FROM = re.compile(r"(?<![\w$.])import\s*((?:" + ID + r"\s*,\s*)?(?:\*\s*as\s+" + ID + r"|\{[^{}'\"`]*\}|" + ID +
                            r"))\s*from\s*(['\"])([^'\"\n]+)\2")
RE_IMPORT_BARE = re.compile(r"(?<![\w$.])import\s*(['\"])([^'\"\n]+)\1")
RE_IMPORT_DYN = re.compile(r"(?<![\w$.])import\s*\(\s*(['\"`])([^'\"`\n$]+)\1\s*[,)]")
RE_IMPORT_DYN_ANY = re.compile(r"(?<![\w$.])import\s*\(")
RE_EXPORT_FROM = re.compile(r"(?<![\w$.])export\s*(\*\s*(?:as\s+" + ID + r"\s*)?|\{[^{}'\"`]*\}\s*)from\s*(['\"])([^'\"\n]+)\2")
RE_EXPORT_DECL = re.compile(r"(?<![\w$.])export\s+(?:async\s+)?(?:function\s*\*?\s*|class\s+|const\s+|let\s+|var\s+)(" + ID + ")")
RE_EXPORT_DEFAULT = re.compile(r"(?<![\w$.])export\s+default\b")
RE_EXPORT_LIST = re.compile(r"(?<![\w$.])export\s*\{([^{}'\"`]*)\}(?!\s*from)")
RE_EXPORT_DESTRUCT = re.compile(r"(?<![\w$.])export\s+(?:const|let|var)\s*\{([^{}'\"`]*)\}\s*=")
RE_NEW_URL = re.compile(r"new\s+URL\s*\(\s*(['\"])([^'\"\n]+)\1\s*,\s*import\.meta\.url\s*\)")


def _split_names(inner):
    res = []
    for part in inner.split(","):
        part = part.strip()
        if not part:
            continue
        pieces = re.split(r"\s+as\s+", part)
        res.append((pieces[0].strip(), (pieces[1] if len(pieces) > 1 else pieces[0]).strip()))
    return res


def parse_module(code, masked=None):
    """code = comment-stripped source, masked = the same with literal interiors masked.
    Statements are found in `masked`; specifier strings are read back from `code` by span."""
    if masked is None:
        masked = code
    imports = []
    for m in RE_IMPORT_FROM.finditer(masked):
        clause, spec = m.group(1).strip(), code[m.start(3):m.end(3)]
        default = ns = None
        names = []
        mm = re.match(r"^(" + ID + r")\s*,\s*(.*)$", clause, re.S)
        if mm and not clause.startswith("{") and not clause.startswith("*"):
            default, clause = mm.group(1), mm.group(2).strip()
        if clause.startswith("*"):
            ns = re.match(r"\*\s*as\s+(" + ID + ")", clause).group(1)
        elif clause.startswith("{"):
            names = [a for a, b in _split_names(clause[1:-1])]
        elif re.match("^" + ID + "$", clause):
            default = clause
        req = list(names)
        if default:
            req.append("default")
        if ns:
            used = sorted(set(re.findall(r"(?<![\w$.])" + re.escape(ns) + r"\s*\.\s*(" + ID + ")", masked)))
            req.extend(used)
        imports.append({"spec": spec, "kind": "static", "names": req, "namespace": ns, "pos": m.start()})
    for m in RE_IMPORT_BARE.finditer(masked):
        imports.append({"spec": code[m.start(2):m.end(2)], "kind": "side-effect", "names": [], "namespace": None, "pos": m.start()})
    for m in RE_EXPORT_FROM.finditer(masked):
        head = m.group(1).strip()
        names = [] if head.startswith("*") else [a for a, b in _split_names(head.strip()[1:-1])]
        imports.append({"spec": code[m.start(3):m.end(3)], "kind": "re-export", "names": names, "namespace": None,
                        "pos": m.start(), "star": head.startswith("*")})
    dyn_literal = 0
    for m in RE_IMPORT_DYN.finditer(masked):
        imports.append({"spec": code[m.start(2):m.end(2)], "kind": "dynamic", "names": [], "namespace": None, "pos": m.start()})
        dyn_literal += 1
    dyn_all = len(RE_IMPORT_DYN_ANY.findall(masked))

    exports, stars = set(), []
    for m in RE_EXPORT_DECL.finditer(masked):
        exports.add(m.group(1))
    if RE_EXPORT_DEFAULT.search(masked):
        exports.add("default")
    for m in RE_EXPORT_LIST.finditer(masked):
        for a, b in _split_names(m.group(1)):
            exports.add(b)
    for m in RE_EXPORT_DESTRUCT.finditer(masked):
        for part in m.group(1).split(","):
            part = part.strip()
            if not part:
                continue
            exports.add(part.split(":")[-1].strip().split("=")[0].strip())
    for m in RE_EXPORT_FROM.finditer(masked):
        head = m.group(1).strip()
        if head.startswith("*"):
            mm = re.match(r"\*\s*as\s+(" + ID + ")", head)
            if mm:
                exports.add(mm.group(1))
            else:
                stars.append(code[m.start(3):m.end(3)])
        else:
            for a, b in _split_names(head[1:-1]):
                exports.add(b)
    urls = [code[m.start(2):m.end(2)] for m in RE_NEW_URL.finditer(masked)]
    return {"imports": imports, "exports": exports, "star_from": stars, "dyn_nonliteral": max(0, dyn_all - dyn_literal),
            "urls": urls}


def parse_source(text):
    code, masked = strip_comments(text)
    return parse_module(code, masked)


def resolve_spec(importer, spec, import_map):
    """importer and result are app-relative posix paths. Returns (kind, target)."""
    if spec.startswith("./") or spec.startswith("../"):
        t = posixpath.normpath(posixpath.join(posixpath.dirname(importer), spec))
        if t.startswith("../") or t == "..":
            return "outside", t
        return "internal", t
    if spec.startswith("/") or re.match(r"^[a-z]+:", spec):
        return "outside", spec
    if spec in import_map:
        return "bare", posixpath.normpath(import_map[spec].lstrip("./"))
    keys = sorted([k for k in import_map if k.endswith("/") and spec.startswith(k)], key=len, reverse=True)
    if keys:
        return "bare", posixpath.normpath((import_map[keys[0]] + spec[len(keys[0]):]).lstrip("./"))
    return "bare-unmapped", spec


def read_import_map(html):
    m = re.search(r"<script[^>]+type=[\"']importmap[\"'][^>]*>([\s\S]*?)</script>", html, re.I)
    return json.loads(m.group(1)).get("imports", {}) if m else {}


# -----------------------------------------------------------------------------
# Load trees
# -----------------------------------------------------------------------------
def is_module(p):
    return p.endswith(".js") or p.endswith(".mjs")


# Third-party and archive trees are not app code (VV's own Na__Verify__Exports__ skips them too).
_SKIP_PARTS = ("/node_modules/", "/dist/", "/00__Archive", "/00__ArchivedVersions/")


def is_app_module(p):
    return is_module(p) and p.startswith(SRC) and not any(s in "/" + p for s in _SKIP_PARTS)


def load_state():
    st = {}
    tv = ls_tree(NAWEB, PIN, TV_PFX)
    st["tv_tree"] = tv
    vv0 = ls_tree(VCB, VV_BASE, VV_PFX)
    st["vv0_tree"] = vv0
    vv1 = ls_worktree(VV_ROOT)
    st["vv1_tree"] = vv1

    tv_mods = {p: s for p, s in tv.items() if is_app_module(p)}
    vv0_mods = {p: s for p, s in vv0.items() if is_app_module(p)}
    vv1_mods = {p: s for p, s in vv1.items() if is_app_module(p)}
    blobs_tv = cat_blobs(NAWEB, list(tv_mods.values()) + [tv["Index.html"]])
    blobs_vv = cat_blobs(VCB, list(vv0_mods.values()))
    blobs_vv.update({s: open(s[3:], "rb").read() for s in list(vv1_mods.values()) + [vv1["index.html"]]})
    st["tv_src"] = {p: decode(blobs_tv[s]) for p, s in tv_mods.items()}
    st["vv0_src"] = {p: decode(blobs_vv[s]) for p, s in vv0_mods.items()}
    # After W0-02: index blobs with W0-02's T6 export rename (the only export-name change it made).
    st["vv1_src"] = {p: decode(blobs_vv[s]).replace("Na__DrawView__ComposerPreset__", "Na__DrawView__RenderPreset__")
                     for p, s in vv1_mods.items()}
    st["tv_import_map"] = read_import_map(decode(blobs_tv[tv["Index.html"]]))
    st["vv_import_map"] = read_import_map(decode(blobs_vv[vv1["index.html"]]))
    return st



# -----------------------------------------------------------------------------
# W0-99: the working tree as the "after" tree (end of Wave 0)
# -----------------------------------------------------------------------------
_WT_SKIP = {".git", ".claude", "node_modules", "__pycache__", ".wrangler"}


def ls_worktree(root):
    """path (relative to the VV app root, '/'-separated) -> 'WT:<absolute path>' for every file on disk, pruning
    .claude/worktrees, node_modules and the AUDIT evidence folder (none of them is app code)."""
    res = {}
    for dp, dn, fn in os.walk(root):
        rel_dir = os.path.relpath(dp, root).replace(os.sep, "/")
        dn[:] = [d for d in dn if d not in _WT_SKIP and not (rel_dir == "." and d.startswith("ValeVision__AUDIT__"))]
        for f in fn:
            p = f if rel_dir == "." else rel_dir + "/" + f
            res[p] = "WT:" + os.path.join(dp, f)
    return res


def check_index_is_w0_02_only():
    out = run(["git", "-C", VCB, "diff", "--cached", "-M", "--name-status", "-z"]).split(b"\0")
    kinds = collections.Counter()
    i = 0
    while i < len(out):
        rec = out[i]
        if not rec:
            i += 1
            continue
        k = rec.decode()
        if k.startswith("R") or k.startswith("C"):
            kinds[k[0] + ("100" if k[1:] == "100" else k[1:])] += 1
            i += 3
        else:
            kinds[k] += 1
            i += 2
    return dict(kinds)


# -----------------------------------------------------------------------------
# Export resolution
# -----------------------------------------------------------------------------
class Exports:
    """Export names of a module in one tree, following `export * from`. Modules outside the
    parsed app set (vendor files) are read from the tree's own blobs on demand."""

    def __init__(self, parsed, tree=None, repo=None, prefix_note="", transform=None):
        self.parsed = parsed          # path -> parse_module result
        self.tree = tree or {}        # path -> blob sha (the same tree the parsed set came from)
        self.repo = repo
        self.transform = transform
        self.cache = {}
        self.loaded_on_demand = []

    def _load(self, path):
        if path in self.parsed:
            return True
        if path not in self.tree or not is_module(path):
            return False
        if str(self.tree[path]).startswith("WT:"):
            blob = open(self.tree[path][3:], "rb").read()
        elif not self.repo:
            return False
        else:
            blob = cat_blobs(self.repo, [self.tree[path]])[self.tree[path]]
        txt = decode(blob)
        if self.transform:
            txt = self.transform(txt)
        self.parsed[path] = parse_source(txt)
        self.loaded_on_demand.append(path)
        return True

    def of(self, path, seen=None):
        if path in self.cache:
            return self.cache[path]
        if not self._load(path):
            return None
        seen = set() if seen is None else seen
        if path in seen:
            return set()
        seen.add(path)
        p = self.parsed[path]
        names = set(p["exports"])
        for spec in p["star_from"]:
            kind, tgt = resolve_spec(path, spec, {})
            if kind == "internal":
                sub = self.of(tgt, seen)
                if sub:
                    names |= (sub - {"default"})
        self.cache[path] = names
        return names


# -----------------------------------------------------------------------------
# Package catalogue
# -----------------------------------------------------------------------------
def norm_tv_source(s):
    m = re.match(r"^(\S+)(?:\s+\((.*)\))?\s*$", s.strip())
    p, ann = m.group(1), (m.group(2) or "")
    if p.startswith("TVM/"):
        return SRC + p[4:], ann
    if p.startswith("TV/"):
        return p[3:], ann
    return None, ann


def norm_vv_target(s):
    s2 = s.strip()
    new = "(new)" in s2
    if "->" in s2:
        s2 = s2.split("->", 1)[1].strip()
    p = s2.split()[0]
    if p.startswith("VVM/"):
        return SRC + p[4:], new
    if p.startswith("VV/"):
        return p[3:], new
    return None, new


# Take mode of every (package, TV JS source) whose VV target is NOT a new file, decided from the
# package's own goal / vv_adaptations / tv_sources annotation (read by hand, 01-Oct-2026).
# whole       = TV's file at the pin taken whole, VV seams re-applied (R3/K3 R3)
# convergence = residual hunks that end with TV's file minus recorded seams (treated as whole for imports)
# hunks       = hunk replay or additive edits onto VV's file (imports only as the hunks need them)
# header      = header / comment re-sync only (no import change)
# vv_body     = VV body behind TV's path and names (a seam, not a port)
# reference   = read for reference, nothing ported
# infra       = shared infrastructure prepared outside VV (staged copies)
OVERRIDES = {
    ("W0-02", "Na__DrawView__RenderPreset__.js"): ("vv_body", "DIV-1 twin: VV composer body behind TV's RenderPreset names (W0-02 goal; K2 H3)"),
    ("W0-04", "Na__Verify__ModuleGraph__.mjs"): ("reference", "test harness fix in VV's own verifier, not an app module port"),
    ("W0-08", "TrueVision__Pwa__ServiceWorker__Registrar__.js"): ("infra", "shared WCP service worker, prepared copy (DR-07)"),
    ("W0-08", "TrueVision__Pwa__ServiceWorker__Logic__.js"): ("infra", "shared WCP service worker, prepared copy (DR-07)"),
    ("W0-10", "CloudflareHandler__R2__.js"): ("reference", "tv_sources: 'reference: TV generic /r2/* is NOT copied'"),
    ("W0-11", "Na__AppUtils__ProjectLoader.js"): ("hunks", "goal: 'Add TV's ... GetProjectFolderFromUrl and ... GetYearFromUrl ...; additive only'"),
    ("W0-13", "Na__AppFlow__LoadingSequence.js"): ("hunks", "adaptation: 'Hand-adapted hunks only'"),
    ("W0-14", "Na__LayoutEditor__Assets__.js"): ("whole", "goal: 'take TV Assets 1.0.1 ... with VV's localhost gate' (seam S9)"),
    ("W0-14", "Na__ProjectedLinework__Persistence__.js"): ("whole", "goal: 'take TV ... Persistence 1.2.1 with VV's localhost gate' (seam S9)"),
    ("W0-14", "Na__AppUtils__R2AssetUpload__.js"): ("hunks", "goal: 'Adopt TV's non-throwing upload contract in VV R2AssetUpload' (DIV-4 file)"),
    ("W0-14", "Na__PresentationMode__Thumbnail__Renderer.js"): ("hunks", "goal: 'let the thumbnail renderer accept TV's CaptureAndUpload call shape' (seam S13)"),
    ("W0-15", "Na__LayoutEditor__ConfigState__.js"): ("whole", "goal: 'port ConfigState barrel 1.29.0'"),
    ("W0-15", "Na__LayoutEditor__ConfigState__Readers__.js"): ("whole", "goal: ConfigState units taken in ONE change"),
    ("W0-15", "Na__LayoutEditor__ConfigState__SheetSetup__.js"): ("whole", "goal: 'SheetSetup 1.9.0'"),
    ("W0-15", "Na__LayoutEditor__ConfigState__ToolSetup__.js"): ("whole", "goal: 'ToolSetup 1.5.0'"),
    ("W0-15", "Na__LayoutEditor__ConfigState__EditorSetup__.js"): ("whole", "goal: 'EditorSetup 1.6.0'"),
    ("W0-15", "Na__LayoutEditor__ConfigState__KeyMap__.js"): ("whole", "goal: 'KeyMap 1.11.0 with TV's drawing-tab key content'"),
    ("W1-01", "Na__RenderLoop__Invalidation.js"): ("hunks", "est_note: 'hunks in Invalidation, LoadingSequence, ModelToggle'"),
    ("W1-01", "Na__UiFeature__ModelToggle__Controls.js"): ("hunks", "est_note: 'hunks in ... ModelToggle'"),
    ("W1-02", "3dObjectIInteraction__Animation__ClickToOpenDoors__.js"): ("hunks", "goal: 'Merge TV door module 1.8.0/1.9.0 onto VV 1.7.1'"),
    ("W1-03", "Na__ModelLoader__MultiModel.js"): ("hunks", "risk: 'MultiModel and the Main config are high-traffic files: hunks only'"),
    ("W1-03", "Na__RenderEffect__Supersampler__.js"): ("hunks", "goal: the supersampler present pass to min(rgb, a) only"),
    ("W1-04", "Na__DrawView__Transitions__.js"): ("hunks", "goal: 'Port ReturnToOrbit and the options.returnToOrbit gate onto VV Transitions'"),
    ("W1-05", "Na__DrawView__ProjectData__.js"): ("whole", "goal: 'Take TV Na__DrawView__ProjectData__ 1.6.0 whole'"),
    ("W1-05", "Na__North__ProjectJson__Data__.js"): ("hunks", "goal: 'North gains Save(showToast, report)'"),
    ("W1-06", "Na__DrawView__RowAccordion__.js"): ("whole", "goal: 'RowAccordion whole'"),
    ("W1-06", "Na__DrawView__RenameDrawing__.js"): ("hunks", "goal: 'RenameDrawing staged holders' on VV's restamp route (seam S23)"),
    ("W1-06", "Na__PresentationMode__DevMenu__Modal__.js"): ("whole", "goal: 'the Presentation modal 1.2.0' (TV's version at the pin)"),
    ("W1-07", "Na__LayoutEditor__AutoSave__.js"): ("whole", "goal: 'Port AutoSave 1.5.0'; W0-08 note: 'W1-07 (AutoSave 1.5.0 whole)'"),
    ("W1-08", "Na__FloorPlan__ConfigState__.js"): ("whole", "goal: 'ConfigState 1.1.0 verbatim'"),
    ("W1-08", "Na__FloorPlan__ProjectJson__Data__.js"): ("whole", "goal: 'take ProjectJson__Data__ 1.1.0 whole'"),
    ("W1-10", "Na__Elevation__ProjectJson__Data__.js"): ("whole", "goal: 'take the elevation ProjectJson__Data__ 1.1.0 whole'"),
    ("W1-11", "Na__North__CompassGizmo__.js"): ("whole", "goal: 'Take CompassGizmo 1.1.0 ... whole'"),
    ("W1-11", "Na__North__DevMenu__Editor__.js"): ("whole", "goal: 'the North Dev editor 1.1.0 whole'"),
    ("W1-12", "Na__LayoutEditor__ProjectRecord__.js"): ("hunks", "goal: 'make ProjectRecord read clientDrawingName and siteAddress' (VV body, seam S15)"),
    ("W1-13", "Na__LayoutEditor__MeasureParse__.js"): ("whole", "goal: 'MeasureParse 1.1.0 ... verbatim and inert'"),
    ("W1-13", "Na__LayoutEditor__ScaleManager__.js"): ("whole", "goal: 'ScaleManager 1.2.1 ... verbatim and inert'"),
    ("W1-18", "Na__LayoutEditor__GradientTool__.js"): ("whole", "goal: 'Take the two drawing-tool leaves whole'"),
    ("W1-18", "Na__LayoutEditor__LineStyleTool__.js"): ("whole", "goal: 'Take the two drawing-tool leaves whole'"),
    ("W1-19", "Na__LayoutEditor__SheetRecords__.js"): ("whole", "goal: 'Bring SheetRecords to TV 1.39.0 ... VV seams only'; est_note TV 1,763 lines"),
    ("W1-20", "Na__LayoutEditor__SheetModel__State__.js"): ("whole", "goal: '... whole'"),
    ("W1-20", "Na__LayoutEditor__SheetModel__Layers__.js"): ("whole", "goal: '... whole'"),
    ("W1-20", "Na__LayoutEditor__SheetModel__Shapes__.js"): ("whole", "goal: '... whole'"),
    ("W1-20", "Na__LayoutEditor__SheetModel__Viewports__.js"): ("whole", "goal: '... whole'"),
    ("W1-20", "Na__LayoutEditor__SheetModel__TextAndDimensions__.js"): ("whole", "goal: '... whole'"),
    ("W1-20", "Na__LayoutEditor__SheetModel__Leaders__.js"): ("whole", "goal: '... whole'"),
    ("W1-20", "Na__LayoutEditor__SheetModel__Groups__.js"): ("whole", "goal: '... whole'"),
    ("W1-20", "Na__LayoutEditor__SheetModel__DrawOrder__.js"): ("header", "goal: 're-sync the DrawOrder and Common headers'"),
    ("W1-20", "Na__LayoutEditor__SheetModel__Common__.js"): ("header", "goal: 're-sync the DrawOrder and Common headers'"),
    ("W1-21", "Na__LayoutEditor__SheetModel__.js"): ("whole", "goal: 'Take the SheetModel facade, the Sheets unit and History whole together'"),
    ("W1-21", "Na__LayoutEditor__SheetModel__Sheets__.js"): ("whole", "goal: 'Take ... the Sheets unit ... whole together'"),
    ("W1-21", "Na__LayoutEditor__History__.js"): ("whole", "goal: 'Take ... History whole together'"),
    ("W1-22", "Na__LayoutEditor__TitleBlock__Cells__.js"): ("whole", "goal: 'port TitleBlock Cells 1.2.0'"),
    ("W1-22", "Na__LayoutEditor__TitleBlock__Modern__.js"): ("whole", "goal: 'Modern 1.5.0 (logo stand-in text in config)' (seam S3)"),
    ("W1-22", "Na__LayoutEditor__PdfFilename__.js"): ("hunks", "goal: 'rename PDF files on the Document ID' (seam S10)"),
    ("W1-22", "Na__LayoutEditor__DrawingScale__.js"): ("header", "goal: 're-sync the code-identical headers'"),
    ("W1-22", "Na__LayoutEditor__SheetLayout__.js"): ("header", "goal: 're-sync the code-identical headers'"),
    ("W1-22", "Na__LayoutEditor__TitleBlock__Classic__.js"): ("header", "goal: 're-sync the code-identical headers'"),
    ("W1-23", "Na__LayoutEditor__SnapshotRenderer__.js"): ("hunks", "tv_sources '(signatures)'; adaptation 'no whole-file take'"),
    ("W1-23", "Na__LayoutEditor__Viewport2d__.js"): ("hunks", "tv_sources '(Describe)'; adaptation 'no whole-file take'"),
    ("W1-24", "Na__LayoutEditor__PdfExporter__.js"): ("hunks", "tv_sources '(1.11.0 hunks)'"),
    ("W1-26", "Na__LayoutEditor__SheetChrome__.js"): ("whole", "goal: 'Take the four sheet-chrome and markup-geometry hubs whole'"),
    ("W1-26", "Na__LayoutEditor__ShapeGeometry__.js"): ("whole", "goal: '... hubs whole'"),
    ("W1-26", "Na__LayoutEditor__DimensionGeometry__.js"): ("whole", "goal: '... hubs whole'"),
    ("W1-26", "Na__LayoutEditor__LeaderGeometry__.js"): ("whole", "goal: '... hubs whole'"),
    ("W1-28", "Na__LayoutEditor__MarkupBridge__.js"): ("whole", "goal: 'MarkupBridge 1.20.0, markup Groups 1.4.0 and SheetSurface 1.13.0 whole'"),
    ("W1-28", "Na__LayoutEditor__Groups__.js"): ("whole", "goal: '... Groups 1.4.0 ... whole'"),
    ("W1-28", "Na__LayoutEditor__SheetSurface__.js"): ("whole", "goal: '... SheetSurface 1.13.0 whole'"),
    ("W1-28", "Na__LayoutEditor__PdfExporter__.js"): ("hunks", "tv_sources '(paint-plan hunks)'"),
    ("W1-29", "Na__Hotkeys__Manager.js"): ("reference", "tv_sources '(reference for the gate)'"),
    ("W1-31", "Na__LayoutEditor__ModeController__.js"): ("reference", "tv_sources '(names the facade mirrors)'"),
    ("W1-32", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(feature-independent hunks)'"),
    ("W1-32", "Na__LayoutEditor__Panel__Scrapbook__.js"): ("hunks", "adaptation: 'Panel__Scrapbook 1.2.1 (the Scrapbook tab hint)' (S11 c.1 row 210: port_adapted)"),
    ("W1-33", "Na__LayoutEditor__LoadingVeil__.js"): ("whole", "adaptation: 'LoadingVeil 1.1.0 whole, keeping VV's DrawingSettled export'"),
    ("W1-34", "Na__LayoutEditor__TabStrip__.js"): ("whole", "goal: 'Port TV TabStrip 2.0.0 whole with VV seams: facade-only imports'"),
    ("W1-35", "Na__LayoutEditor__Toolbar__.js"): ("hunks", "goal: subtractive phase (TV 1.17.0/1.19.0)"),
    ("W1-36", "Na__LayoutEditor__Navigation__.js"): ("whole", "goal: 'Take Navigation 1.3.0, Controls__Pc 1.4.0 and Controls__TouchScreen 1.1.0 whole'"),
    ("W1-36", "Na__LayoutEditor__Controls__Pc__.js"): ("whole", "goal: '... whole'"),
    ("W1-36", "Na__LayoutEditor__Controls__TouchScreen__.js"): ("whole", "goal: '... whole'"),
    ("W1-36", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(keyboard hunks)'"),
    ("W1-38", "Na__LayoutEditor__PanelHost__.js"): ("whole", "goal: 'Take TV PanelHost__.js 1.6.0 whole'"),
    ("W2-02", "Na__DrawView__SectionAdapter__.js"): ("vv_body", "tv_sources '(interface)'; DIV-2 VV bodies (seam S4)"),
    ("W2-03", "Na__Elevation__ModeController__.js"): ("hunks", "tv_sources '(fog-source hook)'; VV keeps its 45 controller (DR-32)"),
    ("W2-04", "Na__FloorPlan__DevMenu__Editor__.js"): ("whole", "goal: 'Take TV's floor plan DevMenu Editor 2.0.0 and RowBuilders 2.0.0 whole'"),
    ("W2-04", "Na__FloorPlan__DevMenu__RowBuilders__.js"): ("whole", "goal: '... RowBuilders 2.0.0 whole'"),
    ("W2-05", "Na__Elevation__DevMenu__Editor__.js"): ("whole", "goal: 'Take TV's elevation DevMenu Editor 2.1.0 and RowBuilders 2.1.0 whole'"),
    ("W2-05", "Na__Elevation__DevMenu__RowBuilders__.js"): ("whole", "goal: '... RowBuilders 2.1.0 whole'"),
    ("W2-06", "Na__ProjectedLinework__AuthoredEdges__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-06", "Na__ProjectedLinework__ClipKernel__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-06", "Na__ProjectedLinework__ConfigAccess__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole' (VV owner keys, new BuildToken)"),
    ("W2-06", "Na__ProjectedLinework__CpuBackend__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-06", "Na__ProjectedLinework__DevMenu__Controls__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole' (VV-only integrations kept, S02b-V01)"),
    ("W2-06", "Na__ProjectedLinework__EdgeExtractor__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-06", "Na__ProjectedLinework__ModelStage__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-06", "Na__ProjectedLinework__Pipeline__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-06", "Na__ProjectedLinework__Projector__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-06", "Na__ProjectedLinework__StageSampler__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-06", "Na__ProjectedLinework__ViewDefinition__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-06", "Na__ProjectedLinework__WebGpuBackend__.js"): ("whole", "goal: 'Take 13 TV folder-50 files whole'"),
    ("W2-16", "Na__LayoutEditor__Viewport2d__.js"): ("whole", "goal: 'Take Viewport2d, ... and Panel__ModelLayers whole from TV HEAD'"),
    ("W2-16", "Na__LayoutEditor__Viewport2d__Frame__.js"): ("whole", "goal: '... whole from TV HEAD'"),
    ("W2-16", "Na__LayoutEditor__Viewport2d__Linework__.js"): ("whole", "goal: '... whole from TV HEAD'"),
    ("W2-16", "Na__LayoutEditor__Viewport2d__Window__.js"): ("whole", "goal: '... whole from TV HEAD'"),
    ("W2-16", "Na__LayoutEditor__Viewport3d__.js"): ("whole", "goal: '... whole from TV HEAD'"),
    ("W2-16", "Na__LayoutEditor__ViewportIdentity__.js"): ("whole", "goal: '... whole from TV HEAD'"),
    ("W2-16", "Na__LayoutEditor__EdgeStyles__.js"): ("whole", "goal: '... whole from TV HEAD'"),
    ("W2-16", "Na__LayoutEditor__ModelLayers__.js"): ("whole", "goal: '... whole from TV HEAD'"),
    ("W2-16", "Na__LayoutEditor__Panel__ModelLayers__.js"): ("whole", "goal: '... whole from TV HEAD'"),
    ("W2-07", "Na__RenderEffect__ProgressiveRefine__.js"): ("hunks", "goal: 'Bring ProgressiveRefine 1.0.2 (... VV floor kept)'"),
    ("W2-07", "Na__AppFlow__LoadingSequence.js"): ("hunks", "tv_sources '(loop hunks)'"),
    ("W2-09", "Na__LayoutEditor__Enhance__.js"): ("whole", "goal: 'Take Enhance 1.1.0 and RenderComposites 1.3.0 whole'"),
    ("W2-09", "Na__LayoutEditor__RenderComposites__.js"): ("whole", "goal: '... whole'"),
    ("W2-10", "Na__LayoutEditor__ViewportTitleText__.js"): ("whole", "goal: 'Take ViewportTitleText 1.1.0 verbatim'"),
    ("W2-15", "Na__LayoutEditor__SnapshotRenderer__.js"): ("hunks", "tv_sources: 'DIV-1 hunk replay, never whole' (F.8 C27)"),
    ("W2-16", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(Model Source and site-plan composites hunks)'"),
    ("W2-17", "Na__LayoutEditor__DevMenu__Controls__.js"): ("hunks", "goal: 'Keep VV's Dev menu 1.4.0 and add TV 1.2.0's live-phase bake filter'"),
    ("W2-20", "Na__LayoutEditor__ContextMenu__.js"): ("whole", "goal: 'Take the context-menu renderer 1.1.0 verbatim'"),
    ("W2-21", "Na__LayoutEditor__EditScope__.js"): ("whole", "goal: 'Take the SheetTools leaves whose exports are supersets of VV's whole'"),
    ("W2-21", "Na__LayoutEditor__ItemClipboard__.js"): ("whole", "goal: '... whole'"),
    ("W2-21", "Na__LayoutEditor__SelectionSet__.js"): ("whole", "goal: '... whole'"),
    ("W2-21", "Na__LayoutEditor__SelectionBox__.js"): ("whole", "goal: '... whole'"),
    ("W2-21", "Na__LayoutEditor__Eyedropper__.js"): ("whole", "goal: '... whole'"),
    ("W2-23", "Na__LayoutEditor__Measurements__.js"): ("whole", "goal: 'Take the Measurements box 1.10.0 whole'"),
    ("W2-24", "Na__LayoutEditor__Grips__.js"): ("whole", "goal: 'Take Grips 1.12.0 whole'"),
    ("W2-26", "Na__LayoutEditor__DimensionTool__.js"): ("whole", "goal: 'Take the four drawing tools whole below VV headers'"),
    ("W2-26", "Na__LayoutEditor__RectangleTool__.js"): ("whole", "goal: '... whole'"),
    ("W2-26", "Na__LayoutEditor__TextTool__.js"): ("whole", "goal: '... whole'"),
    ("W2-26", "Na__LayoutEditor__LeaderTool__.js"): ("whole", "goal: '... whole'"),
    ("W2-29", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(hatch ready and Patterns registration hunks)'"),
    ("W2-30", "Na__LayoutEditor__SpecData__State__.js"): ("whole", "adaptation: 'SpecData__Transport 1.3.0 ports verbatim over Na__CfApi/Na__LocalMirror'; units at TV versions"),
    ("W2-30", "Na__LayoutEditor__SpecData__Document__.js"): ("whole", "goal: 'Document 1.1.0'"),
    ("W2-30", "Na__LayoutEditor__SpecData__Draft__.js"): ("whole", "goal: 'Draft 1.1.0'"),
    ("W2-30", "Na__LayoutEditor__SpecData__Editing__.js"): ("whole", "goal: 'Editing 1.1.0'"),
    ("W2-30", "Na__LayoutEditor__SpecData__Transport__.js"): ("whole", "adaptation: 'SpecData__Transport 1.3.0 ports verbatim'"),
    ("W2-30", "Na__LayoutEditor__SpecData__.js"): ("whole", "goal: 'the barrel 1.5.0'"),
    ("W2-30", "Na__LayoutEditor__SpecLinks__.js"): ("whole", "goal: 'SpecLinks 1.2.0'"),
    ("W2-31", "Na__LayoutEditor__SpecEditor__Bar__.js"): ("hunks", "tv_sources '(1.3.0)': TV's file at the pin is 1.4.0, taken whole by W4-08 (DR-05: 'SpecEditor Bar 1.3.0 now, 1.4.0 with sharing')"),
    ("W2-31", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(lockstep hunks)'"),
    ("W2-32", "Na__LayoutEditor__SpecMargin__.js"): ("whole", "goal: 'SpecMargin 1.5.0'"),
    ("W2-32", "Na__LayoutEditor__MarginGrip__.js"): ("whole", "goal: 'MarginGrip 1.3.0 (its IsMoveAuto line arrives with the W3-03 hub)'"),
    ("W2-35", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(left tabs)'"),
    ("W2-36", "Na__LayoutEditor__Panel__Text__.js"): ("whole", "goal: 'Take Panel__Text 1.4.0 and Panel__Styles 1.7.0 whole'"),
    ("W2-36", "Na__LayoutEditor__Panel__Styles__.js"): ("whole", "goal: '... whole'"),
    ("W2-36", "Na__LayoutEditor__Panel__Shapes__.js"): ("hunks", "tv_sources '(1.8.1, 1.8.2 hunks)'"),
    ("W2-36", "Na__LayoutEditor__Panel__Leaders__.js"): ("header", "goal: 'the Panel__Leaders header'"),
    ("W2-36", "Na__LayoutEditor__Panel__Layers__.js"): ("hunks", "tv_sources '(1.1.1 labels, 1.3.0 Off-red)'"),
    ("W2-36", "Na__LayoutEditor__ScrapbookCustom__.js"): ("hunks", "tv_sources '(Shape__Area hunk)'"),
    ("W2-37", "Na__LayoutEditor__ScrapbookParametric__.js"): ("whole", "goal: 'Take the parametric engine 1.7.0 and its core element modules whole'"),
    ("W2-37", "Na__LayoutEditor__ScrapbookParametric__ScaleBar__.js"): ("whole", "goal: '... whole'"),
    ("W2-37", "Na__LayoutEditor__ScrapbookParametric__DrawingTitle__.js"): ("whole", "goal: '... whole'"),
    ("W2-37", "Na__LayoutEditor__ScrapbookParametric__Grips__.js"): ("whole", "goal: '... whole'"),
    ("W2-37", "Na__LayoutEditor__ScrapbookParametric__LinkNoodle__.js"): ("whole", "goal: '... whole'"),
    ("W2-37", "Na__LayoutEditor__ScrapbookParametric__ViewportLink__.js"): ("hunks", "tv_sources '(1.4.0 hunks)'; taken whole at 1.5.1 by W3-13"),
    ("W2-37", "Na__LayoutEditor__Scrapbook__TileDrag__.js"): ("whole", "goal: 'with TileDrag 1.2.0'"),
    ("W3-01", "Na__LayoutEditor__SheetTools__State__.js"): ("whole", "goal: 'Take the two hub units ... State 1.8.0'"),
    ("W3-01", "Na__LayoutEditor__SheetTools__ToolState__.js"): ("whole", "goal: '... ToolState 1.7.0'"),
    ("W3-03", "Na__LayoutEditor__SheetTools__HitResolution__.js"): ("whole", "goal: 'Take the rest of the SheetTools hub whole in one commit'"),
    ("W3-03", "Na__LayoutEditor__SheetTools__PointerPress__.js"): ("whole", "goal: '... whole'"),
    ("W3-03", "Na__LayoutEditor__SheetTools__PointerDrag__.js"): ("whole", "goal: '... whole'"),
    ("W3-03", "Na__LayoutEditor__SheetTools__Keyboard__.js"): ("whole", "goal: '... whole'"),
    ("W3-03", "Na__LayoutEditor__SheetTools__.js"): ("whole", "goal: '... whole'"),
    ("W3-03", "Na__LayoutEditor__SheetTools__ContextMenu__.js"): ("whole", "goal: '... whole'"),
    ("W3-03", "Na__LayoutEditor__AxisLock__.js"): ("header", "goal: 'with AxisLock and ContentEditing header syncs'"),
    ("W3-03", "Na__LayoutEditor__SheetTools__ContentEditing__.js"): ("header", "goal: '... header syncs'"),
    ("W3-04", "Na__LayoutEditor__SheetTools__HitResolution__.js"): ("hunks", "held (DR-40 items 7-10): removes W3-03's guards; no import change"),
    ("W3-04", "Na__LayoutEditor__SheetTools__PointerPress__.js"): ("hunks", "held (DR-40 items 7-10): removes W3-03's guards; no import change"),
    ("W3-04", "Na__LayoutEditor__SheetTools__PointerDrag__.js"): ("hunks", "held (DR-40 items 7-10): removes W3-03's guards; no import change"),
    ("W3-05", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(grid panel registration, Grid/Axes Attach/Detach)'"),
    ("W3-06", "Na__LayoutEditor__ViewportHandles__.js"): ("whole", "goal: 'Take the three viewport units whole'"),
    ("W3-06", "Na__LayoutEditor__Viewport3dZoom__.js"): ("whole", "goal: '... whole'"),
    ("W3-06", "Na__LayoutEditor__ViewportClipboard__.js"): ("whole", "goal: '... whole'"),
    ("W3-07", "Na__LayoutEditor__ShapeTool__.js"): ("whole", "goal: 'Take ShapeTool 1.10.0 whole'"),
    ("W3-07", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(vector tools hunks)'"),
    ("W3-09", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(images hunks)'"),
    ("W3-10", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(floor areas hunks)'"),
    ("W3-11", "Na__LayoutEditor__Panel__MarginNotes__.js"): ("whole", "goal: 'Panel__MarginNotes 1.2.0 ... verbatim'"),
    ("W3-11", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(region grip hunks)'"),
    ("W3-12", "Na__LayoutEditor__Panel__Dimensions__.js"): ("whole", "goal: 'Take both panels whole'"),
    ("W3-12", "Na__LayoutEditor__Panel__Shapes__.js"): ("whole", "goal: 'Take both panels whole'"),
    ("W3-13", "Na__LayoutEditor__Panel__Layers__.js"): ("whole", "goal: 'Take Panel__Layers 1.3.0 whole'"),
    ("W3-13", "Na__LayoutEditor__ScrapbookParametric__ViewportLink__.js"): ("whole", "goal: '... and ViewportLink 1.5.1'"),
    ("W3-14", "Na__LayoutEditor__Panel__ScrapbookParametric__.js"): ("whole", "goal: 'Take Panel__ScrapbookParametric 1.8.0 whole'"),
    ("W3-15", "Na__LayoutEditor__Panel__ViewportSettings__.js"): ("whole", "goal: 'Take Panel__ViewportSettings 1.10.0 whole'"),
    ("W3-16", "Na__LayoutEditor__PdfExporter__.js"): ("whole", "goal: 'Take PdfExporter 1.12.0 whole'"),
    ("W4-08", "Na__LayoutEditor__SpecEditor__Bar__.js"): ("whole", "goal: 'take SpecEditor Bar 1.4.0 with its Share button'"),
    ("W4-09", "Na__LayoutEditor__WebViewer__.js"): ("whole", "goal: 'Take WebViewer 1.2.0 whole'"),
    ("W4-09", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(viewer guards)'"),
    ("W4-10", "Na__LayoutEditor__Panel__Sheet__.js"): ("whole", "goal: 'take Panel__Sheet 1.4.0'"),
    ("W4-10", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(register hunks)'"),
    ("W4-13", "Na__LayoutEditor__ModeController__.js"): ("hunks", "tv_sources '(statement hunks)'"),
    ("W4-13", "Na__LayoutEditor__TabStrip__.js"): ("hunks", "tv_sources '(Design Statements tab)'"),
    ("W5-01", "Na__LayoutEditor__Toolbar__.js"): ("whole", "goal: 'take TV Toolbar 1.24.0 whole'"),
    ("W5-03", "Na__LayoutEditor__ModeController__.js"): ("convergence", "goal: 'land whatever is left ... so the remaining difference is the recorded VV seams only'"),
    ("W5-04", "Na__UiFeature__FullscreenMode__SystemLogic.js"): ("reference", "tv_sources '(only on request)'; held package"),
    ("W5-04", "Na__UiFeature__FullscreenMode__Prompt.js"): ("reference", "tv_sources '(only on request)'; held package"),
    ("W5-07", "Na__LayoutEditor__TabStrip__.js"): ("reference", "tv_sources '(reference only: the visibility rule at :316)'"),
}

# Declared import seams written into a package (text the porter re-applies instead of TV's import).
# key = (wp_id, TV import target) -> the package text that declares it.
def declared_seam(pk, target, names):
    text = " ".join([pk.get("goal", "")] + pk.get("vv_adaptations", []) + pk.get("notes", []) + pk.get("tv_sources", []))
    base = posixpath.basename(target)
    stem = base[:-3] if base.endswith(".js") else base
    toks = [t for t in stem.split("__") if t and t not in ("Na", "LayoutEditor", "")]
    hits = []
    if target.startswith(SRC + "41__System__SectionCutEngine/"):
        for k in ("SectionAdapter", "DIV-2", "41 Engine", "41 Na__SectionCut", "41 folder", "adapter"):
            if k in text:
                hits.append(k)
    if target.endswith("Na__DrawView__ProfileLines__.js"):
        for k in ("DIV-1", "ProfileLines", "composer"):
            if k in text:
                hits.append(k)
    for t in toks[-1:]:
        if len(t) >= 5 and re.search(r"(?<![A-Za-z])" + re.escape(t) + r"(?![a-z])", text):
            hits.append(t)
    for nm in names:
        short = nm.split("__")[-1]
        if len(short) >= 6 and short in text:
            hits.append(short)
    if "facade-only imports" in text:
        hits.append("facade-only imports")
    return sorted(set(hits))


def load_packages():
    doc = json.load(open(WP_JSON, encoding="utf-8"))
    pks = {p["wp_id"]: p for p in doc["packages"]}
    # transitive ancestors
    anc = {}

    def ancestors(i, stack=()):
        if i in anc:
            return anc[i]
        res = set()
        for d in pks[i].get("depends_on", []):
            if d in pks and d not in stack:
                res.add(d)
                res |= ancestors(d, stack + (i,))
        anc[i] = res
        return res
    for i in pks:
        ancestors(i)
    return doc, pks, anc


def relation(lander, consumer, pks, anc):
    if lander == consumer:
        return "same_package"
    wl, wc = WAVE_IDX[pks[lander]["wave"]], WAVE_IDX[pks[consumer]["wave"]]
    if wl < wc:
        return "earlier_wave"
    if wl > wc:
        return "later_wave"
    if lander in anc[consumer]:
        return "same_wave_ancestor"
    if consumer in anc[lander]:
        return "same_wave_after"
    return "same_wave_unordered"


OK_REL = {"same_package", "earlier_wave", "same_wave_ancestor"}


# -----------------------------------------------------------------------------
# Main analysis
# -----------------------------------------------------------------------------
def main():
    os.makedirs(SCRATCH, exist_ok=True)
    started = datetime.datetime.now()
    idx_kinds = check_index_is_w0_02_only()
    st = load_state()
    tv_src, vv0_src, vv1_src = st["tv_src"], st["vv0_src"], st["vv1_src"]
    vv0_tree, vv1_tree, tv_tree = st["vv0_tree"], st["vv1_tree"], st["tv_tree"]

    # ---- parse every module ------------------------------------------------
    tv_parsed = {p: parse_source(s) for p, s in tv_src.items()}
    vv0_parsed = {p: parse_source(s) for p, s in vv0_src.items()}
    vv1_parsed = {p: parse_source(s) for p, s in vv1_src.items()}
    tv_exp = Exports(dict(tv_parsed), tv_tree, NAWEB)
    vv0_exp = Exports(dict(vv0_parsed), vv0_tree, VCB)
    vv1_exp = Exports(dict(vv1_parsed), vv1_tree, VCB,
                      transform=lambda t: t.replace("Na__DrawView__ComposerPreset__", "Na__DrawView__RenderPreset__"))

    # TV module versions and sign-off markers (informational)
    tv_meta = {}
    for p, s in tv_src.items():
        vers = re.findall(r"Version\s+(\d+\.\d+\.\d+)", s[:60000])
        mod_ver = None
        if vers:
            mod_ver = max(vers, key=lambda v: tuple(int(x) for x in v.split(".")))
        mk = None
        for line in s.splitlines()[:400]:
            if re.search(r"sign-off|signoff|NOT tried by Adam|awaiting Adam|PENDING to ValeVision", line, re.I):
                mk = line.strip()[:200]
                break
        tv_meta[p] = {"version": mod_ver, "signoff_marker": mk, "lines": s.count("\n") + 1}

    # ---- validation: TV and VV(7b4e593a) internally consistent? --------------
    def internal_unresolved(parsed, exp, tree, import_map):
        bad = []
        for p, pr in list(parsed.items()):
            for im in pr["imports"]:
                kind, tgt = resolve_spec(p, im["spec"], import_map)
                if kind not in ("internal", "bare"):
                    continue
                if tgt not in tree:
                    bad.append({"file": p, "spec": im["spec"], "problem": "module not found"})
                    continue
                if not is_module(tgt):
                    continue
                ex = exp.of(tgt)
                if ex is None:
                    continue
                for nm in im["names"]:
                    if nm not in ex:
                        bad.append({"file": p, "spec": im["spec"], "name": nm, "problem": "name not exported"})
        return bad
    tv_bad = internal_unresolved(tv_parsed, tv_exp, tv_tree, st["tv_import_map"])
    vv0_bad = internal_unresolved(vv0_parsed, vv0_exp, vv0_tree, st["vv_import_map"])

    # ---- classify every TV import against VV after W0-02 ----------------------
    vv_vendor_ok = set(vv1_tree)

    def classify_import(importer, im, state="after"):
        kind, tgt = resolve_spec(importer, im["spec"], st["tv_import_map"])
        rec = {"spec": im["spec"], "kind": im["kind"], "target": tgt, "names": im["names"]}
        if kind == "outside":
            rec.update(status="seam", seam="transport", label=LABEL_TRANSPORT + " (outside the TV app root / NAAPPS)")
            return rec
        if kind in ("bare", "bare-unmapped"):
            vk, vt = resolve_spec(importer, im["spec"], st["vv_import_map"])
            ok = vk == "bare" and vt in vv_vendor_ok
            rec.update(status="vendor_ok" if ok else "vendor_missing", vv_target=vt)
            if ok and is_module(vt):
                ex = vv1_exp.of(vt)
                lacking = [n for n in im["names"] if ex is not None and n not in ex]
                if lacking:
                    rec.update(status="vendor_names_missing", lacking=lacking)
            return rec
        if tgt in TRANSPORT_FILES:
            rec.update(status="seam", seam="transport", label=LABEL_TRANSPORT)
            return rec
        if tgt.startswith(SRC + "41__System__SectionCutEngine/"):
            rec.update(status="seam", seam="div2", label=LABEL_DIV2)
            return rec
        if tgt == SRC + "40__System__DrawingViewCore/Na__DrawView__ProfileLines__.js":
            rec.update(status="seam", seam="div1", label=LABEL_DIV1)
            return rec
        if tgt not in vv1_tree:
            rec.update(status="missing")
            return rec
        if not is_module(tgt):
            rec.update(status="present")
            return rec
        ex = vv1_exp.of(tgt) or set()
        lacking = [n for n in im["names"] if n not in ex]
        if lacking and tgt in PLANDIM_SPLIT_FROM:
            # VV is ahead here (S11-V03): the getters TV still keeps in 44 Data / Editor live in VV's
            # split ConfigState__ / EditorPreview__; a ported importer takes them from there.
            homes = {}
            for n in lacking:
                for h in PLANDIM_SPLIT_HOMES:
                    hx = vv1_exp.of(h) or set()
                    if n in hx:
                        homes[n] = h
                        break
            if len(homes) == len(lacking):
                rec.update(status="seam", seam="plandim_split", label=LABEL_PLANDIM, lacking=lacking,
                           split_homes={n: posixpath.basename(h) for n, h in homes.items()})
                return rec
        if lacking:
            rec.update(status="present_names_missing", lacking=lacking)
        else:
            rec.update(status="present")
        return rec

    tv_imports = {p: [classify_import(p, im) for im in tv_parsed[p]["imports"]] for p in tv_parsed}

    # ---- packages and their takes --------------------------------------------
    doc, pks, anc = load_packages()
    takes = []                       # every (package, TV JS source) with its mode
    landers = collections.defaultdict(list)   # VV path -> [{wp, new, mode}]
    pk_vt = {}                                # wp -> VV paths it writes
    for wp, pk in pks.items():
        if pk["wave"] == "WT":
            continue
        vt = {}
        for s in pk.get("vv_targets", []):
            p, new = norm_vv_target(s)
            if p:
                vt[p] = vt.get(p, False) or new
        modes_by_path = {}
        for s in pk.get("tv_sources", []):
            p, ann = norm_tv_source(s)
            if not p or not is_module(p) or not p.startswith(SRC):
                continue
            base = posixpath.basename(p)
            if (wp, base) in OVERRIDES:
                mode, basis = OVERRIDES[(wp, base)]
            elif vt.get(p):
                if wp == "W0-12":
                    mode, basis = "vv_body", "W0-12 facade: TV names and signatures, VV bodies (DR-27; R3 C.4 S1)"
                else:
                    mode, basis = "whole", "new VV file at TV's path (vv_targets '(new)')"
            else:
                mode, basis = "UNCLASSIFIED", "no rule"
            takes.append({"wp": wp, "wave": pk["wave"], "tv_path": p, "annotation": ann, "mode": mode, "basis": basis,
                          "vv_new": bool(vt.get(p)), "vv_target_listed": p in vt, "held": wp in HELD})
            modes_by_path[p] = mode
        for p, new in vt.items():
            landers[p].append({"wp": wp, "new": new, "mode": modes_by_path.get(p, "vv_edit")})
        pk_vt[wp] = set(vt)
    unclassified = [t for t in takes if t["mode"] == "UNCLASSIFIED"]
    if unclassified:
        print("UNCLASSIFIED takes:", json.dumps(unclassified, indent=1))
        sys.exit(2)

    whole_modes = {"whole", "convergence"}
    whole_takes = [t for t in takes if t["mode"] in whole_modes]
    hunk_takes = [t for t in takes if t["mode"] == "hunks"]

    # ---- prerequisite analysis per take ----------------------------------------
    def text_of(pk):
        return " ".join([pk.get("goal", "")] + pk.get("vv_adaptations", []) + pk.get("notes", []) + pk.get("tv_sources", []))

    def lander_verdict(consumer, target, need_names):
        """Who lands `target` (missing, or present but lacking need_names) before `consumer`?"""
        cands = landers.get(target, [])
        res = []
        for c in cands:
            rel = relation(c["wp"], consumer, pks, anc)
            res.append({"wp": c["wp"], "new": c["new"], "mode": c["mode"], "relation": rel,
                        "held": c["wp"] in HELD})
        return res

    def name_mentioned(txt, n):
        if n in txt:
            return True
        short = n.split("__")[-1]
        if len(short) >= 8 and re.search(r"(?<![A-Za-z0-9_])" + re.escape(short) + r"(?![A-Za-z0-9_])", txt):
            return True
        if "__MOD_" in n and "MOD constants" in txt:
            return True
        return False

    def hunk_relevance(pk, wp, rec):
        """Does a hunk package wire this TV import? (it lands the target, or names the target or an imported name)"""
        if rec["target"] in pk_vt.get(wp, set()):
            return "the package lands or edits the target"
        txt = text_of(pk)
        for n in rec.get("names", []):
            if n.startswith("Na__") and n in txt:
                return "the package names %s" % n
        return None

    defects, advisories, prereq_rows = [], [], []
    hunk_defects = []

    def bucket(sev):
        return defects if sev == "defect" else (hunk_defects if sev == "hunk-defect" else advisories)

    hunk_skipped = collections.Counter()
    for t in whole_takes + hunk_takes:
        wp, path = t["wp"], t["tv_path"]
        pk = pks[wp]
        base_severity = "defect" if t["mode"] in whole_modes else "advisory"
        if path not in tv_imports:
            defects.append({"wp": wp, "tv_path": path, "problem": "TV source not found at the pin"})
            continue
        for rec in tv_imports[path]:
            st_ = rec["status"]
            row = {"wp": wp, "wave": t["wave"], "take_mode": t["mode"], "importer": path, "import": rec["target"],
                   "spec": rec["spec"], "kind": rec["kind"], "status": st_, "names": rec.get("names", [])}
            severity = base_severity
            if st_ in ("present", "vendor_ok"):
                continue
            if t["mode"] == "hunks":
                why = hunk_relevance(pk, wp, rec)
                if not why:
                    hunk_skipped[wp] += 1     # VV keeps its own import here; the hunk does not wire this module
                    continue
                row["hunk_relevance"] = why
                severity = "hunk-defect"
            if st_ in ("vendor_missing", "vendor_names_missing"):
                row["verdict"] = ("vendor file missing in VV" if st_ == "vendor_missing" else
                                  "vendor file in VV does not export %s" % ", ".join(rec.get("lacking", [])))
                bucket(severity).append(row)
                prereq_rows.append(row)
                continue
            if st_ == "seam":
                row["seam"] = rec["seam"]
                row["label"] = rec["label"]
                if rec["seam"] == "transport":
                    lv = lander_verdict(wp, SRC + "80__CloudflareIntegration/Na__CloudflareIntegration__ApiClient__.js", [])
                    w012 = [x for x in lv if x["wp"] == "W0-12"]
                    row["landers"] = w012
                    if w012 and w012[0]["relation"] in OK_REL:
                        row["verdict"] = "ok: facade landed earlier by W0-12 (%s)" % w012[0]["relation"]
                    else:
                        row["verdict"] = "ORDER: the W0-12 facade is not guaranteed to land before %s (%s)" % (
                            wp, w012[0]["relation"] if w012 else "no W0-12 lander")
                        bucket(severity).append(dict(row))
                elif rec["seam"] == "plandim_split":
                    row["lacking"] = rec.get("lacking", [])
                    row["split_homes"] = rec.get("split_homes", {})
                    txt = text_of(pk)
                    hits = [k for k in ("PlanDim", "44 ConfigState", "Na__PlanDimensions__ConfigState__", "EditorPreview") if k in txt]
                    row["declared_by_text"] = hits
                    if hits:
                        row["verdict"] = "ok: seam declared in the package (%s)" % ", ".join(hits)
                    else:
                        row["verdict"] = "SEAM NOT DECLARED in the package text (PlanDimensions split)"
                        bucket(severity).append(dict(row))
                else:
                    hits = declared_seam(pk, rec["target"], rec.get("names", []))
                    row["declared_by_text"] = hits
                    if hits:
                        row["verdict"] = "ok: seam declared in the package (%s)" % ", ".join(hits)
                    else:
                        row["verdict"] = "SEAM NOT DECLARED in the package text"
                        bucket(severity).append(dict(row))
                prereq_rows.append(row)
                continue
            need = rec.get("lacking", []) if st_ == "present_names_missing" else rec.get("names", [])
            lv = lander_verdict(wp, rec["target"], need)
            row["landers"] = lv
            if st_ == "present_names_missing":
                row["lacking"] = rec["lacking"]
            ok = [x for x in lv if x["relation"] in OK_REL and not (x["held"] and not t["held"])]
            if st_ == "missing":
                ok_creators = [x for x in ok if x["new"] or x["mode"] in whole_modes]
                if ok_creators:
                    row["verdict"] = "ok: landed by %s (%s)" % (ok_creators[0]["wp"], ok_creators[0]["relation"])
                else:
                    hits = declared_seam(pk, rec["target"], rec.get("names", []))
                    row["declared_by_text"] = hits
                    creators = [x for x in lv if x["new"] or x["mode"] in whole_modes]
                    if hits and not creators:
                        row["verdict"] = "seam? no package lands it; the package text mentions %s - verify the seam" % ", ".join(hits)
                        advisories.append(dict(row))
                    elif creators:
                        row["verdict"] = "ORDER: landed only by %s" % ", ".join("%s (%s%s)" % (
                            c["wp"], c["relation"], ", held" if c["held"] else "") for c in creators)
                        if hits:
                            row["verdict"] += "; package text mentions %s (possible declared seam)" % ", ".join(hits)
                        bucket(severity).append(dict(row))
                    else:
                        row["verdict"] = "UNOWNED: no package lands this module"
                        bucket(severity).append(dict(row))
            else:   # present but lacking names
                lacking = set(rec["lacking"])
                whole_ok = [x for x in ok if x["mode"] in whole_modes and x["wp"] != wp]
                hunk_ok = [x for x in ok if x["mode"] not in whole_modes and x["wp"] != wp]
                same = [x for x in lv if x["wp"] == wp]
                mentioned = {}
                for x in hunk_ok:
                    mentioned[x["wp"]] = [n for n in rec["lacking"] if name_mentioned(text_of(pks[x["wp"]]), n)]
                covered = set()
                for v in mentioned.values():
                    covered |= set(v)
                same_mentioned = set(n for n in rec["lacking"] if same and name_mentioned(text_of(pk), n))
                later = [x for x in lv if x["relation"] not in OK_REL]
                later_whole = [x for x in later if x["mode"] in whole_modes]
                if hunk_ok:
                    row["hunk_landers_mentioning_names"] = mentioned
                if whole_ok:
                    row["verdict"] = "ok: %s takes it whole earlier (%s)" % (whole_ok[0]["wp"], whole_ok[0]["relation"])
                elif same and any(x["mode"] in whole_modes for x in same):
                    row["verdict"] = "ok: the same package takes it whole (%s), so the names land together" % wp
                elif same and "facade-only imports" in text_of(pk) and rec["target"].startswith(LE):
                    row["verdict"] = ("ok (declared seam): %s takes TV's file with facade-only imports - %s come through the "
                                      "lazy-loader facade (R3 C.4 S5; W1-31 adds the loader entry points)" % (wp, ", ".join(rec["lacking"])))
                elif (covered | same_mentioned) >= lacking:
                    who = [w for w, v in mentioned.items() if v] + ([wp + " (same package)"] if same_mentioned else [])
                    row["verdict"] = "ok (declared): %s add(s) %s earlier or in the same change" % (", ".join(who), ", ".join(rec["lacking"]))
                elif "facade-only imports" in text_of(pk) and rec["target"].startswith(LE):
                    row["verdict"] = ("ok (declared seam): %s takes TV's file with facade-only imports - the names %s come through "
                                      "the lazy-loader facade (R3 C.4 S5; W1-31 adds the loader entry points)" % (wp, ", ".join(rec["lacking"])))
                elif later_whole and all(name_mentioned(text_of(pk), n) for n in rec["lacking"]):
                    row["verdict"] = ("ok (declared deferral): %s names %s and lands without it; %s takes %s whole later"
                                      % (wp, ", ".join(rec["lacking"]), later_whole[0]["wp"], posixpath.basename(rec["target"])))
                    row["declared_deferral"] = True
                elif same or hunk_ok:
                    row["verdict"] = ("advisory: only hunk edits land it first (%s) - they must add %s (named in their text: %s)" % (
                        ", ".join(sorted({x["wp"] for x in hunk_ok + same})), ", ".join(rec["lacking"]),
                        ", ".join(sorted(covered | same_mentioned)) or "none"))
                    advisories.append(dict(row))
                else:
                    hits = declared_seam(pk, rec["target"], rec["lacking"])
                    row["declared_by_text"] = hits
                    if hits:
                        row["verdict"] = ("seam? names %s not in VV and no earlier package adds them; the package text mentions %s"
                                          % (", ".join(rec["lacking"]), ", ".join(hits)))
                        if later:
                            row["verdict"] += "; later editors: " + ", ".join("%s (%s)" % (x["wp"], x["relation"]) for x in later)
                        advisories.append(dict(row))
                    else:
                        row["verdict"] = "NAMES: %s not exported by VV's file and no earlier package adds them" % ", ".join(rec["lacking"])
                        if later:
                            row["verdict"] += "; later editors: " + ", ".join("%s (%s, %s)" % (x["wp"], x["relation"], x["mode"]) for x in later)
                        bucket(severity).append(dict(row))
            prereq_rows.append(row)

    # ---- hunk takes: what would break if the porter took TV's file whole instead ----------------
    hunk_hazards = []
    for t in hunk_takes:
        wp, path = t["wp"], t["tv_path"]
        blockers = []
        for rec in tv_imports.get(path, []):
            if rec["status"] not in ("missing", "present_names_missing"):
                continue
            lv = lander_verdict(wp, rec["target"], [])
            ok_l = [x for x in lv if x["relation"] in OK_REL]          # the same package counts: it lands in the same change
            if rec["status"] == "missing" and any(x["new"] or x["mode"] in whole_modes for x in ok_l):
                continue
            if rec["status"] == "present_names_missing" and any(x["mode"] in whole_modes for x in ok_l):
                continue
            later = [x["wp"] for x in lv if x["relation"] not in OK_REL]
            hunk_only = [x["wp"] for x in ok_l if x["wp"] != wp]
            blockers.append({"import": rec["target"], "status": rec["status"], "names": rec.get("lacking", []),
                             "lands_later_in": later, "earlier_hunk_editors": hunk_only})
        if blockers:
            hunk_hazards.append({"wp": wp, "tv_path": path, "blockers": blockers,
                                 "note": "replay only the package's hunks; taking TV's file whole at this point would not link"})

    # ---- module graph: closure, levels, SCCs ---------------------------------
    whole_by_path = collections.defaultdict(list)
    for t in whole_takes:
        whole_by_path[t["tv_path"]].append(t["wp"])
    hunks_by_path = collections.defaultdict(list)
    for t in hunk_takes:
        hunks_by_path[t["tv_path"]].append(t["wp"])

    def prereqs(p):
        out = []
        for rec in tv_imports.get(p, []):
            if rec["status"] == "missing" or rec["status"] == "present_names_missing":
                if rec["target"] in tv_parsed:
                    out.append(rec["target"])
        return sorted(set(out))

    nodes = set(whole_by_path)
    frontier = list(nodes)
    while frontier:
        p = frontier.pop()
        for x in prereqs(p):
            if x not in nodes:
                nodes.add(x)
                frontier.append(x)
    edges = {p: [x for x in prereqs(p) if x in nodes] for p in nodes}

    # Tarjan SCC
    index, low, onst, stack, sccs = {}, {}, set(), [], []
    counter = [0]
    sys.setrecursionlimit(10000)

    def strong(v):
        index[v] = low[v] = counter[0]
        counter[0] += 1
        stack.append(v)
        onst.add(v)
        for w in edges[v]:
            if w not in index:
                strong(w)
                low[v] = min(low[v], low[w])
            elif w in onst:
                low[v] = min(low[v], index[w])
        if low[v] == index[v]:
            comp = []
            while True:
                w = stack.pop()
                onst.discard(w)
                comp.append(w)
                if w == v:
                    break
            sccs.append(sorted(comp))
    for v in sorted(nodes):
        if v not in index:
            strong(v)
    comp_of = {}
    for i, c in enumerate(sccs):
        for v in c:
            comp_of[v] = i
    level = {}

    def lev(ci):
        if ci in level:
            return level[ci]
        level[ci] = 0
        deps = set()
        for v in sccs[ci]:
            for w in edges[v]:
                if comp_of[w] != ci:
                    deps.add(comp_of[w])
        level[ci] = 0 if not deps else 1 + max(lev(d) for d in deps)
        return level[ci]
    for ci in range(len(sccs)):
        lev(ci)

    def closure(p):
        seen, fr = set(), list(edges.get(p, []))
        while fr:
            x = fr.pop()
            if x in seen:
                continue
            seen.add(x)
            fr.extend(edges.get(x, []))
        seen.discard(p)
        return sorted(seen)

    modules = {}
    for p in sorted(nodes):
        recs = tv_imports.get(p, [])
        miss = sorted({r["target"] for r in recs if r["status"] == "missing"})
        upg = {}
        for r in recs:
            if r["status"] == "present_names_missing":
                upg.setdefault(r["target"], set()).update(r["lacking"])
        seams = [{"target": r["target"], "seam": r["seam"], "label": r["label"], "names": r["names"]}
                 for r in recs if r["status"] == "seam"]
        vendor_missing = [r["spec"] for r in recs if r["status"] == "vendor_missing"]
        cl = closure(p)
        modules[p] = {
            "tv_version": tv_meta.get(p, {}).get("version"),
            "tv_lines": tv_meta.get(p, {}).get("lines"),
            "tv_signoff_marker": tv_meta.get(p, {}).get("signoff_marker"),
            "in_vv_after_w0_02": p in vv1_tree,
            "exists_in_live_tree_now": os.path.exists(os.path.join(VV_ROOT, p.replace("/", os.sep))),
            "taken_whole_by": whole_by_path.get(p, []),
            "hunks_by": hunks_by_path.get(p, []),
            "landed_or_edited_by": [x["wp"] for x in landers.get(p, [])],
            "level": level[comp_of[p]],
            "scc_size": len(sccs[comp_of[p]]),
            "blocked_by_missing": miss,
            "blocked_by_upgrade": {k: sorted(v) for k, v in sorted(upg.items())},
            "blocked_by_closure": cl,
            "seams": seams,
            "vendor_missing": vendor_missing,
            "direct_blockers": len(miss) + len(upg),
        }

    # Blocked-by list with the landing package, as the W0 Parity Scribe needs it for the ledger Module Register
    for p, m in modules.items():
        lines = []
        for r in prereq_rows:
            if r["importer"] != p or r["take_mode"] not in whole_modes:
                continue
            lander = None
            v = r.get("verdict", "")
            mm = re.search(r"(W\d-\d\d)", v)
            if mm:
                lander = mm.group(1)
            lines.append({"for_package": r["wp"], "import": r["import"], "status": r["status"],
                          "names": r.get("lacking") or [], "seam": r.get("seam"), "landed_by": lander, "verdict": v})
        m["blocked_by_with_landers"] = lines
        m["missing_module_count"] = len(m["blocked_by_missing"])
        m["upgrade_count"] = len(m["blocked_by_upgrade"])

    order = collections.defaultdict(list)
    for p, m in modules.items():
        order[m["level"]].append(p)
    order_list = [{"level": lv_, "modules": sorted(order[lv_])} for lv_ in sorted(order)]
    hubs = sorted(modules, key=lambda p: (-modules[p]["direct_blockers"], -len(modules[p]["blocked_by_closure"]), p))[:25]
    cycles = [c for c in sccs if len(c) > 1]

    # ---- transport seams: every TV import of the client / mirror --------------
    transport = []
    for p in sorted(tv_imports):
        for r in tv_imports[p]:
            if r["status"] == "seam" and r["seam"] == "transport":
                transport.append({"importer": p, "target": r["target"], "spec": r["spec"], "kind": r["kind"],
                                  "names": r["names"], "label": r["label"],
                                  "taken_whole_by": whole_by_path.get(p, []), "hunks_by": hunks_by_path.get(p, []),
                                  "in_vv_after_w0_02": p in vv1_tree})
    facade_names = {}
    for tf in sorted(TRANSPORT_FILES):
        needed_all = collections.defaultdict(set)
        needed_whole = collections.defaultdict(set)
        for t in transport:
            if t["target"] == tf:
                for n in t["names"]:
                    needed_all[n].add(t["importer"])
                    if t["taken_whole_by"]:
                        needed_whole[n].add(t["importer"])
        tv_ex = sorted(tv_exp.of(tf) or [])
        facade_names[tf] = {
            "tv_exports": tv_ex,
            "tv_export_count": len(tv_ex),
            "imported_by_any_tv_module": {n: sorted(v) for n, v in sorted(needed_all.items())},
            "imported_by_whole_take_modules": {n: sorted(v) for n, v in sorted(needed_whole.items())},
            "imported_names_not_exported_by_tv": sorted(set(needed_all) - set(tv_ex)),
            "vv_live_facade_exists_now": os.path.exists(os.path.join(VV_ROOT, tf.replace("/", os.sep))),
        }
    live_facade_exports = {}
    for tf in sorted(TRANSPORT_FILES):
        fp = os.path.join(VV_ROOT, tf.replace("/", os.sep))
        if os.path.exists(fp):
            pr = parse_source(decode(open(fp, "rb").read()))
            ex = pr["exports"]
            need = set(facade_names[tf]["imported_by_any_tv_module"])
            live_facade_exports[tf] = {"exports": sorted(ex), "missing_vs_tv_importers": sorted(need - ex)}
    other_seams = []
    for p in sorted(tv_imports):
        for r in tv_imports[p]:
            if r["status"] == "seam" and r["seam"] != "transport":
                other_seams.append({"importer": p, "target": r["target"], "seam": r["seam"], "names": r["names"],
                                    "label": r["label"], "taken_whole_by": whole_by_path.get(p, []),
                                    "hunks_by": hunks_by_path.get(p, [])})

    # lazy-loader rule (R3 C.4 S5): a whole-take module outside the LE folder importing LE modules statically
    lazy_rule = []
    for t in whole_takes:
        p = t["tv_path"]
        if p.startswith(LE):
            continue
        for r in tv_imports.get(p, []):
            if r["target"].startswith(LE) and r["kind"] in ("static", "side-effect", "re-export"):
                lazy_rule.append({"wp": t["wp"], "importer": p, "target": r["target"], "kind": r["kind"],
                                  "note": "VV loads the Layout Editor lazily (DR-24, R3 C.4 S5): route through Na__LeLoad__* or keep a literal import()"})

    # resource references (new URL(..., import.meta.url)) of whole-take modules (informational)
    resources = []
    for t in whole_takes:
        p = t["tv_path"]
        for u in tv_parsed.get(p, {}).get("urls", []):
            if not (u.startswith("./") or u.startswith("../")):
                continue
            if u.endswith("/") or not posixpath.splitext(u)[1]:
                continue                      # a folder URL (a library root), not a file
            tgt = posixpath.normpath(posixpath.join(posixpath.dirname(p), u))
            if tgt in vv1_tree:
                continue
            lv = lander_verdict(t["wp"], tgt, [])
            ok = [x for x in lv if x["relation"] in OK_REL]
            resources.append({"wp": t["wp"], "importer": p, "resource": tgt, "in_tv_at_pin": tgt in tv_tree,
                              "landers": lv, "verdict": ("ok: %s" % ok[0]["wp"]) if ok else
                              ("no earlier lander" + ("" if lv else " (no package lists it)"))})

    # ---- S11 Appendix D reproduction ----------------------------------------
    s11 = open(S11_MD, encoding="utf-8").read().split("\n")
    rows = []
    for l in s11:
        m = re.match(r"\| (\d+) \| `([^`]+)` \| ([^|]*) \| `([^`]+)` \| ([^|]*) \| ([^|]*) \| ([^|]*) \| ([^|]*) \| ([^|]*) \| ([^|]*) \|", l)
        if m:
            rows.append(m.groups())
    appd = {}
    in_appd = False
    for l in s11:
        if l.startswith("## Appendix D"):
            in_appd = True
            continue
        if in_appd and l.startswith("## "):
            break
        if in_appd:
            m = re.match(r"\| (\d+) \| `([^`]+)` \| (\d+) \| (.*) \| (yes)? ?\|$", l)
            if m:
                appd[int(m.group(1))] = {"tv": m.group(2), "count": int(m.group(3)),
                                         "names": sorted(re.findall(r"`([^`]+)`", m.group(4))), "transport": bool(m.group(5))}
    prereq = json.load(open(PREREQ_JSON, encoding="utf-8")) if os.path.exists(PREREQ_JSON) else None
    appd_rows = []
    for r in rows:
        num, tvp, _, vvp, _, _, _, _, action, adapt = r
        if not action.strip().startswith("port_whole"):
            continue
        num = int(num)
        raw = tv_src.get(tvp)
        if raw is None:
            appd_rows.append({"row": num, "tv": tvp, "error": "not found at pin"})
            continue
        # (1) the verifier's own method: raw text, relative specifiers, old folder map, VV at 7b4e593a
        imps = set(re.findall(r"from\s+['\"](\.[^'\"]+)['\"]", raw)) | set(re.findall(r"import\(\s*['\"](\.[^'\"]+)['\"]", raw))
        miss_raw = []
        for i in imps:
            tgt = posixpath.normpath(posixpath.join(posixpath.dirname(tvp), i))
            vrel = tgt
            for a, b in OLD_MAP.items():
                vrel = vrel.replace(SRC + a + "/", SRC + b + "/")
            if vrel not in vv0_tree:
                miss_raw.append(tgt.replace(SRC, ""))
        miss_raw = sorted(miss_raw)
        # (2) comment-aware parser, same baseline
        miss_parsed = []
        for im in tv_parsed[tvp]["imports"]:
            k, tgt = resolve_spec(tvp, im["spec"], st["tv_import_map"])
            if k != "internal":
                continue
            vrel = tgt
            for a, b in OLD_MAP.items():
                vrel = vrel.replace(SRC + a + "/", SRC + b + "/")
            if vrel not in vv0_tree:
                miss_parsed.append(tgt.replace(SRC, ""))
        miss_parsed = sorted(set(miss_parsed))
        # (3) after W0-02: identity paths against the index
        miss_after = sorted({r_["target"].replace(SRC, "") for r_ in tv_imports[tvp] if r_["status"] == "missing"})
        seams_after = sorted({r_["target"].replace(SRC, "") + " [" + r_["seam"] + "]" for r_ in tv_imports[tvp] if r_["status"] == "seam"})
        upg_after = sorted({r_["target"].replace(SRC, "") for r_ in tv_imports[tvp] if r_["status"] == "present_names_missing"})
        stems = sorted(posixpath.basename(x)[:-3] for x in miss_raw)
        ad = appd.get(num)
        transport_flag = any("80__CloudflareIntegration" in x or "LocalProjectMirror__" in x for x in miss_raw)
        appd_rows.append({
            "row": num, "tv": tvp, "adaptation": adapt.strip(),
            "missing_before_swarm": miss_raw, "count_before_swarm": len(miss_raw),
            "transport_before_swarm": transport_flag,
            "appendix_d": ad,
            "matches_appendix_d": (ad is None and not miss_raw) or (ad is not None and ad["count"] == len(miss_raw)
                                                                     and sorted(ad["names"]) == stems and ad["transport"] == transport_flag),
            "matches_prereq_json": (prereq is None) or (sorted(prereq.get(str(num), {}).get("missing", [])) == miss_raw),
            "comment_aware_parser_agrees": miss_parsed == miss_raw,
            "comment_aware_missing": miss_parsed,
            "missing_after_w0_02": miss_after,
            "seams_after_w0_02": seams_after,
            "name_upgrades_needed_after_w0_02": upg_after,
            "canonical_whole_takers": whole_by_path.get(tvp, []),
            "canonical_hunk_takers": hunks_by_path.get(tvp, []),
            "canonical_other_takes": sorted({"%s:%s" % (t["wp"], t["mode"]) for t in takes
                                             if t["tv_path"] == tvp and t["mode"] not in ("whole", "convergence", "hunks")}),
        })
    n_rows = len(appd_rows)
    n_blocked = sum(1 for r in appd_rows if r.get("count_before_swarm"))
    n_match = sum(1 for r in appd_rows if r.get("matches_appendix_d"))
    n_match_pr = sum(1 for r in appd_rows if r.get("matches_prereq_json"))
    n_blocked_after = sum(1 for r in appd_rows if r.get("missing_after_w0_02"))
    appendix_d = {
        "port_whole_rows": n_rows, "blocked_before_swarm": n_blocked, "rows_matching_appendix_d": n_match,
        "rows_matching_prereq_json": n_match_pr, "prereq_json_read": PREREQ_JSON if prereq is not None else None,
        "appendix_d_rows_in_s11": len(appd),
        "blocked_after_w0_02_missing_modules": n_blocked_after,
        "rows": appd_rows,
    }

    # ---- package summaries ------------------------------------------------------
    pk_summary = {}
    for wp, pk in pks.items():
        if pk["wave"] == "WT":
            continue
        tk = [t for t in takes if t["wp"] == wp]
        pre = [r for r in prereq_rows if r["wp"] == wp]
        d = [x for x in defects if x["wp"] == wp]
        hd = [x for x in hunk_defects if x["wp"] == wp]
        a = [x for x in advisories if x["wp"] == wp]
        pk_summary[wp] = {
            "wave": pk["wave"], "title": pk["title"], "held": wp in HELD,
            "takes": [{"tv_path": t["tv_path"], "mode": t["mode"], "basis": t["basis"]} for t in tk],
            "prerequisites": pre,
            "defects": len(d), "hunk_defects": len(hd), "advisories": len(a),
            "hunk_imports_not_wired_by_this_package": hunk_skipped.get(wp, 0),
            "verdict": "defect" if d else ("hunk-defect" if hd else ("advisory" if a else ("ok" if tk else "no TV module taken"))),
            "level": max([modules[t["tv_path"]]["level"] for t in tk if t["tv_path"] in modules] or [None], key=lambda x: -1 if x is None else x),
        }

    result = {
        "id": "W0-05 port-order map (TrueVision import graph, leaves first, hubs last)",
        "generated": started.strftime("%d-%b-%Y %H:%M"),
        "tv_pin": run(["git", "-C", NAWEB, "rev-parse", PIN]).decode().strip(),
        "vv_base": run(["git", "-C", VCB, "rev-parse", VV_BASE]).decode().strip(),
        "vv_after_w0_02": {
            "source": "git index of D:/10_CoreLib__ValeCodebase (W0-02's git mv renames over 7b4e593a); export names from the "
                      "index blobs with W0-02's T6 rename Na__DrawView__ComposerPreset__* -> Na__DrawView__RenderPreset__* applied",
            "staged_changes": idx_kinds,
            "vv_files": len(vv1_tree), "vv_modules": len(vv1_src),
        },
        "tv_modules_parsed": len(tv_src),
        "labels": {"transport": LABEL_TRANSPORT, "div2": LABEL_DIV2, "div1": LABEL_DIV1},
        "method": [
            "Imports: static `import ... from`, side-effect `import '...'`, `export ... from` and literal `import('...')`, parsed from "
            "comment-stripped source (string, template and regex-literal aware); named, default and namespace imports (namespace: "
            "the NS.Name uses) give the requested names.",
            "A TV import is resolved at TV's own path (identity map after W0-02) against the VV git index; 'missing' = no file at "
            "that path; 'present_names_missing' = the file exists but does not export every requested name (export * followed).",
            "Seams are never ports: 80__CloudflareIntegration/LocalProjectMirror__ (and anything outside the TV app root) -> "
            "transport seam (DIV-4) resolved by the W0-12 facade; TV 41__System__SectionCutEngine -> SectionAdapter (DIV-2); "
            "TV 40 ProfileLines -> dropped (DIV-1).",
            "Take modes per package come from the package text (goal, vv_adaptations, tv_sources annotations); every non-new "
            "target was classified by hand (OVERRIDES table in the script). 'whole' and 'convergence' are checked strictly "
            "(defects). For 'hunks' only the TV imports the package wires are checked (it lands or edits the target, or its "
            "text names the module or an imported name); those failures are 'hunk_defects'; the rest stay VV's own imports.",
            "A name VV lacks counts as delivered by an earlier hunk package when that package's text names it (e.g. W0-11 "
            "adds the ProjectLoader helpers); a whole take whose package declares 'facade-only imports' (W1-34) takes LE "
            "names through the lazy-loader facade (R3 C.4 S5).",
            "Order check: a prerequisite landed by package L is fine for consumer P when L == P, L is in an earlier wave (R11 "
            "barrier) or L is a transitive depends_on ancestor of P in the same wave; a held lander never satisfies a non-held "
            "consumer.",
            "Levels: Tarjan SCCs over the 'missing or needs-upgrade' edges between TV modules reachable from the whole-take set; "
            "level 0 = no blockers; a module's level = 1 + the highest level of its blockers (leaves first, hubs last).",
        ],
        "validation": {
            "tv_internal_unresolved_imports": tv_bad,
            "vv_7b4e593a_internal_unresolved_imports": vv0_bad,
            "note": "A self-consistency check of the parser: TV at the pin and VV at 7b4e593a both pass their own export "
                    "harnesses, so any entry here is a parser limitation or a real defect in that tree (listed, not hidden).",
        },
        "appendix_d_reproduction": appendix_d,
        "transport_seams": transport,
        "facade_names_needed_by_w0_12": facade_names,
        "facade_live_check_now": live_facade_exports,
        "other_seams": other_seams,
        "lazy_loader_rule": lazy_rule,
        "resource_references": resources,
        "takes": takes,
        "modules": modules,
        "order": order_list,
        "cycles": cycles,
        "hubs": [{"module": h, "direct_blockers": modules[h]["direct_blockers"], "closure": len(modules[h]["blocked_by_closure"]),
                  "taken_whole_by": modules[h]["taken_whole_by"], "level": modules[h]["level"]} for h in hubs],
        "packages": pk_summary,
        "defects": defects,
        "hunk_defects": hunk_defects,
        "advisories": advisories,
        "hunk_take_whole_file_hazards": hunk_hazards,
    }
    out1 = os.path.join(SCRATCH, "port_order_map__endW3.json")
    out2 = os.path.join(SCRATCH, "port_order_map__endW3__copy.json")
    txt = json.dumps(result, indent=1, ensure_ascii=False)
    for o in (out1, out2):
        with open(o, "w", encoding="utf-8", newline="\n") as f:
            f.write(txt + "\n")
    with open(os.path.join(SCRATCH, "run_summary.json"), "w", encoding="utf-8") as f:
        json.dump({
            "generated": result["generated"], "index": idx_kinds, "tv_modules": len(tv_src),
            "appendix_d": {k: v for k, v in appendix_d.items() if k != "rows"},
            "takes": collections.Counter(t["mode"] for t in takes),
            "whole_takes": len(whole_takes), "nodes": len(nodes), "levels": len(order_list), "cycles": cycles,
            "defects": len(defects), "hunk_defects": len(hunk_defects), "advisories": len(advisories),
            "transport_imports": len(transport), "tv_bad": len(tv_bad), "vv0_bad": len(vv0_bad),
        }, f, indent=1, default=list)
    print("Appendix D: rows %d, blocked %d, match S11 %d, match prereq.json %d, blocked after W0-02 %d" % (
        n_rows, n_blocked, n_match, n_match_pr, n_blocked_after))
    print("takes:", dict(collections.Counter(t["mode"] for t in takes)))
    print("graph nodes %d, levels %d, cycles %d" % (len(nodes), len(order_list), len(cycles)))
    print("defects %d, hunk defects %d, advisories %d, transport imports %d, tv_bad %d, vv0_bad %d" % (
        len(defects), len(hunk_defects), len(advisories), len(transport), len(tv_bad), len(vv0_bad)))
    print("wrote", out1, "and", out2)


if __name__ == "__main__":
    main()
