"""W1-99 - the end-of-Wave-1 port-order analysis: W0-99's working-tree copy of W0-05's script
(scratch/W0-99/pom/port_order_map__endW0.py), with only its output folder and file names changed, written into
scratch/W1-99/pom/. Neither original is changed. Every replacement is anchored and asserted to match exactly once.
The analysis is read-only on both repositories (git ls-tree, ls-files, cat-file, diff --cached, rev-parse; files read
from disk).

Run:  python -B make_pom_endW1.py   then   python -B pom/port_order_map__endW1.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'W0-99', 'pom', 'port_order_map__endW0.py')
DST_DIR = os.path.join(HERE, 'pom')
DST = os.path.join(DST_DIR, 'port_order_map__endW1.py')

text = open(SRC, encoding='utf-8').read()
REPLACEMENTS = [
    ('SCRATCH = os.path.join(EXEC, "scratch", "W0-99", "pom")',
     'SCRATCH = os.path.join(EXEC, "scratch", "W1-99", "pom")'),
    ('    out1 = os.path.join(SCRATCH, "port_order_map__endW0.json")\n'
     '    out2 = os.path.join(SCRATCH, "port_order_map__endW0__copy.json")\n',
     '    out1 = os.path.join(SCRATCH, "port_order_map__endW1.json")\n'
     '    out2 = os.path.join(SCRATCH, "port_order_map__endW1__copy.json")\n'),
]
for old, new in REPLACEMENTS:
    n = text.count(old)
    if n != 1:
        raise SystemExit('anchor found %d times: %r' % (n, old[:80]))
    text = text.replace(old, new)
# drop W0-99's two-line generated banner and put this one's
lines = text.split('\n')
assert lines[0].startswith('# GENERATED by scratch/W0-99/make_pom_endW0.py'), lines[0]
assert lines[1].startswith('# TREE (end of Wave 0)'), lines[1]
text = '\n'.join(lines[2:])
os.makedirs(DST_DIR, exist_ok=True)
with open(DST, 'w', encoding='utf-8', newline='\n') as fh:
    fh.write('# GENERATED by scratch/W1-99/make_pom_endW1.py from scratch/W0-99/pom/port_order_map__endW0.py - reads the\n'
             '# VV WORKING TREE (end of Wave 1) as its "after" tree and writes only into scratch/W1-99/pom/.\n')
    fh.write(text)
print('wrote', DST)
