# =============================================================================
# Py_PdfUtils__PdfToTextExtractor__MarkdownWriter.py
# =============================================================================
# Description : Serialises a list of MarkdownBlocks to disk at
#               <stem>__TextExtracted__DD-Mon-YYYY__.md, preceded by a
#               provenance preamble that documents source file, page count
#               and per-page extraction strategy.
# =============================================================================

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from Py_PdfUtils__PdfToTextExtractor__AppUtils import (
    MarkdownBlock,
    PageStrategy,
    build_output_markdown_path,
    format_date_stamp,
    summarise_page_strategies,
)

# =============================================================================
# REGION | Preamble Rendering
# =============================================================================

# Produces the provenance preamble block placed at the top of every emitted
# Markdown file. Intentionally uses plain Markdown (no YAML front matter) so
# the file is renderable in any viewer.
def _render_preamble(
    source_pdf   : Path,
    page_count   : int,
    strategies   : dict[int, PageStrategy],
    ocr_missing  : list[str],
) -> str:
    lines: list[str] = []
    lines.append(f"<!-- Generated by Py_PdfUtils__PdfToTextExtractor on {datetime.now().isoformat(timespec='seconds')} -->")
    lines.append("")
    lines.append("> **Source PDF** : " + source_pdf.name)
    lines.append("> **Pages**      : " + str(page_count))
    lines.append("> **Strategy**   : " + summarise_page_strategies(strategies))
    if ocr_missing:
        lines.append(
            "> **OCR Notice** : OCR was unavailable because these native "
            "binaries were missing at extraction time - "
            + ", ".join(ocr_missing)
        )
    lines.append("> **Extracted**  : " + format_date_stamp())
    lines.append("")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)

# endregion -------------------------------------------------------------------

# =============================================================================
# REGION | Block Rendering
# =============================================================================

# Converts a single MarkdownBlock into its final Markdown text representation.
def _render_block(block: MarkdownBlock) -> str:
    text = block.text.strip()
    if not text:
        return ""
    if 1 <= block.level <= 4:
        return ("#" * block.level) + " " + text
    return text

# endregion -------------------------------------------------------------------

# =============================================================================
# REGION | Paragraph Grouping
# =============================================================================

# Groups consecutive body-text (level 0) blocks into one paragraph so the
# output reads naturally, with blank lines separating paragraphs and headers.
def _stream_markdown(blocks: list[MarkdownBlock]) -> str:
    out_lines: list[str] = []
    current_body: list[str] = []

    def flush_body():
        if current_body:
            out_lines.append(" ".join(current_body))
            out_lines.append("")
            current_body.clear()

    for block in blocks:
        rendered = _render_block(block)
        if not rendered:
            continue
        if block.level == 0:
            current_body.append(rendered)
            continue
        flush_body()
        out_lines.append(rendered)
        out_lines.append("")

    flush_body()
    return "\n".join(out_lines).rstrip() + "\n"

# endregion -------------------------------------------------------------------

# =============================================================================
# REGION | Public API
# =============================================================================

# Writes the Markdown output to the user-selected folder and returns the
# final Path. Creates the directory if it does not exist.
def write_markdown_document(
    source_pdf   : str | Path,
    output_dir   : str | Path,
    blocks       : list[MarkdownBlock],
    strategies   : dict[int, PageStrategy],
    page_count   : int,
    ocr_missing  : list[str] | None = None,
) -> Path:
    source_pdf = Path(source_pdf)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = build_output_markdown_path(source_pdf, output_dir)

    preamble = _render_preamble(source_pdf, page_count, strategies, ocr_missing or [])
    body     = _stream_markdown(blocks)

    with output_path.open("w", encoding="utf-8") as fp:
        fp.write(preamble)
        fp.write(body)

    logging.info(f"MarkdownWriter | wrote {output_path} ({len(blocks)} blocks)")
    return output_path

# endregion -------------------------------------------------------------------
